### ISSUE TITLE
Snap install breaks tooling on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by Minibrams** [dotnet/sdk#10874]
After installing the most recent .NET Core SDK with `snap`, there is an apparent mismatch between where tools are installed and where `dotnet` looks for installed tools. 

Steps to reproduce: 
First install the SDK:
```
sudo snap install dotnet-sdk --classic
sudo snap alias dotnet-sdk.dotnet dotnet
```
Then install tooling for EntityFrameworkCore (which should succeed):
```
dotnet tool install --global dotnet-ef
```
With a restarted session, even if the installation succeeded, the tool cannot be found:
```
dotnet ef --version

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```
... and the tool listing remains empty:
```
dotnet tool list

Package Id      Version      Commands      Manifest
---------------------------------------------------

```

While `dotnet` cannot find the `dotnet ef` tool, it has been installed in `/home/user/.dotnet/tools`: 
```
ls ~/home/user/.dotnet/tools

dotnet-ef
``` 
... though this evidently isn't where the snap-installation of `dotnet` is expecting the tools to be installed.

System information: 
* Ubuntu 18.04 LTS
* .NET Core SDK 3.1.102

**Comment by gsacavdm** [comment]
I'm having the same issue. Did you have any luck getting this to work @Minibrams ?

**Comment by Minibrams** [comment]
@gsacavdm Couldn't get it to work, unfortunately. I ended up simply installing the older version with `sudo apt-get install dotnet-sdk-3.1` and making sure my tool installations were of compatible versions.
 
It's pretty unfortunate, I think, that the only way to install the latest version of the SDK seemingly breaks something so significant with no clear way of fixing the issue.

**Comment by peppy** [comment]
This applies to .NET 5 as well, where snap is the recommended install method..

**Comment by Fosol** [comment]
I attempted to follow the steps posted here - https://offby2.com/posts/003-installing-dotnet-core-in-linux/

It gets past the original error and displays the following error;
```
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/fosol/.dotnet/tools/.store/dotnet-ef/3.1.8/dotnet-ef/3.1.8/tools/netcoreapp3.1/any/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.20.04-x64
```

**Comment by Fosol** [comment]
Then I tried the following;
```
export PATH="$PATH:$HOME/.dotnet/tools"
export DOTNET_ROOT=/snap/dotnet-sdk/current
export MSBuildSDKsPath=$DOTNET_ROOT/sdk/$(${DOTNET_ROOT}/dotnet --version)/Sdks
export PATH="${PATH}:${DOTNET_ROOT}"
export PATH="$PATH:$HOME/.dotnet/tools"
```
But it results in the following error;
```
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String, System.String)
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation ByRef)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(System.String, System.Reflection.Assembly)
   at Microsoft.EntityFrameworkCore.Tools.Properties.Resources..cctor()
   at Microsoft.EntityFrameworkCore.Tools.Properties.Resources.GetString(System.String, System.String[])
   at Microsoft.EntityFrameworkCore.Tools.Properties.Resources.get_DotnetEfFullName()
   at Microsoft.EntityFrameworkCore.Tools.RootCommand.Configure(Microsoft.DotNet.Cli.CommandLine.CommandLineApplication)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(System.String[])
```

**Comment by Fosol** [comment]
Finally the following fixed everything;

```
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
```

It appears to work now.

**Comment by mochsner** [comment]
@Fosol has this been working for you since? I've been on dotnet-sdk 6.0.300 for a while, and when snap did a refresh to 6.0.301 this seemed to break everything. 

Interestingly, I've heard reports that the dotnet sdk works fine in CLI, but not from Rider or other IDEs - I'm guessing Microsoft requires elevated priveleges after it's updated. 

If using it after updates requires elevated priveleges, we should probably centralize all the various issues into a single one related to permissioning issues with snap updates for the dotnet team.

**Comment by Fosol** [comment]
Regrettably I haven't looked too closely at this for a while.  All I know is the above resolved my issues at the time.
