### ISSUE TITLE
DCProj breaks DotNet when calling Entity Framework.

### ISSUE THREAD

**Issue by computamike** [dotnet/sdk#10871]
_This was originally logged under [Entity Framework Core issue 20256](https://github.com/dotnet/efcore/issues/20256) but after talking with the team there we believe that it is actually a Dotnet CLI issue._

Adding Orchestration to a project in Visual Studio Community 2019 prevents Entity Framework CLI from executing.

### Steps to reproduce
1. Create an ASP.NET MVC Project (with Docker Linux container support)
1. Access Package Manager Console
1. Execute ```dotnet ef```
1. Entity Framework "unicorn" screen is presented.
![image](https://user-images.githubusercontent.com/464876/76424169-cab48700-639f-11ea-9cfa-711acc5ac391.png)
1. Right click project, Add, Container Orchestrator Support
1. Select `Docker Compose`
1. Select `Linux` for  Docker Support Options, Target OS
1. VS has now added a dcproj file to the project.
1. Access Package Manager Console
1. Execute ```dotnet ef```
1. Entity Framework error screen is presented.
![image](https://user-images.githubusercontent.com/464876/76424483-37c81c80-63a0-11ea-8c7b-9e4fdddf256d.png)

Here is a simplified project with 2 commits.
https://github.com/computamike/EntityFrameworkOrchestration

### Further technical details

EF Core version: Entity Framework Core .NET Command-line Tools 3.1.2
Database provider: N/A
Target framework: .NET Core 3.1
Operating system: Windows 10 v 1809 (OS Build 17763.1039)
IDE: Visual Studio 2019 Community

### Research done
I can see that an error message matching the error shown can be seen in the localizable strings ```RunCommandExceptionMultipleProjects``` - and that this error is thrown from [RunCommand.cs](https://github.com/dotnet/sdk/blob/b1223209644d900702287faea8e9b71f95ec49f8/src/Cli/dotnet/commands/dotnet-run/RunCommand.cs#L273)

I believe that the check for `*.*proj` is also selecting *.dcproj and *.csproj files.  Adding Docker Container support adds a *.dcproj file.

I wonder if rather than scanning for any files *proj, whether there could be a list of extensions that are supported - I don't know what those are, but for example : ['csproj','fsproj','vbproj'] and scan for files in the directory matching extensions from that list?

**Comment by wli3** [comment]
```
λ dotnet -d ef
Telemetry is: Enabled
projectfactory: MSBUILD_EXE_PATH = C:\Program Files\dotnet\sdk\3.1.201\MSBuild.dll
Microsoft.DotNet.Cli.Utils.GracefulException: Specify which project file to use because this 'C:\Users\wul\Downloads\EntityFrameworkOrchestration-master\EntityFrameworkOrchestration-master' contains more than one project file.
   at Microsoft.DotNet.CommandFactory.ProjectFactory.GetMSBuildProjPath(String projectDirectory)
   at Microsoft.DotNet.CommandFactory.ProjectFactory.GetMSBuildProj(String projectDirectory, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.CommandFactory.ProjectToolsCommandResolver.ResolveFromProjectTools(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.CommandFactory.ProjectToolsCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.CommandFactory.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.CommandFactory.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.CommandFactory.CommandFactoryUsingResolver.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by wli3** [comment]
ProjectTools run before global tools resolver. And the resolver does not like having multiple *proj in the folder.

@computamike in the meantime you can run "dotnet-ef" to workaround it.

**Comment by wli3** [comment]
@KathleenDollard project tools is in maintenance mode. It is unlikely to solve the root cause considering *proj is valid msbuild project convention. I am wondering if I can just move the project tools resolver priority lower than `dotnet-*` on path. The means in some case, some project tools  can never be called due to a naming conflict with a program on path.

**Comment by wli3** [comment]
The biggest problem is there is no way to guide the user to run `dotnet-ef``
