### ISSUE TITLE
dotnet publish with output folder specified triggers System.IO.FileLoadException after main assembly is executed

### ISSUE THREAD

**Issue by consysPM** [dotnet/sdk#11268]
dotnet version: 3.1.101
my .net core projects files are using .net core version: 2.1.802

after running
dotnet publish "<.SLN>" --force --configuration Release -r win10-x64 --self-contained true -o "<OUTPUT_FOLDER>" 
and executing the .exe file a exception is thrown

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Text.RegularExpressions.Regex.GetCachedCodeEntryInternal(CachedCodeEntryKey key, Boolean isToAdd)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean addToCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern)
   at Serilog.Sinks.File.PathRoller..ctor(String path, RollingInterval interval)
   at Serilog.Sinks.File.RollingFileSink..ctor(String path, ITextFormatter textFormatter, Nullable`1 fileSizeLimitBytes, Nullable`1 retainedFileCountLimit, Encoding encoding, Boolean buffered, Boolean shared, RollingInterval rollingInterval, Boolean rollOnFileSizeLimit)
   at Serilog.FileLoggerConfigurationExtensions.ConfigureFile(Func`4 addSink, ITextFormatter formatter, String path, LogEventLevel restrictedToMinimumLevel, Nullable`1 fileSizeLimitBytes, LoggingLevelSwitch levelSwitch, Boolean buffered, Boolean propagateExceptions, Boolean shared, Nullable`1 flushToDiskInterval, Encoding encoding, RollingInterval rollingInterval, Boolean rollOnFileSizeLimit, Nullable`1 retainedFileCountLimit)
   at Serilog.FileLoggerConfigurationExtensions.File(LoggerSinkConfiguration sinkConfiguration, String path, LogEventLevel restrictedToMinimumLevel, String outputTemplate, IFormatProvider formatProvider, Nullable`1 fileSizeLimitBytes, LoggingLevelSwitch levelSwitch, Boolean buffered, Boolean shared, Nullable`1 flushToDiskInterval, RollingInterval rollingInterval, Boolean rollOnFileSizeLimit, Nullable`1 retainedFileCountLimit, Encoding encoding)

when i'm not specifying the output folder everything works as expected.
dotnet publish "<.SLN>" --force --configuration Release -r win10-x64 --self-contained true.

the interesting thing is everything worked 1 or 2 months ago and i didnt change any project or solution files within this time period. (and i didnt update the .net core sdk)

EDIT: The System.Threading.dll is different. **Why does it change when specifying a custom output folder?**

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by consysPM** [comment]
i referenced a nuget fallback folder, after removing the reference everything started to work again. But i still dont get it why it worked before
