### ISSUE TITLE
GenerateDepsFile sometimes fails with System.IO.FileNotFoundException: C:\Users\tomat\.nuget\packages\microsoft.diasymreader.native\1.7.0\runtimes\win\native\Microsoft.DiaSymReader.Native.arm64.dll

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#11270]
When building Roslyn GenerateDepsFile  may fail with the following error:

```
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly.
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018: System.IO.FileNotFoundException: C:\Users\tomat\.nuget\packages\microsoft.diasymreader.native\1.7.0\runtimes\win\native\Microsoft.DiaSymReader.Native.arm64.dll
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.NET.Build.Tasks.FileUtilities.GetFileVersion(String sourcePath)
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.NET.Build.Tasks.DependencyContextBuilder.CreateRuntimeFile(String path, String fullPath)
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.NET.Build.Tasks.DependencyContextBuilder.CreateRuntimeFile(ResolvedFile resolvedFile)
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.Extensions.DependencyModel.RuntimeAssetGroup..ctor(String runtime, IEnumerable`1 runtimeFiles)
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.NET.Build.Tasks.DependencyContextBuilder.GetRuntimeLibrary(DependencyLibrary library)
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.NET.Build.Tasks.DependencyContextBuilder.Build()
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath)
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore()
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
58>C:\Program Files\dotnet\sdk\3.1.300-preview-015048\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

It's not clear to me why does it think arm64 flavor of the binary should exist in the package.

**Comment by dsplaisted** [comment]
Can you share a binlog and the assets file of the project where it's failing?

**Comment by tmat** [comment]
I'll try to get it. I was building from VS.

**Comment by tmat** [comment]
Hit this again - binlog: [Build.zip](https://github.com/dotnet/sdk/files/5448026/Build.zip), assets file: [project.assets.zip](https://github.com/dotnet/sdk/files/5448033/project.assets.zip)
