### ISSUE TITLE
[Feedback] XAML designer for .net core WPF just shows blank after loading

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#11350]
@chabiss commented on [Tue Oct 29 2019](https://github.com/dotnet/installer/issues/5417)

* .NET Core Version: (e.g. 3.0 Preview1, or daily build number, use `dotnet --info`)
* Windows version: (`winver`)
* Does the bug reproduce also in WPF for .NET Framework 4.8?: WPF Core Only
* Is this bug related specifically to tooling in Visual Studio (e.g. XAML Designer, Code editing, etc...)? 

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/994355
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1007006

* Security issues and bugs should be reported privately, learn more via our [responsible disclosure guidelines](https://github.com/dotnet/wpf/blob/master/README.md#reporting-security-issues-and-security-bugs).

 
 
 **Problem description:**
I think the core issue here is that the project is self-published

<PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
   <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Platforms>AnyCPU;x64</Platforms>

The shadow cache contains the local payload: 
C:\Users\chabiss\AppData\Local\Microsoft\VisualStudio\16.0_c362bee8\Designer\Cache\11519015903x64DA
You can see the content below
\\ddfiles\Team\XAML\User\chabiss\ShadowCache\11519015903x64DA

However, WPF throws with this exception below? 

Failed WPF DLL consistency checks. Expected location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0.
DLL Name: PresentationNative_cor3.dll DLL Location: C:\Users\chabiss\AppData\Local\Microsoft\VisualStudio\16.0_c362bee8\Designer\Cache\11519015903x64DA
DLL Name: WpfGfx_cor3.dll DLL Location: C:\Users\chabiss\AppData\Local\Microsoft\VisualStudio\16.0_c362bee8\Designer\Cache\11519015903x64DA

   at System.Windows.WpfDllVerifier.VerifyWpfDllSet(String[] additionalDlls)
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Interop.HwndTarget..ctor(IntPtr hwnd)
   at System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters)
   at System.Windows.Interop.HwndSource..ctor(HwndSourceParameters parameters)
   at Microsoft.VisualStudio.XSurface.Wpf.DesignerSurface.CreateSource()

In the \\ddfiles\Team\XAML\User\chabiss\ShadowCache\11519015903x64DA\WpfSurface.runtimeConfig.json

With 
  "configProperties": {
      "Microsoft.NETCore.DotNetHostPolicy.SetAppPaths": true
    }

Assembly binding should *always* look first in the shadow cache folder and falls into C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0?  If the self-contained payload is accurately inside the Shadow cache, what gives here? 
 

 **Actual behavior:** 
However, WPF throws with this exception below? 

Failed WPF DLL consistency checks. Expected location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0.
DLL Name: PresentationNative_cor3.dll DLL Location: C:\Users\chabiss\AppData\Local\Microsoft\VisualStudio\16.0_c362bee8\Designer\Cache\11519015903x64DA
DLL Name: WpfGfx_cor3.dll DLL Location: C:\Users\chabiss\AppData\Local\Microsoft\VisualStudio\16.0_c362bee8\Designer\Cache\11519015903x64DA

   at System.Windows.WpfDllVerifier.VerifyWpfDllSet(String[] additionalDlls)
   at System.Windows.Media.MediaContextNotificationWindow..ctor(MediaContext ownerMediaContext)
   at System.Windows.Media.MediaContext..ctor(Dispatcher dispatcher)
   at System.Windows.Media.MediaContext.From(Dispatcher dispatcher)
   at System.Windows.Interop.HwndTarget..ctor(IntPtr hwnd)
   at System.Windows.Interop.HwndSource.Initialize(HwndSourceParameters parameters)
   at System.Windows.Interop.HwndSource..ctor(HwndSourceParameters parameters)
   at Microsoft.VisualStudio.XSurface.Wpf.DesignerSurface.CreateSource()

In the \\ddfiles\Team\XAML\User\chabiss\ShadowCache\11519015903x64DA\WpfSurface.runtimeConfig.json

With 
  "configProperties": {
      "Microsoft.NETCore.DotNetHostPolicy.SetAppPaths": true
    }

Assembly binding should *always* look first in the shadow cache folder and falls into C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0?  If the self-contained payload is accurately inside the Shadow cache, what gives here? 

 **Expected behavior:**
 
WPF doesn't throw

 **Minimal repro:**
cloned the project at https://github.com/DivoPL/WpfAppCore

Open the project in Visual Studio. 
Build the project first
Then open MainPage.xaml

---

@rladuca commented on [Wed Oct 30 2019](https://github.com/dotnet/installer/issues/5417#issuecomment-548107639)

Transferred here as per discussion.

FYI @nguerrera @chabiss

**Comment by nguerrera** [comment]
The designer has implemented a work around for this, but this should track a more robust fix, which we've discussed. I'll document the changes that would be needed here for that.

**Comment by nguerrera** [comment]
See also:

* Original feature request for the designer support: https://github.com/dotnet/sdk/issues/2707
* Original implementation of the feature: https://github.com/dotnet/sdk/pull/2895

**Comment by nguerrera** [comment]
Relevant code:

https://github.com/dotnet/sdk/blob/f98197d56b051f8c5078e9017de1ef7046125205/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DesignerSupport.targets#L47-L70

https://github.com/dotnet/sdk/blob/f98197d56b051f8c5078e9017de1ef7046125205/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DesignerSupport.targets#L126-L140

Notice how SelfContained is always false and we filter out nuget and runtime pack assets from the asset group. The design was assuming that the designer would only copy the files we put in the output group to the shadow cache location. NuGet deps can be loaded from global packages folder and the runtime can always be from shared fx. 

This approach would have saved on files being copied, but is problematic because user code under design can depend on various loose files and what not being next to various dlls. Given that, the designer opts to wholesale copy the bin folder. This creates a discrepancy between our shared framework config and the actual self-contained payload that is copied.

My recommendation for a fix here would be to stop removing the runtime pack and nuget assets from the output group but instead add some metadata to them saying what they are for. The designer can then take anything tagged as being from the runtime and exclude it from the shadow copy. This would eliminate having to copy the entire runtime to shadow cache if app is self-contained, make the runtime config work, but still let the designer bulk copy any other loose files that may need to be in bin.
