### ISSUE TITLE
Can not install dotnet-ef through CLI (Unauthorized)

### ISSUE THREAD

**Issue by Think3wang** [dotnet/sdk#11837]
I am trying to install dotnet-ef package through dotnet cli, how ever it gave me 401 (Unauthorized) error.

The command I run is ```dotnet tool install --global dotnet-ef```
what I don't understand is, the dotnet-ef is a public package that anyone can install, what is this "authorized" about? 

The detailed result I got is : 

```
C:\Program Files\dotnet\sdk\3.1.300\NuGet.targets(128,5): error : Unable to load the service index for source https://microsoft.pkgs.visualstudio.com/_packaging/Universal.Store/nuget/v3/index.json. [C:\Users\<myUserName>\AppData\Local\Temp\wojjcmbm.aon\restore.csproj]
C:\Program Files\dotnet\sdk\3.1.300\NuGet.targets(128,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\<myUserName>\AppData\Local\Temp\wojjcmbm.aon\restore.csproj]
```

**Comment by joeloff** [comment]
The authentication relates to the package feed it's trying to access. Check your global nuget.config file for that package source and potentially remove it.

You can also try to run with ```--ignore-failed-sources```.

**Comment by RehanSaeed** [comment]
I'm getting the same issue. I'm not using any custom nuget.config files. These are my listed packages. I'm getting this error with .NET 5.0.100.

```
dotnet nuget list source
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

**Comment by gifthove** [comment]
If you have many sources for packages you will need to include " --ignore-failed-sources", this worked for me. 
`dotnet tool install --global dotnet-ef --version 5.0.13 --ignore-failed-sources`

**Comment by prags9** [comment]
> The authentication relates to the package feed it's trying to access. Check your global nuget.config file for that package source and potentially remove it. You can run `dotnet nuget list source` to see which sources you are using by default.
> 
> You can also try to run with `--ignore-failed-sources`.

I had to add nuget.config file with the following content - 

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="NuGet Public" value="https://api.nuget.org/v3/index.json" />
  </packageSources>   
</configuration>

**Comment by umerkle** [comment]
> > The authentication relates to the package feed it's trying to access. Check your global nuget.config file for that package source and potentially remove it. You can run `dotnet nuget list source` to see which sources you are using by default.
> > You can also try to run with `--ignore-failed-sources`.
> 
> I had to add nuget.config file with the following content -

@prags9 
What content? A dash?

**Comment by deadlydog** [comment]
I had some additional custom sources. Just using `--ignore-failed-sources` wasn't enough. I went into Visual Studio -> Tools -> Options -> NuGet Package Manager -> Package Sources and unchecked the extra package sources so only `nuget.org` and `Microsoft Visual Studio Offline Packages` was left checked. After doing that I was able to install the tool using `dotnet tool install dotnet-ef --global --ignore-failed-sources`, and then I re-enabled my custom package sources.

**Comment by markopavic** [comment]
I confirm: --ignore-failed-sources, isn't working, still getting 401 (Unauthorized). 
I temporarely removed the additional sources from the global nuget config file, then I was able to succesfully run dotnet tool install --global dotnet-ef

**Comment by CoolDadTx** [comment]
Same issue here. `--ignore-failed-sources` used to work but somewhere along the way it now fails. I have custom sources and have had to use that flag for years but after updating to NET 8 it doesn't seem to work anymore.  Seems like a regression bug.

**Comment by whiskycompiler** [comment]
Same issue. I get this:
```
PS C:\Users\whisky\Desktop\test> dotnet tool update --global dotnet-ef --ignore-failed-sources
Unhandled exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.LoadRegistrationIndexAsync(HttpSource httpSource, Uri registrationUri, String packageId, SourceCacheContext cacheContext, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.GetMetadataAsync(String packageId, Boolean includePrerelease, Boolean includeUnlisted, VersionRange range, SourceCacheContext sourceCacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.GetMetadataAsync(String packageId, Boolean includePrerelease, Boolean includeUnlisted, SourceCacheContext sourceCacheContext, ILogger log, CancellationToken token)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetPackageMetadataAsync(PackageSource source, String packageIdentifier, Boolean includePrerelease, Boolean includeUnlisted, CancellationToken cancellationToken)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetMatchingVersionInternalAsync(String packageIdentifier, IEnumerable`1 packageSources, VersionRange versionRange, CancellationToken cancellationToken)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetBestPackageVersionAsync(PackageId packageId, VersionRange versionRange, PackageSourceLocation packageSourceLocation)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.<>c__DisplayClass8_0.<InstallPackage>b__0()
   at Microsoft.DotNet.Cli.TransactionalAction.Run[T](Func`1 action, Action commit, Action rollback)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.<>c__DisplayClass20_0.<Execute>b__1()
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.RunWithHandlingInstallError(Action installAction)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
   at Microsoft.DotNet.Tools.Tool.Update.ToolUpdateGlobalOrToolPathCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

The workaround that worked for me:
1. Create a nuget config that only references the nuget.org feed:
```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="public" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

2. call `dotnet tool update --global dotnet-ef --configfile .\nuget.config` referencing the clean nuget.config

**Comment by jepperaskdk** [comment]
If the problem is that the feed is not public, you can install the CredentialProvider to make dotnet commands prompt for login:
https://github.com/microsoft/artifacts-credprovider

**Comment by pablo-sk** [comment]
I have the same problem on Azure DevOps.

.Net 9
Agent: Windows-Latest


dotnet new tool-manifest
dotnet tool install dotnet-reportgenerator-globaltool --ignore-failed-sources --version 5.4.4 --verbosity diag
reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"


==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.247.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\6f92bcae-fd2c-47b0-b5fb-20d25acf275c.ps1'"
The template "Dotnet local tool manifest file" was created successfully.

[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/index.json
[NuGet Manager] [Info]   GET https://pkgs.dev.azure.com/XXXXXX/_packaging/10525e33-eabc-45e6-94a3-c0f7245dc7b9/nuget/v3/registrations2-semver2/dotnet-reportgenerator-globaltool/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/index.json 174ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/page/4.0.0-alpha10/4.2.16.json
[NuGet Manager] [Info]   Unauthorized https://pkgs.dev.azure.com/XXXXXXXXX/_packaging/10525e33-eabc-45e6-94a3-c0f7245dc7b9/nuget/v3/registrations2-semver2/dotnet-reportgenerator-globaltool/index.json 187ms
Unhandled exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.LoadRegistrationIndexAsync(HttpSource httpSource, Uri registrationUri, String packageId, SourceCacheContext cacheContext, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.GetMetadataAsync(String packageId, Boolean includePrerelease, Boolean includeUnlisted, VersionRange range, SourceCacheContext sourceCacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.GetMetadataAsync(String packageId, Boolean includePrerelease, Boolean includeUnlisted, SourceCacheContext sourceCacheContext, ILogger log, CancellationToken token)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetPackageMetadataAsync(PackageSource source, String packageIdentifier, Boolean includePrerelease, Boolean includeUnlisted, CancellationToken cancellationToken)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetPackageMetadataAsync(String packageIdentifier, NuGetVersion packageVersion, IEnumerable`1 sources, CancellationToken cancellationToken, Boolean includeUnlisted)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetPackageSourceAndVersion(PackageId packageId, NuGetVersion packageVersion, PackageSourceLocation packageSourceLocation, Boolean includePreview, Boolean includeUnlisted, PackageSourceMapping packageSourceMapping)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.DownloadPackageAsync(PackageId packageId, NuGetVersion packageVersion, PackageSourceLocation packageSourceLocation, Boolean includePreview, Nullable`1 includeUnlisted, Nullable`1 downloadFolder, PackageSourceMapping packageSourceMapping)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.DownloadAndExtractPackage(PackageId packageId, INuGetPackageDownloader nugetPackageDownloader, String packagesRootPath, NuGetVersion packageVersion, PackageSourceLocation packageSourceLocation, Boolean includeUnlisted)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.<>c__DisplayClass9_0.<InstallPackage>b__0()
   at Microsoft.DotNet.Cli.TransactionalAction.Run[T](Func`1 action, Action commit, Action rollback)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallLocalInstaller.Install(FilePath manifestFile, PackageId packageId)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallLocalCommand.InstallNewTool(FilePath manifestFile, PackageId packageId)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallLocalCommand.ExecuteInstallCommand(PackageId packageId)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallLocalCommand.Execute()
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)

**Comment by ccarmannt** [comment]
How can this still be a bug 5 YEARS later?

**Comment by marthijn** [comment]
Same problem here since a few days. Restore and build tasks (with private package feed) work fine, the tool install command fails (even with `--ignore-failed-sources`).

**Comment by oltkachenk** [comment]
I was able to install EF with `dotnet tool install --global dotnet-ef` command outside of project directory

**Comment by Rene-Sackers** [comment]
Yeah how is this still a thing.. `--ignore-failed-sources` doesn't solve it for me. Here's the only solution that worked for me; disabling all NuGet sources that aren't `https://api.nuget.org/v3/index.json`.
Open your NuGet.config, should be: `%appdata%\NuGet\NuGet.Config`

Add `<disabledPackageSources>` and add keys for all but the official NuGet feed:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="YourAuthenticatedFeed" value="https://example.com/nuget/v3/index.json" />
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
  </packageSources>
  <disabledPackageSources>
    <add key="YourAuthenticatedFeed" value="true" />
    <add key="Microsoft Visual Studio Offline Packages" value="true" />
  </disabledPackageSources>
</configuration>
```

If you have Rider, you can do this through UI in the NuGet packkage manger -> sources tab:
<img width="999" height="277" alt="Image" src="https://github.com/user-attachments/assets/c2bd55ea-02b6-469d-9aff-1b17f57eda82" />

You could also just temporarily cut the other feeds from the config file, I suppose. I just did it through the Rider UI, hence the disable keys was the way it worked for me.

Now the tool installs fine. Of course, remove the `<disabledPackageSources>` afterwards.

**Comment by CoolDadTx** [comment]
@Rene-Sackers Yes, this is shocking that it is still broken after 6 years even though dotnet is heavily used everywhere and many people probably have private, authenticated feeds. But your solution is probably more complex than you actually need. 

dotnet, like other Nuget tooling, follows a hierarchy to figure out the Nuget configuration. The easiest workaround, when possible, is to simply create a local nuget.config file in the working directory from which dotnet will try to restore packages. Local nuget.config files override higher level configs. So all you need to do is have a blank nuget.config file that contains just the main nuget feed listed in it. Place it in the working folder that you're going to restore and then run dotnet. It'll use your local config instead of what is globally configured. Personally I drop the file in, restore packages and then remove/rename it. There isn't a need to edit your existing file and restore it. Of course all this is predicated on you being able to modify the working directory to begin with.

At this point I've lost all hope that they'll eventually fix this as it has been several NET Core releases since this was originally found. The tooling has been updated but this bug has yet to be fixed. They just don't seem to care.

**Comment by AndreyBespamyatnov** [comment]
needs more Copilot integrations, it will 100% sure fix all of these issues

**Comment by szmynczyk** [comment]
I found a solution working for me: on the beginning I was trying to update ef tools in "regular" powershell, but it didn't update it for developer powershell which I use in Visual Studio 2022/2026. Next I just opened developer powershell in windows (not in Visual Studio), ran the command `dotnet tool update --global dotnet-ef` and it worked fine. After checking in developer powershell in VS 2026 I have the newest version of ef tools installed
