### ISSUE TITLE
GenerateRuntimeConfigurationFiles task failed unexpectedly on a project targeting netcoreapp1.0

### ISSUE THREAD

**Issue by prafullbhosale** [dotnet/sdk#1189]
### Setup: 
CLI Version : 2.0.0-preview1-005972
VS Version: d15rel 26507.0

### Repro steps: 

1. Create a new Asp.NET Core Web application (1.0) in VS
2. Add a global.json with `{ "sdk" : { "version": "1.0.4" } }`
3. Right click project -> Publish -> Folder -> Publish.

It fails with the error 
```
C:\Program Files\dotnet\sdk\2.0.0-preview1-005972\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(134,5): Error MSB4018: The "GenerateRuntimeConfigurationFiles" task failed unexpectedly.
System.InvalidCastException: [A]NuGet.ProjectModel.LockFile cannot be cast to [B]NuGet.ProjectModel.LockFile. Type A originates from 'NuGet.ProjectModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' in the context 'LoadFrom' at location 'C:\Program Files\dotnet\sdk\1.0.4\Sdks\Microsoft.NET.Sdk\tools\net46\NuGet.ProjectModel.dll'. Type B originates from 'NuGet.ProjectModel, Version=4.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' in the context 'LoadFrom' at location 'C:\Program Files\dotnet\sdk\2.0.0-preview1-005972\Sdks\Microsoft.NET.Sdk\tools\net46\NuGet.ProjectModel.dll'.
   at Microsoft.NET.Build.Tasks.LockFileCache.GetLockFile(String path)
   at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

cc @vijayrkn @mlorbetske @balachir

**Comment by vijayrkn** [comment]
@nguerrera 
Does the msbuild resolver look for global.json sdk version, when determining which sdk to use?

**Comment by nguerrera** [comment]
It does, but it seems that somehow we're not getting the same directory information from msbuild and so some things are not finding global.json. This causes a mix of 1.0.4 and latest to be used. cc @AndyGerlicher 

```
  <!--
============================================================================================================================================
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk.Web">
  This import was added implicitly because of the Project element's Sdk attribute specified "Microsoft.NET.Sdk.Web".

C:\Program Files\dotnet\sdk\1.0.4\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props
============================================================================================================================================
-->
  <!--
***********************************************************************************************
Sdk.props

WARNING:  DO NOT MODIFY this file unless you are knowledgeable about MSBuild and have
          created a backup copy.  Incorrect changes to this file will make it
          impossible to load or build your projects from the command-line or the IDE.

Copyright (c) .NET Foundation. All rights reserved. 
***********************************************************************************************
-->
  <!--
============================================================================================================================================
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk">
  This import was added implicitly because of the Project element's Sdk attribute specified "Microsoft.NET.Sdk".

C:\Program Files\dotnet\sdk\2.0.0-preview1-005957\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props
```

**Comment by nguerrera** [comment]
Debugging this, there are several layers of issues here:

* The ProjectFilePath that is used when no SolutionFilePath is available is actually the importing project path and not the csproj we expected (Microsoft/msbuild#2083). 
  * So when the csproj imports the web sdk, we respect the global.json and get web sdk 1.0.4, but then when the web sdk imports the net sdk, we don't see a global.json at the web sdk location and so we get the latest net sdk instead of matching 1.0.4 sdk. 

* On the command line, we sometimes get "*Undefined*" instead of null (microsoft/msbuild#2082) for SolutionFilePath when building a single project. This can cause a similar issue on the command line, but the repro here is in the IDE so it's not the cause.

* In the IDE, we almost always get a correct SolutionFilePath from CPS evaluation, but Microsoft.VisualStudio.Web.Publish.dll appears to do its own msbuild evaluations without setting SolutionPath. 
  * @prafullbhosale Where should I log the issue against Microsoft.VisualStudio.Web.Publish.dll? I haven't checked what this code is doing, but I think it should be asking the project system and not using the msbuild evaluation API directly (cc @davkean).

Stack when MS.VS.Web.Publish evaluates the project without providing SolutionPath:
```
Microsoft.Build.dll!Microsoft.Build.Evaluation.ProjectCollection.LoadProject(string fileName, System.Collections.Generic.IDictionary<string, string> globalProperties, string toolsVersion)
Microsoft.VisualStudio.Web.Publish.dll!Microsoft.VisualStudio.Web.Publish.VisualStudio.ProjectK.DotNetCoreWebProject.GetFolderPathWithFilesToDeploy(Microsoft.VisualStudio.Web.Publish.Model.BuildConfigEntity slnConfig)
Microsoft.VisualStudio.Web.Publish.dll!Microsoft.VisualStudio.Web.Publish.PublishWorkFlowFactory.CreatePublishWorker(Microsoft.VisualStudio.Web.Publish.MSBuild.PublishOutputToVsShell outputToShell, Microsoft.VisualStudio.Web.Publish.IPublishableProject project, Microsoft.VisualStudio.Web.Publish.Model.LegacyPublishProfile profile, Microsoft.VisualStudio.Web.Publish.Model.BuildConfigEntity buildConfigToRestoreOnPostPublish)
Microsoft.VisualStudio.Web.Publish.dll!Microsoft.VisualStudio.Web.Publish.PublishWorkFlowFactory.CreatePublishWorker(Microsoft.VisualStudio.Web.Publish.MSBuild.PublishOutputToVsShell outputToShell, Microsoft.VisualStudio.Web.Publish.IPublishableProject project, Microsoft.VisualStudio.Web.Publish.Model.PublishProfileModel profile, Microsoft.VisualStudio.Web.Publish.VSMsDeployTaskHostObject hostObject, Microsoft.VisualStudio.Web.Publish.Model.BuildConfigEntity buildConfigToRestoreOnPostPublish)
Microsoft.VisualStudio.Web.Publish.dll!Microsoft.VisualStudio.Web.Publish.ProjectPublishData.PublishWithAProfile(Microsoft.VisualStudio.Web.Publish.Model.PublishProfileModel profile)
Microsoft.VisualStudio.Web.Publish.dll!Microsoft.VisualStudio.Web.Publish.ProjectPublishData.PublishWithAProfile(string profileName)
Microsoft.VisualStudio.Web.Publish.dll!Microsoft.VisualStudio.Web.Publish.PublishService.VsWebProjectPublish.PublishAsync(string profileName)
Microsoft.VisualStudio.ApplicationCapabilities.Publish.Web.dll!Microsoft.VisualStudio.ApplicationCapabilities.Publish.Web.WebPublishRequirements.DefaultWebPublishSteps.WebPublishAsync(string id)
Microsoft.VisualStudio.ApplicationCapabilities.Publish.dll!Microsoft.VisualStudio.ApplicationCapabilities.Publish.Model.DefaultPublishSteps.get_CorePublish.AnonymousMethod__0(string id)
Microsoft.VisualStudio.ApplicationCapabilities.Publish.dll!Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.PublishProfileAsync()
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<PublishProfileAsync>d__73>(ref Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<PublishProfileAsync>d__73 stateMachine)
Microsoft.VisualStudio.ApplicationCapabilities.Publish.dll!Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.PublishProfileAsync()
Microsoft.VisualStudio.ApplicationCapabilities.Publish.dll!Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.PublishProfile()
Microsoft.VisualStudio.ApplicationCapabilities.Publish.dll!Microsoft.VisualStudio.ApplicationCapabilities.Publish.View.Framework.ActionCommand.From.AnonymousMethod__0(object o)
Microsoft.VisualStudio.ApplicationCapabilities.Publish.dll!Microsoft.VisualStudio.ApplicationCapabilities.Publish.View.Framework.ActionCommand.Execute(object parameter)
```

**Comment by nguerrera** [comment]
@dsplaisted @johnbeisner

**Comment by nguerrera** [comment]
This issue was moved to dotnet/cli#6553

**Comment by nguerrera** [comment]
Moved to CLI because the resolver is implemented there.

**Comment by vijayrkn** [comment]
@nguerrera for the publish issue, the code is in tfs and we will fix it.
