### ISSUE TITLE
GenerateRuntimeConfigurationFiles fails with a crash if it doesn't find the runtimeconfig.json

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#1234]
1. File -> New Console App
2. Right-click project, and choose Edit ConsoleApp1.csproj
3. Change target framework to net48
4. Build:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "GenerateRuntimeConfigurationFiles" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\davkean\Source\Repos\ConsoleApp4\ConsoleApp4\bin\Debug\net48\ConsoleApp4.runtimeconfig.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteToJsonFile(String fileName, Object value)
   at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.WriteRuntimeConfig(ProjectContext projectContext)
   at Microsoft.NET.Build.Tasks.GenerateRuntimeConfigurationFiles.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ConsoleApp4	C:\Program Files\dotnet\sdk\1.0.4\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets	129	
```

**Comment by nguerrera** [comment]
It's *writing* the RuntimeConfig, not looking for it, but the output directory doesn't exist yet, which is odd.

**Comment by nguerrera** [comment]
Looks related to https://github.com/Microsoft/msbuild/issues/2116

**Comment by nguerrera** [comment]
@dsplaisted
