### ISSUE TITLE
GenerateDepsFile Build Error: An item with the same key has already been added.

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/sdk#12473]
---
**Issue moved from microsoft/msbuild#5509**
- Please respond to @rlmartins76.

---

_From @rlmartins76 on Sunday, July 12, 2020 9:06:17 PM_

```
C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly.
C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018: System.ArgumentException: An item with the same key has already been added.
C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.Extensions.DependencyModel.DependencyContextWriter.WritePortableTarget(IReadOnlyList`1 runtimeLibraries, IReadOnlyList`1 compilationLibraries)
C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.Extensions.DependencyModel.DependencyContextWriter.WriteTargets(DependencyContext context)
C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.Extensions.DependencyModel.DependencyContextWriter.Write(DependencyContext context)
C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.Extensions.DependencyModel.DependencyContextWriter.Write(DependencyContext context, Stream stream)
C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath)
C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore()
C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(194,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by mikegoatly** [comment]
I'm getting this too - I'm not 100% sure, but I think it may have started since I updated to the latest Visual Studio Preview release (16.7.0 Preview 6.0).

Cleaning the solution, removing obj/bin folders has no effect - on the next build the error reoccurs. I currently only have access to one machine, but this repo continually fails to build for me: https://github.com/mikegoatly/html2md - it would be interesting to see if that's reproducible for anyone else.

**Comment by mikegoatly** [comment]
Figured my problem out - I'd changed the `PackageId` of a project to a name that matched the name of another project that referenced it. To be honest I didn't expect the PackageId to have any effect when using a project reference, but you live and learn.

**Comment by bbrowndpi** [comment]
Visual Studio v17.0.2. ASP.Net Core 6.0 project. 
I modified Project Properties->Win32 Resources and set an icon image file in the Icon field.
In Project Properties->Package I've also set a png file in the Icon field.
When I try to compile I get the GenerateDepsFile build error. If I remove the Package Icon file, I am able to build the project.

**Comment by Thomasdb05** [comment]
I get the same problem when I include the dll to a class library I made, it goes away when I remove the reference to the library.

**Comment by jeanplevesque** [comment]
> Figured my problem out - I'd changed the `PackageId` of a project to a name that matched the name of another project that referenced it. To be honest I didn't expect the PackageId to have any effect when using a project reference, but you live and learn.

I've had the same problem, but in my case I had 2 projects with the same `AssemblyName` (and different values for `PackageId`).

**Comment by markus27183** [comment]
My solution and projects had the same name as the referenced dll.  I changed them and it worked.

**Comment by lbosquett** [comment]
same issue, a project was added as a reference with the same name:

`Company.Foo.csproj` file:

```
<Reference Include="Company.Foo">
  <HintPath>..\Packages\SomethingElse.dll</HintPath>
</Reference>
```

removing it did the trick

**Comment by devtekve** [comment]
> same issue, my IDE added a reference to a csproj file where the name of the Reference was the same as the project
> 
> `Company.Foo.csproj` file:
> 
> ```
> <Reference Include="Company.Foo">
>   <HintPath>..\Packages\SomethingElse.dll</HintPath>
> </Reference>
> ```
> 
> removing it did the trick

Thanks! This was exactly what it was !

**Comment by UweKeim** [comment]
For me, this error occurred since .NET SDK 9.0.300. Below 300, the issue did not occur with .NET SDK 9.

[This workaround helped me](https://github.com/dotnet/aspnetcore/issues/59625#issuecomment-2809271725).
