### ISSUE TITLE
NullReferenceException when running dotnet new command in Ubuntu

### ISSUE THREAD

**Issue by t-bzhan** [dotnet/sdk#13474]
We get NullReferenceException  when running dotnet new related commands in Ubuntu, the error message is like:

> dotnet -d new console
> Telemetry is: Enabled
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.DotNet.Cli.Utils.Muxer..ctor()
>    at Microsoft.DotNet.Tools.New.NewCommandShim.CreateHost()
>    at Microsoft.DotNet.Tools.New.NewCommandShim.Run(String[] args)
>    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
>    at Microsoft.DotNet.Cli.Program.Main(String[] args)

dotnet -info outputs:

> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.402
>  Commit:    9b5de826fd
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  16.04
>  OS Platform: Linux
>  RID:         ubuntu.16.04-x64
>  Base Path:   /usr/share/dotnet/sdk/3.1.402/
> 
> Host (useful for support):
>   Version: 3.1.8
>   Commit:  9c1330dedd
> 
> .NET Core SDKs installed:
>   3.1.402 [/usr/share/dotnet/sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download

OS related information:

> cat /etc/os-release
> NAME="Ubuntu"
> VERSION="16.04.6 LTS (Xenial Xerus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 16.04.6 LTS"
> VERSION_ID="16.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
> VERSION_CODENAME=xenial
> UBUNTU_CODENAME=xenial

**Comment by dsplaisted** [comment]
Looks like it's throwing a null reference exception on this line:

https://github.com/dotnet/sdk/blob/710d762423473ecef1656ad58f04de05d519f2f6/src/Cli/Microsoft.DotNet.Cli.Utils/Muxer.cs#L39

**Comment by tremblaysimon** [comment]
Can't reproduce with Ubuntu 20.04.6 and .NET 6.0.417

```
simon@simon-machine:~/workspace/test-sdk$ dotnet -d new console
Telemetry is: Enabled
[2023-12-19 08:42:57.101] [Debug] [Microsoft.TemplateEngine.Cli.CliTemplateEngineHost] => [Execute]: Execute started
[2023-12-19 08:42:57.174] [Debug] [Microsoft.TemplateEngine.Cli.CliTemplateEngineHost] => [Execute] => [Template from config /usr/share/dotnet/templates/6.0.25/microsoft.dotnet.common.projecttemplates.6.0.6.0.417.nupkg/content/ConsoleApplication-CSharp/.template.config/template.json]: Template from config /usr/share/dotnet/templates/6.0.25/microsoft.dotnet.common.projecttemplates.6.0.6.0.417.nupkg/content/ConsoleApplication-CSharp/.template.config/template.json started
[2023-12-19 08:42:57.179] [Debug] [Microsoft.TemplateEngine.Orchestrator.RunnableProjects.RunnableProjectGenerator] => [Execute] => [Template from config /usr/share/dotnet/templates/6.0.25/microsoft.dotnet.common.projecttemplates.6.0.6.0.417.nupkg/content/ConsoleApplication-CSharp/.template.config/template.json]: The template configuration /usr/share/dotnet/templates/6.0.25/microsoft.dotnet.common.projecttemplates.6.0.6.0.417.nupkg(/content/ConsoleApplication-CSharp/.template.config/template.json) is missing common information:
  One or more postActions have a malformed or missing manualInstructions value.

[2023-12-19 08:42:57.190] [Debug] [Microsoft.TemplateEngine.Cli.CliTemplateEngineHost] => [Execute] => [Template from config /usr/share/dotnet/templates/6.0.25/microsoft.dotnet.common.projecttemplates.6.0.6.0.417.nupkg/content/ConsoleApplication-CSharp/.template.config/template.json]: Template from config /usr/share/dotnet/templates/6.0.25/microsoft.dotnet.common.projecttemplates.6.0.6.0.417.nupkg/content/ConsoleApplication-CSharp/.template.config/template.json finished, took 16 ms
[2023-12-19 08:42:57.191] [Debug] [Microsoft.TemplateEngine.Edge.Template.TemplateCreator] => [Execute] => [Template content generation]: Template content generation started
[2023-12-19 08:42:57.350] [Debug] [Microsoft.TemplateEngine.Edge.Template.TemplateCreator] => [Execute] => [Template content generation]: Template content generation finished, took 159 ms
The template "Console App" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /home/simon/workspace/test-sdk/test-sdk.csproj...
  Determining projects to restore...
  Restored /home/simon/workspace/test-sdk/test-sdk.csproj (in 81 ms).
Restore succeeded.


[2023-12-19 08:42:58.064] [Debug] [Microsoft.TemplateEngine.Cli.CliTemplateEngineHost] => [Execute]: Execute finished, took 964 ms
simon@simon-machine:~/workspace/test-sdk$
