### ISSUE TITLE
System.ArgumentException: Invalid input specification: Found multiple entries with the same BundleRelativePath

### ISSUE THREAD

**Issue by ppekrol** [dotnet/sdk#13777]
Hi,

I'm trying to use the Single File Applications (SFA) in .NET 5.0 RC, but I'm getting following exception:

```
2>The "GenerateBundle" task failed unexpectedly.
2>System.ArgumentException: Invalid input specification: Found multiple entries with the same BundleRelativePath
2>   at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs)
2>   at Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore()
2>   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
2>   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

I've tracked down the issue to this NuGet package `Microsoft.Diagnostics.Tracing.TraceEvent` (version 2.0.61). Creating an empty  console app and publishing SFA yields that exception. Is this a bug or I'm doing something wrong?

```
Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]
```

**Comment by ppekrol** [comment]
Any guidance?

**Comment by frederik-hoeft** [comment]
Same problem here
