### ISSUE TITLE
Building from NFS: The last access/last write time on file cannot be set

### ISSUE THREAD

**Issue by emmenlau** [dotnet/sdk#13808]
I'm working with sources on an NFS mapped drive on Windows 10 2004. The drive is mapped with the Microsoft Windows NFSv3 client. User and group IDs are mapped to the correct Linux server user/group IDs. I can read and write from the drive without problems.

But when I try to build a .NET Core 3.1 project with dotnet 3.1.402, the build fails very early with error:
```
C:\Program Files\dotnet\sdk\3.1.402\Microsoft.Common.CurrentVersion.targets(4385,5): error MSB3374: The last access/last write time on file "U:\Source\thrift\lib\netstd\Tests\Thrift.PublicInterfaces.Compile.Tests\obj\cygwin\Debug\netcoreapp3.1\Thrift.PublicInterfaces.Compile.Tests.csproj.CopyComplete" cannot be set. The parameter is incorrect. : 'U:\Source\thrift\lib\netstd\Tests\Thrift.PublicInterfaces.Compile.Tests\obj\cygwin\Debug\netcoreapp3.1\Thrift.PublicInterfaces.Compile.Tests.csproj.CopyComplete' [U:\Source\thrift\lib\netstd\Tests\Thrift.PublicInterfaces.Compile.Tests\Thrift.PublicInterfaces.Compile.Tests.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. [U:\Source\thrift\lib\netstd\Tests\Thrift.IntegrationTests\Thrift.IntegrationTests.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: System.IO.IOException: The parameter is incorrect. : 'U:\Source\thrift\lib\netstd\Tests\Thrift.IntegrationTests\obj\cygwin\Debug\netcoreapp3.1\Thrift.IntegrationTests.exe' [U:\Source\thrift\lib\netstd\Tests\Thrift.IntegrationTests\Thrift.IntegrationTests.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at System.IO.FileSystem.SetLastWriteTime(String fullPath, DateTimeOffset time, Boolean asDirectory) [U:\Source\thrift\lib\netstd\Tests\Thrift.IntegrationTests\Thrift.IntegrationTests.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc) [U:\Source\thrift\lib\netstd\Tests\Thrift.IntegrationTests\Thrift.IntegrationTests.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.HostModel.RetryUtil.RetryOnIOError(Action func) [U:\Source\thrift\lib\netstd\Tests\Thrift.IntegrationTests\Thrift.IntegrationTests.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [U:\Source\thrift\lib\netstd\Tests\Thrift.IntegrationTests\Thrift.IntegrationTests.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [U:\Source\thrift\lib\netstd\Tests\Thrift.IntegrationTests\Thrift.IntegrationTests.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. [U:\Source\thrift\lib\netstd\Benchmarks\Thrift.Benchmarks\Thrift.Benchmarks.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018: System.IO.IOException: The parameter is incorrect. : 'U:\Source\thrift\lib\netstd\Benchmarks\Thrift.Benchmarks\obj\cygwin\Debug\netcoreapp3.1\Thrift.Benchmarks.exe' [U:\Source\thrift\lib\netstd\Benchmarks\Thrift.Benchmarks\Thrift.Benchmarks.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at System.IO.FileSystem.SetLastWriteTime(String fullPath, DateTimeOffset time, Boolean asDirectory) [U:\Source\thrift\lib\netstd\Benchmarks\Thrift.Benchmarks\Thrift.Benchmarks.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc) [U:\Source\thrift\lib\netstd\Benchmarks\Thrift.Benchmarks\Thrift.Benchmarks.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.HostModel.RetryUtil.RetryOnIOError(Action func) [U:\Source\thrift\lib\netstd\Benchmarks\Thrift.Benchmarks\Thrift.Benchmarks.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom) [U:\Source\thrift\lib\netstd\Benchmarks\Thrift.Benchmarks\Thrift.Benchmarks.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() [U:\Source\thrift\lib\netstd\Benchmarks\Thrift.Benchmarks\Thrift.Benchmarks.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [U:\Source\thrift\lib\netstd\Benchmarks\Thrift.Benchmarks\Thrift.Benchmarks.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [U:\Source\thrift\lib\netstd\Benchmarks\Thrift.Benchmarks\Thrift.Benchmarks.csproj]
C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(424,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [U:\Source\thrift\lib\netstd\Benchmarks\Thrift.Benchmarks\Thrift.Benchmarks.csproj]
```

I can understand from the error that .NET tries to update a time stamp, and this seems to fail. But I assume that time stamp updates are possible on NFS mapped drives because I can see correct file creation time stamps. Or is there something fundamental broken?

**Comment by zerovian** [comment]
Also running into this on an NFS mounted drive:

<removed>\dotnetcore\3.1.403\sdk\3.1.403\Microsoft.Common.CurrentVersion.targets(4385,5): error MSB3374: The last access/last write time on file "<removed>.csproj.CopyComplete" cannot be set. The parameter is incorrect. : '<removed>\obj\x64\Debug\netstandard2.0\o4glrt.csproj.CopyComplete' [<removed>.csproj]
    780 Warning(s)
    1 Error(s)


this is causing my builds to fail and I cannot migrate my library to .net core.

$> dotnet --version
3.1.4031

running this inside a cygwin shell on an NFS mounted drive.

**Comment by zerovian** [comment]
Please note that my project is hosted in a clearcase VOB mounted on Windows.

In case it helps this is how the drive  shows up using 'mount' command from cygwin. I'm running dotnet under cygwin shell as most of our build scripts are cross platform we use cygwin on windows.

Z: on /cygdrive/z type mvfs (binary,noacl,posix=0,noumount,auto)

**Comment by zerovian** [comment]
Running with -v diag shows this:

                             bin\x64\Debug\netstandard2.0\zh-TW\Progress.Messages.resources.dll
                             bin\x64\Debug\netstandard2.0\zh\Progress.Messages.resources.dll (TaskId:58)
                   Done executing task "Copy". (TaskId:58)
                   Using "Touch" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
                   Task "Touch" (TaskId:59)
                     Task Parameter:Files=Z:\vobs_prgs\src\dotnet\o4glrt\obj\x64\Debug\netstandard2.0\o4glrt.csproj.CopyComplete (TaskId:59)
                     Task Parameter:AlwaysCreate=True (TaskId:59)
                     Touching "Z:\vobs_prgs\src\dotnet\o4glrt\obj\x64\Debug\netstandard2.0\o4glrt.csproj.CopyComplete". (TaskId:59)
14:14:24.140   1:7>\\rdlserv\tools\nt64\dotnetcore\3.1.403\sdk\3.1.403\Microsoft.Common.CurrentVersion.targets(4385,5): error MSB3374: The last access/last write time on file "Z:\vobs_prgs\src\dotnet\o4glrt\obj\x64\Debug\netstandard2.0\o4glrt.csproj.CopyComplete" cannot be set. The parameter is incorrect. : 'Z:\vobs_prgs\src\dotnet\o4glrt\obj\x64\Debug\netstandard2.0\o4glrt.csproj.CopyComplete' [Z:\vobs_prgs\src\dotnet\o4glrt\o4glrt.csproj]
                   Done executing task "Touch" -- FAILED. (TaskId:59)

**Comment by flecmart** [comment]
Running into the same problem using a clear case vob. Did you make  some progress?

**Comment by zerovian** [comment]
Our solution was to set the IntermediateOutputPath property in the top level PropertyGroup section of each of our .csproj files.

Something like this, and we ensure that TMPDIR and USER environment variables are setup in our build environments. Its a workaround, but not a solution.

    <IntermediateOutputPath>$(TMPDIR)/$(USER)/project/obj</IntermediateOutputPath>

**Comment by flecmart** [comment]
Thanks for the workaround. I can confirm that it works when you move the IntermediateOutputPath to a local path.

The strange thing is that the solution builds from inside vs studio 2019 (with IntermediateOutputPath on clearcase).

**Comment by zerovian** [comment]
Yup. same. doesn't fail when built in visual studio. only from command line.

**Comment by marcpopMSFT** [comment]
Does this still repro with current SDKs?  CC @vitek-karas @elinor-fung

**Comment by smx-smx** [comment]
I can reproduce on dotnet SDK 8.0.100 on a NFS share
```
C:\Program Files\dotnet\sdk\8.0.100\Microsoft.Common.CurrentVersion.targets(4933,5): error MSB3374: The last access/las
t write time on file "<csproj file here>CopyComplete
" cannot be set. The parameter is incorrect. : '<csproj file here>.CopyComplete' [<csproj file here>]
```

However a `touch` command from msys/cygwin on NFS works, so i'm not sure why it's not working here.
Not sure if it helps, but i found this while searching for the problem: https://github.com/mono/mono/issues/14089

**Comment by danmoseley** [comment]
Can someone confirm that SetLastWriteTime in 8.0 fails against NFS? If so please ensure there is an issue open in dotnet/runtime to make it work, or at least fail with a better message.

**Comment by smx-smx** [comment]
#### mount NFS
```
mount [remote] T:
T: is now successfully connected to [remote]
```

#### source code
```csharp
Console.WriteLine("Hello, dotnet " + Environment.Version);

var t = DateTime.Now.Subtract(TimeSpan.FromDays(1));
System.IO.File.SetLastWriteTime(@"T:\thefile.txt", t);
```

#### output
```
Hello, dotnet 8.0.0
Unhandled exception. System.IO.IOException: The parameter is incorrect. : 'T:\thefile.txt'
   at System.IO.FileSystem.SetFileTime(SafeFileHandle fileHandle, String fullPath, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.FileSystem.SetFileTime(String fullPath, Boolean asDirectory, Int64 creationTime, Int64 lastAccessTime, Int64 lastWriteTime, Int64 changeTime, UInt32 fileAttributes)
   at System.IO.FileSystem.SetLastWriteTime(String fullPath, DateTimeOffset time, Boolean asDirectory)
   at System.IO.File.SetLastWriteTime(String path, DateTime lastWriteTime)
   at Program.<Main>$(String[] args) in G:\projects\nfs-issue\Program.cs:line 4
   ```

**Comment by virzak** [comment]
This also happens when trying to build in podman in rootless mode. The `IntermediateOutputPath` workaround mentioned above is great, but setting `/P:IntermediateOutputPath=/tmp/$USER/project/obj/` every time is annoying, and editing the project file is not desired

**Comment by zerovian** [comment]
> This also happens when trying to build in podman in rootless mode. The `IntermediateOutputPath` workaround mentioned above is great, but setting `/P:IntermediateOutputPath=/tmp/$USER/project/obj/` every time is annoying, and editing the project file is not desired

we ended up creating a Directory.build.props file in the dir above the projects so we dont have to edit all the .csproj files. it contains just this setting and one other.

**Comment by virzak** [comment]
> creating a Directory.build.props

Doing the same thing now:

```xml
<PropertyGroup Condition="'$(container)' == 'podman'">
  <IntermediateOutputPath>/tmp/$(USER)/project/obj/</IntermediateOutputPath>
</PropertyGroup>
```

**Comment by nietras** [comment]
I’m seeing what appears to be the same underlying timestamp problem when building from WSL2 on a Windows-mounted filesystem. Note this is latest version for all. Incl. NET 10.

Environment:

* Windows 11: 10.0.26200.9168
* WSL: 2.7.12.0
* WSL kernel: 6.18.33.2-2
* Ubuntu 26.04
* .NET SDK: 10.0.400
* MSBuild: 18.9.6
* Repository/build directory: `/mnt/d/...`
* `/mnt/d` is mounted through WSL's 9p/DrvFs layer

The build fails with:

`MSB3374: The last access/last write time on file ".../.Up2Date" cannot be set. Access to the path ".../.Up2Date" is denied.`

I was able to isolate the problem to .NET's timestamp handling:

* `touch /mnt/d/test-file` → succeeds
* Python `os.utime()` → succeeds
* Windows PowerShell `LastWriteTime = Get-Date` → succeeds
* `.NET File.SetLastWriteTimeUtc()` → fails with `UnauthorizedAccessException` / `IOException: Operation not permitted`
* MSBuild's `<Touch>` task → fails with MSB3374

The same .NET timestamp operation works normally on the native WSL filesystem (`/tmp`).

For example:

```csharp
File.SetLastWriteTimeUtc(
    "/mnt/d/test-dotnet-timestamp",
    DateTime.UtcNow);
```

fails with:

`System.UnauthorizedAccessException: Access to the path '/mnt/d/test-dotnet-timestamp' is denied.`

while the equivalent Python `os.utime()` succeeds.

I also tested `/mnt/d` with the `metadata` mount option; the behavior was unchanged.

This may be relevant to the NFS timestamp/MSBuild issue discussed here, although in my case the filesystem is WSL's 9p/DrvFs rather than NFS. It appears that the Linux .NET timestamp implementation is incompatible with this filesystem's timestamp semantics, while the underlying filesystem itself supports timestamp updates.
