### ISSUE TITLE
cswinrt cannot run a library targeting higher SDK

### ISSUE THREAD

**Issue by wli3** [dotnet/sdk#14066]
If a cswinrt library is compiled with an higher version of SDK. A lower version of application can build with such library build cannot run. Error with:

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Windows.SDK.NET, Version=10.0.19041.7, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.Windows.SDK.NET, Version=10.0.19041.7, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at ConsoleApp21.Program.DiscoverDevices()
   at app.Program.Main(String[] args) in C:\work\temp\bugbash\1\app\Program.cs:line 10
```

**Comment by wli3** [comment]
Normal pack works since all reference assembly has the same version

**Comment by wli3** [comment]
Related https://github.com/microsoft/CsWinRT/issues/459
