### ISSUE TITLE
dotnet test <dll> -- <RunSettingsOverrides> fails with NotImplementedException

### ISSUE THREAD

**Issue by hallipr** [dotnet/sdk#14401]
When calling `dotnet test some.dll -- key=value`, I get a run time exception in CLIRunSettingsArgumentExecutor.

## Given a single test 
``` cs
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;

namespace Simple
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            Assert.AreEqual("Value", Environment.GetEnvironmentVariable("SomeThing"));
        }
    }
}
```

## in a simple test project, simple.csproj
``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="2.1.0" />
    <PackageReference Include="coverlet.collector" Version="1.2.0" />
  </ItemGroup>
  
</Project>
``` 

## After `dotnet build`, this doesn't work
```
dotnet test bin\Debug\netcoreapp3.1\simple.dll -- RunConfiguration.EnvironmentVariables.SomeThing=Value 
```

```
Microsoft (R) Test Execution Command Line Tool Version 16.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.CLIRunSettingsArgumentExecutor.Initialize(String argument)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.ArgumentProcessorFactory.<>c__DisplayClass20_0.<WrapLazyProcessorToInitializeOnInstantiation>b__0()
   at System.Lazy`1.PublicationOnlyViaFactory(LazyHelper initializer)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.GetArgumentProcessors(String[] args, List`1& processors)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.Execute(String[] args)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Program.Main(String[] args)
```

## These all work
```
dotnet vstest bin\Debug\netcoreapp3.1\simple.dll -- RunConfiguration.EnvironmentVariables.SomeThing=Value 

vstest.console .\bin\Debug\netcoreapp3.1\simple.dll -- RunConfiguration.EnvironmentVariables.SomeThing=Value

dotnet test -- RunConfiguration.EnvironmentVariables.SomeThing=Value

dotnet test simple.csproj -- RunConfiguration.EnvironmentVariables.SomeThing=Value

dotnet test --no-build -- RunConfiguration.EnvironmentVariables.SomeThing=Value
```

The last one was surprising.   I assumed that --no-build would use the same codepath as `dotnet test <dll>`, but I guess not.

**Comment by plemasantos** [comment]
Bumped into the exact same problem a couple of minutes ago.

**Comment by wli3** [comment]
This issue was moved to microsoft/vstest#2626
