### ISSUE TITLE
LDAP: System.DirectoryServices.Protocols SearchRequest don't work on linux (5.0.0-rc.2.20475.5)

### ISSUE THREAD

**Issue by mduperche** [dotnet/sdk#14414]
On linux I Received this message but on Windows it Work.
**Error message**
```
An operation error occurred.System.DirectoryServices.Protocols.DirectoryOperationException: An operation error occurred.

at System.DirectoryServices.Protocols.LdapConnection.ConstructResponseAsync(Int32 messageId, LdapOperation operation, ResultAll resultType, TimeSpan requestTimeOut, Boolean exceptionOnTimeOut, Boolean sync)

at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
...
```
**Wired Shark response**
```
Lightweight Directory Access Protocol
    LDAPMessage searchResDone(3) operationsError (000004DC: LdapErr: DSID-0C090A22, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v3839) [0 results]
        messageID: 3
        protocolOp: searchResDone (5)
            searchResDone
                resultCode: operationsError (1)
                matchedDN: 
                errorMessage: 000004DC: LdapErr: DSID-0C090A22, comment: In order to perform this operation a successful bind must be completed on the connection
```
**Code**
```
var username = "username@company.com";
var id = new LdapDirectoryIdentifier(Parameters.Domain, 389);
            using (var connection = new LdapConnection(id, new NetworkCredential("serviceAccount", "servicePassword"), AuthType.Basic))
{
    connection.Bind();
    var query = new SearchRequest("DC=pub,DC=company,DC=com", $"(&(objectClass=user)(userPrincipalName={username}))", SearchScope.Subtree);
    var response = (SearchResponse)connection.SendRequest(query);
}
```
**System info**
- Linux
- docker: mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim
- dotnet core 2.1 
- Nuget: System.DirectoryServices.Protocols version 5.0.0-rc.2.20475.5

**Comment by wli3** [comment]
Issue moved to [dotnet/runtime #44566](https://github.com/dotnet/runtime/issues/44566) via [**ZenHub**](https://www.zenhub.com/)
