### ISSUE TITLE
RazorTagHelper - DOTNET_HOST_PATH is not set

### ISSUE THREAD

**Issue by celoko-cintra** [dotnet/sdk#14497]
After updating VS 2019 16.8.0  I'm facing this error on compilation on any project:

**Web C# .net core 2.2**

Erro	MSB4018	Falha inesperada da tarefa "RazorTagHelper".
System.InvalidOperationException: DOTNET_HOST_PATH is not set
   em Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.get_DotNetPath()
   em Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.GenerateFullPathToTool()
   em Microsoft.Build.Utilities.ToolTask.ComputePathToTool()
   em Microsoft.Build.Utilities.ToolTask.Execute()
   em Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.Execute()
   em Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   em Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	QRPlus	C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets	79	

Anyone knows whats is going on?

**Comment by Lanticee** [comment]
I got same problem too. anyone can help?

**Comment by terrier-tom** [comment]
I doubt this is a permanent or proper solution, but I got rid of the error by adding a system environment variable named DOTNET_HOST_PATH with a value of dotnet. There are several ways in Windows to get to the spot where you can add system environment variables. Either use the Windows search (enter system environment variable in the search box) or get there via Control Panel -> System -> Advanced System Properties and then Environment Variables button.

All I can say is by doing the above my program would again build.

**Comment by Yavari** [comment]
We are using ASP.NET Core 2.2 with .NET Framework 4.61 and I get the same exception with Visual Studio 2019 16.8.0.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "RazorGenerate" task failed unexpectedly.
System.InvalidOperationException: DOTNET_HOST_PATH is not set
   at Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.get_DotNetPath()
   at Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.GenerateFullPathToTool()
   at Microsoft.Build.Utilities.ToolTask.ComputePathToTool()
   at Microsoft.Build.Utilities.ToolTask.Execute()
   at Microsoft.AspNetCore.Razor.Tasks.DotNetToolTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	<ProjectName>	<HOME_PATH>\.nuget\packages\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets	131

**Comment by duweiblog** [comment]
目录路径：C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\

删除上面目录以下两个文件：
Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets
Microsoft.AspNetCore.Razor.Design.props

ps:文件路径因人而异

**Comment by mcurko** [comment]
Microsoft's own sample app https://github.com/Azure-Samples/service-fabric-dotnet-quickstart/ wont compile after VS was upgraded (.NET 4.7.2 in these projects).

**Comment by olivermue** [comment]
Added the following environment variable to my user environment to make it build again:
DOTNET_HOST_PATH
%ProgramFiles%\dotnet\dotnet.exe

**Comment by tolbxela** [comment]
@olivermue thanks a lot!
It solved my problem too. 

Funny is, that the project was successfully built using **dotnet CLI** without the _DOTNET_HOST_PATH_ env. variable.

**Comment by celoko-cintra** [comment]
I added DOTNET_HOST_PATH as dotnet, and it also **solved** after restarting VS twice.
Thanks to everyone!

**Comment by Elinareso** [comment]
I faced the same issue after update VS to the latest version 16.8 and after apply the @olivermue solution I was able to compile and run the web app, however any of the javascript and styles files are loaded correctly now :(.

**Comment by celoko-cintra** [comment]
> I faced the same issue after update VS to the latest version 16.8 and after apply the @olivermue solution I was able to compile and run the web app, however any of the javascript and styles files are loaded correctly now :(.

It´s a problem on Razon to recognize new env variable.
Just try to restart your computer. I had the same problem and after restarting all came back!

**Comment by fsari** [comment]
> Added the following environment variable to my user environment to make it build again:
> DOTNET_HOST_PATH
> %ProgramFiles%\dotnet\dotnet.exe

It was worked for me

**Comment by fsari** [comment]
> > I faced the same issue after update VS to the latest version 16.8 and after apply the @olivermue solution I was able to compile and run the web app, however any of the javascript and styles files are loaded correctly now :(.
> 
> It´s a problem on Razor to recognize new env variable.
> Just try to restart your computer. I had the same problem and after restarting all came back!

It is not working. solution is environment editing

**Comment by faridprogrammer** [comment]
> I faced the same issue after update VS to the latest version 16.8 and after apply the @olivermue solution I was able to compile and run the web app, however any of the javascript and styles files are loaded correctly now :(.
Hi
Did you find the solution? I am having the same problem now.

**Comment by augustoproiete** [comment]
I got the same issue and had to manually set  the `DOTNET_HOST_PATH`
 environment variable as described by @olivermue above

```
setx DOTNET_HOST_PATH "%ProgramFiles%\dotnet\dotnet.exe"
```

**Comment by faridprogrammer** [comment]
> I got the same issue and had to manually set the `DOTNET_HOST_PATH`
> environment variable as described by @olivermue above
> 
> ```
> setx DOTNET_HOST_PATH "%ProgramFiles%\dotnet\dotnet.exe"
> ```

Thanks.
Setting it normally on windows settings didn't work for me. But this way solved the problem

**Comment by dathway** [comment]
Getting the same error in Visual Studio for Mac 8.8

Is there a known workaround for this? I can't figure out how to set the environment variable on mac...

**Comment by faridprogrammer** [comment]
> Getting the same error in Visual Studio for Mac 8.8
> 
> Is there a known workaround for this? I can't figure out how to set the environment variable on mac...

@augustoproiete reply was helpful for me.

**Comment by dathway** [comment]
> > Getting the same error in Visual Studio for Mac 8.8
> > Is there a known workaround for this? I can't figure out how to set the environment variable on mac...
> 
> @augustoproiete reply was helpful for me.
> 
> `setx DOTNET_HOST_PATH "%ProgramFiles%\dotnet\dotnet.exe"`

I'm on Mac, not windows.

**Comment by Silvenga** [comment]
Not sure this issue should be under the SDK project. Is there an open issue on the developer community?

**Comment by augustoproiete** [comment]
@dathway I'd guess that on OSX it would look something similar to

```
export DOTNET_HOST_PATH=/usr/local/share/dotnet
```

You should be able to run `which dotnet` to find dotnet on the path.

**Comment by dathway** [comment]
> @dathway I'd guess that on OSX it would look something similar to
> 
> ```
> export DOTNET_HOST_PATH=/usr/local/share/dotnet
> ```
> 
> You should be able to run `which dotnet` to find dotnet on the path.

Tried this, but it does not work. Still stuck.

**Comment by parrywh** [comment]
> > @dathway I'd guess that on OSX it would look something similar to
> > ```
> > export DOTNET_HOST_PATH=/usr/local/share/dotnet
> > ```
> > 
> > 
> > You should be able to run `which dotnet` to find dotnet on the path.
> 
> Thank you, but I've tried this and it does not work. Still stuck. All of my projects which target dotnet core 3.1 are unaffected, just the ones at 2.2

same here, using Mac and exporting the DOTNET_HOST_PATH doesn't seem to resolve the build issue

**Comment by Chengxiaozhi** [comment]
> > > @dathway I'd guess that on OSX it would look something similar to
> > > ```
> > > export DOTNET_HOST_PATH=/usr/local/share/dotnet
> > > ```
> > > 
> > > 
> > > You should be able to run `which dotnet` to find dotnet on the path.
> > 
> > 
> > Thank you, but I've tried this and it does not work. Still stuck. All of my projects which target dotnet core 3.1 are unaffected, just the ones at 2.2
> 
> same here, using Mac and exporting the DOTNET_HOST_PATH doesn't seem to resolve the build issue

Using vs mac fails, but using vs code is normal.

**Comment by Bowab** [comment]
I did 3 steps to get it to build AND to get the ( ~/ ) variable to work.

1. Open cmd and write this: **setx DOTNET_HOST_PATH "%ProgramFiles%\dotnet\dotnet.exe"** 

2. Open **C:\Program Files\dotnet\sdk** in here delete the folder: **NuGetFallbackFolder**

3. Restart your pc!

**Comment by Shane32** [comment]
I'm having the same problem

**Comment by brunokenj** [comment]
Anyone found a solution for osx (10.15.6) / vs 16.8.0 / aspnetcore 2.2 project ?

Same problem after: deleted NuGetFallbackFolder folder, added export DOTNET_HOST_PATH in .profile or .bash_profile, .zshrc, .zprofile, seen the variable in 'env', added in run 'custom configuration'.

**Comment by KevinRansom** [comment]
Oh bugger it looks like we can expect asp.net developers to be setting DOTNET_HOST_PATH which eliminates it's usefulness almost completely. Sigh!!!!!

**Comment by jonalexjm** [comment]
> > Added the following environment variable to my user environment to make it build again:
> > DOTNET_HOST_PATH
> > %ProgramFiles%\dotnet\dotnet.exe
> 
> It was worked for me

It Was worked too me! Thanks

**Comment by jcdekoning** [comment]
Any suggestion how to solve this for a solution that both contains a Microsoft.NET.Sdk.Razor project and F# class libraries. Because setting DOTNET_HOST_PATH environment variable interfere with running the F# compiler as discussed here https://github.com/dotnet/fsharp/issues/10447

**Comment by dgenezini** [comment]
> I did 3 steps to get it to build AND to get the ( ~/ ) variable to work.
> 
>     1. Open cmd and write this: **setx DOTNET_HOST_PATH "%ProgramFiles%\dotnet\dotnet.exe"**
> 
>     2. Open **C:\Program Files\dotnet\sdk** in here delete the folder: **NuGetFallbackFolder**
> 
>     3. Restart your pc!

Thanks.

If someone is using a build agent or building in a service, the command must have a **/M** to make it system wide and not only local:

`setx DOTNET_HOST_PATH "%ProgramFiles%\dotnet\dotnet.exe /M`

**Comment by terrier-tom** [comment]
I added a comment to the thread on the VS developer community site (link below) with an update on how I got things to work for me. Essentially I got rid of a nuget package in my local cache and things worked without the DOTNET_HOST_PATH system environment variable. The only "gotcha" was if I did a rebuild all on my solution, the package was re-added to my local nuget cache and the problem returned. Deleting the cached package (again) did (again) fix things -- at least for me.

https://developercommunity2.visualstudio.com/t/razortaghelper-task-failed-unexpectedly/1249786?from=email&viewtype=all#T-ND1255738

**Comment by jcdekoning** [comment]
@terrier-tom that does not solve the issue for me. While build is working, it is no longer created the compiled Razor views dll

**Comment by terrier-tom** [comment]
I posted another option in the developercommunity thread (link above). Unfortunately I am not able to successfully include in my post excerpts from my project file. Not sure what I'm doing wrong, but it doesn't like when I embed XML in a code block.

Essentially I found a link showing how someone created a UsingTask for setting environment variables. I added the UsingTask block to my project. I then added a prebuild event to the project that set the environment variable (note, the value should probably be the path to dotnet.exe, but it seems to work fine with just dotnet as the value).

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <EnvVarSet VarName="DOTNET_HOST_PATH" VarValue="dotnet"/>
  </Target>

**Comment by clxx** [comment]
For me, a **global.json** on the solution folder level with the 2.2 SDK (`dotnet --list-sdks`) was a viable workaround:

```json
{
  "sdk": {
    "version": "2.2.207"
  }
}
```

**Comment by AskYous** [comment]
How do I solve this for Mac?

**Comment by iCodeSometime** [comment]
@AskYous To expand on the solution from @terrier-tom - I was able to work around this by adding the following to my project file.

```
  <UsingTask 
    TaskName="EnvVarSet" 
    TaskFactory="CodeTaskFactory" 
    AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v4.0.dll">
    <ParameterGroup>
      <VarName ParameterType="System.String" Required="true"/>
      <VarValue ParameterType="System.String" Required="true" />
    </ParameterGroup>
    <Task>
      <Code Type="Fragment" Language="cs">
        <![CDATA[
          Console.WriteLine("Setting var name {0} to {1}...", VarName, VarValue);
          System.Environment.SetEnvironmentVariable(VarName, VarValue);
          Console.WriteLine("{0}={1}", VarName, VarValue);
        ]]>
      </Code>
    </Task>
  </UsingTask>

    
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <EnvVarSet VarName="DOTNET_HOST_PATH" VarValue="dotnet"/>
  </Target>

```

**Comment by ajklotz** [comment]
So, what is _causing_ this error? I see folks just adding the environment variable, and in my case I added it to my yaml build job as a variable for Azure Devops pipeline...but I would like to understand it better.

**Comment by jcdekoning** [comment]
@ajklotz I also wants to understand this issue in more detail. Why is this environment variable not needed when using a global.json and setting the .net core version to 3.1. Why is this causing issues when using .net 5.

I use this in combination with Razor templates to generate emails and pdfs. Besides the need of setting this env variable to get the code to compile, it does not find the razor views during runtime with .net 5. The same code is working fine with .net 3.1. Unclear about what is different.

I also understand from the f# community that the environment variable is misused here.

**Comment by AskYous** [comment]
Thanks you @iCodeSometime. That worked for me!

**Comment by wooooooood** [comment]
**RazorTagHelper** issue solved Thanks to @olivermue 's solution. But faced with **RazorGenerate** issue with same error message😭

I solved this problem with 
**Visual studio installer -> Modify -> Install ASP.NET and web development** (It was unchecked though I installed previously..)

**Comment by fabsenet** [comment]
I had success switching the project from .net core 2.2 to 5 and then actually updating all nuget packages.

**Comment by makemefeelgr8** [comment]
This issue appeared after I had removed the directory with nuget packages and started a .net core 2.2 project.

The command

> setx DOTNET_HOST_PATH "%ProgramFiles%\dotnet\dotnet.exe"

did fix it for me.

**Comment by TimurMingaziev** [comment]
This command below fixed "System.InvalidOperationException: DOTNET_HOST_PATH is not set" error
`setx DOTNET_HOST_PATH "%ProgramFiles%\dotnet\dotnet.exe"`

But after that I have another error message: 
`rzc generate exited with code -2147450730.	Priority1.Dashboard`
C:\Users\{userName}\.nuget\packages\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets	131

Do you know how to fix it?

**Comment by nathan-globaloffice** [comment]
For what it's worth, I ran into this same issue when updating VS. Adding the `Microsoft.NET.Sdk.Razor` package, to the web app projects affected, resolved the build issue.

**Comment by jackshiung** [comment]
@iCodeSometime Thxs, it's work for me.
![image](https://user-images.githubusercontent.com/12004523/99933101-027c2700-2d95-11eb-9013-fca0e86a3dab.png)

**Comment by bilalmalik777** [comment]
I am facing the same error at the time of building in the azure DevOps pipeline. please help me where I need to add **DOTNET_HOST_PATH ** variable what value needs to be set there in the variable

**Comment by jcdekoning** [comment]
FYI I only get the DOTNET_HOST_PATH not found error when my Razor Template library is targeting .net 4.8 or .net standard. If it is targeting .net core 3.1 or .net 5 it is working fine.

**Comment by lucavice** [comment]
@bilalmalik777  For Azure DevOps, the workaround is to add this as variable, either in the YAML pipeline or the GUI-based pipelines. It will be injected as environment variable. It fixed the issue for me.

![image](https://user-images.githubusercontent.com/14258744/99958796-46b5fa00-2d8a-11eb-8347-f938fd50a521.png)

**Comment by bilalmalik777** [comment]
@lucavice thanks a lot, issue has been resolved by setting the variable in the pipeline

**Comment by ianfoster99** [comment]
> Microsoft.NET.Sdk.Razor

This worked for me

**Comment by SheepRock** [comment]
> For me, a **global.json** on the solution folder level with the 2.2 SDK (`dotnet --list-sdks`) like [MSB4018 The RazorTagHelper task failed unexpectedly - after VS upgrade](https://github.com/dotnet/aspnetcore/issues/27249#issuecomment-718286186) suggested was a viable workaround:
> 
> ```json
> {
>   "sdk": {
>     "version": "2.2.207"
>   }
> }
> ```

This is the most simple solution. Worked for me without restarting the VS or the PC.

**Comment by Syedkumailabbaszaidi** [comment]
> Adding Microsoft.NET.Sdk.Razor to my Web project worked for me

This worked for me on Visual Studio For Mac.

**Comment by nqdung16** [comment]
> Adding Microsoft.NET.Sdk.Razor to my Web project worked for me

I'm new here so I don't know where to add that line. Please give me more specific info

**Comment by nathan-globaloffice** [comment]
@nqdung16 `Microsoft.NET.Sdk.Razor` is a nuget package. You'll need to add it to your web project using either `NuGet Pacakage Manager` (built into VS) or, if your using the new project reference style, by editing the `.csproj` file.

**Comment by nqdung16** [comment]
> Microsoft.NET.Sdk.Razor

I got it. Thanks

**Comment by Fabian651** [comment]
On mac, I fixed it with run project from bash `dotnet watch run --urls http://0.0.0.0:5001`

**Comment by Martin367** [comment]
Adding this line in project file works or install razor package:
	  `<PackageReference Include="Microsoft.NET.Sdk.Razor" Version="2.2.0"></PackageReference>`

**reference:**

[https://stackoverflow.com/questions/64827539/msb4018the-razorgenerate-task-failed-unexpectedly](url)
