### ISSUE TITLE
T4 and .NET 5.0

### ISSUE THREAD

**Issue by drano** [dotnet/sdk#14526]
I've tried to use T4 in .NET 5.0 and Visual Studio 16.8.0

My T4 template begins with 

`<#@ template debug="false" hostspecific="true" #>
<#@ output extension="/" encoding="utf-8"#>
<#@ assembly name="System.Runtime" #>
<#@ assembly name="System.Collections" #>
<#@ assembly name="System.Linq" #>`

But I have this error message 

`System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.VisualStudio.TextTemplating05D7343102CC185093E40C2F7414E90895A33BDE252A34209A8215EB7A4A9BF35A99C4714D8643C41A38596C5192A2A014A7BC151F1A90DC0498BDBE28990599.GeneratedTextTransformation.TransformText()
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.VisualStudio.TextTemplating.TransformationRunner.PerformTransformation()
`

**Comment by joeloff** [comment]
@drano by "use", I take it you have a .NET 5 application trying to calling into TransformText and then hitting the error?
