### ISSUE TITLE
Unable to update setting since it is in an uneditable config file - since upgrading to .net 5.0.100 sdk

### ISSUE THREAD

**Issue by jonesdwg** [dotnet/sdk#14787]
Since upgrading to VS 16.8.2, I get several errors when running a dotnet restore via the command line:

`dotnet restore`
`C:\Program Files\dotnet\sdk\5.0.100\NuGet.targets(131,5): error : Unable to update setting since it is in an uneditable config file. [C:\dev\client\pel\frontier\Frontier.sln]`

I have a NuGet.config file in my solution directory and can workaround the issue by pointing to that.

`dotnet restore --configfile NuGet.config`

It also works if I rollback to .net core 3.1 with a global.json file.

Here is an example of the stack trace from the msbuild logs:

```
System.InvalidOperationException: Unable to update setting since it is in an uneditable config file.
  at NuGet.Configuration.SettingItem.Update(SettingItem setting)
  at NuGet.Configuration.UnknownItem.Update(SettingItem setting)
  at NuGet.Configuration.UnknownItem.Merge(UnknownItem item)
  at NuGet.Configuration.VirtualSettingSection.Merge(SettingSection other)
  at NuGet.Configuration.NuGetConfiguration.MergeSectionsInto(Dictionary`2 sectionsContainer)
  at NuGet.Configuration.Settings..ctor(IList`1 settingsFiles)
  at NuGet.Configuration.Settings.LoadSettingsForSpecificConfigs(String root, String configFileName, List`1 validSettingFiles, IMachineWideSettings machineWideSettings, Boolean loadUserWideSettings, Boolean useTestingGlobalPath, SettingsLoadingContext settingsLoadingContext)
  at NuGet.Configuration.Settings.LoadSettingsGivenSettingsFiles(List`1 settings)
  at NuGet.Configuration.Settings.LoadImmutableSettingsGivenConfigPaths(IList`1 configFilePaths, SettingsLoadingContext settingsLoadingContext)
  at NuGet.Commands.DependencyGraphSpecRequestProvider.Create(String projectNameToRestore, ExternalProjectReference project, HashSet`1 projectReferenceClosure, RestoreArgs restoreArgs, DependencyGraphSpec projectDgSpec, SettingsLoadingContext settingsLoadingContext)
  at NuGet.Commands.DependencyGraphSpecRequestProvider.<>c__DisplayClass5_0.<GetRequestsFromItems>b__2(String projectNameToRestore)
  at System.Threading.Tasks.Parallel.<>c__DisplayClass32_0`2.<ForEachWorker>b__0(Int32 i)
  at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
```

**Comment by jonesdwg** [comment]
Ah, the bane of my life, getting modern tooling working behind a corporate proxy...

To work around previous nuget proxy issues, I had a system.net setting defined in my %appdata%/Nuget folder:

  <system.net>
    <defaultProxy useDefaultCredentials="true" enabled="true">
      <proxy usesystemdefault="True" proxyaddress="http://horrible_corporate_proxy:8080" />
    </defaultProxy>
  </system.net>

Removing this fixed the issue (not sure why the restore needs to edit this file).

**Comment by sfoslund** [comment]
Based on your comment above it sounds like this issue was solved, please feel free to reopen if that's not the case. Thanks!
