### ISSUE TITLE
ArgumentException in ResolveFrameworkReferences because ResolvedTargetingPacks contain duplicates

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/sdk#15116]
I was debugging a build and I saw an exception in ResolveFrameworkReferences:

```
C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(294,5): error MSB4018: The "ResolveFrameworkReferences" task failed unexpectedly.
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at Microsoft.NET.Build.Tasks.ResolveFrameworkReferences.ExecuteCore()
```

This is because ResolvedTargetingPacks had three of each item identity:
![image](https://user-images.githubusercontent.com/679326/103319402-a38a7d00-49e6-11eb-8c41-8a8bc90354e4.png)

So this line that calls ToDictionary throws:
https://github.com/dotnet/sdk/blob/6545e81bd505d68f57941fa91babc6345a22e1a7/src/Tasks/Microsoft.NET.Build.Tasks/ResolveFrameworkReferences.cs#L28

How is this not a problem usually and why haven't we noticed this before? Am I doing something wrong?

**Comment by KirillOsenkov** [comment]
Aha, normally they're deduplicated:
![image](https://user-images.githubusercontent.com/679326/103319503-f49a7100-49e6-11eb-8097-f943b1153d25.png)

**Comment by KirillOsenkov** [comment]
I'm closing this as it's highly likely I'm doing something wrong. I'll reopen if I can prove there's an actual bug.
