### ISSUE TITLE
dotnet-dump collect and dotnet-gcdump collect fails when process runs as www-data user on Ubuntu 

### ISSUE THREAD

**Issue by ahmetmithat** [dotnet/sdk#15187]
### Problem

I want to use **dotnet-dump** and **dotnet-gcdump** to collect core dumps of an ASP.NET Core web application running as a daemon with **www-data** user in Ubuntu but I am getting the following error:

```
myuser@myserver:~$ dotnet-gcdump collect -p 2357 -v

Writing gcdump to '/home/myuser/20210106_165550_2357.gcdump'...
  0.0s: Creating type table flushing task
  0.1s: [Error] Exception during gcdump: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (13): Permission denied /tmp/dotnet-diagnostic-2357-17566203-socket
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
...
<removed for brevity>
...
```

### Details

**Here is the unit file:**

```
[Unit]
Description=My buggy application

[Service]
WorkingDirectory=/var/buggyweb/
ExecStart=/usr/bin/dotnet /var/buggyweb/buggyweb.dll
Restart=always
# Restart service after 10 seconds if the dotnet service crashes:
RestartSec=10
KillSignal=SIGINT
SyslogIdentifier=buggyweb-identifier
User=www-data
Environment=ASPNETCORE_ENVIRONMENT=Development
Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
Environment=ASPNETCORE_URLS=http://localhost:5001
Environment=COMPlus_DbgEnableMiniDump=1

[Install]
WantedBy=multi-user.target
```
**Here are the environment details:**

```
myuser@myserver:~$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**And here is the dotnet tool info:**

```
myuser@myserver:~$ dotnet tool list -g
Package Id         Version         Commands
------------------------------------------------
dotnet-dump        5.0.160202      dotnet-dump
dotnet-gcdump      5.0.160202      dotnet-gcdump
dotnet-sos         5.0.160202      dotnet-sos
dotnet-symbol      1.0.155902      dotnet-symbol
```

I see my first "problem" when I try to get the PIDs with **ps** option, the path cannot be determined because it is an "elevated process":

```
myuser@myserver:~$ dotnet-gcdump ps

      2357 dotnet     [Elevated process - cannot determine path]
     26091 dotnet     [Elevated process - cannot determine path]
```

But as I explained above, my main problem is that the dump collection fails for both **dotnet-dump** and **dotnet-gcdump** when my process runs as **www-data** user:

```
myuser@myserver:~$ dotnet-gcdump collect -p 2357 -v

Writing gcdump to '/home/myuser/20210106_165550_2357.gcdump'...
  0.0s: Creating type table flushing task
  0.1s: [Error] Exception during gcdump: System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (13): Permission denied /tmp/dotnet-diagnostic-2357-17566203-socket
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state, Boolean flowContext)
...
<removed for brevity>
...
```

So, I get this error:

```(13): Permission denied /tmp/dotnet-diagnostic-2357-17566203-socket```

This is the permissions of **/tmp/dotnet-diagnostic-2357-17566203-socket** file:

```
myuser@myserver:~$ ll /tmp/dotnet-diagnostic-2357-17566203-socket
srw------- 1 www-data www-data 0 Jan  6 16:11 /tmp/dotnet-diagnostic-2357-17566203-socket=
```

If I change the user in my unit file and use "myuser" (which is obviously the user that I logged in my machine) then everything works fine:

```User=myuser```

I am pretty new to Linux and I couldn't find an easy way to monitor file accesses to troubleshoot this issue (e.g.: something like Process Monitor in Windows).

Can I use **dotnet-dump** or **dotnet-gcdump** to collect dumps of my process in this kind of set up? Am I missing something obvious?

**Comment by ahmetmithat** [comment]
I think I found it, this is already discussed in this issue: https://github.com/dotnet/diagnostics/issues/449

The correct command format should be like following when the process runs with a different user:

**sudo -H -u <user name of service> bash -c "<full path to dotnet tools>/dotnet-dump collect -p <PID> -o <output path>"**

E.g.: 

**sudo -H -u www-data bash -c "/home/myuser/.dotnet/tools/dotnet-dump collect -p 15586 -o /tmp/coredump.manual.1"**

Of course the output path should have write permission for the user and I think **/tmp** is the one to go safely.

I think this issue can be closed.
