### ISSUE TITLE
ResolvePackageFileConflicts fails when paths have New Line characters

### ISSUE THREAD

**Issue by natidea** [dotnet/sdk#1538]
NewLine characters in HintPaths are causing an exception in ResolvePackageFileConflicts for projects that previously worked. E.g. 

```xml
<Reference Include="System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
      <HintPath>
      ..\..\packages\System.Collections.Immutable.1.3.1\lib\portable-net45+win8+wp8+wpa81\System.Collections.Immutable.dll
      </HintPath>
</Reference>
```

StackTrace:
```
The "ResolvePackageFileConflicts" task failed unexpectedly.
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at Microsoft.NET.Build.Tasks.ItemUtilities.GetTargetPath(ITaskItem item)
   at Microsoft.NET.Build.Tasks.ItemUtilities.GetReferenceTargetPath(ITaskItem item)
   at Microsoft.NET.Build.Tasks.ConflictResolution.ResolvePackageFileConflicts.<>c.<ExecuteCore>b__35_1(ConflictItem ci)
   at Microsoft.NET.Build.Tasks.ConflictResolution.ConflictResolver`1.ResolveConflicts(IEnumerable`1 conflictItems, Func`2 getItemKey, Action`1 foundConflict, Boolean commitWinner, Action`1 unresolvedConflict)
   at Microsoft.NET.Build.Tasks.ConflictResolution.ResolvePackageFileConflicts.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Services (Services\Services)			
```

Reports:
- [VSFeedback](https://developercommunity.visualstudio.com/content/problem/99813/illegal-characters-in-path.html) | [484081](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/484081)
- StackOverflow: https://stackoverflow.com/questions/45796041/visual-studio-illegal-characters-in-path
- [VSFeedback](https://developercommunity.visualstudio.com/content/problem/98225/the-resolvepackagefileconflicts-task-failed-unexpe.html) | [482572](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/482572)

/cc @dsplaisted

**Comment by wli3** [comment]
@rainersigwald i think MsBuild simply see it as there is a new line in the middle. Is that intended? I can see the benefit of not using `&#xD;` all the time

**Comment by ceddlyburge** [comment]
Projects like this used to work and now don't, so I think it will be causing people pain.

If it is desired behaviour, then maybe an improved error message would be a decent compromise?

This could detail the reference that has the problem, which would be a big help while fixing up.

**Comment by natidea** [comment]
@wli3 you could just add a `Trim()` to [GetTargetPath](https://github.com/dotnet/sdk/blob/cd25d6bbfc2aac61cc790c511900427ac64fdaa8/src/Tasks/Common/src/ItemUtilities.cs#L133)

**Comment by livarcocc** [comment]
@wli3 this seems simple enough. I will mark it for 2.1.3xx, any chance you can get this in in between your other stuff?

**Comment by dsplaisted** [comment]
@wli3 I'm not sure, try changing the `TargetFramework` to netcoreapp2.0 and seeing what happens.

**Comment by wli3** [comment]
I can repo with msbuid /t:build

**Comment by wli3** [comment]
Further root cause

run the same code on fullframework and dotnet core
```c#
Path.GetFileName("\r\n                   net461\\lib\\System.Net.Http.dll\r\n");
```
fullframework throws but core is good

**Comment by wli3** [comment]
core impl is here https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/IO/Path.cs#L167

**Comment by wli3** [comment]
Core GetFileName don't check Path.GetInvalidPathChars()

**Comment by wli3** [comment]
https://github.com/dotnet/cli/issues/4523 similar to Nuget we should trim our own

**Comment by uzairnoor02** [comment]
i have the same issue with "ResolvePackageFileConflict" tried updating visual studio 2019, reinstalled .net core tried every possible thing I can but same issue. this issue is with .netcore. it gives issue inside .net core 5.0.4 folder. below is the code that is causing error...

` <ResolvePackageFileConflicts References="@(Reference)"
                                 ReferenceCopyLocalPaths="@(ReferenceCopyLocalPaths)"
                                 OtherRuntimeItems="@(_RuntimeAssetsForConflictResolution)"
                                 PlatformManifests="@(PackageConflictPlatformManifests)"
                                 TargetFrameworkDirectories="$(TargetFrameworkDirectory)"
                                 PackageOverrides="@(PackageConflictOverrides)"
                                 PreferredPackages="$(PackageConflictPreferredPackages)">
      <Output TaskParameter="ReferencesWithoutConflicts" ItemName="_ReferencesWithoutConflicts" />
      <Output TaskParameter="ReferenceCopyLocalPathsWithoutConflicts" ItemName="_ReferenceCopyLocalPathsWithoutConflicts" />
      <Output TaskParameter="Conflicts" ItemName="_ConflictPackageFiles" />
    </ResolvePackageFileConflicts>` 



the error is I am given is this:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "ResolvePackageFileConflicts" task failed unexpectedly.
System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Microsoft.NET.Build.Tasks.Logger.CreateMessage(MessageLevel level, String format, String[] args)
   at Microsoft.NET.Build.Tasks.Logger.LogMessage(MessageImportance importance, String format, String[] args)
   at Microsoft.NET.Build.Tasks.ConflictResolution.ConflictResolver`1.LogMessage(String conflictMessage, String format, Object[] args)
   at Microsoft.NET.Build.Tasks.ConflictResolution.ConflictResolver`1.ResolveConflict(TConflictItem item1, TConflictItem item2, Boolean logUnresolvedConflicts)
   at Microsoft.NET.Build.Tasks.ConflictResolution.ConflictResolver`1.ResolveConflicts(IEnumerable`1 conflictItems, Func`2 getItemKey, ConflictCallback`1 foundConflict, Boolean commitWinner)
   at Microsoft.NET.Build.Tasks.ConflictResolution.ResolvePackageFileConflicts.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	adaptive card bot	C:\Program Files\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets	39	
`

**Comment by dsplaisted** [comment]
@uzairnoor02 Probably what you're encountering is a different issue.  Could you file a new issue with a repro and/or a [binlog](https://aka.ms/binlog)?

**Comment by uzairnoor02** [comment]
Ok i will
