### ISSUE TITLE
"dotnet test" fails to write crash dump

### ISSUE THREAD

**Issue by mattleibow** [dotnet/sdk#15706]
My command:

`dotnet test tests/SkiaSharp.NetCore.Tests -v diag --no-build --blame-crash-collect-always -d diag.log --filter FullyQualifiedName~SkiaSharp.Tests.GRContextTest`

```

TpTrace Information: 0 : 15998, 1, 2021/02/06, 05:56:19.394, 18337037247743, datacollector.dll, ProcessDumpUtility.CrashDump: Creating full dump of process dotnet (16010) into temporary path '/var/folders/mq/tzb2r5fx3bl3961rhkjh1p_r0000gn/T/9f6c0222-a01d-456d-9f24-829af4f4e55d'.
TpTrace Information: 0 : 15998, 1, 2021/02/06, 05:56:19.395, 18337038012540, datacollector.dll, CrashDumperFactory: Creating dumper for Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 with target framework .NETCoreApp,Version=v5.0.
TpTrace Information: 0 : 15998, 1, 2021/02/06, 05:56:19.395, 18337038236456, datacollector.dll, CrashDumperFactory: This is Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 on .NETCoreApp,Version=v5.0 .NETClient dumper which uses env variables to collect crashdumps of testhost and any child process.
TpTrace Information: 0 : 15998, 1, 2021/02/06, 05:56:20.451, 18338094365547, datacollector.dll, DataCollectionRequestHandler.ProcessRequests : Datacollector received message: (DataCollection.AfterTestRunEnd) -> false
TpTrace Error: 0 : 15998, 8, 2021/02/06, 05:57:49.346, 18426989207082, datacollector.dll, DataCollectionRequestHandler.HandleBeforeTestRunStart: TestCaseEventHandler timed out while connecting to the Sender.
TpTrace Error: 0 : 15998, 8, 2021/02/06, 05:57:49.358, 18427001727692, datacollector.dll, DataCollectionRequestHandler.HandleBeforeTestRunStart : Error occurred during initialization of TestHost : Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: datacollector process failed to connect to testhost process after 90 seconds. This may occur due to machine slowness, please set environment variable VSTEST_CONNECTION_TIMEOUT to increase timeout.
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.DataCollection.DataCollectionRequestHandler.<HandleBeforeTestRunStart>b__23_0()
TpTrace Information: 0 : 15998, 1, 2021/02/06, 05:57:49.359, 18427002056893, datacollector.dll, Blame Collector : Session End
TpTrace Error: 0 : 15998, 1, 2021/02/06, 05:57:49.360, 18427003072241, datacollector.dll, ProcessDumpUtility.GetDumpFile: Could not find any dump file in .
TpTrace Warning: 0 : 15998, 1, 2021/02/06, 05:57:49.361, 18427004065796, datacollector.dll, System.IO.FileNotFoundException: Collect dump was enabled but no dump file was generated.
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcessDumpUtility.GetDumpFiles(Boolean warnOnNoDumpFiles)
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.BlameCollector.SessionEndedHandler(Object sender, SessionEndEventArgs args)
TpTrace Warning: 0 : 15998, 1, 2021/02/06, 05:57:49.361, 18427004169503, datacollector.dll, Data collector 'datacollector://microsoft/TestPlatform/Extensions/Blame/v1' logged the following warning: System.IO.FileNotFoundException: Collect dump was enabled but no dump file was generated.
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcessDumpUtility.GetDumpFiles(Boolean warnOnNoDumpFiles)
   at Microsoft.TestPlatform.Extensions.BlameDataCollector.BlameCollector.SessionEndedHandler(Object sender, SessionEndEventArgs args)
```

[diag.log](https://github.com/dotnet/sdk/files/5936703/diag.log)
[diag.datacollector.21-02-06_05-56-18_88961_4.log](https://github.com/dotnet/sdk/files/5936704/diag.datacollector.21-02-06_05-56-18_88961_4.log)
[diag.host.21-02-06_05-56-19_35664_4.log](https://github.com/dotnet/sdk/files/5936705/diag.host.21-02-06_05-56-19_35664_4.log)

**Comment by nohwnd** [comment]
I see this was labeled after a loong time to dotnet test. There were some recent fixes to blame in 7.0.4xx. Please let me know if you are still having this issue.
