### ISSUE TITLE
`dotnet new` is not showing list

### ISSUE THREAD

**Issue by sysek** [dotnet/sdk#15866]
After update on openSuse to version `5.0.103`, command `dotnet new` is now working properly, it should print me list of template but instead of that I've got exception

```
usern@hostname ~/D/dotnet> dotnet new
Getting ready...
Object reference not set to an instance of an object.
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save(TemplateCache cacheToSave)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save()
   at Microsoft.TemplateEngine.Cli.Installer.InstallPackages(IEnumerable`1 installationRequests, IList`1 nuGetSources, Boolean debugAllowDevInstall, Boolean interactive)
   at Microsoft.TemplateEngine.Cli.Installer.InstallPackages(IEnumerable`1 installationRequests, IList`1 nuGetSources, Boolean debugAllowDevInstall, Boolean interactive)
   at Microsoft.TemplateEngine.Cli.Installer.InstallPackages(IEnumerable`1 installationRequests)
   at Microsoft.DotNet.Tools.New.NewCommandShim.FirstRun(IEngineEnvironmentSettings environmentSettings, IInstaller installer)
   at Microsoft.TemplateEngine.Cli.New3Command.ConfigureEnvironment()
   at Microsoft.TemplateEngine.Cli.New3Command.Initialize()
   at Microsoft.TemplateEngine.Cli.New3Command.ExecuteAsync()
   at Microsoft.TemplateEngine.Cli.CommandParsing.NewCommandInputCli.<>c__DisplayClass19_0.<<OnExecute>b__0>d.MoveNext()
```

I've saw couple of topics here but no resolve. I also try do `dotnet new --debug:reinit` but nothing shows up on terminal. 

`dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    9effbc8ad5

Runtime Environment:
 OS Name:     opensuse-leap
 OS Version:  15.2
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.103/

Host (useful for support):
  Version: 5.0.3
  Commit:  eae88cc11b

.NET SDKs installed:
  5.0.103 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

`/usr/share/dotnet/templates/`
```
.:
3.1.12/  5.0.2/  5.0.3/

./3.1.12:

./5.0.2:

./5.0.3:
microsoft.dotnet.common.itemtemplates.5.0.3.nupkg                     microsoft.dotnet.web.projecttemplates.5.0.5.0.3.nupkg
microsoft.dotnet.common.projecttemplates.5.0.5.0.3.nupkg              microsoft.dotnet.web.spa.projecttemplates.5.0.5.0.3.nupkg
microsoft.dotnet.test.projecttemplates.5.0.1.0.2-beta4.20420.1.nupkg  nunit3.dotnetnew.template.1.8.1.nupkg
microsoft.dotnet.web.itemtemplates.5.0.3.nupkg
```

**Comment by sysek** [comment]
I solved problem by removing everything include dotnet configuration, now `dotnet new` is working 

* `~/.dotnet`
* `~/.nuget`
* `/usr/share/dotnet`

**Comment by Suundumused** [comment]
Just call `dotnet new list` and this will show all templates for all installed Frameworks.
