### ISSUE TITLE
[Windows ARM64] with 3.1.408 SDK installed, error "Failed to launch testhost with error: System.AggregateException: One or more errors occurred. (The specified executable is not a valid application for this OS platform.)" when running unit test project

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#16221]
Repro steps:
Install SDK via unzipping dotnet-sdk-3.1.408-win-arm64.zip to 'C:\Program Files\dotnet' on windows ARM64 machine.
dotnet new xunit(or nunit or mstest) in cmd.
dotnet build and dotnet test

**Expected behavior**
project can be build and run successfully

**Actual behavior**
error occurred when running "dotnet test"
Failed to launch testhost with error: System.AggregateException: One or more errors occurred. (The specified executable is not a valid application for this OS platform.)
 ---> System.ComponentModel.Win32Exception (216): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String arguments, String workingDirectory, IDictionary`2 envVariables, Action`2 errorCallback, Action`1 exitCallBack, Action`2 outputCallBack)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.LaunchHost(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.<>c__DisplayClass38_0.<LaunchTestHostAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.LaunchTestHostAsync(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)

Test Run Aborted.

![image](https://user-images.githubusercontent.com/65637796/110078663-0b808980-7dc3-11eb-8dcc-f407bf9417c0.png)

**Note:**
Not repro dotnet-sdk-3.1.114-win-arm64

dotnet --info:
C:\Users\v-danche>dotnet --info
.NET Core SDK (reflecting any global.json):
Version: 3.1.408
Commit: e08bd26ce8

Runtime Environment:
OS Name: Windows
OS Version: 10.0.18363
OS Platform: Windows
RID: win10-arm64
Base Path: C:\Program Files\dotnet\sdk\3.1.408\

Host (useful for support):
Version: 3.1.14
Commit: d0e340e1ed

.NET Core SDKs installed:
3.1.408 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by nohwnd** [comment]
This is a known issue. The version of test platform shipped with 3.1.408 SDK is not compatible with ARM64. Using net5 or net6 for ARM64 is recommended.
