### ISSUE TITLE
dotnet build -v causes Telemetry exception.

### ISSUE THREAD

**Issue by dazinator** [dotnet/sdk#1657]
```
 dotnet build -v
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.LogVerbosityForAllTopLevelCommand(ICollection`1 result, ParseResult parseResult, String topLevelCommandName)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
PS C:\Users\darre\Documents\visual studio 2017\Projects\DnnExtension135\DnnExtension135> dotnet -version
Unknown option: -version
.NET Command Line Tools (2.0.0)
```

**Comment by dazinator** [comment]
Sorry, looks like I checked the wrong repo. This has been raised here: https://github.com/dotnet/cli/issues/7589
