### ISSUE TITLE
Running the console app

### ISSUE THREAD

**Issue by cobaltsoftware** [dotnet/sdk#17541]
Problem encountered on https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/run
Operating System: windows

using Powershell ISE in Admin mode, I get this:

> PS F:\net6\myapp> dotnet run
dotnet : System.ComponentModel.Win32Exception (5): Access is denied.
At line:1 char:1
+ dotnet run
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Componen...cess is denied. 
   :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo 
startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan 
startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

Using the default command line in admin mode, I get this:
F:\>cd net6\myapp

F:\net6\myApp>dotnet run
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

F:\net6\myApp>

BUT, Using VS 2019 (Version 16.9.4), after opening the .csproj file, and running the project, I get this:
Hello World!

F:\net6\myApp\bin\Debug\net6.0\myApp.exe (process 17640) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

The web instructions state that I should get the result that came with using VS 2019, from the regular commandline, run in the project directory, but this fails. Is this known Issue?  If yes, is there a workaround that does not involve the IDE?

**Comment by dsplaisted** [comment]
I'm not sure what's going on here.

What happens if you run `dotnet build` and then run the `.exe` file from the output folder directly?  It will be under a path such as `.\bin\Debug\net6.0\myApp.exe`

**Comment by cobaltsoftware** [comment]
Following the suggestion, here's the Build Result:
PS F:\net6\myApp> dotnet build
Microsoft (R) Build Engine version 16.10.0-preview-21181-07+073022eb4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-previ
ew
  myApp -> F:\net6\myApp\bin\Debug\net6.0\myApp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.68

I then tried to run the exe from outside of the \bin\Debug location:
`PS F:\net6\myApp> cd bin\debug

PS F:\net6\myApp\bin\debug> dotnet run .\net6.0\myApp.exe`

and got this as the Result:
dotnet : Couldn't find a project to run. Ensure a project exists in 
F:\net6\myApp\bin\debug, or pass the path to the project using --project.
At line:1 char:1
+ dotnet run .\net6.0\myApp.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Couldn't find a...sing --project. 
   :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Next I went to the fq location, and made sure that I was in the right place:
PS F:\net6\myApp\bin\debug> cd net6.0

PS F:\net6\myApp\bin\debug\net6.0> ls


    Directory: F:\net6\myApp\bin\debug\net6.0


Mode                 LastWriteTime         Length Name                         
----                 -------------         ------ ----                         
d-----          5/9/2021  11:52 AM                ref                          
-a----         5/12/2021   2:57 PM         164864 myApp.exe                    
-a----         5/12/2021   2:57 PM            407 myApp.deps.json              
-a----         5/12/2021   2:57 PM            165 myApp.runtimeconfig.json     
-a----         5/12/2021   2:57 PM            379 myApp.runtimeconfig.dev.json 
-a----         5/12/2021   2:57 PM           4608 myApp.dll                    
-a----         5/12/2021   2:57 PM           9620 myApp.pdb

Upon seeing that I was in the right location to comply with the suggestion, I ran this:
`PS F:\net6\myApp\bin\debug\net6.0> dotnet run myApp.exe`

And got this as a result:
dotnet : Couldn't find a project to run. Ensure a project exists in 
F:\net6\myApp\bin\debug\net6.0, or pass the path to the project using 
--project.
At line:1 char:1
+ dotnet run myApp.exe
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Couldn't find a...sing --project. 
   :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError


Obviously this was done in PowerShell, but that is how my machine is set up. 

Thoughts? Suggestions?

**Comment by dsplaisted** [comment]
`dotnet run` is used to build a project and then run it.  If you want to run a DLL, just do:

`dotnet myApp.dll`

For the `.exe` file, you can just run it directly without `dotnet`:

`myApp.exe`

Can you see how those commands work for you?

**Comment by cobaltsoftware** [comment]
Apologies for the length of time.  Yes, I understand how the CLI works, and why. but the CLI doesn't meet my needs. If I'm working on an android application, I need to se it on a device, or an emulator. 

The CLI is the same as it always has been since .Net 1.1 (and actually further back than that, but that's another subject). And there are still some scenarios were it will not work.

**Comment by dsplaisted** [comment]
It sounds like `dotnet run` isn't working from admin command prompts for you.  I'm not sure why that is happening.  So I asked you to try running the app without `dotnet run` in order to try to narrow down the issue.

`dotnet run` from the project folder should work, but I don't believe `dotnet run myApp.dll` or `dotnet run myApp.exe` has ever worked.

@joeloff Any ideas here?

**Comment by cobaltsoftware** [comment]
I know it's been a while, but any traction on this issue?

**Comment by dsplaisted** [comment]
Is the problem that `dotnet run` doesn't work for android apps, or is it the access denied error that you were hitting?
