### ISSUE TITLE
dotnet run fails with "Access is denied"

### ISSUE THREAD

**Issue by tjkb** [dotnet/sdk#17969]
Steps to reproduce: 

- dotnet new console
- dotnet run

This results in the following error:
```
PS C:\repos\console> dotnet run
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

After rebooting, running the console app works the first time, the second time it again fails:
```
PS C:\repos\console> dotnet run
Hello World!
PS C:\repos\console> dotnet run
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

Windows version:
```
PS C:\repos\console> systeminfo
Host Name:                 ------
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19043 N/A Build 19043
```

dotnet --info
```
PS C:\repos\console> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.409
 Commit:    217439b5ae

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.409\

Host (useful for support):
  Version: 3.1.15
  Commit:  dc339bd0fb

.NET Core SDKs installed:
  3.1.409 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by tjkb** [comment]
The problem was the following: the IT department has ransomware protection in place that prevents dotnet.exe from running: 
![image](https://user-images.githubusercontent.com/40162050/120175063-1900b080-c206-11eb-96a4-29c27c30a291.png)

Check under "Ransomware protection - Block history"

**Comment by zachrburke** [comment]
In case it helps anyone, I just ran into an issue where I accidentally built a shared dll using Rider IDE running as Administrator.  This caused my `dotnet run` command to fail when not running in a privileged mode.  

I was able to fix the issue by running `dotnet clean` in the solution.
