### ISSUE TITLE
.Net 6p5, Trimming apps versus Windows Forms

### ISSUE THREAD

**Issue by Betaminos** [dotnet/sdk#18475]
### Description

I am currently building a very basic application using Windows Forms.

My initial code looks like this (unchanged from template):
```
using System;
using System.Windows.Forms;

namespace WinFormsApp
{
	static class Program
	{
		/// <summary>
		///  The main entry point for the application.
		/// </summary>
		[STAThread]
		static void Main()
		{
			Application.SetHighDpiMode(HighDpiMode.SystemAware);
			Application.EnableVisualStyles();
			Application.SetCompatibleTextRenderingDefault(false);
			Application.Run(new MainView());
		}
	}
}
```

Whenver I try to run it, while trimming (regardless of trimming mode) is activated in the .csproj, my Debugger will instantly run into an unhandled exception when hitting the last line of code:
```
System.NotSupportedException
  HResult=0x80131515
  Message=Built-in COM has been disabled via a feature switch. See https://aka.ms/dotnet-illink/com for more information.
  Source=System.Private.CoreLib
  StackTrace:
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr& ppUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at System.Windows.Forms.UnsafeNativeMethods.CreateStdAccessibleObject(HandleRef hWnd, Int32 objID, Guid& refiid, Object& pAcc)
   at System.Windows.Forms.AccessibleObject.UseStdAccessibleObjects(IntPtr handle, Int32 objid)
   at System.Windows.Forms.Control.ControlAccessibleObject.set_Handle(IntPtr value)
   at System.Windows.Forms.Control.ControlAccessibleObject.InitHandle(Control ownerControl)
   at System.Windows.Forms.Control.ControlAccessibleObject..ctor(Control ownerControl)
   at System.Windows.Forms.TextBoxBase.TextBoxBaseAccessibleObject..ctor(TextBoxBase owner)
   at System.Windows.Forms.TextBoxBase.CreateAccessibilityInstance()
   at System.Windows.Forms.Control.get_AccessibilityObject()
   at System.Windows.Forms.TextBoxBase.SelectInternal(Int32 start, Int32 length, Int32 textLen)
   at System.Windows.Forms.TextBox.SelectInternal(Int32 start, Int32 length, Int32 textLen)
   at System.Windows.Forms.TextBox.OnGotFocus(EventArgs e)
   at System.Windows.Forms.Control.WmSetFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

My expectation would have been that Windows Forms is not trimmed (or affected by activating trimming) as it is referenced by a using-statement.
After some experimenting, I am only able to get around this unhandled exception by completely disabling trimming on this project.
The program starts up and works as expected, once I set trimming to false:
`<PublishTrimmed>false</PublishTrimmed>`

### Configuration

* Which version of .NET is the code running on? .Net 6 preview 5 and Visual Studio 2022 Preview (happens in Visual Studio 2019 as well)
* What OS and version, and for Linux, what distro? Windows 10, 21H1 (19043.1055)
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Do you know whether it is specific to that configuration? I'd assume that it is not specific to my setup

**Comment by Betaminos** [comment]
> @Betaminos Did you see the warning "Windows Forms is not supported or recommended with trimming enabled."?

I just checked to make sure that I had not missed it, but no I don't see it.
As the trim-command is not exposed by the Project settings GUI, I am manually adding this line
`<PublishTrimmed>true</PublishTrimmed>`

Neither when saving the modified .csproj nor after trying to run it (and failing) am I receiving an error or a warning:
![image](https://user-images.githubusercontent.com/1180151/123124764-3c56fe00-d448-11eb-9f95-faf3d0419ab2.png)

**Comment by vitek-karas** [comment]
Thanks @Betaminos .

That is basically https://github.com/dotnet/sdk/issues/18474.
You should see the warning when publishing the app with `dotnet publish` (or via the "Publish" gesture in VS).

**Comment by Betaminos** [comment]
> You should see the warning when publishing the app with `dotnet publish` (or via the "Publish" gesture in VS).

Thank you for looking into this.
I did try a Publish just now and it does show this line:
`3>Windows Forms is not supported or recommended with trimming enabled. Please go to https://aka.ms/dotnet-illink/windows-forms for more details.`

Nonetheless, I am running into this unhandled exception even when debugging the application (where no error / warning is generated at all).
My understanding was that trimming is only triggered when publishing, but not when running the app via Debug (F5).
However, I am not sure whether my understanding of PublishTrimmed is flawed.

**Comment by vitek-karas** [comment]
This is all super valid feedback. We've been discussing that `PublishTrimmed` should be renamed https://github.com/mono/linker/issues/2085. The main reason being that it affects build and not just publish.

A bit more details:
- PublishTrimmed will disable certain runtime features which are not compatible with trimming - for example the built in COM interop support (but lot of others) [list here](https://github.com/dotnet/runtime/blob/main/docs/workflow/trimming/feature-switches.md).
- These features are disabled even when not trimming to provide a consistent experience - we want the app to behave the same with/without trimming (or produce warnings/errors if that's not the case). We don't want you to run into issues only when you publish the app into "production" ([discussion on feature switches](https://github.com/dotnet/designs/blob/main/accepted/2020/feature-switch.md))

For this to work we need to know if trimming is supposed to be used all the time - that's why declaring `PublishTrimmed=true` in your project file is actually the right thing to do currently. Unfortunately we haven't cleaned up all the things around this yet - including possibly renaming the property (or having another one which would do that).

**Comment by dsplaisted** [comment]
@vitek-karas As far as I can tell there's not currently any action for the SDK team to take on this, so I assigned this to you.

**Comment by vitek-karas** [comment]
@LakshanF who handled fixing this.

I checked on latest nightly of the SDK and it now warns even on build (not just publish). Adding @agocke since we've discussed turning the warning into error as well (I don't remember the end result of that discussion though).

**Comment by LakshanF** [comment]
@agocke is changing the warning to an error with PR #1940

@dsplaisted, I believe the changes we have made takes care of the original issue. It is not possible to trim `WinForm/WPF` apps and we make developers aware of this during build since these apps are negatively impacted during the app development in trimming.
