### ISSUE TITLE
[CLI] Command 'dotnet /..' shows IndexOutOfRangeException instead of 'Could not execute...' message

### ISSUE THREAD

**Issue by Tacodude7729** [dotnet/sdk#18724]
The command `dotnet /..` shows this error:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.DotNet.CommandFactory.DotnetToolsCommandResolver.Resolve(CommandResolverArguments arguments)
   at Microsoft.DotNet.CommandFactory.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.CommandFactory.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.CommandFactory.CommandFactoryUsingResolver.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
This error is present if you put things before the `/..` (IE `dotnet anything/..` gives the error) but not after (IE `dotnet /..anything` doesn't give the error)

Dotnet 5.0.301 Ubuntu 20.04.2 LTS

**Comment by dsplaisted** [comment]
This still happens in .NET 6.  In the CLI's `Program.ProcessArgs` method we get `/..` as the result of `parseResult.ValueForArgument<string>(Parser.DotnetSubCommand)`, and then we combine that with `dotnet-` and end up trying to resolve the command `dotnet-/..`, which then messes up the path processing logic in `DotnetToolsCommandResolver`.
