### ISSUE TITLE
.NET 6 Preview 6 SDK: System.IO.FileLoadException when running net461 app from publish location

### ISSUE THREAD

**Issue by nr-ahemsath** [dotnet/sdk#19329]
Summary: when running an ASP.NET Core 2.1 WebApi app that targets `net461` from a published output location after `dotnet publish` with the .NET 6 Preview 6 SDK, the following exception is observed:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Console.ConsoleLogger..ctor(String name, Func`3 filter, IExternalScopeProvider scopeProvider, ConsoleLoggerProcessor loggerProcessor)
   at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider.CreateLoggerImplementation(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLoggers(String categoryName)
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.Extensions.Logging.Logger`1..ctor(ILoggerFactory factory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at WebApplication1.Program.Main(String[] args)
```

Note that this exception does *not* occur if you run the application from `bin/Debug/net461` after running `dotnet build`.

I can reproduce this with a standard template ASP.NET Core WebApi application generated with VS2019, with "Target Framework" set to "NET Core 2.1 (Long-term support)" and the "Run on .NET Framework" box checked.

This might be a duplicate of issue #18101.

**Comment by marcpopMSFT** [comment]
When we investigate #18101, we should ensure this scenario is covered in that investigation.

**Comment by nr-ahemsath** [comment]
#18101 is marked closed in .NET 6 RC1; I tested the scenario I described above in RC1 and it is working as expected now.  Thanks!
