### ISSUE TITLE
OsOptionIsCorrectlyResolved fails with unexpected distributedlogger parameter on the end

### ISSUE THREAD

**Issue by danmoseley** [dotnet/sdk#19483]
I've seen similiar failures before. Apparently this is failing 13% of the time(!!). @dotnet/domestic-cat could you take a look? It might reduce the necessity for auto retries.

https://github.com/dotnet/sdk/pull/19476/checks?check_run_id=3231858428

```
 Microsoft.DotNet.Cli.MSBuild.Tests.GivenDotnetOsArchOptions.OsOptionIsCorrectlyResolved [Details] [History] [Helix Test Artifacts]
Exception Message
Expected string to be \r\n\"-maxcpucount -verbosity:m -restore -consoleloggerparameters:Summary -property:RuntimeIdentifier=os-x64\" with a length of 102, but \r\n\"-maxcpucount -verbosity:m -restore -consoleloggerparameters:Summary -property:RuntimeIdentifier=os-x64 -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,D:\\workspace\\_work\\1\\s\\artifacts\\bin\\redist\\Release\\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,D:\\workspace\\_work\\1\\s\\artifacts\\bin\\redist\\Release\\dotnet.dll\" has a length of 347.
CallStack
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in FluentAssertions.dll:token 0x600015c+0x1d
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message) in FluentAssertions.dll:token 0x6000164+0x11
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message) in FluentAssertions.Core.dll:token 0x6000372+0x0
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in FluentAssertions.Core.dll:token 0x600034f+0x71
   at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstLengthDifferences() in FluentAssertions.Core.dll:token 0x600029f+0x0
   at FluentAssertions.Primitives.StringValidator.Validate() in FluentAssertions.Core.dll:token 0x60002a9+0x5b
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in FluentAssertions.Core.dll:token 0x600027c+0x1a
   at Microsoft.DotNet.Cli.MSBuild.Tests.GivenDotnetOsArchOptions.<>c.b__3_0() in /_/src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetOsArchOptions.cs:line 37
   at Microsoft.DotNet.Cli.CommandDirectoryContext.PerformActionWithBasePath(String basePath, Action action) in /_/src/Cli/dotnet/CommandDirectoryContext.cs:line 38
   at Microsoft.DotNet.Cli.MSBuild.Tests.GivenDotnetOsArchOptions.OsOptionIsCorrectlyResolved() in /_/src/Tests/dotnet.Tests/dotnet-msbuild/GivenDotnetOsArchOptions.cs:line 32
Pass Rate
Test has failed 256 out of 1977 runs (12.95%)
Failing Configuration
Windows_NT_Windows_NT Build_Release_14
Darwin_Darwin Build_Release_11
```

**Comment by danmoseley** [comment]
https://github.com/dotnet/sdk/pull/19476

**Comment by sfoslund** [comment]
Oops, I missed updating that test in https://github.com/dotnet/sdk/pull/19324, I'll make a PR to fix it
