### ISSUE TITLE
Could we add support for `dotnet tool update -g -all`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/sdk#19650]
Currently, we had to update the dotnet tools one by one, could we provide a command like `dotnet tool update -g -all` to update all tools to the latest versions? And maybe for local dotnet tools also

It may relate to #18727

```sh
# update all global dotnet tools
dotnet tool update --global -all

# update all local dotnet tools
dotnet tool update --local -all
```

**Comment by marcpopMSFT** [comment]
CC @baronfel on thoughts on priority

**Comment by WeihanLi** [comment]
I drafted a dotnet-tool `dotnet-update-all-tools` according to the dotnet tool list output, source code here: https://github.com/WeihanLi/SamplesInPractice/tree/main/CommandLineAppSamples/UpgradeAllTools

Install the tool

```sh
dotnet tool install --global dotnet-update-all-tools
```

Update all global tools

```sh
dotnet-update-all-tools
```

Update all local tools

```sh
dotnet-update-all-tools --local
```

Hope it would help

**Comment by WeihanLi** [comment]
Yeah, that's really a thing, it would be better to support `--format json`

**Comment by philipp-naused** [comment]
If you try to use `dotnet tool update -g --all` right now (`9.0.100-preview.6`), it just crashes with a `NullReferenceException`:

```
Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Tools.Tool.List.ToolListGlobalOrToolPathCommand.GetPackages(Nullable`1 toolPath, Nullable`1 packageId)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
   at Microsoft.DotNet.Tools.Tool.Update.ToolUpdateGlobalOrToolPathCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

**Comment by marcpopMSFT** [comment]
Confirmed that this made it in in 9.0.100 and 8.0.4xx so closing.
