### ISSUE TITLE
"dotnet workload update --print-download-link-only" command fails

### ISSUE THREAD

**Issue by nosami** [dotnet/sdk#19691]
I tried this with both the released version of preview 7 and the latest RC main branch build of the installer.

`dotnet workload update --print-download-link-only` fails.
`dotnet workload update` (without `--print-download-link-only`) works fine, but I need to download packages in the background for VSMac.

This command was working AFAIR with preview 7 before I went on vacation a couple of weeks back.

```
jasonimison@Jasons-MacBook-Pro-2 ~/Library/Caches/VisualStudio/17.0/TempDownload $ /usr/local/share/dotnet/dotnet workload update --print-download-link-only  --temp-dir "/var/folders/j1/ykgr31c54fg72hz1gfqw_dch0000gn/T/-1203675120"
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Did not find workload manifest dependency 'Microsoft.NET.Workload.Emscripten' required by manifest 'microsoft.net.workload.mono.toolchain.manifest-6.0.100.6.0.0-preview.7.21377.19' [/var/folders/j1/ykgr31c54fg72hz1gfqw_dch0000gn/T/-1203675120/dotnet-manifest-extraction/microsoft.net.workload.mono.toolchain.manifest-6.0.100.6.0.0-preview.7.21377.19/WorkloadManifest.json]
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.ComposeWorkloadManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion)
   at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand.UseTempManifestsToResolvePacksAsync(DirectoryPath tempPath, Boolean includePreview)
   at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand.GetUpdatablePackageUrlsAsync(Boolean includePreview)
   at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand.Execute()
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by nosami** [comment]
@jonathanpeppers @marek-safar Can either of you two possibly help me? Am I missing a NuGet feed?

**Comment by jonathanpeppers** [comment]
I've not used `--print-download-link`, but daily builds of that package seems like it is on this feed:

https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

If you're using the public release, everything *should* be on NuGet.org, though.

**Comment by nosami** [comment]
> I've not used `--print-download-link`, but daily builds of that package seems like it is on this feed:
> 
> https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json
> 
> If you're using the public release, everything _should_ be on NuGet.org, though.

@jonathanpeppers Thanks for the help, but I still get he same error when I add that feed.

@wli3 can reproduce this error and is currently investigating.

**Comment by wli3** [comment]
it is interesting. This issue only happens in --print-download-link. Now even normal workload update

**Comment by wli3** [comment]
@nosami this is a bug in SDK being exposed only in `--print-download-link` and aot started to use "depend-on" feature
