### ISSUE TITLE
ItFiltersSatelliteResources test fails on Linux

### ISSUE THREAD

**Issue by tmds** [dotnet/sdk#19783]
This test fails for me on Linux:
```
Microsoft.NET.Build.Tasks.UnitTests.GivenAResolveRuntimePackAssetsTask.ItFiltersSatelliteResources
Expected string \"/home/tmds/repos/sdk/artifacts/tmp/Debug/ItFiltersSate---6E2447EA/runtimes/de/a.resources.dll\" to contain \"runtimes\\de\\a.resources.dll\".
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.StringAssertions.Contain(String expected, String because, Object[] becauseArgs)
   at Microsoft.NET.Build.Tasks.UnitTests.GivenAResolveRuntimePackAssetsTask.ItFiltersSatelliteResources() in /home/tmds/repos/sdk/src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/GivenAResolveRuntimePackAssetsTask.cs:line 55
```
The difference in directory separator (`\` vs `/`) are cause of the failure.

Does this test run and pass in CI on Linux?

cc @joeloff @sfoslund @dsplaisted

**Comment by dsplaisted** [comment]
Combined with another test failure I saw locally, I am starting to suspect that we are not running the task unit tests in CI.
