### ISSUE TITLE
Post build variables empty when executing "Publish"

### ISSUE THREAD

**Issue by ManuelHaas** [dotnet/sdk#1987]
Hi,

a working post build event is not working when publishing the project because $(SolutionDir) and $(TargetDir) are empty.

Project file:
```
<PropertyGroup>
  <TargetFramework>net462</TargetFramework>
  <PreserveCompilationContext>true</PreserveCompilationContext>
  <AssemblyName>XXX</AssemblyName>
  <OutputType>Exe</OutputType>
  <PackageId>XXX</PackageId>
  <UserSecretsId>XYZ</UserSecretsId>
  <RuntimeIdentifiers>win8-x64</RuntimeIdentifiers>
  <PostBuildEvent>xcopy /D /Y "$(SolutionDir)src\ABC\*.*" $(TargetDir)</PostBuildEvent>
  <TypeScriptToolsVersion>2.5</TypeScriptToolsVersion>
</PropertyGroup>
```
Error:

`The command "xcopy /D /Y "src\ABC\*.*" " exited with code 4.`

Exception:

```
System.AggregateException: One or more errors occurred. ---> System.Exception: Publish failed due to build errors. Check the error list for more details.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Web.Publish.PublishService.VsWebProjectPublish.<>c__DisplayClass40_0.<PublishAsync>b__2()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ApplicationCapabilities.Publish.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__108.MoveNext()
---> (Inner Exception #0) System.Exception: Publish failed due to build errors. Check the error list for more details.<---
```

**Comment by livarcocc** [comment]
This is likely a dup of https://github.com/dotnet/sdk/issues/677.

Can you try replacing your post build event with a Target?

Also, below is a exert from https://github.com/Microsoft/msbuild/issues/2743

```
Do not depend on SolutionDir, or any other sln dependent property. SolutionDir is only set when you are building a solution. It has no meaning when building the csproj directly (or a dirs.proj sln replacement). Best to consider the sln file deprecated. Instead, place a directory.build.props at the root of your repo and define a root property like $(MSBuildThisFileDirectory)
```

**Comment by ManuelHaas** [comment]
I don't know it its a dup of #677. The error here occurs when publishing a solution. So publishing in conjunction with post build events with variables is not possible.
Replacing the post build event with a Target would work but is inpractical in team environment.

> "Best to consider the sln file deprecated." 

This is a joke, right? Is this the official position of Microsoft? If yes why are sln files still included in project templates?

**Comment by dasMulli** [comment]
you could also do

```xml
<ItemGroup>
  <Content Include="..\src\ABC\**"
           CopyToOutputDirectory="PreserveNewest" 
           CopyToPublishDirectory="PreserveNewest" />
</ItemGroup>
```

instead of the post build event. That way it even works cross-platform (`xcopy` is windows only)

**Comment by ManuelHaas** [comment]
@dasMulli Thanks a lot! I didn't know about that. This solved it for me.

**Comment by soroshsabz** [comment]
ITNOA

How to find solution dir with new msbuild?
