### ISSUE TITLE
DOTNETSDK_WORKLOAD_MANIFEST_ROOTS pointing to workloads that are not lowercased fails

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/sdk#19994]
Repro: [brokenworkloads-1b6a566.zip](https://github.com/dotnet/sdk/files/7031534/brokenworkloads-1b6a566.zip)

Download & extract && execute `make nay`:

```
$ make nay
dotnet --version
6.0.100-rc.2.21420.30
DOTNETSDK_WORKLOAD_MANIFEST_ROOTS=/Users/rolf/test/dotnet/brokenworkloads/Cased       dotnet workload list
System.IO.FileNotFoundException: Could not find file '/Users/rolf/test/dotnet/brokenworkloads/WorkloadManifest.json'.
File name: '/Users/rolf/test/dotnet/brokenworkloads/WorkloadManifest.json'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenRead(String path)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.<>c__DisplayClass7_0.<GetManifests>b__0()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.LoadManifestsFromProvider(IWorkloadManifestProvider manifestProvider)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion)
   at Microsoft.DotNet.Workloads.Workload.List.WorkloadListCommand..ctor(ParseResult result, IReporter reporter, IWorkloadInstallationRecordRepository workloadRecordRepo, String currentSdkVersion, String dotnetDir, String userHome, String tempDirPath, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, IWorkloadResolver workloadResolver)
   at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.<get_SubCommands>b__9_3(ParseResult appliedOption)
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
make: *** [nay] Error 1
```

If the workloads are lowercased, this happens (which is the expected behavior):

```
$ make yay
dotnet --version
6.0.100-rc.2.21420.30
DOTNETSDK_WORKLOAD_MANIFEST_ROOTS=/Users/rolf/test/dotnet/brokenworkloads/Lowercased/ dotnet workload list
Inadequate permissions. Run the command with elevated privileges.
Description:
  List workloads available.

Usage:
  dotnet [options] workload list

Options:
  -v, --verbosity <LEVEL>  Set the MSBuild verbosity level. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].
  --sdk-version <VERSION>  The version of the SDK.
  --temp-dir <temp-dir>    Specify a temporary directory for this command to download and extract NuGet packages (must be secure).
  --include-previews       Allow prerelease workload manifests.
  --disable-parallel       Prevent restoring multiple projects in parallel.
  --ignore-failed-sources  Treat package source failures as warnings.
  --no-cache               Do not cache packages and http requests.
  --interactive            Allows the command to stop and wait for user input or action (for example to complete authentication).
  -?, -h, --help           Show command line help.

make: *** [yay] Error 1
```

This is the file layout of the repro:

```
./Makefile
./Lowercased
./Lowercased/6.0.100
./Lowercased/6.0.100/microsoft.net.sdk.ios
./Lowercased/6.0.100/microsoft.net.sdk.ios/WorkloadManifest.json
./Lowercased/6.0.100/microsoft.net.sdk.ios/LICENSE
./Lowercased/6.0.100/microsoft.net.sdk.ios/WorkloadManifest.targets
./Cased
./Cased/6.0.100
./Cased/6.0.100/Microsoft.NET.Sdk.iOS
./Cased/6.0.100/Microsoft.NET.Sdk.iOS/WorkloadManifest.json
./Cased/6.0.100/Microsoft.NET.Sdk.iOS/LICENSE
./Cased/6.0.100/Microsoft.NET.Sdk.iOS/WorkloadManifest.targets
```

My guess would be that it's because either (or both) of these two creates case-sensitive dictionaries/hashsets:

https://github.com/dotnet/sdk/blob/c7ccfae6beb258bf229e903a4646c4c6da4df3b6/src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs#L92

https://github.com/dotnet/sdk/blob/c7ccfae6beb258bf229e903a4646c4c6da4df3b6/src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/SdkDirectoryWorkloadManifestProvider.cs#L60

**Comment by dsplaisted** [comment]
@rolfbjarne Is this still an issue at all?  I think everything that writes to the manifest roots should be writing lowercased paths for the manifests.

**Comment by rolfbjarne** [comment]
@dsplaisted In the end I stopped using `DOTNETSDK_WORKLOAD_MANIFEST_ROOTS` (I wasn't able to make it work), so this isn't an issue for us anymore.
