### ISSUE TITLE
IPV6 stack is required for .NET 5

### ISSUE THREAD

**Issue by thebitllc** [dotnet/sdk#20808]
We ran into a weird problem with Elasticsearch.NET package when upgraded to .net5. Our docker machines don't have ipv6, specifically they don't have /proc/net/tcp6, they have /proc/net/tcp.

In StringParsingHelpers.Connections.cs:

```
        internal static TcpConnectionInformation[] ParseActiveTcpConnectionsFromFiles(string tcp4ConnectionsFile, string tcp6ConnectionsFile)
        {
            if (!File.Exists(tcp4ConnectionsFile) || !File.Exists(tcp6ConnectionsFile))
            {
                throw new PlatformNotSupportedException(SR.net_InformationUnavailableOnPlatform);
            }
```

/proc/net/tcp6 is a required file and the exception will be thrown if its missing.

```
Unhandled exception. System.AggregateException: One or more errors occurred. (The information requested is unavailable on the current platform.)
 ---> Elasticsearch.Net.UnexpectedElasticsearchClientException: The information requested is unavailable on the current platform.
 ---> System.PlatformNotSupportedException: The information requested is unavailable on the current platform.
   at System.Net.NetworkInformation.StringParsingHelpers.ParseActiveTcpConnectionsFromFiles(String tcp4ConnectionsFile, String tcp6ConnectionsFile) in /_/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Connections.cs:line 36
   at System.Net.NetworkInformation.LinuxIPGlobalProperties.GetActiveTcpConnections() in /_/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxIPGlobalProperties.cs:line 10
   at Elasticsearch.Net.Diagnostics.TcpStats.GetActiveTcpConnections()
   at Elasticsearch.Net.Diagnostics.TcpStats.GetStates()
   at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken)
   at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)
```

**Comment by NN---** [comment]
I guess you should report it to https://github.com/dotnet/runtime/
