### ISSUE TITLE
dotnet workload update command fails with ArgumentNullException

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/sdk#20914]
### Describe the bug
I am trying to update the package versions for Maui using the dotnet workload update command but it throws `System.ArgumentNullException: Value cannot be null. (Parameter 'paths')` before printing anything else.

### To Reproduce
1. Install the latest version of the dotnet runtime using the [dotnet install script](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script). Install command used: `dotnet-install.ps1 -Channel 6.0.1xx -Quality daily`
2. Using the latest dotnet runtime, run `dotnet workload update`

### Exceptions (if any)
```
System.ArgumentNullException: Value cannot be null. (Parameter 'paths')
   at System.IO.Path.Combine(String[] paths)
   at Microsoft.DotNet.Workloads.Workload.WorkloadFileBasedInstall.GetUserInstallFilePath(String dotnetDir, String sdkFeatureBand)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallerFactory.GetWorkloadInstaller(IReporter reporter, SdkFeatureBand sdkFeatureBand, IWorkloadResolver workloadResolver, VerbosityOptions verbosity, String userProfileDir, INuGetPackageDownloader nugetPackageDownloader, String dotnetDir, String tempDirPath, PackageSourceLocation packageSourceLocation, RestoreActionConfig restoreActionConfig, Boolean elevationRequired)
   at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version)
   at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.<get_SubCommands>b__9_2(ParseResult appliedOption)
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

### Further technical details
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21460.6
 Commit:    09a29e5308

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\WDAGUtilityAccount\Desktop\dotnet\sdk\6.0.100-rc.2.21460.6\

Host (useful for support):
  Version: 6.0.0-rc.2.21459.6
  Commit:  06b23ba6ed

.NET SDKs installed:
  6.0.100-rc.2.21460.6 [C:\Users\WDAGUtilityAccount\Desktop\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.2.21459.34 [C:\Users\WDAGUtilityAccount\Desktop\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21459.6 [C:\Users\WDAGUtilityAccount\Desktop\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21459.9 [C:\Users\WDAGUtilityAccount\Desktop\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download 
```
- Successful output from previous versions
```
No workloads installed for this feature band. To update workloads installed with earlier SDK versions, include the --from-previous-sdk option.
Skip NuGet package signing validation. The current .NET SDK is not signed by first party.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
No workloads installed for this feature band. To update workloads installed with earlier SDK versions, include the --from-previous-sdk option.
Garbage collecting for SDK feature band(s) ...

Successfully updated workload(s): .
```

**Comment by LoopedBard3** [comment]
This seems to have been fixed in the latest version (6.0.100-rc.2.21460.37)
