### ISSUE TITLE
Parsing CSV (TextFieldParser) from ZipArchive fails with .net 6 RC1. 

### ISSUE THREAD

**Issue by ashcor** [dotnet/sdk#21030]
### Describe the bug
Parsing a CSV file extracted from a ZipArchive fails with a MalformedLineExceptionin .net 6 RC 1.
```
         class Program
       {
        static void Main(string[] args)
        {
            Console.WriteLine($"Lines: {ReadCsv().Count()}");
        }

        public static IEnumerable<string[]> ReadCsv()
        {
            using (var zipStream = File.OpenRead("stops.zip"))
            using (var archive = new ZipArchive(zipStream))
            using (var stream = archive.GetEntry("stops.txt").Open())
            using (var reader = new StreamReader(stream))
            using (var parser = new TextFieldParser(reader)
            {
                TextFieldType = FieldType.Delimited,
                Delimiters = new string[] { "," },
                HasFieldsEnclosedInQuotes = true,
            })
            {
                while (!parser.EndOfData)
                    yield return parser.ReadFields();
            }
        }
    }
```

### To Reproduce
clone https://github.com/ashcor/net6parse/tree/main/ConsoleApp1 and do `dotnet run`. The code fails with .net 6 RC1 but works fine when changing to `<TargetFramework>net5.0</TargetFramework>`. The zip file in question was produced with 7zip with the default settings. The encoding of the zipped file is UTF-8 BOM. Not sure 

### Exceptions (if any)
```
PS C:\Users\ashco\Documents\Github\net6parse\ConsoleApp1> dotnet run
Unhandled exception. Microsoft.VisualBasic.FileIO.MalformedLineException: Line 39136 cannot be parsed using the current Delimiters.
   at Microsoft.VisualBasic.FileIO.TextFieldParser.ParseDelimitedLine()
   at Microsoft.VisualBasic.FileIO.TextFieldParser.ReadFields()
   at ConsoleApp1.Program.ReadCsv()+MoveNext() in C:\Users\ashco\Documents\Github\net6parse\ConsoleApp1\Program.cs:line 31
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\ashco\Documents\Github\net6parse\ConsoleApp1\Program.cs:line 14 Line Number:39136
```

### Further technical details
`dotnet --info`
```
PS C:\Users\ashco\Documents\Github\net6parse\ConsoleApp1> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21458.32
 Commit:    d7c22323c4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1
```

**Comment by KalleOlaviNiemitalo** [comment]
Likely related to [Breaking change: Partial and zero-byte reads in DeflateStream, GZipStream, and CryptoStream - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams) and <https://github.com/dotnet/runtime/pull/53644>. The [TextFieldParser.ReadNextLine](https://github.com/dotnet/runtime/blob/d7619cd4b165c13430484e381042f055d4c5a9c7/src/libraries/Microsoft.VisualBasic.Core/src/Microsoft/VisualBasic/FileIO/TextFieldParser.vb#L800-L872) method appears to correctly loop calling `ByVal ChangeBuffer As ChangeBufferFunction`, i.e. either IncreaseBufferSize or ReadToBuffer, until it gets vbCr, vbLf, or a zero-length read; but perhaps there is some problem that I'm not noticing.

**Comment by ashcor** [comment]
@KalleOlaviNiemitalo yes, this could likely be related. When changing the code to read full lines
```
while (!parser.EndOfData)
        yield return parser.ReadLine();
```
the last line of the file is only partially read:
```
"8793698","Buswiller-Eglise","48.8194726014747","7.55968244303174","",""
"8799
```

With a different parser, eg CsvHelper
```
 using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
  {
      while (csv.Read())
          yield return csv.Parser.RawRecord;
  }
```
the last two lines are read as expected:
```
"8793698","Buswiller-Eglise","48.8194726014747","7.55968244303174","",""
"8799803","Annecy, gare routière","45.9020779242132","6.11820082216869","",""
```
