### ISSUE TITLE
Microsoft.PackageDependencyResolution.targets(5,5): Error MSB4018: The "JoinItems" task failed unexpectedly.

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/sdk#2132]
This is `2.1.300-preview1-008174`.

We're on the VSMac team and we have a bug:

1. Create a new ASP.NET Core Web App that uses .NET Core 2.1 (the version above)
2. The created web project fails to build with:

```
C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets
line 456
C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(5,5): Error MSB4018: The "JoinItems" task failed unexpectedly.
System.InvalidOperationException: The item metadata "%(FileName)" cannot be applied to the path "C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Microsoft.NET.Sdk\build\..\..\..\..\NuGetFallbackFolder\microsoft.aspnetcore.authentication.microsoftaccount\2.1.0-preview1-final\lib\netstandard2.0\Microsoft.AspNetCore.Authentication.MicrosoftAccount.dll". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
  at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args)
  at Microsoft.Build.Shared.FileUtilities.ItemSpecModifiers.GetItemSpecModifier(String currentDirectory, String itemSpec, String definingProjectEscaped, String modifier, String& fullPath)
  at Microsoft.Build.Evaluation.BuiltInMetadata.GetMetadataValueEscaped(String currentDirectory, String evaluatedIncludeBeforeWildcardExpansionEscaped, String evaluatedIncludeEscaped, String definingProjectEscaped, String name, String& fullPath)
  at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetBuiltInMetadataEscaped(String name)
  at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadataEscaped(String metadataName)
  at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadata(String metadataName)
  at Microsoft.NET.Build.Tasks.JoinItems.<>c__DisplayClass28_0.<ExecuteCore>b__0(ITaskItem item)
  at System.Linq.Enumerable.<JoinIterator>d__38`4.MoveNext()
  at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
  at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
  at Microsoft.NET.Build.Tasks.JoinItems.ExecuteCore()
  at Microsoft.NET.Build.Tasks.TaskBase.Execute()
  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
  at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() (MSB4018) (mvc21test)
```

The path `C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Microsoft.NET.Sdk\build\..\..\..\..\NuGetFallbackFolder\microsoft.aspnetcore.authentication.microsoftaccount\2.1.0-preview1-final\lib\netstandard2.0\Microsoft.AspNetCore.Authentication.MicrosoftAccount.dll` is too long.

This seems to be a recent regression since this error is not present in .NET Core 2.0. 

I'm guessing that a carefully placed `Path.GetFullPath` should shorten this path significantly by removing all those `..\..\..\..`.

@dsplaisted would be super nice to understand what's going on here.

cc @toddgrun

**Comment by dsplaisted** [comment]
@KirillOsenkov What version of VS / MSBuild are you using?

**Comment by KirillOsenkov** [comment]
VS 2017 15.6.3 on Windows

**Comment by KirillOsenkov** [comment]
@dsplaisted do you have some estimate for us on this bug? Thanks!

**Comment by rrelyea** [comment]
In the parallel NuGet issue (https://github.com/NuGet/Home/issues/7132) I ask if we know what has changed here in 2.1.400/15.8?

**Comment by KirillOsenkov** [comment]
We now think that this is a MonoDevelop-specific issue: https://github.com/mono/monodevelop/issues/5556

Closing this one.
