### ISSUE TITLE
Update to .NET 6 RC 2, then workloads are not able to GC

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/sdk#21983]
### Describe the bug

```
$ sudo dotnet workload update --verbosity diag
```

Prints a warning:
```
Warning: Workload garbage collection failed with error:    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkManagedInstaller.GarbageCollectInstalledWorkloadPacks(Nullable`1 offlineCache)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand.TryRunGarbageCollection(IInstaller workloadInstaller, IReporter reporter, VerbosityOptions verbosity, Nullable`1 offlineCache).
```

It does not appear to be able to remove (GC) the older workload pack versions:

```
$ ls /usr/local/share/dotnet/packs/Microsoft.Android.Ref
31.0.100-rc.1.12      31.0.101-preview.9.16
```

### To Reproduce

I think you could:

1. Install .NET 6 RC 1, and the RC 1 `maui` workload. You might need to use a rollback file to do this.
2. Install .NET 6 RC 2
3. Run `dotnet workload update`

### Further technical details

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.6
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-rc.2.21505.57/

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  5.0.400 [/usr/local/share/dotnet/sdk]
  6.0.100-rc.1.21458.32 [/usr/local/share/dotnet/sdk]
  6.0.100-rc.2.21505.57 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/dotnet/sdk/pull/20876> was merged between v6.0.100-rc.1.21458.71 and v6.0.100-rc.2.21505.11, so this is now a cross RC conflict rather than the intended cross preview conflict.
