### ISSUE TITLE
.NET 6 RC 2 PublishReadyToRun=true causes TypeLoadException at MethodInfo.GetCustomAttributes(bool) in certain conditions

### ISSUE THREAD

**Issue by recumbented** [dotnet/sdk#22258]
### Describe the bug

At assembly published with .NET 6 RC 2 PublishReadyToRun=true,
TypeLoadException is thrown at MethodInfo.GetCustomAttributes(bool),
if the MethodInfo has 'async' keyword and contains non-ASCII character in classs or namespace name.

Assembly with PublishReadyToRun=false or published with .NET 5 SDK with PublishReadyToRun=true runs with no exception.

### To Reproduce
```C#
foreach (var type in System.Reflection.Assembly.GetExecutingAssembly().GetTypes().Where(t => t.Namespace is nameof(Classes)))
{
    foreach (var method in type.GetMethods())
    {
        Console.WriteLine($"{type.FullName}.{method}");
        method.GetCustomAttributes(inherit: false);
    }
}

//
namespace Classes
{
    public class ASCIINameClass
    {
        public void SyncMethod()
        {
        }

        public async Task AsyncMethod() => await Task.CompletedTask;
    }

    public class UmlautNämeClass
    {
        public void SyncMethod()
        {
        }

        public async Task AsyncMethod() => await Task.CompletedTask;
    }

    public class 日本語NameClass
    {
        public void SyncMethod()
        {
        }

        public async Task AsyncMethod() => await Task.CompletedTask;
    }
}
```
dotnet publish -c Debug -p:PublishReadyToRun=true -r win-x64 --self-contained=false

### Exceptions (if any)
Unhandled exception. System.TypeLoadException: Could not load type 'Classes.UmlautNameClass+<AsyncMethod>d__1' from assembly 'ReadyToRunValidator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Boolean inherit)
   at Program.<Main>$(String[] args) in R:\Volatile\ReadyToRunValidator\ReadyToRunValidator\Program.cs:line 6

### Further technical details
- dotnet  Version:   6.0.100-rc.2.21505.57

**Comment by marcpopMSFT** [comment]
Old issue triage: Please ping if this is still an issue.
