### ISSUE TITLE
Race condition in ResolvePackageAssets leading to InvalidDataException

### ISSUE THREAD

**Issue by dfederm** [dotnet/sdk#22538]
### Describe the bug
`ResolvePackageAssets` throws a `InvalidDataException` in certain race conditions.

### To Reproduce
Assume there are 3 projects: `src\A\A.csproj` (A), `src\B\B.csproj` (B), and `src\C\C.csproj` (C).

A and B both depend on C, but via different directory symlinks. A references C via some `ASandbox\C\C.csproj` (`ASandbox\` is a directory symlink to `src\`) and similarly B references C via `BSandbox\C\C.csproj` (`BSandbox\` is a directory symlink to `src\`)

Intermittently we'll see the following when building both A and B at the same time:
```
The "ResolvePackageAssets" task failed unexpectedly.
System.IO.InvalidDataException: Found invalid data while decoding.
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.ValidateHeader(BinaryReader reader, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.OpenCacheStream(Stream stream, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

It seems like the race specifically is on the second read of the cache file. On first read the cache file, the exception is caught. Then the cache file is written to disk and the re-read from disk. If that 2nd read fails, the exception is not caught and fails the build. The race condition seems to be if there are two of these "write+2nd reads" at the same time. I believe the symlinks are important here since the project's path is part of the "settings hash" used in the cache file's header.

### Further technical details
This is a CloudBuild scenario

**Comment by dfederm** [comment]
FYI @dsplaisted based on offline discussion

**Comment by lambdageek** [comment]
I'm getting this with .NET 7 Preview 1 in local builds on macOS sometimes for a Blazor WebAssembly project.  (`dotnet new blazorwasm` then `dotnet build` a half-dozen times while making minor changes to Counter.razor)


```
/usr/local/share/dotnet/sdk/7.0.100-preview.1.22110.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly. [/Users/alklig/work/blazor-net7p1/hrtest1/hrtest1.csproj]
/usr/local/share/dotnet/sdk/7.0.100-preview.1.22110.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018: System.IO.InvalidDataException: Found invalid data while decoding. [/Users/alklig/work/blazor-net7p1/hrtest1/hrtest1.csproj]
/usr/local/share/dotnet/sdk/7.0.100-preview.1.22110.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.ValidateHeader(BinaryReader reader, Byte[] settingsHash) [/Users/alklig/work/blazor-net7p1/hrtest1/hrtest1.csproj]
/usr/local/share/dotnet/sdk/7.0.100-preview.1.22110.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.OpenCacheStream(Stream stream, Byte[] settingsHash) [/Users/alklig/work/blazor-net7p1/hrtest1/hrtest1.csproj]
/usr/local/share/dotnet/sdk/7.0.100-preview.1.22110.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.OpenCacheFile(String path, Byte[] settingsHash) [/Users/alklig/work/blazor-net7p1/hrtest1/hrtest1.csproj]
/usr/local/share/dotnet/sdk/7.0.100-preview.1.22110.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash) [/Users/alklig/work/blazor-net7p1/hrtest1/hrtest1.csproj]
/usr/local/share/dotnet/sdk/7.0.100-preview.1.22110.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task) [/Users/alklig/work/blazor-net7p1/hrtest1/hrtest1.csproj]
/usr/local/share/dotnet/sdk/7.0.100-preview.1.22110.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups() [/Users/alklig/work/blazor-net7p1/hrtest1/hrtest1.csproj]
/usr/local/share/dotnet/sdk/7.0.100-preview.1.22110.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore() [/Users/alklig/work/blazor-net7p1/hrtest1/hrtest1.csproj]
/usr/local/share/dotnet/sdk/7.0.100-preview.1.22110.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/Users/alklig/work/blazor-net7p1/hrtest1/hrtest1.csproj]
/usr/local/share/dotnet/sdk/7.0.100-preview.1.22110.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/alklig/work/blazor-net7p1/hrtest1/hrtest1.csproj]
/usr/local/share/dotnet/sdk/7.0.100-preview.1.22110.4/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/alklig/work/blazor-net7p1/hrtest1/hrtest1.csproj]
```

Doing `killall dotnet` between builds to kill off the MSBuild nodes doesn't help.

**Comment by baronfel** [comment]
@dfederm are y'all still seeing this in cloudbuild on non-preview 7+ SDKs?

**Comment by baronfel** [comment]
ping @dfederm - have you seen this reappear in the meantime?

**Comment by dfederm** [comment]
I don't recall seeing this recently, but I also haven't been tracking this specific issue closely.

**Comment by marcpopMSFT** [comment]
Old issue triage: Likely the race was fixed at some point. Closing.
