### ISSUE TITLE
Cannot sign certificates with elliptic curve secp256k1

### ISSUE THREAD

**Issue by msfcolombo** [dotnet/sdk#22660]
### Description

The `CertificateRequest.CreateSelfSigned` does not work with the blockchain curve secp256k1. I get an exception with message `The provided key does not match the public key for this certificate. (Parameter 'privateKey')`. The NIST P-256 curve works fine.

### Steps to Reproduce

Run the following on Win10 x64 and dotnet 5.0.12:

```c#
using System;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;

namespace Secp256k1Repro
{
    public static class Secp256k1Repro
    {
        public static void Main()
        {
            Console.WriteLine("FrameworkDescription: {0}", RuntimeInformation.FrameworkDescription);
            Console.WriteLine("RuntimeIdentifier: {0}", RuntimeInformation.RuntimeIdentifier);
            Console.WriteLine("OSArchitecture: {0}", RuntimeInformation.OSArchitecture);
            Console.WriteLine("OSDescription: {0}", RuntimeInformation.OSDescription);
            Console.WriteLine("Environment Version: {0}", Environment.Version);

            TestCurve(ECCurve.NamedCurves.nistP256);
            TestCurve(ECCurve.CreateFromFriendlyName("secp256k1"));
        }

        private static void TestCurve(ECCurve curve)
        {
            Console.WriteLine("---------------------------");
            Console.WriteLine("Using curve oid={0}, friendlyName={1}", curve.Oid.Value, curve.Oid.FriendlyName ?? "(null)");
            try
            {
                ECDsa ecdsa = ECDsa.Create(curve);
                CertificateRequest req = new("CN=foo.com", ecdsa, HashAlgorithmName.SHA256);
                DateTimeOffset now = DateTimeOffset.UtcNow;
                req.CreateSelfSigned(now, now + TimeSpan.FromDays(180));
                Console.WriteLine("Worked.");
            }
            catch (Exception ex)
            {
                Console.WriteLine("{0}", ex);
            }

            Console.WriteLine("---------------------------");
        }
    }
}

```

The output will be:

```
FrameworkDescription: .NET 5.0.12
RuntimeIdentifier: win10-x64
OSArchitecture: X64
OSDescription: Microsoft Windows 10.0.19043
Environment Version: 5.0.12
---------------------------
Using curve oid=1.2.840.10045.3.1.7, friendlyName=nistP256
Worked.
---------------------------
---------------------------
Using curve oid=1.3.132.0.10, friendlyName=secp256k1
System.ArgumentException: The provided key does not match the public key for this certificate. (Parameter 'privateKey')
   at System.Security.Cryptography.X509Certificates.ECDsaCertificateExtensions.CopyWithPrivateKey(X509Certificate2 certificate, ECDsa privateKey)
   at System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSelfSigned(DateTimeOffset notBefore, DateTimeOffset notAfter)
   at Secp256k1Repro.Secp256k1Repro.TestCurve(ECCurve curve)
---------------------------
```

### Further technical details

```
C:\>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.403
 Commit:    bf9d168ac2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.403\

Host (useful for support):
  Version: 5.0.12
  Commit:  7211aa01b3

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.526 [C:\Program Files\dotnet\sdk]
  2.1.818 [C:\Program Files\dotnet\sdk]
  2.2.110 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.120 [C:\Program Files\dotnet\sdk]
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.209 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by msfcolombo** [comment]
Sorry, this should be on runtime. Let me close that.
