### ISSUE TITLE
`Version string portion was too short or too long` error while installing dotnet-dev-certs

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/sdk#22734]
In 6.0.2xx I get an ArgumentException while trying to install the latest dotnet-dev-certs.

``` bash
> /repos/tarball1/testing-smoke/builtCli/dotnet tool install -g dotnet-dev-certs --version 6.0.0-rtm.21573.1 --add-source https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json
Unhandled exception: System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.<>c.<Execute>b__17_1(NuGetFramework f)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallCommand.Execute()
   at Microsoft.DotNet.Cli.ToolInstallCommandParser.<>c.<ConstructCommand>b__14_0(ParseResult parseResult)
```

This was discovered by the source-build smoke-tests.

Related to https://github.com/dotnet/source-build/issues/2626

**Comment by sfoslund** [comment]
This is a known issue that has been fixed, let us know if you see it again. cc @joeloff

**Comment by ananya-R** [comment]
I see this issue again in VS2022 for mac when I am trying to load one of my project.

**Comment by CypherPotato** [comment]
I am seeing this issue when loading more than one project in VS2022 for windows.

**Comment by shahrozjan** [comment]
Still reporting it on the latest Visual Studio for Mac when trying run a Xamarin app in iOS
