### ISSUE TITLE
[dotnet-sdk-7.0.100-alpha.1.21568.2] GlobalTool trx2junit install failed

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/sdk#23289]
**Application Name**: trx2junit (global tool app)
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number**: dotnet-sdk-7.0.100-alpha.1.21568.2
 
**Verify Scenarios:**
1). Windows10 RS5 x64+dotnet-sdk-7.0.100-alpha.1.21568.2:Fail
2). Windows10 RS5 x64+dotnet-sdk-6.0.200-preview.21612.2: Pass

**Repro steps:**
1.Open cmd.exe form %windir%\System32
2.Input install command:  dotnet tool install -g trx2junit
3.Press keyboard 'Enter'

**Expected Result:**
install successfully.

**Actual Result:**
It shows error:
```
Unhandled exception: System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
at System.Version.Parse(String input)
at System.Version..ctor(String version)
at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.<>c.<Execute>b__17_1(NuGetFramework f)
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
```
Description:
Install global or local tool. Local tools are added to manifest and restored.

Usage:
dotnet tool install [<PACKAGE_ID>] [options]

Arguments:
<PACKAGE_ID> The NuGet Package Id of the tool to install.

Options:
-g, --global Install the tool for the current user.
--local Install the tool and add to the local tool manifest (default).
--tool-path <PATH> The directory where the tool will be installed. The directory will be created if it does not
exist.
--version <VERSION> The version of the tool package to install.
--configfile <FILE> The NuGet configuration file to use.
--tool-manifest <PATH> Path to the manifest file.
--add-source <SOURCE> Add an additional NuGet package source to use during installation.
--framework <FRAMEWORK> The target framework to install the tool for.
--prerelease determining whether to include pre-release packages.
--disable-parallel Prevent restoring multiple projects in parallel.
--ignore-failed-sources Treat package source failures as warnings.
--no-cache Do not cache packages and http requests.
--interactive Allows the command to stop and wait for user input or action (for example to complete
authentication).
-v, --verbosity <LEVEL> Set the MSBuild verbosity level. Allowed values are q[uiet], m[inimal], n[ormal],
d[etailed], and diag[nostic].
-a, --arch <arch> The target architecture.
-?, -h, --help Show command line help.

**Findings:**
According to this issue, this is a known issue and fixed in 6.0.2xx, but doesn't work in .NET 7.0.
https://github.com/dotnet/sdk/issues/22734

@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
This issue has been fixed in the latest build, hence closing it.

Windows10 RS5 x64+dotnet-sdk-7.0.100-alpha.1.22057.7: Pass
