### ISSUE TITLE
UseCommonOutputDirectory=true breaks CopyLocalLockFileAssemblies flag

### ISSUE THREAD

**Issue by human33** [dotnet/sdk#23342]
### Describe the bug

NuGet dependencies aren't getting copied if I set UseCommonOutputDirectory=true in my .csproj file.

### To Reproduce

1. Clone https://github.com/human33/dotnent-sdk-ref-copy-issue
2. Build and run

What happens: It crashes with ```Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'CJE, Version=3.3.10.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.``` 
because no dll was copied to output directory.

What should happen: CJE.dll should be copied to output dir during building process and console should print `Hello World!CJE.Event`.

### Further technical details

- Include the output of `dotnet --info`

.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  21.10
 OS Platform: Linux
 RID:         ubuntu.21.10-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  5.0.404 [/usr/share/dotnet/sdk]
  6.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

JetBrains Rider 2021.3.2, but works the same if I use `dotnent run` in project dir  

---

I'm trying to use UseCommonOutputDirectory because this [comment](https://github.com/dotnet/sdk/issues/17645#issuecomment-844492769) suggested this and I need to build my projects to one common directory.

**Comment by human33** [comment]
Also, if I set verbosity level to "Detailed", I see messages like:
>This reference is not "CopyLocal" because at least one source item had "Private" set to "false" and no source items had "Private" set to "true".

If it's not too complicated and somebody can help me by telling me where to look to fix the issue, I could try to fix it in my spare time.

**Comment by KalleOlaviNiemitalo** [comment]
The message about "CopyLocal" and "Private" comes even if you don't set UseCommonOutputDirectory.

The DLL in the package would normally be copied by the _CopyFilesMarkedCopyLocal target, but if `'$(UseCommonOutputDirectory)' == 'true'`, then that target does not copy anything. So the fix might be that you make the _CopyFilesMarkedCopyLocal target detect if some of the ReferenceCopyLocalPaths items came from NuGet packages, and copy them regardless of UseCommonOutputDirectory. On the other hand, if the items came from framework NuGet packages like Microsoft.WindowsDesktop.App.Ref, then I guess those still should not be copied. It seems pretty complicated.

**Comment by human33** [comment]
@KalleOlaviNiemitalo thanks for the explanation.

**Comment by jozefsivek** [comment]
This is clear regression in dotnet 6. Projects with `<TargetFramework>net5.0</TargetFramework>` do work, while `<TargetFramework>net6.0</TargetFramework>` will result in error, when using `<UseCommonOutputDirectory>True</UseCommonOutputDirectory>`.

Is there any update on when to expect solution? Building the solution to one directory, in order to save resources, should not be something impossible.

Note that for net6.0 projects without `<UseCommonOutputDirectory>True</UseCommonOutputDirectory>` the libraries like `Microsoft.Win32.Registry.dll` are copied too, which was not the case for net5.0 projects, whatever the reason is.

**Comment by justinswork** [comment]
Thanks for documenting this @jozefsivek I am seeing this regression as well

**Comment by bkoelman** [comment]
I'm trying to upgrade a working .NET 5 project that uses `UseCommonOutputDirectory` to .NET 6. After updating the TFM, xUnit tests no longer work.

```
Starting test discovery for requested test run
========== Starting test discovery ==========
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.TestPlatform.CoreUtilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'Microsoft.TestPlatform.CoreUtilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
. Please check the diagnostic logs for more information.
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(Boolean testHostExited)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
========== Test discovery aborted: 0 Tests found in 1.4 sec ==========
========== Starting test run ==========
========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
```

**Comment by yzbai** [comment]
> I'm trying to upgrade a working .NET 5 project that uses `UseCommonOutputDirectory` to .NET 6. After updating the TFM, xUnit tests no longer work.
> 
> ```
> Starting test discovery for requested test run
> ========== Starting test discovery ==========
> Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Testhost process exited with error: Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.TestPlatform.CoreUtilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> File name: 'Microsoft.TestPlatform.CoreUtilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
>    at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
> . Please check the diagnostic logs for more information.
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.ThrowOnTestHostExited(Boolean testHostExited)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
>    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.DiscoverTests(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler)
> ========== Test discovery aborted: 0 Tests found in 1.4 sec ==========
> ========== Starting test run ==========
> ========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
> ```

Same on me. Any new finding?

**Comment by yzbai** [comment]
@bkoelman Maybe your Test Project use <UseCommonOutputDirectory>true</UseCommonOutputDirectory> ?
Test Projects should not use this. 
Refer to this:  https://github.com/dotnet/roslyn/issues/8975#issuecomment-270699573

**Comment by bkoelman** [comment]
@yzbai Thanks, that helps. I had `UseCommonOutputDirectory` in Directory.Build.props, which I now made conditional for non-test projects:

```xml
<PropertyGroup Condition="!$(MSBuildProjectName.EndsWith('Test'))">
```
Unfortunately, that brings me back to the original issue that DLLs from NuGet dependencies aren't being copied.

Adding `<GenerateRuntimeConfigDevFile>true</GenerateRuntimeConfigDevFile>` helps for local development, but pointing to paths into my local user profile directory still prevents me from zipping up the output for someone else.

**Comment by lilith** [comment]
Related: https://github.com/dotnet/sdk/issues/27320

**Comment by Gav-Brown** [comment]
If it helps, I posted a possible solution [here](https://github.com/dotnet/sdk/issues/17645#issuecomment-1228955558) which allows you to not set `UseCommonOutputDirectory` but just the `OutputDir` and then projects, dlls, and NuGet dlls all get copied to a single "bin" folder without missing deps.json files etc.

**Comment by ChristoWolf** [comment]
I am observing the same issue in .NET 6 projects.
`UseCommonOutputDirectory=true` works, but even with `CopyLocalLockFileAssemblies=true` no NuGet dependencies are copied.

**Comment by jspanoeddson** [comment]
Any word on a fix for this?  Pretty annoying.  Have to remember to copy new stuff to the output directory.

**Comment by marcpopMSFT** [comment]
Old issue triage: @rainersigwald is this just a known gap in UseCommonOutputDirectory? Any suggestions?

**Comment by marcpopMSFT** [comment]
FWIW, it might be worth us documenting all the recommended ways of managing outputs for projects. We could also explore the concept of a metaproject that pulls together the outputs of all the dependencies that gives the result of UseCommonOutputDirectory but works better.

**Comment by lilith** [comment]
I agree, this is area is a deep source of misery, especially when you
combine multiple framework targets, native dlls, xplat, package publishing,
and unit testing. Having some approach that actually works would be
incredible.

**Comment by dsplaisted** [comment]
Per discussion on #23366, for some people setting `GenerateRuntimeConfigDevFile` to true may resolve this.  That setting will write a runtimeconfig.dev.json which will direct the runtime to look for libraries in the NuGet package folders that were used in the build.

**Comment by baronfel** [comment]
Folks that have commented on this thread - what use cases are you hoping to use `UseCommonOutputDirectory` for? In general, we regard multiple projects using the same output directory as a practice we do not want to encourage in the general case. This practice opens up your build to race conditions and dependency confusion due to multiple projects wanting to copy over different versions of transitive deps.

There may be more clear pathways for specific scenarios that you have - we'd like to hear more about them.

**Comment by cremor** [comment]
> In general, we regard multiple projects using the same output directory as a practice we do not want to encourage in the general case.

The feature exists and is [documented](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-change-the-build-output-directory?view=visualstudio&tabs=netfx#build-to-a-common-output-directory-1). Unless it is a legacy feature and is clearly documented to not be used any more, it should work correctly.

**Comment by Gav-Brown** [comment]
Hi @baronfel. I don't use `UseCommonOutputDirectory`, however, I do build to a single "bin" folder.
If it helps, my setup is as follows:

Set `OutputPath` to the same top-level "bin" folder for all projects.
Our solution has over 50 projects, with shared dlls and multiple exes.
They all use the same NuGet dependencies via a `Directory.Packages.props` file.

- Pros
  - All dlls, exes, support files etc end up in the same single place.
  - Unit/system tests etc. can all run any dll, exe without any additional setup
  - Installer can pull in all files from one place
  - etc.
- Cons
  - Sometimes during the build there is a race coping dependencies to `OutputPath`
    - But the built in retries typically resolve this
  - "Rebuild All" is broken, see [this](https://github.com/dotnet/sdk/issues/17645#issuecomment-1229268421)
    - Have to use "Clean All" and then "Build All"
    - I assume Rebuild is performing a clean and build per project, instead of clean all then build all

So while I just previously commented on this issue to help out, I hope the above information helps in some way.
p.s. I'm happy to hear of better ways to do this.

**Comment by jwfx** [comment]
@Gav-Brown
How did you solve the version mismatches of transitive dependencies that are not part of your Directory.Packages.props?
YourAppA -> NuGetA -> NuGet**C** v1.0.0
YourAppB -> NuGetB -> NuGet**C** v2.0.0

Since this part is basically completely unsolved in MSBuild/dotnet it is a gamble which version of NuGetC you end up with in the output folder. Alternatively it complains about conflicts trying to write the same file in the same place.

Sure, the transitive dependencies can also be version pinned in Directory.Packages.props, but that is a crazy amount of annoying manual work to maintain these versions.

As far as I currently know, MSBuild does sort out competing versions within an application, but not cross-application.

Any pointers how solve this would be appreciated.

**Comment by Gav-Brown** [comment]
@jwfx This could be a non-obvious issue with this approach. Though, I know Visual Studio complains when it resolves (at least some) NuGet packages to 2 different versions, and so I have to pin "some" packages. But i've never had to pin "all". That would be a pain, yes. I guess I don't know if VS complains for all conflicts, or just some.

Though having said that, if we have multiple dlls and exes all building separately and pulling down different dependency versions, how would you combine all these into one install folder? I know the version numbers are compiled into the dlls and they all work together, so I have to assume everything is working with our single "bin" folder approach. Else each dll/exe would require a dll version that didn't exist.

**Comment by jwfx** [comment]
> Though having said that, if we have multiple dlls and exes all building separately and pulling down different dependency versions, how would you combine all these into one install folder?

I have been chasing this question for years (#10415), but never found a good answer or solution. Just bouncing around from one half-baked thing, like `UseCommonOutputDirectory`, to the next.

For reasons I don't understand engineers at Microsoft do not seem to think that shipping more than a single application at once is a valid use case.
The compiler already sorts out all transitive dependencies properly within one application. Why can't it just do it for an entire solution, or multiple apps/libs that were being specified to be built together?

Nobody wants to ship duplicate DLLs, or do things like we did, copying everything together in a post-build step and sorting out all the conflicting dependency versions ourselves, hoping that nothing will blow up at runtime. The compiler could build a full cross-app dependency graph and then validate everything during compile time.

Instead the time is spent on things like AOT or trimming, which is barely being useable since there is always that one dependency that doesn't support it yet.

**Comment by Gav-Brown** [comment]
@jwfx Interesting. I do "publish" solution files. It's the only way I've found to publish a "product" containing multiple exes. I am surprised at the response you got. Even the official [.NET Publish](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish) webpage says it supports solution files.

Certainly I've used the approach I describe for over 20 years without issue. And still works on .NET 6 to .NET 10. Only "Rebuild All" is broken for me.
