### ISSUE TITLE
Can't install dotnet-ef 6.0.1 by command line

### ISSUE THREAD

**Issue by uopeydel** [dotnet/sdk#23435]
**My info**

```
C:\Windows\system32>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Error below**

```

C:\Windows\system32>dotnet tool install --global dotnet-ef --version 6.0.1
C:\Users\UserTestName\AppData\Local\Temp\j4xluze5.ga0\restore.csproj(5,31): error MSB4242: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk". Exception: "Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestFormatException: Missing or invalid manifest version
C:\Users\UserTestName\AppData\Local\Temp\j4xluze5.ga0\restore.csproj(5,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestReader.ReadWorkloadManifest(String id, String informationalPath, LocalizationCatalog localizationCatalog, Utf8JsonStreamReader& reader)
C:\Users\UserTestName\AppData\Local\Temp\j4xluze5.ga0\restore.csproj(5,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestReader.ReadWorkloadManifest(String manifestId, Stream manifestStream, Stream localizationStream, String informationalPath)
C:\Users\UserTestName\AppData\Local\Temp\j4xluze5.ga0\restore.csproj(5,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.LoadManifestsFromProvider(IWorkloadManifestProvider manifestProvider)
C:\Users\UserTestName\AppData\Local\Temp\j4xluze5.ga0\restore.csproj(5,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir)
C:\Users\UserTestName\AppData\Local\Temp\j4xluze5.ga0\restore.csproj(5,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir)
C:\Users\UserTestName\AppData\Local\Temp\j4xluze5.ga0\restore.csproj(5,31): error MSB4242:    at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
C:\Users\UserTestName\AppData\Local\Temp\j4xluze5.ga0\restore.csproj(5,31): error MSB4242:    at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.ResolveSdk(Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio)""
The tool package could not be restored.
Tool 'dotnet-ef' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```
 
**Ps.** I try to install another version and without specific version it's the same.

###  provider and version information
 
Windows 10
Target framework: ( .NET 5.0,.NET 6.0)
Operating system:
  Visual Studio 2019 16.11.9 
  Visual Studio 2022 17.0.4

**Comment by ajcvickers** [comment]
Moving to SDK since this does not seem specific to the dotnet-ef tool.

**Comment by roji** [comment]
@uopeydel yeah, this looks like it could be some sort of networking issue - for example, check that you have access to https://api.nuget.org/v3/index.json from the machine where this is happening. In any case this is a nuget feed access issue rather than anything related to EF Core.

**Comment by uopeydel** [comment]
@roji It able to access.

![image](https://user-images.githubusercontent.com/12793024/149511721-13229a1f-203c-4030-aae6-1af487cd7318.png)

**Comment by baronfel** [comment]
I think the actual error here is the workload manifest issue showing in the logs.  When tools are installed we behind the scenes 'restore' on an invisible project file,

@uopeydel can you try running `dotnet workload repair` to fix your manifests and retry the tool install?

**Comment by uopeydel** [comment]
@baronfel 
Still error.
```

C:\Windows\system32>dotnet workload repair
Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestFormatException: Missing or invalid manifest version
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestReader.ReadWorkloadManifest(String id, String informationalPath, LocalizationCatalog localizationCatalog, Utf8JsonStreamReader& reader)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestReader.ReadWorkloadManifest(String manifestId, Stream manifestStream, Stream localizationStream, String informationalPath)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.LoadManifestsFromProvider(IWorkloadManifestProvider manifestProvider)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir)
   at Microsoft.DotNet.Workloads.Workload.Repair.WorkloadRepairCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, String dotnetDir, String tempDirPath, String version, String userProfileDir)
   at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.<get_SubCommands>b__9_6(ParseResult appliedOption)
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Workloads.Workload.WorkloadCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

```

**Comment by baronfel** [comment]
Thanks for trying. I chatted with the team a bit about this today, and we're all uncertain how your workload manifests could have been corrupted in this way. If time is of the essence, I would suggest deleting the entire `sdk-manifests` directory from your SDK install location, and then reinstalling any workloads you're actually using via the `dotnet workload` family of commands. If you have more time then we can dig into how you acquired the workloads and your SDK/VS install situation for more details.

**Comment by uopeydel** [comment]
Now in delete directory ` C:\Program Files\dotnet\sdk-manifests  `
```

C:\Windows\system32>dotnet tool install --global dotnet-ef --version 6.0.1
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '6.0.1') was successfully installed.

```

Ok great it work fine!

Note: in that sdk-manifests directory it have only 6.0.100 And i try to uninstall dotnet sdk version from 3.1 to 6.0.1. It wouldnt create sdk-manifests directory again. And all command is i want to use work fine have no any error.

```

C:\Windows\system32>dotnet workload repair

No workloads are installed, nothing to repair. Run `dotnet workload search` to find workloads to install.

```
