### ISSUE TITLE
dotnet build -r crashes with exception

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/sdk#23510]
C:\> dotnet build -r      
System.InvalidOperationException: Required argument missing for option: -r
   at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
   at System.CommandLine.Parsing.OptionResult.GetValueOrDefault[T]()
   at System.CommandLine.Parsing.ParseResult.ValueForOption[T](String alias)
   at Microsoft.DotNet.Cli.Telemetry.TopLevelCommandNameAndOptionToLog.AllowList(ParseResult parseResult, Dictionary`2 measurements)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

### Describe the bug

Expected a good error not an exception stack.

### To Reproduce

`dotnet build -r`

### Exceptions (if any)
System.InvalidOperationException: Required argument missing for option: -r
   at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
   at System.CommandLine.Parsing.OptionResult.GetValueOrDefault[T]()
   at System.CommandLine.Parsing.ParseResult.ValueForOption[T](String alias)
   at Microsoft.DotNet.Cli.Telemetry.TopLevelCommandNameAndOptionToLog.AllowList(ParseResult parseResult, Dictionary`2 measurements)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by marcpopMSFT** [comment]
@jonsequitur Is the guidance to just wrap this in an exception handler? Looks like we check if the option exists before getting the value but there doesn't appear to be a way to check if the option has a value at all. https://github.com/dotnet/sdk/blob/2f85677968752d6ec3293b758f57754524f67ef3/src/Cli/dotnet/Telemetry/TopLevelCommandNameAndOptionToLog.cs#L38

**Comment by baronfel** [comment]
There's [`parseResult.HasOption(option)`](https://github.com/dotnet/command-line-api/blob/main/src/System.CommandLine/Parsing/ParseResultExtensions.cs#L178-L188) that would tell if it was safe to access the value. But this whole thing seems more like a parsing error to me - if `-r` requires an argument then it should fail fast on parsing, which means we need to make sure the Arity is set to `ArgumentArity.One`. I'm not sure that's being done with [the current argument registration](https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/CommonOptions.cs#L57-L63).
