### ISSUE TITLE
ResolvePackageAssets fails badly inside VS if you have a project with malformed or empty target framework

### ISSUE THREAD

**Issue by davkean** [dotnet/sdk#2363]
If you open the following file inside VS:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1_1</TargetFrameworks>
  </PropertyGroup>

</Project>
```

-or-

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1_1</TargetFrameworks>
  </PropertyGroup>

</Project>
```

Expected:

```
C:\Program Files\dotnet\sdk\2.1.400-preview-008963\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(96,5): error : The TargetFramework value '' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [C:\Users\davkean\Source\Repos\ClassLibrary20\ClassLibrary20\ClassLibrary20.csproj]
```

Actual:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "ResolvePackageAssets" task failed unexpectedly.
NuGet.Frameworks.FrameworkException: Invalid framework identifier ''.
   at NuGet.Frameworks.NuGetFramework.GetShortFolderName(IFrameworkNameProvider mappings)
   at Microsoft.NET.Build.Tasks.LockFileExtensions.GetTargetAndThrowIfNotFound(LockFile lockFile, NuGetFramework framework, String runtime)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter..ctor(ResolvePackageAssets task, Stream stream)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ClassLibrary20	C:\Program Files\dotnet\sdk\2.1.400-preview-008963\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	

```

Doesn't look like _CheckForUnsupportedTargetFramework is running in the correct places.

**Comment by davkean** [comment]
This was hit by an MVP.

**Comment by smoothdeveloper** [comment]
I'm getting this error, the scenario is: create a proj file from scratch and try to get code code to compile via `dotnet build`:

dotnet.future.proj:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <!-- netmodule power for .net sdk v+1  -->
    <Compile Include="src/cool.cs" />
    <Compile Include="src/awesome.fs" />
    <Compile Include="src/back.to.basics.vb" />
    <Compile Include="src/unsafe.il" />
  </ItemGroup>
  <Import Project=".paket/Paket.Restore.targets" />
</Project>
```

cmd.exe:
```console
C:\tmp\dotnetsdk-woes-or-fly\fromscratch>dotnet build
Microsoft (R) Build Engine version 16.0.385-preview+g966cdf2ac6 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\3.0.100-preview-010184\NuGet.targets(114,5): error : Invalid framework identifier ''. [C:\tmp\dotnetsdk-woes-or-fly\fromscratch\dotnet.future.proj]

Build FAILED.
```
Suggestions:

###  Have dotnet output troubleshooting suggestions after the error message:

* specify TargetFramework(s) on the command line: dotnet build -p:TargetFramework=net472
* edit dotnet.future.proj and add `<TargetFramework>` element to a `<PropertyGroup>`
* ( hypothetically ) run `dotnet alter project properties add TargetFramework=net472` to add the property to the project file
* ( hypothetically ) run `dotnet build --autofix-proj-file TargetFramework=net472`

### have the sdk resolve the default target (and print warnings while doing so):

For programs, I'm assuming here a given SDK has a default target runtime, for example, it would pick latest netcore of netframework for programs, and netstandard for class libraries.

The first part will make the developer workflow more fluent / help people that deal with msbuild project files with a text editor.

For the second part, I'm not sure this can be considered as casually as enhancing the error message, it is also probably less important from developer's standpoint.
