### ISSUE TITLE
Unable to update .NET6 workloads with  6.0.200-preview.22055.15

### ISSUE THREAD

**Issue by GouriKumari** [dotnet/sdk#23653]
### Describe the bug
Unable to update .NET6 workloads 6.0.101  to 6.0.200-preview versions

### To Reproduce
Install dotnet-sdk-6.0.101-osx-x64 and .NET6 workloads, https://gist.github.com/GouriKumari/119d63b1bf7d4f6b99180682601a7406#file-gistfile1-txt-L374
Install dotnet-sdk-6.0.200-preview.22055.15-osx-x64 and execute the following command from terminal:
`dotnet workload update --print-download-link-only --sdk-version 6.0.200-preview.22055.15 `

### Exceptions (if any)
 dotnet workload update --print-download-link-only --sdk-version 6.0.200-preview.22055.15
Failed to resolve manifest package URL microsoft.net.workload.emscripten.manifest-6.0.200.
Skip NuGet package signing validation. NuGet signing validation is not available on Linux or macOS https://aka.ms/workloadskippackagevalidation .
Failed to download manifest package microsoft.net.workload.emscripten.
Unhandled exception: Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Did not find workload manifest dependency 'Microsoft.NET.Workload.Emscripten' required by manifest 'microsoft.net.workload.mono.toolchain' [/var/folders/g4/1257z2rs3kbc1phy218c3bg80000gn/T/dotnet-manifest-extraction/microsoft.net.workload.mono.toolchain.manifest-6.0.200.6.0.2-mauipre.1.22076.3/WorkloadManifest.json]
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.ComposeWorkloadManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir)
   at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand.UseTempManifestsToResolvePacksAsync(DirectoryPath tempPath, Boolean includePreview)
   at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand.GetUpdatablePackageUrlsAsync(Boolean includePreview)
   at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand.Execute()
   at Microsoft.DotNet.Cli.WorkloadUpdateCommandParser.<>c.<ConstructCommand>b__15_0(ParseResult parseResult)
Description:
  Update all installed workloads.
### Further technical details
- Include the output of `dotnet --info`: https://gist.github.com/GouriKumari/f3204ff46e041ba691296b941b24f58f
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: https://gist.github.com/GouriKumari/0ba45b1851f0429abba421f2eb5bd268

**Comment by marcpopMSFT** [comment]
This is the same as https://github.com/dotnet/sdk/issues/23403. We plan on updating 6.0.200 with a 200 band emscripten which should resolve this and then we'll fix the other bug in .300.
