### ISSUE TITLE
"[XmlException] Data at the root level is invalid" at xml app.config read since .Net6

### ISSUE THREAD

**Issue by Maxyeah** [dotnet/sdk#23964]
### Describe the bug
Our internal configuration implementation with app.config isn´t working since update to .Net6.
If the application has no certificate at startup, it will create a new on and updates the app.config with properties from the certificate.
The Extension update fails with the following exception: [XmlException] Data at the root level is invalid. Line 1, position 1.
```
           // serialize value.
            var strm = new System.IO.MemoryStream();

            using (strm)
            {
                if (value != null)
                {
                    if (!UsesXmlSerialization(typeof(T)))
                    {
                        DataContractSerializer serializer = new DataContractSerializer(typeof(T));
                        serializer.WriteObject(strm, value);
                    }
                    else
                    {
                        XmlSerializer serializer = new XmlSerializer(typeof(T));
                        serializer.Serialize(strm, value);
                    }
                }
                // update dictionary.
                extensions[elementName] = strm.ToArray();
            }
```

The XML begins with:
```
 <?xml version="1.0" ?>
 <configuration>
   <configSections>
```

### Exceptions (if any)
Stack Trace:
[XmlException] Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at System.Xml.XmlDocument.set_InnerXml(String value)

### Further technical details
$ dotnet --info
.NET SDK (gem▒▒ "global.json"):
 Version:   6.0.101
 Commit:    ef49f6213a

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  2.1.806 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

- Running on VS2022 (Version 17.0.5)

**Comment by KalleOlaviNiemitalo** [comment]
A longer stack trace might help find the problem. Is the exception thrown during the `extensions[elementName] = strm.ToArray();` assignment or later?

**Comment by Maxyeah** [comment]
Hi, 
the thing is the exception will not thrown during `extensions[elementName] = strm.ToArray();` it is the last call in the function. But the exceptions appears after leaving the function.

```
[XmlException] Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at System.Xml.XmlDocument.set_InnerXml(String value)
   at Schema.SecuredApplication.Set[T](T extension, XmlQualifiedName name) in D:\Test\Schema\SecuredApplicationHelpers.cs:line 76
   at Schema.SecuredApplicationEx.UpdateXmlExtenions() in D:\Test\Configuration\SecuredApplication.IConfiguration.cs:line 452
   at Schema.SecuredApplicationAppConfig.Save() in D:\Test\Configuration\SecuredApplication.IConfiguration.cs:line 626
```

**Comment by KalleOlaviNiemitalo** [comment]
What is the type of `extensions` and how does the data get from there to the configuration system?

What kind of string does `SecuredApplication.Set<T>` assign to `InnerXml`? Is it the XML that you showed below "The XML begins with"?

The `strm.ToArray()` call returns a `byte[]`, which then goes to an element of `extensions`, but `InnerXml` needs a string, so there must be some kind of conversion in between.

**Comment by KalleOlaviNiemitalo** [comment]
I suspect a character encoding mismatch. Perhaps `strm.ToArray()` returns `byte[]` encoded in UTF-8 and you then convert that to `string` using some other encoding and attempt to assign the result to `InnerXml`.

**Comment by Maxyeah** [comment]
Thanks Kalle for your thoughts. 
We dig a bit deeper and found out that the `serializer.Serialize(strm, value);` method behaves different the think.

The exception like i mentioned comes from an other code part. We now find were.

the code is 
```
XmlDocument document = new XmlDocument();
string content = new UTF8Encoding(false).GetString(ii.Value);
document.InnerXml = content;
this.Extensions.Add(document.DocumentElement);
```
Where ii.Value is the value that comes from `extensions[elementName]` that is filled by the `serializer.Serialize(strm, value);` stream output. 

So we think `serializer.Serialize()` behaves different sins .net 6

The encoded byte[] in content string shows the difference:
With NetCore3.1: "<?xml version=\"1.0\"?>\r\n<EndpointSettings ...."
With Net6          : "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EndpointSettings ..."

**Comment by KalleOlaviNiemitalo** [comment]
It's caused by <https://github.com/dotnet/runtime/pull/54949>. `new XmlTextWriter(stream, null)` doesn't add a byte order mark, but `XmlWriter.Create(stream)` does.

**Comment by KalleOlaviNiemitalo** [comment]
Then this is a duplicate of <https://github.com/dotnet/runtime/issues/63585>.

**Comment by Maxyeah** [comment]
ok we will test it, thanks a lot @KalleOlaviNiemitalo
