### ISSUE TITLE
Implicit netstandard version from 2.2.1xx stage0 CLI cannot be found

### ISSUE THREAD

**Issue by nguerrera** [dotnet/sdk#2410]
Pinning it to 2.0.3 for now.

```
Microsoft.NET.Restore.Tests.GivenThatWeWantToRestoreToUseImplicitPackages.It_uses_NetstandardLibrary20x_as_the_implicit_version_for_NetStandard20 [FAIL]
      Expected string to be 
      "2.0.3" with a length of 5, but 
      "2.1.0-preview1-25902-01" has a length of 23.
      Stack Trace:
        C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs(32,0): at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
        C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs(197,0): at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
        C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringEqualityValidator.cs(30,0): at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstLengthDifferences()
        C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs(41,0): at FluentAssertions.Primitives.StringValidator.Validate()
        C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs(41,0): at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs)
        D:\Src\sdk\src\Tests\Microsoft.NET.Restore.Tests\GivenThatWeWantRestoreToUseImplicitPackages.cs(54,0): at Microsoft.NET.Restore.Tests.GivenThatWeWantToRestoreToUseImplicitPackages.It_uses_NetstandardLibrary20x_as_the_implicit_version_for_NetStandard20()
      Output:
        > D:\Src\sdk\.dotnet\dotnet.exe msbuild /t:restore D:\Src\sdk\artifacts\Debug\tmp\It_uses_Netst---76433CD0\NetStandard2Library\NetStandard2Library.csproj
        Microsoft (R) Build Engine version 15.8.138-preview+ge0cd4f1c1f for .NET Core
        Copyright (C) Microsoft Corporation. All rights reserved.
          Restoring packages for D:\Src\sdk\artifacts\Debug\tmp\It_uses_Netst---76433CD0\NetStandard2Library\NetStandard2Library.csproj...
        D:\Src\sdk\artifacts\Debug\tmp\It_uses_Netst---76433CD0\NetStandard2Library\NetStandard2Library.csproj : warning NU1603: NetStandard2Library depends on NETStandard.Library (>= 2.0.4-servicing-26522-02) but NETStandard.Library 2.0.4-servicing-26522-02 was not found. An approximate best match of NETStandard.Library 2.1.0-preview1-25902-01 was resolved.
          Generating MSBuild file D:\Src\sdk\artifacts\Debug\tmp\It_uses_Netst---76433CD0\NetStandard2Library\obj\NetStandard2Library.csproj.nuget.g.props.
          Generating MSBuild file D:\Src\sdk\artifacts\Debug\tmp\It_uses_Netst---76433CD0\NetStandard2Library\obj\NetStandard2Library.csproj.nuget.g.targets.
          Restore completed in 2.27 sec for D:\Src\sdk\artifacts\Debug\tmp\It_uses_Netst---76433CD0\NetStandard2Library\NetStandard2Library.csproj.
```  

```
 Microsoft.NET.Build.Tests.GivenThatWeWantToBuildADesktopLibrary.It_resolves_assembly_conflicts_with_a_NETFramework_library [FAIL]
      The command output contained a result it should not have contained: warning
      
      File Name: D:\Src\sdk\.dotnet\dotnet.exe
      Arguments: msbuild /t:Build D:\Src\sdk\artifacts\Debug\tmp\It_resolves_a---950EE480\NETFrameworkLibrary\NETFrameworkLibrary.csproj
      Exit Code: 0
      StdOut:
      Microsoft (R) Build Engine version 15.8.138-preview+ge0cd4f1c1f for .NET Core
      Copyright (C) Microsoft Corporation. All rights reserved.
      D:\Src\sdk\artifacts\Debug\bin\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(143,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [D:\Src\sdk\artifacts\Debug\tmp\It_resolves_a---950EE480\NETFrameworkLibrary\NETFrameworkLibrary.csproj]
      D:\Src\sdk\artifacts\Debug\tmp\It_resolves_a---950EE480\NETFrameworkLibrary\NETFrameworkLibrary.csproj : warning NU1603: NETFrameworkLibrary depends on NETStandard.Library (>= 2.0.4-servicing-26522-02) but NETStandard.Library 2.0.4-servicing-26522-02 was not found. An approximate best match of NETStandard.Library 2.1.0-preview1-25902-01 was resolved.
```

**Comment by nguerrera** [comment]
The actual netstandard.library bundled version in stage0 2.2.1xx CLI is 2.0.4-servicing-26522-02, not sure where the 2.1.0 came from!

**Comment by nguerrera** [comment]
Ah
``
D:\Src\sdk\artifacts\Debug\tmp\It_uses_Netst---76433CD0\NetStandard2Library\NetStandard2Library.csproj : warning NU1603: NetStandard2Library depends on NETStandard.Library (>= 2.0.4-servicing-26522-02) but NETStandard.Library 2.0.4-servicing-26522-02 was not found. An approximate best match of NETStandard.Library 2.1.0-preview1-25902-01 was resolved
```

**Comment by nguerrera** [comment]
I don't think we should be targeting netstandard 2.0.0x preview versions by default ever. The logic probably needs to be similar to netcoreapp, where we're prepared to target netstandard2.1 previews by default, but not servicing previews of previous versions.

**Comment by nguerrera** [comment]
The missing package was later found to be on the dotnet-core myget feed but not the blob feed. cc @dagood Do you know why NETStandard.Library 2.1.0-preview1-25902-01 would not be on the blob feed.

**Comment by nguerrera** [comment]
cc @johnbeisner Who I think was going to follow up on the feed issue with this package.

**Comment by nguerrera** [comment]
This is fixed. We handle 2.1 as a framework reference separately.
