### ISSUE TITLE
dotnet test fails on sdk 6.0.200 - System.AccessViolationException

### ISSUE THREAD

**Issue by alexandrehtrb** [dotnet/sdk#24124]
### Describe the bug
An exception is thrown when I run `dotnet test`, after updating to SDK version 6.0.200. It works perfectly with SDK versions 6.0.101 and 6.0.102.

The problem also happened with other unit test projects, not just the sample xUnit project.

### To Reproduce
* Install .NET SDK 6.0.200
* `mkdir TestTest`
* `cd TestTest`
* `dotnet new xunit`
* `dotnet test`

### Further technical details
- Include the output of `dotnet --info`

```
C:\Projetos\TestTest> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  6.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- Exception thrown in console:

```
C:\Projetos> CD TestTest
C:\Projetos\TestTest> dotnet new xunit
The template "xUnit Test Project" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Projetos\TestTest\TestTest.csproj...
  Determining projects to restore...
  Restored C:\Projetos\TestTest\TestTest.csproj (in 1,27 sec).
Restore succeeded.

C:\Projetos\TestTest> dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  TestTest -> C:\Projetos\TestTest\bin\Debug\net6.0\TestTest.dll
Test run for C:\Projetos\TestTest\bin\Debug\net6.0\TestTest.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication t
hat other memory is corrupt.
   at System.Reflection.RuntimeAssembly.InternalLoad(System.Runtime.CompilerServices.ObjectHandleOnStack, System.Runtime
.CompilerServices.ObjectHandleOnStack, System.Runtime.CompilerServices.StackCrawlMarkHandle, Boolean, System.Runtime.Com
pilerServices.ObjectHandleOnStack, System.Runtime.CompilerServices.ObjectHandleOnStack)
   at System.Reflection.RuntimeAssembly.InternalLoad(System.Reflection.AssemblyName, System.Reflection.RuntimeAssembly,
System.Threading.StackCrawlMark ByRef, Boolean, System.Runtime.Loader.AssemblyLoadContext)
   at System.Reflection.Assembly.Load(System.Reflection.AssemblyName)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.CurrentDomainAssemblyResolve(System.
Object, Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.Interfaces.AssemblyResolveEventArgs)
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformAssemblyResolver.AssemblyResolverEvent(System.Obj
ect, System.Object)
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(System.Reflection.AssemblyNam
e)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(System.Reflection.AssemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr, System.Reflection.AssemblyName)
   at System.Reflection.RuntimeModule.GetTypes(System.Reflection.RuntimeModule)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromAssembly[[
System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Can
on, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Reflection.Assemb
ly, System.Collections.Generic.Dictionary`2<System.String,System.__Canon>)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromFiles[[Sys
tem.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon,
 System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.String[], System.Col
lections.Generic.Dictionary`2<System.String,System.__Canon>)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsInformation[[S
ystem.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Cano
n, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generi
c.IEnumerable`1<System.String>)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.GetTestExtensions[[System.__Canon, S
ystem.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Privat
e.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<
System.String>)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.DiscoverTestExtensions[[System.__Can
on, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.P
rivate.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.String)
   at Microsoft.VisualStudio.TestPlatform.Common.Hosting.TestRuntimeExtensionManager.Create(Microsoft.VisualStudio.TestP
latform.ObjectModel.Logging.IMessageLogger)
   at Microsoft.VisualStudio.TestPlatform.Common.Hosting.TestRuntimeProviderManager.get_Instance()
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.TestEngine..ctor()
   at Microsoft.VisualStudio.TestPlatform.Client.TestPlatform..ctor()
   at Microsoft.VisualStudio.TestPlatform.Client.TestPlatformFactory.GetTestPlatform()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager..ctor()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.get_Instance()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.RunTestsArgumentProcessor+<>c.<get_Executor>b__6_0()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7be
a7798e]].ViaFactory(System.Threading.LazyThreadSafetyMode)
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7be
a7798e]].ExecutionAndPublication(System.LazyHelper, Boolean)
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7be
a7798e]].CreateValue()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7be
a7798e]].get_Value()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.ArgumentProcessorFactory+<>c__DisplayClass20_0.<WrapLaz
yProcessorToInitializeOnInstantiation>b__0()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7be
a7798e]].CreateValue()
   at System.Lazy`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7be
a7798e]].get_Value()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.GetArgumentProcessors(System.String[], System.Collections
.Generic.List`1<Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.IArgumentProcessor> ByRef)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.Execute(System.String[])
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Program.Main(System.String[])
```

**Comment by nohwnd** [comment]
I used 6.0.200 and it works just fine for me. Please confirm you are still having the issue. 

```
C:\t> mkcd xunit-fail
C:\t\xunit-fail> dotnet new globaljson --sdk-version 6.0.200
The template "global.json file" was created successfully.
C:\t\xunit-fail> ls

    Directory: C:\t\xunit-fail

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          07/03/2022    10:37             47 global.json

C:\t\xunit-fail> dotnet new xunit
The template "xUnit Test Project" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\t\xunit-fail\xunit-fail.csproj...
  Determining projects to restore...
  Restored C:\t\xunit-fail\xunit-fail.csproj (in 640 ms).
Restore succeeded.

C:\t\xunit-fail> dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  xunit-fail -> C:\t\xunit-fail\bin\Debug\net6.0\xunit-fail.dll
Test run for C:\t\xunit-fail\bin\Debug\net6.0\xunit-fail.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: < 1 ms - xunit-fail.dll (net6.0)
```

**Comment by nesc58** [comment]
Issue still exists with `6.0.201`

**Comment by nohwnd** [comment]
Oh there is a callstack in the original issue, I did not see that. It looks like it happens when extensions are loaded, please run `dotnet test --diag:logs\log.txt` There is probably going to be just 1 file. But if there are more please post the whole folder.

You can also VSTEST_RUNNER_DEBUG=1 to tell vstest.console to wait for a debugger to be attached, and attach from VS, e.g. how you do it in powershell:

```powershell
C:\t\xunit-fail> $env:VSTEST_RUNNER_DEBUG=1; dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  xunit-fail -> C:\t\xunit-fail\bin\Debug\net6.0\xunit-fail.dll
Test run for C:\t\xunit-fail\bin\Debug\net6.0\xunit-fail.dll (.NETCoreApp,Version=v6.0)
Waiting for debugger attach...
Process Id: 109648, Name: dotnet
```

Attach to 109648 from VS and Continue.

**Comment by alexandrehtrb** [comment]
Here is the log.txt:

```
TpTrace Verbose: 0 : 3164, 1, 2022/03/12, 10:21:56.563, 1796268267, vstest.console.dll, Version: 17.1.0-release-20220113-05
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796290926, vstest.console.dll, Using .Net Framework version:.NETCoreApp,Version=v6.0
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796292174, vstest.console.dll, FilePatternParser: The given file C:\Projetos\TestXunitFail\bin\Debug\net6.0\TestXunitFail.dll is a full path.
TpTrace Verbose: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796308660, vstest.console.dll, TestPluginCache.DiscoverTestExtensions: finding test extensions in assemblies ends with: RuntimeProvider.dll TPluginInfo: Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.Utilities.TestRuntimePluginInformation TExtension: Microsoft.VisualStudio.TestPlatform.ObjectModel.Host.ITestRuntimeProvider
TpTrace Verbose: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796309874, vstest.console.dll, TestPluginCache.GetExtensionPaths: Filtered extension paths: 
TpTrace Verbose: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796313512, vstest.console.dll, TestPluginCache.GetExtensionPaths: Added default extension paths: C:\Program Files\dotnet\sdk\6.0.200\Extensions\DumpMinitool.exe
C:\Program Files\dotnet\sdk\6.0.200\Extensions\DumpMinitool.x86.exe
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.Diagnostics.NETCore.Client.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.TestPlatform.Extensions.BlameDataCollector.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.TestPlatform.Extensions.EventLogCollector.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.TestPlatform.TestHostRuntimeProvider.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.dll
TpTrace Verbose: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796313782, vstest.console.dll, TestPluginCache.GetExtensionPaths: Added unfilterableExtensionPaths: 
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796316772, vstest.console.dll, AssemblyResolver.ctor: Creating AssemblyResolver with searchDirectories C:\Program Files\dotnet\sdk\6.0.200\Extensions,C:\Program Files\dotnet\sdk\6.0.200
TpTrace Verbose: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796319745, vstest.console.dll, TestPluginCache.DiscoverTestExtensions: Discovering the extensions using extension path.
TpTrace Verbose: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796320434, vstest.console.dll, TestPluginCache.GetExtensionPaths: Filtered extension paths: 
TpTrace Verbose: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796320542, vstest.console.dll, TestPluginCache.GetExtensionPaths: Added default extension paths: C:\Program Files\dotnet\sdk\6.0.200\Extensions\DumpMinitool.exe
C:\Program Files\dotnet\sdk\6.0.200\Extensions\DumpMinitool.x86.exe
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.Diagnostics.NETCore.Client.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.TestPlatform.Extensions.BlameDataCollector.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.TestPlatform.Extensions.EventLogCollector.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.TestPlatform.TestHostRuntimeProvider.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.dll
TpTrace Verbose: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796320639, vstest.console.dll, TestPluginCache.GetExtensionPaths: Added unfilterableExtensionPaths: 
TpTrace Verbose: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796320873, vstest.console.dll, TestPluginCache.DiscoverTestExtensions: Discovering the extensions using allExtensionPaths: C:\Program Files\dotnet\sdk\6.0.200\Extensions\DumpMinitool.exe
C:\Program Files\dotnet\sdk\6.0.200\Extensions\DumpMinitool.x86.exe
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.Diagnostics.NETCore.Client.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.TestPlatform.Extensions.BlameDataCollector.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.TestPlatform.Extensions.EventLogCollector.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.TestPlatform.TestHostRuntimeProvider.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Html.TestLogger.dll
C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions.Trx.TestLogger.dll
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796321523, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\6.0.200\Extensions,C:\Program Files\dotnet\sdk\6.0.200
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796321681, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\6.0.200\Extensions,C:\Program Files\dotnet\sdk\6.0.200
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796321767, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\6.0.200\Extensions,C:\Program Files\dotnet\sdk\6.0.200
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796321854, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\6.0.200\Extensions,C:\Program Files\dotnet\sdk\6.0.200
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796321931, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\6.0.200\Extensions,C:\Program Files\dotnet\sdk\6.0.200
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796322013, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\6.0.200\Extensions,C:\Program Files\dotnet\sdk\6.0.200
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796322089, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\6.0.200\Extensions,C:\Program Files\dotnet\sdk\6.0.200
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796322163, vstest.console.dll, AssemblyResolver.AddSearchDirectories: Adding more searchDirectories C:\Program Files\dotnet\sdk\6.0.200\Extensions,C:\Program Files\dotnet\sdk\6.0.200
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.573, 1796323567, vstest.console.dll, AssemblyResolver.OnResolve: DumpMinitool: Resolving assembly.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796324414, vstest.console.dll, AssemblyResolver.OnResolve: DumpMinitool: Searching in: 'C:\Program Files\dotnet\sdk\6.0.200\Extensions'.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796324781, vstest.console.dll, AssemblyResolver.OnResolve: DumpMinitool: Assembly path does not exist: 'C:\Program Files\dotnet\sdk\6.0.200\Extensions\DumpMinitool.dll', returning.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796325820, vstest.console.dll, AssemblyResolver.OnResolve: DumpMinitool: Loading assembly 'C:\Program Files\dotnet\sdk\6.0.200\Extensions\DumpMinitool.exe'.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796326992, vstest.console.dll, AssemblyResolver.OnResolve: Resolved assembly: DumpMinitool, from path: C:\Program Files\dotnet\sdk\6.0.200\Extensions\DumpMinitool.exe
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796333914, vstest.console.dll, AssemblyResolver.OnResolve: DumpMinitool.x86: Resolving assembly.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796334242, vstest.console.dll, AssemblyResolver.OnResolve: DumpMinitool.x86: Searching in: 'C:\Program Files\dotnet\sdk\6.0.200\Extensions'.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796334506, vstest.console.dll, AssemblyResolver.OnResolve: DumpMinitool.x86: Assembly path does not exist: 'C:\Program Files\dotnet\sdk\6.0.200\Extensions\DumpMinitool.x86.dll', returning.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796335276, vstest.console.dll, AssemblyResolver.OnResolve: DumpMinitool.x86: Loading assembly 'C:\Program Files\dotnet\sdk\6.0.200\Extensions\DumpMinitool.x86.exe'.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796336260, vstest.console.dll, AssemblyResolver.OnResolve: Resolved assembly: DumpMinitool.x86, from path: C:\Program Files\dotnet\sdk\6.0.200\Extensions\DumpMinitool.x86.exe
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796337502, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Diagnostics.NETCore.Client: Resolving assembly.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796337655, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Diagnostics.NETCore.Client: Searching in: 'C:\Program Files\dotnet\sdk\6.0.200\Extensions'.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796338220, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Diagnostics.NETCore.Client: Loading assembly 'C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.Diagnostics.NETCore.Client.dll'.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796344290, vstest.console.dll, AssemblyResolver.OnResolve: Resolved assembly: Microsoft.Diagnostics.NETCore.Client, from path: C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.Diagnostics.NETCore.Client.dll
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796352793, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Resolving assembly.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796353123, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Searching in: 'C:\Program Files\dotnet\sdk\6.0.200\Extensions'.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796353361, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Assembly path does not exist: 'C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.Bcl.AsyncInterfaces.dll', returning.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796353488, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Assembly path does not exist: 'C:\Program Files\dotnet\sdk\6.0.200\Extensions\Microsoft.Bcl.AsyncInterfaces.exe', returning.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796353558, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Searching in: 'C:\Program Files\dotnet\sdk\6.0.200'.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796353700, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Assembly path does not exist: 'C:\Program Files\dotnet\sdk\6.0.200\Microsoft.Bcl.AsyncInterfaces.dll', returning.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796353819, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Assembly path does not exist: 'C:\Program Files\dotnet\sdk\6.0.200\Microsoft.Bcl.AsyncInterfaces.exe', returning.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796353889, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Failed to load assembly.
TpTrace Verbose: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796354018, vstest.console.dll, CurrentDomainAssemblyResolve: Resolving assembly 'Microsoft.Bcl.AsyncInterfaces'.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796354192, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Resolving assembly.
TpTrace Information: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796354318, vstest.console.dll, AssemblyResolver.OnResolve: Microsoft.Bcl.AsyncInterfaces: Resolved from cache.
TpTrace Verbose: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796354400, vstest.console.dll, CurrentDomainAssemblyResolve: Resolving assembly 'Microsoft.Bcl.AsyncInterfaces'.
TpTrace Verbose: 0 : 3164, 1, 2022/03/12, 10:21:56.583, 1796354527, vstest.console.dll, CurrentDomainAssemblyResolve: Failed to resolve assembly 'Microsoft.Bcl.AsyncInterfaces'.
```

**Comment by TheRealAyCe** [comment]
Could this be related to using Windows 7?

**Comment by nohwnd** [comment]
I am unable to startup Win7 virtual machine with dotnet 6, I guess that is because I don't have extended security updates.

**Comment by loop-evgeny** [comment]
This is also happening to me with NUnit [https://github.com/microsoft/vstest/issues/3543] and downgrading to SDK 6.0.103 works around it.

**Comment by lycanthotep** [comment]
This problem still happens in 6.0.301, NUnit and MSTest don't work.
The only solution I found was downgrading to 6.0.103.

**Comment by GeorgeVovos** [comment]
For me both 6.0.301 and 6.0.200 fail.
I had to swtich to 6.0.101 for it to work
