### ISSUE TITLE
dotnet tool install error installing when a private feed is in nuget.config

### ISSUE THREAD

**Issue by kjbartel** [dotnet/sdk#24140]
### Describe the bug
dotnet tool install -g foobar does not install any tools if a private nuget feed is in the nuget.config which requires authentication.

This is an exact copy of https://github.com/dotnet/sdk/issues/9555 which has incorrectly been closed and subsequently ignored even though multiple people continue to comment begging the for the bug to be fixed.

### To Reproduce
Execute:
'dotnet tool install -g sourcelink'
and have in the the global nuget.config the company nuget feed from vsts.

If i comment out the private feed out in then nuget.config, then the tool get's installed.

nuget restore does not have a problem with the nuget feed. dotnet restore (which should not be used with VSTS because you have to store a Cleartext PAT in the nuget.config) clearly has the same problem like dotnet tool

### Exceptions (if any)
C:\Program Files\dotnet\sdk\2.1.301\NuGet.targets(114,5): error : Fehler beim Abrufen von Informationen zu "sourcelink" aus der Remotequelle "https://XYZ.pkgs.visualstudio.com/_packaging/172bc92f-50b3-48bc-b4cf-9555b7f0fd10/nuget/v3/flat2/fo/index.json". [C:\Users\DerAl\AppData\Local\Temp\ctdjxp0q.bbs\restore.csproj]
C:\Program Files\dotnet\sdk\2.1.301\NuGet.targets(114,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Users\DerAl\AppData\Local\Temp\ctdjxp0q.bbs\restore.csproj]

**Comment by andrerav** [comment]
Just want to voice my support and express my hope that this will get fixed sometime :)

**Comment by rvdginste** [comment]
I bumped into the same issue and already wasted quite some time on it. In the end, I found #9555 which was closed in 2018, but was never really fixed.

I use a private NuGet feed on Azure Artifacts for my project. This feed is configured to also fetch packages from nuget.org, so only one NuGet feed is needed. A NuGet.Config is provided in the root of the project to configure the feed.

This is used in a build pipeline, and I used the following nuget.config to pass credentials through environment variables.
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="private-nuget" value="https://pkgs.dev.azure.com/private/aaa-aaa-aaa-aaa-aaa/_packaging/private-nuget/nuget/v3/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <private-nuget>
      <add key="Username" value="%AzureDevopsUser%" />
      <add key="ClearTextPassword" value="%AzureDevopsPersonalAccessToken%" />
    </private-nuget>
  </packageSourceCredentials>
</configuration>
```

This works fine with a `dotnet restore`, but it fails when using it to install dotnet tools. I get an Unauthorized error. Is it not possible for dotnet tools to use the stanard authentication mechanisms available in NuGet?

The workaround suggested in 2018 comes down to basically not using authenticated feeds for the dotnet tools....

**Comment by dsplaisted** [comment]
This may be related to #24220

**Comment by DanielTheCoder** [comment]
Workaround posted here https://github.com/dotnet/sdk/issues/22987

**Comment by deloorc** [comment]
I stumbled upon this issue while facing a similar problem in my own CI setup with Azure Artifacts, and I thought I'd share how I managed to resolve it in case it helps.

Reflecting on the error logs I had, which were nearly identical to the ones you've provided:

- `warning NU1801: Failed to retrieve information about '<my dotnet tool name>' from remote source...`
- `error NU1101: Unable to find package <my dotnet tool name>..`

Reading the detailed logs I also saw I was receiving `error : Response status code does not indicate success: 401 (Unauthorized).`

In my case it appeared to be an authentication issue with the Azure Artifacts feed, a situation not uncommon when dealing with private NuGet feeds.

In my case, what worked was adding the `NuGetAuthenticate` task to my pipeline configuration. This task ensures that the required credentials are properly set, allowing the .NET CLI to authenticate and access the private feed. Here’s how I did it:

```yaml
- task: NuGetAuthenticate@1
  inputs:
    forceReinstallCredentialProvider: true

- task: DotNetCoreCLI@2
  displayName: "Restore dotnet tools"
  inputs:
    command: "custom"
    custom: "tool"
    arguments: "restore --ignore-failed-sources --disable-parallel"
    workingDirectory: $(basePath)
    nugetConfigPath: "$(basePath)/NuGet.Config"
    feedsToUse: config
```
Notice that I've placed the `NuGetAuthenticate` task right before the `DotNetCoreCLI` task. This ensures that the credentials are available when attempting to restore the .NET tool.

Below my NuGet.config:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="<feedName>" value="https://pkgs.dev.azure.com/<organization>/<project>/_packaging/<feed>/nuget/v3/index.json" />
  </packageSources>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
</configuration>
```
NOTE: I've replaced the organization, project, and feed names with placeholders.

Lastly, for local development, ensure that you've authenticated with Azure Artifacts using the credentials provider. You can find a guide on how to do this [https://github.com/microsoft/artifacts-credprovider](https://github.com/microsoft/artifacts-credprovider).

Hope this helps!

**Comment by SpaceOgre** [comment]
I'm having problems with this as well.
I followed the recommendation from Microsoft to not have multiple sources in my Nuget.config file and only added the private one that have the official Nuget as upstream.

To bypass the 401 error I'm using this before:
```yml
  - task: NuGetAuthenticate@1
 ```
But now the task that tries to install is telling me that the tool does not exist in my private feed.
```
dotnet-coverage is not found in NuGet feeds https://[orgname].pkgs.visualstudio.com/_packaging/[feedname]/nuget/v3/index.json.
```

The task looks like this:
```yml
  - task: DotNetCoreCLI@2
    displayName: "Install dotnet-coverage"
    inputs:
      command: custom
      custom: tool
      arguments: "install --global dotnet-coverage"
```

Since it exist in the upstream source of nuget I expect it to find it and install it through that.

**Comment by hayer** [comment]
This is still not fixed. `--ignore-failed-sources` does not seem to work, neither does `--interactive`.

**Comment by henrikweimenhog** [comment]
Same problem here. Trying to install Swagger. Works fine with dotnet7 but fails with dotnet8.
This is what I am doing:

    - task: UseDotNet@2
      displayName: 'Use dotnet sdk'
      inputs:
        packageType: sdk
        version: 7.x # setting this to 8.x will produce a 401 error when running the install swashbuckle task
           
    - task: NuGetToolInstaller@0
      displayName: 'Use NuGet 6.10.0'
      inputs:
        versionSpec: 6.10.0
        checkLatest: true

    - task: DotNetCoreCLI@2
      displayName: 'Create a manifest file'
      inputs:
        command: 'custom'
        custom: 'new'
        arguments: 'tool-manifest'

    # this is where it blows up when using dotnet8
    - task: DotNetCoreCLI@2
      displayName: 'Install Swashbuckle'
      inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install --version 6.6.2 Swashbuckle.AspNetCore.Cli

    - task: DotNetCoreCLI@2
      displayName: 'Restore solution'
      inputs:
        command: 'restore'
        projects: '${{ variables.solutionName }}'
        feedsToUse: 'config'
        nugetConfigPath: '${{ variables.nugetConfig }}'
        verbosityRestore: Normal   
        
    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: 'build'
        projects: '${{ variables.solutionName }}'

    ## Build the swagger file
    - task: DotNetCoreCLI@2
      displayName: 'Build swagger.json'
      inputs:
        command: custom
        custom: swagger
        arguments:  tofile --output swagger.json $(System.DefaultWorkingDirectory)\${{ variables.projectFolderName }}\bin\Debug\net8.0\${{ variables.projectName }}.dll ${{ variables.swaggerVersion }}


And I tried keeping the dotnet7 and then inject a "use dotnet8" after the swagger had been installed but before I build my solution, but that blew up the "build swagger file" step.

**Comment by henrikweimenhog** [comment]
I have the same problem but worked around it in a stupid but functioning way.

My pipeline was basically:
1. Checkout
2. Use dotnet 8 (everything worked until this changed from 7)
3. Use nuget
4. Restore solution
5. Build solution
6. Create manifest file
7. Install swashbuckle (this is where dotnet 8 gave me 401)
8. Build Swagger.json
9. Do some other irrelevant stuff

What I had to do to make it work was:
1. Checkout
2. Use nuget
3. Use dotnet 7 <-- start with 7
4. Create manifest file
5. Install Swashbuckle (now it works)
6. Use dotnet 8 <-- now we can do this
5. Restore solution
6. Build solution
7. dotnet tool restore
9. Build Swagger.json
10. Do some other irrelevant stuff

I hope this gets you guys going for now.

**Comment by srikcgaa2** [comment]
I had one more observation which I am unable to understand as well.  If I use "dotnet restore <solution name> --interactive", I am able to get the prompt to login to https://microsoft.com/devicelogin along with code to authenticate.  Using that code, I am able to successfully restore the NuGet packages from my private feed.  After doing this, on the same folder, I am running the command "dotnet tool restore --configfile NuGet.config --interactive" and this time, I get an error that the "Response status code does not indicate success: 401" error.  In both the cases, it uses the exact same private feed and on the exact same folder/repository workspace.  How does the command NuGet restore work fine while the tool restore fails to authenticate for the same private feed?

**Comment by Forgind** [comment]
Can someone check to see whether https://github.com/dotnet/sdk/pull/44309 resolved this issue as well? On a hunch, I suspect --ignore-failed-sources and this _may_ have been failing for the same reason: that we were making a new NuGetPackageDownloader in the ToolCommand for installation and not giving it the relevant information. Just want to see if that's the case before looking further 🙂

**Comment by marcpopMSFT** [comment]
Old issue triage: per forgind, we rewrote both the tool logic and improved the apis so looking for someone to report that this is still broken.

**Comment by sliekens** [comment]
@marcpopMSFT  Maybe I am holding it wrong, but I can't figure out how to bypass my internal feed and provide the public feed  to `dotnet tool install` with command line args.

Use case: bootstrap Azure Artifacts credential provider at the workspace/repository level instead of machine-wide.

``` pwsh
> dotnet tool install Microsoft.Artifacts.CredentialProvider.NuGet.Tool --source https://api.nuget.org/v3/index.json --ignore-failed-sources --create-manifest-if-needed -v diag

[NuGet Manager] [Warning] NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://pkgs.dev.azure.com/redacted-org/IT/_packaging/redacted-feed/nuget/v3/index.json.
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
   at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
   at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetPackageMetadataAsync(PackageSource source, String packageIdentifier, Boolean includePrerelease, Boolean includeUnlisted, CancellationToken cancellationToken)
microsoft.artifacts.credentialprovider.nuget.tool is not found in NuGet feeds https://pkgs.dev.azure.com/redacted-org/IT/_packaging/redacted-feed/nuget/v3/index.json.
```

nuget.config

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="redacted-feed" value="https://pkgs.dev.azure.com/redacted-org/IT/_packaging/redacted-feed/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

dotnet info

``` text
.NET SDK:
 Version:           10.0.101
 Commit:            fad253f51b
 Workload version:  10.0.100-manifests.9f71effe
 MSBuild version:   18.0.6+fad253f51

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.26200
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\10.0.101\

.NET workloads installed:
There are no installed workloads to display.
Configured to use workload sets when installing new manifests.
No workload sets are installed. Run "dotnet workload restore" to install a workload set.

Host:
  Version:      10.0.1
  Architecture: x64
  Commit:       fad253f51b

.NET SDKs installed:
  9.0.308 [C:\Program Files\dotnet\sdk]
  10.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 10.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 10.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 10.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  DOTNET_BUNDLE_EXTRACT_BASE_DIR           [C:\development\dotnet-bundle-extract]
  DOTNET_CLI_TELEMETRY_OPTOUT              [true]

global.json file:
  C:\redacted\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

````

**Comment by Forgind** [comment]
Does the nuget.config need to have the `<clear />` part? I'm wondering if that's clearing the source you added on the command line. (That part is just a guess.) Alternatively, perhaps you could add the source to the nuget.config rather than having it separate?

Counterintuitively, --ignore-failed-soures doesn't actually _ignore_ sources despite the name; it just converts errors into warnings, and from your output, it looks like it did that.

**Comment by sliekens** [comment]
@Forgind for actual package restores, `<clear />` is an absolute must for my organization, all packages must be restored from our internal mirror. The problem however is that the mirror requires authorization. I'm trying to see if I can bootstrap the [credential provider](https://www.nuget.org/packages/Microsoft.Artifacts.CredentialProvider.NuGet.Tool) with a `dotnet tool install` command.

If sources from `nuget.config` (including `<clear />`) are handled last, that sounds like a bug to me. I would expect command line args to be handled last and override file configs.

**Comment by marcpopMSFT** [comment]
The original issue was slightly different than what sliekens is reporting. I can confirm that --source doesn't replace the existing sources from a nuget.config (with a quick test repro) which is the primary complaint from sliekens. Asked copilot to take a crack at that behavior to see if it can quickly track down why --source doesn't replace existing sources. https://github.com/dotnet/sdk/pull/52787
