### ISSUE TITLE
dotnet run --property:Configuration=Release creates release binaries on linux, but tries to execute debug version which is not there

### ISSUE THREAD

**Issue by pepe78** [dotnet/sdk#24277]
Command:

    dotnet run --property:Configuration=Release

Creates ./bin/Release/ ...

But then tries to execute debug version "bin/Debug/net6.0/main":

System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/home/pepe/code/pepe78/python-performance/bin/Debug/net6.0/main' with working directory '/home/pepe/code/pepe78/python-performance'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

Steps to repro:
1. git clone https://github.com/pepe78/python-performance
2. cd python-performance
3. wget https://download.visualstudio.microsoft.com/download/pr/807f9d72-4940-4b1a-aa4a-8dbb0f73f5d7/cb666c22a87bf9413f29615e0ba94500/dotnet-sdk-6.0.200-linux-x64.tar.gz
4. mkdir -p $HOME/dotnet
5. tar zxf dotnet-sdk-6.0.200-linux-x64.tar.gz -C $HOME/dotnet
6. export DOTNET_ROOT=$HOME/dotnet
7. export PATH=$PATH:$HOME/dotnet
8. dotnet run --property:Configuration=Release

On Linux Ubuntu 20 & 22 with SDK 6.0.

**Comment by wyp84** [comment]
Any news on this, we've the same issue here.

**Comment by CrazyB0y** [comment]
Using ``--configuration Release``
instead of ``--property:Configuration=Release``
does not cause the problem

**Comment by marcpopMSFT** [comment]
Old issue triage: This should be fixed as previously the .NET CLI was not correctly handling the property flag for run. Should be fixed in 9.0.1xx for sure and we think 8.0.1xx.
