### ISSUE TITLE
Entity framework produces libSystem.native error

### ISSUE THREAD

**Issue by anthonystanton** [dotnet/sdk#24697]

**Comment by mdashiqu** [comment]
my mac version is 10.13.6 and i am getting this error 

Unhandled exception. System.DllNotFoundException: Unable to load shared library 'System.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libSystem.Native, 1): image not found
   at Interop.Sys.Stat(String path, FileStatus& output)
   at Internal.IO.File.InternalExists(String fullPath)
   at Internal.IO.File.Exists(String path)
   at System.TimeZoneInfo.TryLoadTzFile(String tzFilePath, Byte[]& rawData, String& id)
   at System.TimeZoneInfo.TryGetLocalTzFile(Byte[]& rawData, String& id)
   at System.TimeZoneInfo.GetLocalTimeZoneFromTzFile()
   at System.TimeZoneInfo.CachedData.CreateLocal()
   at System.DateTime.get_Now()
   at Crawler_WinApp.Program.Exceptionlog(Exception ex)
   at Crawler_WinApp.Program.Main()
Abort trap: 6
 
can anyone help what is the actual problem and i run dotnet 3.1,5.1,6.1 but still same issue
