### ISSUE TITLE
ThrowExceptionForHR from an SDK task fails due to missing resource

### ISSUE THREAD

**Issue by sbomer** [dotnet/sdk#2552]
An MSBuild task in this repo that calls Marshal.ThrowExceptionForHR fails due to a missing resource assembly:

```
d:\sdk\artifacts\Debug\bin\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(308,5): error MSB4018: System.IO.FileNotFoundException: Could not load the specified file. [d:\sdk\artifacts\Debug\tmp\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
d:\sdk\artifacts\Debug\bin\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(308,5): error MSB4018: File name: 'Microsoft.Build.Tasks.CodeAnalysis.resources' [d:\sdk\artifacts\Debug\tmp\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
d:\sdk\artifacts\Debug\bin\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(308,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName) [d:\sdk\artifacts\Debug\tmp\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
d:\sdk\artifacts\Debug\bin\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(308,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName) [d:\sdk\artifacts\Debug\tmp\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
d:\sdk\artifacts\Debug\bin\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(308,5): error MSB4018:    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo) [d:\sdk\artifacts\Debug\tmp\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
```

I'm not sure why this specific resource is needed by ThrowExceptionForHR. It looks like it may be caused by https://github.com/dotnet/roslyn/issues/26777.

**Comment by livarcocc** [comment]
@sbomer can you provide us a repro for this? Also, in which version of the SDK did you hit this?

**Comment by sbomer** [comment]
@livarcocc, here you go
- clone https://github.com/sbomer/sdk/tree/throwExceptionForHRRepro
- build.cmd
- .dotnet\dotnet.exe test src\tests\Microsoft.NET.Build.Tests\Microsoft.NET.Build.Tests.csproj --filter "FullyQualifiedName=Microsoft.NET.Build.Tests.GivenThatWeWantToCustomizeTheApphost.It_contains_resources_from_the_managed_dll"

The output is:
```
D:\sdk>.dotnet\dotnet.exe test src\tests\Microsoft.NET.Build.Tests\Microsoft.NET.Build.Tests.csproj --filter "FullyQualifiedName=Microsoft.NET.Build.Tests.GivenThatWeWantToCustomizeTheApphost.It_contains_resources_from_the_managed_dll"
Build started, please wait...
Build completed.

Test run for D:\sdk\artifacts\bin\Tests\Microsoft.NET.Build.Tests\Debug\Microsoft.NET.Build.Tests.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0-preview-20180807-05
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:03.12]     Microsoft.NET.Build.Tests.GivenThatWeWantToCustomizeTheApphost.It_contains_resources_from_the_managed_dll [FAIL]
Failed   Microsoft.NET.Build.Tests.GivenThatWeWantToCustomizeTheApphost.It_contains_resources_from_the_managed_dll
Error Message:
 Expected command to pass but it did not.
File Name: D:\sdk\.dotnet\dotnet.exe
Arguments: msbuild /t:Build D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj
Exit Code: 1
StdOut:
Microsoft (R) Build Engine version 15.9.8-preview+g0a5001fc4d for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(142,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018: System.IO.FileNotFoundException: Could not load the specified file. [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018: File name: 'Microsoft.Build.Tasks.CodeAnalysis.resources' [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName) [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName) [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo) [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResourceUpdater.ThrowExceptionForLastWin32Error() in D:\sdk\src\Tasks\Microsoft.NET.Build.Tasks\ResourceUpdater.cs:line 404 [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResourceUpdater..ctor(String peFile) in D:\sdk\src\Tasks\Microsoft.NET.Build.Tasks\ResourceUpdater.cs:line 186 [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at Microsoft.NET.Build.Tasks.AppHost.Create(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String intermediateAssembly, Logger log) in D:\sdk\src\Tasks\Microsoft.NET.Build.Tasks\AppHost.cs:line 82 [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() in D:\sdk\src\Tasks\Microsoft.NET.Build.Tasks\CreateAppHost.cs:line 31 [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() in D:\sdk\src\Tasks\Common\TaskBase.cs:line 35 [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]

StdErr:


Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at Microsoft.NET.TestFramework.Assertions.CommandResultAssertions.Pass() in D:\sdk\src\tests\Microsoft.NET.TestFramework\Assertions\CommandResultAssertions.cs:line 30
   at Microsoft.NET.Build.Tests.GivenThatWeWantToCustomizeTheApphost.It_contains_resources_from_the_managed_dll() in D:\sdk\src\tests\Microsoft.NET.Build.Tests\GivenThatWeWantToCustomizeTheApphost.cs:line 44
Standard Output Messages:
 > D:\sdk\.dotnet\dotnet.exe msbuild /t:restore D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj
 Microsoft (R) Build Engine version 15.9.8-preview+g0a5001fc4d for .NET Core
 Copyright (C) Microsoft Corporation. All rights reserved.
   Restoring packages for D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj...
   Generating MSBuild file D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\obj\ResourceTest.csproj.nuget.g.props.
   Generating MSBuild file D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\obj\ResourceTest.csproj.nuget.g.targets.
   Restore completed in 122.93 ms for D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj.

 > D:\sdk\.dotnet\dotnet.exe msbuild /t:Build D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj
 Microsoft (R) Build Engine version 15.9.8-preview+g0a5001fc4d for .NET Core
 Copyright (C) Microsoft Corporation. All rights reserved.
 D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(142,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
 D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
 D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018: System.IO.FileNotFoundException: Could not load the specified file. [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
 D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018: File name: 'Microsoft.Build.Tasks.CodeAnalysis.resources' [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
 D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName) [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
 D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName) [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
 D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo) [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
 D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResourceUpdater.ThrowExceptionForLastWin32Error() in D:\sdk\src\Tasks\Microsoft.NET.Build.Tasks\ResourceUpdater.cs:line 404 [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
 D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResourceUpdater..ctor(String peFile) in D:\sdk\src\Tasks\Microsoft.NET.Build.Tasks\ResourceUpdater.cs:line 186 [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
 D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at Microsoft.NET.Build.Tasks.AppHost.Create(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String intermediateAssembly, Logger log) in D:\sdk\src\Tasks\Microsoft.NET.Build.Tasks\AppHost.cs:line 82 [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
 D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() in D:\sdk\src\Tasks\Microsoft.NET.Build.Tasks\CreateAppHost.cs:line 31 [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
 D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() in D:\sdk\src\Tasks\Common\TaskBase.cs:line 35 [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
 D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
 D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]

 Exit Code: 1



Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 3.8594 Seconds

D:\sdk>
```

Note the missing resource dll:
```
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018: System.IO.FileNotFoundException: Could not load the specified file. [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
D:\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(293,5): error MSB4018: File name: 'Microsoft.Build.Tasks.CodeAnalysis.resources' [D:\sdk\artifacts\tmp\Debug\It_contains_r---AB2009D8\ResourceTest\ResourceTest.csproj]
```

**Comment by peterhuene** [comment]
I'll take a look.  I haven't seen something like this yet.

**Comment by livarcocc** [comment]
@nguerrera can you take a quick look? @tmat said this is blocking roslyn for moving to the 3.0 SDK. Is this something that should really be fixed in Roslyn or something that we are doing wrong on our side?

**Comment by nguerrera** [comment]
That stack trace is very odd.

It is possible that latest Roslyn will fix this as the build task no longer does assembly resolve shenanigans. It might also change the symptom to something more decipherable. I will focus on that and then look at this.

**Comment by nguerrera** [comment]
This is fixed. 

After merging master and accounting for test rename in command shown below, the appropriate exception is raised:
```
.dotnet\dotnet.exe test src\tests\Microsoft.NET.Build.Tests\Microsoft.NET.Build.Tests.csproj --filter "FullyQualifiedName=Microsoft.NET.Build.Tests.AppHostTests.AppHost_contains_resources_from_the_managed_dll"
```

```
D:\Src\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(328,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. [D:\Src\sdk\artifacts\tmp\Debug\AppHost_conta---13435BED\ResourceTest\ResourceTest.csproj]
 D:\Src\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(328,5): error MSB4018: System.IO.DirectoryNotFoundException: The system cannot find the path specified. (0x80070003) [D:\Src\sdk\artifacts\tmp\Debug\AppHost_conta---13435BED\ResourceTest\ResourceTest.csproj]
 D:\Src\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(328,5): error MSB4018:    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode) [D:\Src\sdk\artifacts\tmp\Debug\AppHost_conta---13435BED\ResourceTest\ResourceTest.csproj]
 D:\Src\sdk\artifacts\bin\Debug\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(328,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResourceUpdater.ThrowExceptionForLastWin32Error() in D:\Src\sdk\src\Tasks\Microsoft.NET.Build.Tasks\ResourceUpdater.cs:line 43
```
