### ISSUE TITLE
SDK did not generate a binding redirection for System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/sdk#25974]
### Describe the bug

.NET SDK did not generate a binding redirection for System.Runtime.CompilerServices.Unsafe, in a project that targets .NET Framework 4.7.2 and references Microsoft.Extensions.Primitives 2.1.6.

### To Reproduce

Unify.csproj:

```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="2.1.6" />
  </ItemGroup>

</Project>
```

Program.cs:

```C#
using System;

namespace Unify
{
    class Program
    {
        static void Main() {
            _ = "hello".AsSpan().Slice(2, 3);
        }
    }
}
```

### Exceptions (if any)

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.MemoryExtensions.AsSpan(String text)
   at Unify.Program.Main() in C:\Projects\Kalle\Unify\Program.cs:line 8
```

### Further technical details

Microsoft.Extensions.Primitives/2.1.6 is the latest version of this package in the 2.1.\* series, which is supported for [ASP.NET Core 2.1 on .NET Framework](https://dotnet.microsoft.com/en-us/platform/support/policy/aspnetcore-2.1).

In the `bin\Debug\net472` directory:

* Microsoft.Extensions.Primitives.dll is `Microsoft.Extensions.Primitives, Version=2.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60` from the "Microsoft.Extensions.Primitives/2.1.6" package. On net472, this package depends on System.Memory (>= 4.5.1) and System.Runtime.CompilerServices.Unsafe (>= 4.5.2). The assembly depends on netstandard 2.0.0.0, System.Memory 4.0.1.0, and System.Runtime.CompilerServices.Unsafe 4.0.4.1.
* System.Memory.dll is `System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51` from the "System.Memory/4.5.1" package. On net472, this package depends on System.Buffers (>= 4.4.0), System.Numerics.Vectors (>= 4.4.0), and System.Runtime.CompilerServices.Unsafe (>= 4.5.0). The assembly depends on netstandard 2.0.0.0, System.Numerics.Vectors 4.1.3.0, System.Runtime.CompilerServices.Unsafe 4.0.4.0 ⚠, and System.Buffers 4.0.2.0.
* System.Buffers.dll is `System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51` from the "System.Buffers/4.4.0" package. On net472, this package does not depend on any packages. The assembly depends on netstandard 2.0.0.0.
* System.Numerics.Vectors.dll is `System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` from the "System.Numerics.Vectors/4.4.0" package.  On net472, this package does not depend on any packages. The assembly depends on mscorlib 4.0.0.0 and System.Numerics 4.0.0.0.
* System.Runtime.CompilerServices.Unsafe.dll is `System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` ⚠ from the "System.Runtime.CompilerServices.Unsafe/4.5.2" package. On net472, this package does not depend on any packages. The assembly depends on System.Runtime 4.0.0.0.

System.Memory.dll thus depends on System.Runtime.CompilerServices.Unsafe 4.0.4.0, but the directory contains System.Runtime.CompilerServices.Unsafe 4.0.4.1, which is a different version. .NET SDK should have generated a binding redirection for this, but it did not.

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  2.1.526 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

No IDE.

**Comment by KalleOlaviNiemitalo** [comment]
This is not a NuGet issue, because obj\project.assets.json correctly indicates the latest version:

```JSON
      "System.Runtime.CompilerServices.Unsafe/4.5.2": {
        "type": "package",
        "compile": {
          "ref/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll": {}
        },
        "runtime": {
          "lib/netstandard2.0/System.Runtime.CompilerServices.Unsafe.dll": {}
        }
```

Rather, the problem seems to be in the MSBuild task "ResolveAssemblyReference".

**Comment by KalleOlaviNiemitalo** [comment]
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET

[msbuild.log](https://github.com/dotnet/sdk/files/8884710/msbuild.log)

[msbuild.binlog.zip](https://github.com/dotnet/sdk/files/8884712/msbuild.binlog.zip) (GitHub does not accept `msbuild.binlog` as is.)

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps this should be moved to the MSBuild repo.
