### ISSUE TITLE
Unable to build project with 6.0.400-preview.22301.10 and /nowarn: set

### ISSUE THREAD

**Issue by domagojmedo** [dotnet/sdk#26120]
### Describe the bug
I'm using cake to build my project but it fails if I try to set any /nowarn:.
It seems that it's tied to dotnet version that's used to build. If I put 6.0.300 in global.json or if I remove /nowarn: then the build passes 

### To Reproduce

```
Process = "C:\Program Files\dotnet\dotnet.exe"
       MSBuild executable path = "C:\Program Files\dotnet\sdk\6.0.400-preview.22301.10\MSBuild.dll"
       Command line arguments = "C:\Program Files\dotnet\sdk\6.0.400-preview.22301.10\MSBuild.dll -maxcpucount -verbosi
       ty:m -restore -target:Publish -property:PublishDir=C:\Users\DomagojMedo\source\repos\project\.build\project -property:SelfContained=True -property:_CommandLineDefinedSelfContained=true -property:RuntimeIden
       tifier=win-x64 -property:_CommandLineDefinedRuntimeIdentifier=true -property:Configuration=Release -verbosity:de
       tailed C:/Users/DomagojMedo/source/repos/project/project/project.csproj /nowarn:CS15
       91,CS0612,CS0618,CS0168,CS0108,CS1702,CS8618,AD0001,CA1416,CA1416,CA1416,CS0162,CS0168,CS0169,CS0414,CS1570,CS15
       72,CS1573,CS1998,CS4014,CS8600,CS8601,CS8602,CS8603,CS8604,CS8618,CS8619,CS8620,CS8622,CS8625,CS8629,CS8714,CS87
       65,CS8767,IDE0052,IDE1006,NU1608,NU1803,SA0001,SA1002,SA1005,SA1025,SA1027,SA1028,SA1106,SA1107,SA1108,SA1110,SA
       1111,SA1116,SA1117,SA1118,SA1119,SA1120,SA1121,SA1122,SA1123,SA1125,SA1127,SA1129,SA1131,SA1132,SA1133,SA1134,SA
       1137,SA1203,SA1204,SA1206,SA1208,SA1214,SA1300,SA1303,SA1306,SA1310,SA1312,SA1313,SA1314,SA1400,SA1401,SA1405,SA
       1407,SA1408,SA1500,SA1502,SA1503,SA1506,SA1507,SA1509,SA1512,SA1513,SA1514,SA1515,SA1517,SA1518,SA1520,SA1601,SA
       1604,SA1612,SA1614,SA1616,SA1617,SA1618,SA1622,SA1626,SA1627,SA1642,SA1202,SA1508,SA1201,SA1505,SA1510,CS0114,CS
       8605"
```
### Exceptions (if any)
```
C:\Program Files\dotnet\sdk\6.0.400-preview.22301.10\NuGet.targets(132,5): error : Operations that change non-co
       ncurrent collections must have exclusive access. A concurrent update was performed on this collection and corrup
       ted its state. The collection's state is no longer correct. [C:\Users\DomagojMedo\source\repos\project\project\project\project.csproj]
         Restoring packages for .NETCoreApp,Version=v6.0...
         Restoring packages for .NETCoreApp,Version=v6.0...
         Restoring packages for .NETCoreApp,Version=v6.0...
         Restoring packages for .NETCoreApp,Version=v6.0...
         System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access
         . A concurrent update was performed on this collection and corrupted its state. The collection's state is no l
         onger correct.
            at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
            at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
            at Microsoft.Build.BackEnd.Logging.LoggingService.GetWarningsForProject(BuildEventContext context, IDiction
         ary`2 warningsByProject, ISet`1 warnings)
            at Microsoft.Build.BackEnd.Logging.LoggingService.GetWarningsAsMessages(BuildEventContext context)
            at Microsoft.Build.BackEnd.Logging.TaskLoggingContext.GetWarningsAsMessages()
            at Microsoft.Build.BackEnd.TaskHost.get_WarningsAsMessages()
            at Microsoft.Build.BackEnd.TaskHost.ShouldTreatWarningAsError(String warningCode)
            at Microsoft.Build.Utilities.TaskLoggingHelper.LogWarning(String subcategory, String warningCode, String he
         lpKeyword, String helpLink, String file, Int32 lineNumber, Int32 columnNumber, Int32 endLineNumber, Int32 endC
         olumnNumber, String message, Object[] messageArgs)
            at Microsoft.Build.Utilities.TaskLoggingHelper.LogWarning(String subcategory, String warningCode, String he
         lpKeyword, String file, Int32 lineNumber, Int32 columnNumber, Int32 endLineNumber, Int32 endColumnNumber, Stri
         ng message, Object[] messageArgs)
            at NuGet.Build.MSBuildLogger.LogError(INuGetLogMessage logMessage, LogErrorWithDetails logWithDetails, LogE
         rrorAsString logAsString)
            at NuGet.Build.MSBuildLogger.LogForNonMono(INuGetLogMessage message)
            at NuGet.Build.MSBuildLogger.Log(ILogMessage message)
            at NuGet.Build.MSBuildLogger.LogAsync(ILogMessage message)
            at NuGet.Commands.RestoreCollectorLogger.LogAsync(IRestoreLogMessage message)
            at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
            at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
            at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, IRestoreProgres
         sReporter progressReporter, CancellationToken token)
            at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
            at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreArgs, Cancellati
         onToken token)
            at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token)
            at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean intera
         ctive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force
         , Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupported
         Projects, ILogger log, CancellationToken cancellationToken)
            at NuGet.Build.Tasks.RestoreTask.ExecuteAsync(ILogger log)
       Done executing task "RestoreTask" -- FAILED.
```

### Further technical details

```
.NET SDK (reflecting any global.json):
 Version:   6.0.400-preview.22301.10
 Commit:    25580ffe7a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400-preview.22301.10\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  5.0.407 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  6.0.400-preview.22301.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Running through cake script with DotNetPublish method.

**Comment by marcpopMSFT** [comment]
@domagojmedo does this repro in a very simple project that you can share with us?

**Comment by domagojmedo** [comment]
If I try it in a new project then it works. Not sure how to create a repro other than with the big project I have issue in.
