### ISSUE TITLE
.NET 6.0.6: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 doesn't work any more

### ISSUE THREAD

**Issue by ww898** [dotnet/sdk#26277]
Windows x64 .NET SDK 6.0.301. Languages: en-us, de-de, ru-ru. `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1` doesn't work any more.

`sample.cmd`:
```
set DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
dotnet new console
```

Console output:
```
dotnet new console
The template "Console App" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Work\__\__.csproj...
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at System.Globalization.CultureInfo..ctor(String name)
   at Microsoft.Build.CommandLine.MSBuildApp.SetConsoleUI()
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
Unhandled exception: System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at System.Globalization.CultureInfo..ctor(String name)
   at Microsoft.Build.CommandLine.MSBuildApp.SetConsoleUI()
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
   at Microsoft.DotNet.Cli.Utils.MSBuildForwardingAppWithoutLogging.ExecuteInProc(String[] arguments)
Restore failed.
Post action failed.
```

**Comment by ww898** [comment]
Move to MsBuild https://github.com/dotnet/msbuild/issues/7747
