### ISSUE TITLE
Just installed the 2.2 preview 3 sdk - fails with MSB4018

### ISSUE THREAD

**Issue by Allann** [dotnet/sdk#2635]
Just installed latest SDK preview (first time using 2.2), and when I try to build my solution it fails inside Visual Studio, but not Visual Studio Code.

```
Error	MSB4018	The "GenerateDepsFile" task failed unexpectedly.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.NET.Build.Tasks.LockFileExtensions.CollectDependencies(IDictionary`2 libraryLookup, IEnumerable`1 dependencies, HashSet`1 exclusionList)
   at Microsoft.NET.Build.Tasks.LockFileExtensions.CollectDependencies(IDictionary`2 libraryLookup, IEnumerable`1 dependencies, HashSet`1 exclusionList)
   at Microsoft.NET.Build.Tasks.LockFileExtensions.CollectDependencies(IDictionary`2 libraryLookup, IEnumerable`1 dependencies, HashSet`1 exclusionList)
   at Microsoft.NET.Build.Tasks.LockFileExtensions.CollectDependencies(IDictionary`2 libraryLookup, IEnumerable`1 dependencies, HashSet`1 exclusionList)
   at Microsoft.NET.Build.Tasks.LockFileExtensions.GetPlatformExclusionList(LockFileTarget lockFileTarget, LockFileTargetLibrary platformLibrary, IDictionary`2 libraryLookup)
   at Microsoft.NET.Build.Tasks.ProjectContext.GetRuntimeLibraries(IEnumerable`1 excludeFromPublishPackageIds)
   at Microsoft.NET.Build.Tasks.DependencyContextBuilder.Build()
   at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Core.Messaging.Tests	C:\Program Files\dotnet\sdk\2.2.100-preview3-009430\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	129	

```
Visual Studio 2017: 15.9.0 Preview 4 (also fails in 15.8.8)
Microsoft .NET Core SDK 2.2.100 0 Preview3 (x64)
OS: Windows 10 Enterprise 1803 (17134.345)

Solution build log attached
[bugrepo.zip](https://github.com/dotnet/sdk/files/2532330/bugrepo.zip)

**Comment by livarcocc** [comment]
@dsplaisted can you take a look?

**Comment by Allann** [comment]
Once SDK (2.1.403) was installed and the path added back in and changing no code in the solution, it now builds again fine.

**Comment by Allann** [comment]
Thanks, will re-install 2.2.1, but by adding app, wouldn't I need to change the project to sdk.web too?
