### ISSUE TITLE
dotnet sdk check throws exception when trying to print installed runtimes.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/sdk#26509]
### Describe the bug
When I got to try to run ``dotnet sdk check`` to ensure my SDK is up to date I instead get InvalidOperationException right after it prints ".NET Runtimes:".

### To Reproduce

1. Install the .NET 6.0.400-preview.22301.10 SDK and run ``dotnet sdk check`` in a simple project folder (with a solution file).
2. Install https://github.com/Elskom/EFCore-Installer/releases/tag/6.0.6 and add it's SDK (in github packages) to the project (``<Sdk Name="[package name]" Version="6.0.6" />``).
3. Install https://github.com/Elskom/Serilog-Installer/releases/tag/6.0.6 and add it's SDK (in github packages) to the project (``<Sdk Name="[package name]" Version="6.0.6" />``).
4. Install https://github.com/Elskom/Remora.Discord-Installer/releases/tag/2022.43.0 and add it's SDK (in github packages) to the project (``<Sdk Name="[package name]" Version="2022.43.0" />``).

``dotnet --list-runtimes`` works however.

### Exceptions (if any)

```
.NET SDKs:
Version                       Status
-----------------------------------------
6.0.106                       Up to date.
6.0.203                       Up to date.
6.0.302                       Up to date.
6.0.400-preview.22301.10      Up to date.

Try out the newest .NET SDK features with .NET 7.0.100-preview.5.22307.18.

.NET Runtimes:
Unhandled exception: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.DotNet.Tools.Sdk.Check.BundleOutputWriter.BundleIsEndOfLife(INetBundleInfo bundle)
   at Microsoft.DotNet.Tools.Sdk.Check.RuntimeOutputWriter.GetRuntimeStatusMessage(NetRuntimeInfo runtime)
   at Microsoft.DotNet.Tools.Sdk.Check.RuntimeOutputWriter.<PrintRuntimeInfo>b__2_2(NetRuntimeInfo runtime)
   at Microsoft.DotNet.Cli.PrintableTable`1.<>c__DisplayClass9_0.<CalculateColumnWidths>b__0(Column c)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.Cli.PrintableTable`1.CalculateColumnWidths(IEnumerable`1 rows)
   at Microsoft.DotNet.Cli.PrintableTable`1.PrintRows(IEnumerable`1 rows, Action`1 writeLine)
   at Microsoft.DotNet.Tools.Sdk.Check.RuntimeOutputWriter.PrintRuntimeInfo()
   at Microsoft.DotNet.Tools.Sdk.Check.SdkCheckCommand.Execute()
   at Microsoft.DotNet.Tools.Sdk.Check.SdkCheckCommand.Run(ParseResult parseResult)
   at Microsoft.DotNet.Cli.ParseResultCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

```
.NET SDK (reflecting any global.json):
 Version:   6.0.400-preview.22301.10
 Commit:    25580ffe7a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400-preview.22301.10\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  6.0.106 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.400-preview.22301.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Elskom.Sdk.App 6.0.0-dev [C:\Program Files\dotnet\shared\Elskom.Sdk.App] (I made this)
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.EntityFrameworkCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.EntityFrameworkCore.App] (I made this)
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Remora.Discord.App 2022.43.0 [C:\Program Files\dotnet\shared\Remora.Discord.App] (I made this)
  Serilog.App 6.0.6 [C:\Program Files\dotnet\shared\Serilog.App] (I made this)

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

IDE: Visual Studio 2022 latest preview

**Comment by AraHaan** [comment]
I think the exception happens when it cant find the version of a specific runtime in the elements of versions given by the way it requests for all versions of the .NET Runtimes. I think a good patch to this is when this happens, have it say on that line "No version found to check if this is up to date."
