### ISSUE TITLE
dotnet watch does not work in eng\dogfood.cmd environment

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#26668]
Originally filed as https://github.com/dotnet/aspnetcore/issues/42509 but it seems that the issue is with versioning of dotnet/sdk dependencies in dogfood environment.

Using sdk\eng\dogfood.ps1:

```
PS D:\temp\BW> dotnet --version
7.0.100-dev
PS D:\temp\BW> dotnet nuget list source
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  3.  Package source 1 [Enabled]
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json
  4.  Package source 2 [Enabled]
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
  5.  Package source 3 [Enabled]
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json
PS D:\temp\BW> dotnet --info
.NET SDK:
 Version:   7.0.100-dev
 Commit:    0cd38c9a0a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\sdk\artifacts\bin\redist\Debug\dotnet\sdk\7.0.100-dev\

Host:
  Version:      7.0.0-preview.6.22325.3
  Architecture: x64
  Commit:       988f570dc4

.NET SDKs installed:
  7.0.100-dev [D:\sdk\artifacts\bin\redist\Debug\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.7.21355.4 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.3.22157.6 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21356.2 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21378.2 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.3.22151.6 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.6.22325.3 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21352.1 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.3.22157.2 [D:\sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  DOTNET_ROOT       [D:\sdk\artifacts\bin\redist\Debug\dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
PS D:\temp\BW> dotnet new blazorwasm
The template "Blazor WebAssembly App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/7.0-third-party-notices for details.

Processing post-creation actions...
Running 'dotnet restore' on D:\temp\BW\BW.csproj...
  Determining projects to restore...
  Restored D:\temp\BW\BW.csproj (in 392 ms).
Restore succeeded.


PS D:\temp\BW> dotnet watch
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
D:\sdk\artifacts\bin\redist\Debug\dotnet\sdk\7.0.100-dev\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057:
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [D:\temp\BW\BW.csproj]
  BW -> D:\temp\BW\bin\Debug\net7.0\BW.dll
  BW (Blazor output) -> D:\temp\BW\bin\Debug\net7.0\wwwroot
dotnet watch ❌ System.TypeLoadException: Could not load type 'System.Net.Quic.QuicImplementationProviders' from assembly 'System.Net.Quic, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.AspNetCore.Hosting.WebHostBuilderQuicExtensions.IsQuicSupported()
   at Microsoft.AspNetCore.Hosting.WebHostBuilderQuicExtensions.UseQuic(IWebHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderKestrelExtensions.UseKestrel(IWebHostBuilder hostBuilder)
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshServer.<>c__DisplayClass12_0.<StartAsync>b__0(IWebHostBuilder builder) in D:\sdk\src\BuiltInTools\dotnet-watch\Filters\BrowserRefreshServer.cs:line 59
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder builder, Action`1 configure, Action`1 configureWebHostBuilder)
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshServer.StartAsync(CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\Filters\BrowserRefreshServer.cs:line 56
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshFilter.ProcessAsync(DotNetWatchContext context, CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\Filters\BrowserRefreshFilter.cs:line 54
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(DotNetWatchContext context, CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\HotReloadDotNetWatcher.cs:line 88
   at Microsoft.DotNet.Watcher.Program.MainInternalAsync(CommandLineOptions options, CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\Program.cs:line 293
   at Microsoft.DotNet.Watcher.Program.MainInternalAsync(CommandLineOptions options, CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\Program.cs:line 293
   at Microsoft.DotNet.Watcher.Program.HandleWatch(CommandLineOptions options) in D:\sdk\src\BuiltInTools\dotnet-watch\Program.cs:line 191
dotnet watch ❌ An unexpected error occurred
```

**Comment by marcpopMSFT** [comment]
Do you have more to go on than "caused by the SDK somehow"? The dogfood script just sets a bunch of environment variables and it's not obvious how watch would be affected or how it worked before.

**Comment by tmat** [comment]
There is some versioning issue between the SDK and ASP.NET packages. It's not clear to me how this works. 

The dogfood script sets up environment with SDK `7.0.100-dev` (current dev build). 
The repo sets `tools.dotnet` in global.json to `7.0.100-preview.3.22158.2`. 
The project generated by `dotnet new blazorwasm` has package references to `7.0.0-preview.3.22157.6`

The ASP.NET SDK installed on the machine (in Program Files) is also `7.0.0-preview.3.22157.6` so the version is taken from there I guess.

```
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.0-preview.3.22157.6" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="7.0.0-preview.3.22157.6" PrivateAssets="all" />
```

These different versions are not compatible.

If I change the versions of the packages in the generated project to `7.0.100-preview.3.22158.2` to match the repo's version I get:

```
D:\temp\bw\BW.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.Components.WebAssembly with version (>
= 7.0.100-preview.3.22158.2)
```

Note that I have dotnet7 feed in nuget sources.

I have not found yet what version should I use to make it all work together.

**Comment by tmat** [comment]
@marcpopMSFT I am running from the app directory and can certainly add `global.json` to the app directory.

What's not clear to me is what versions of `Microsoft.AspNetCore.Components.WebAssembly.*` packages should the project reference and what version of dotnet should be in `global.json`. All combinations so are resulted in either "Unable to find package Microsoft.AspNetCore.Components.WebAssembly with version" nuget restore error or "System.TypeLoadException: Could not load type 'System.Net.Quic.QuicImplementationProviders'" exception.

**Comment by marcpopMSFT** [comment]
@tmat I'm really not sure as the sdk team doesn't do much with aspnet in the repo. The tests build aspnet apps but I don't believe we install an aspnet runtime during the dogfood build.  I thought maybe it was incoherency between runtime and aspnet but building and running dotnet watch in the preview 7 branch (and added the matching aspnet runtime to the global.json so it got installed) also had the Quic TypeLoad exception. I'm not sure how watch is trying to load that, what version it's trying to load, or what.

From procexp, I see it trying to load the file from here: sdk\artifacts\bin\redist\Debug\dotnet\shared\Microsoft.NETCore.App\7.0.0-preview.7.22369.4\System.Net.Quic.dll but not sure why it won't load or what dependency is missing.

**Comment by tmat** [comment]
@TanayParikh @javiercn @mkArtakMSFT

**Comment by tmat** [comment]
The script works now.

1) Build the repo
2) Start dogfood script
3) `dotnet nuget add source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json`
4) 
```
dotnet new blazorwasm
dotnet watch
```
