### ISSUE TITLE
Crash in `dotnet restore` for missing argument value

### ISSUE THREAD

**Issue by richlander** [dotnet/sdk#26809]
The CLI wants something like `-v detailed`. It shouldn't crash.

```bash
[root@f13a50a82b2b app]# dotnet restore -v
System.InvalidOperationException: Required argument missing for option: -v
   at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
   at System.CommandLine.Parsing.OptionResult.GetValueOrDefault[T]()
   at System.CommandLine.Parsing.SymbolResult.GetValueForOption[T](Option`1 option)
   at System.CommandLine.ParseResult.GetValueForOption[T](Option`1 option)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.LogVerbosityForAllTopLevelCommand(ICollection`1 result, ParseResult parseResult, String topLevelCommandName, Dictionary`2 measurements)
   at Microsoft.DotNet.Cli.Telemetry.TelemetryFilter.Filter(Object objectToFilter)
   at Microsoft.DotNet.Cli.Utils.TelemetryEventEntry.SendFiltered(Object o)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by baronfel** [comment]
This is something that I think would be caught if we used `UseParseErrorReporting` more universally. I think our current setup with the dotnet-tools integration is what blocks this. In the interim we should fix this - a fix that doesn't rely on the underlying parsing infrastructure would look at the `OptionResult` and see if there was an error. Sending PR shortly.
