### ISSUE TITLE
.NET Core WPF app doesn't correctly list NativeReference in manifest file

### ISSUE THREAD

**Issue by sicil1ano** [dotnet/sdk#27027]
### Describe the bug
Hi. 
Our .NET Core WPF App needs to interact with a 3rd-party API. These APIs are exposed via COM objects using a primary interop assembly, for development purposes, or via a NativeReference, by using their *.manifest file, for production-ready purposes. 
This manifest is needed to make sure all the API assemblies are sitting next to any application consuming them, avoiding the registration of COM objects in the registry, but registering them instead on runtime.

When I build the app with Visual Studio 2022 17.2.6, targeting .NET Core 6.0.302, the output directory looks okay, but the content of its manifest (auto-generated) is the following:

```
<?xml version="1.0" encoding="utf-8"?>
<assembly xsi:schemaLocation="urn:schemas-microsoft-com:asm.v1 assembly.adaptive.xsd" manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:asmv1="urn:schemas-microsoft-com:asm.v1" xmlns:asmv2="urn:schemas-microsoft-com:asm.v2" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3" xmlns:dsig="http://www.w3.org/2000/09/xmldsig#" xmlns:co.v1="urn:schemas-microsoft-com:clickonce.v1" xmlns:co.v2="urn:schemas-microsoft-com:clickonce.v2">
  <assemblyIdentity name="TestNativeReferenceNetCore.exe" version="1.0.0.0" type="win32" />
  <file name="MyComReference.manifest" size="3530" xmlns="urn:schemas-microsoft-com:asm.v2">
    <hash>
      <dsig:Transforms>
        <dsig:Transform Algorithm="urn:schemas-microsoft-com:HashTransforms.Identity" />
      </dsig:Transforms>
      <dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
      <dsig:DigestValue>pbYOjDIqVH6zsRyWLwxG7BfYooI=</dsig:DigestValue>
    </hash>
  </file>
</assembly>
```
The above app's manifest reports the NativeReference ("MyComReference.manifest") as an extra file, but not as a dependency.

If I build the same app targeting .NET Framework 4.8 instead, its manifest will look like this instead:

```
<?xml version="1.0" encoding="utf-8"?>
<assembly xsi:schemaLocation="urn:schemas-microsoft-com:asm.v1 assembly.adaptive.xsd" manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:asmv1="urn:schemas-microsoft-com:asm.v1" xmlns:asmv2="urn:schemas-microsoft-com:asm.v2" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3" xmlns:dsig="http://www.w3.org/2000/09/xmldsig#" xmlns:co.v1="urn:schemas-microsoft-com:clickonce.v1" xmlns:co.v2="urn:schemas-microsoft-com:clickonce.v2">
  <assemblyIdentity name="TestNativeReferenceNetFramework.exe" version="1.0.0.0" type="win32" />
  <dependency>
    <dependentAssembly asmv2:dependencyType="install" asmv2:codebase="MyComReference.manifest" asmv2:size="3528">
      <assemblyIdentity name="MyComReference" version="4.6.460.21" processorArchitecture="x86" type="win32" />
      <hash xmlns="urn:schemas-microsoft-com:asm.v2">
        <dsig:Transforms>
          <dsig:Transform Algorithm="urn:schemas-microsoft-com:HashTransforms.Identity" />
        </dsig:Transforms>
        <dsig:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
        <dsig:DigestValue>ExA6jtLLMAdytHAraysKsEVIgPo=</dsig:DigestValue>
      </hash>
    </dependentAssembly>
  </dependency>
</assembly>
```

As you can see, the "MyComReference.manifest" is instead correctly considered listed as a dependency.

In a few words, .NET Core lists a NativeReference in a WPF app like a file, but not as a dependency, like .NET Framework does.

### To Reproduce

1. Create a solution with a WPF app targeting .NET Core 6 and another WPF app targeting .NET Framework 4.8;
2. Add a NativeReference to both projects;
3. Build both projects;
4. Inspect both apps' manifest files;

**EXPECTED BEHAVIOUR:**
Both manifest files list the NativeReference using `<dependency>` and `<dependentAssembly>` nodes.

**CURRENT BEHAVIOUR:**
The .NET Core's manifest file lists the NativeReference as a file, instead of a dependentAssembly, like .NET Framework does.

### Exceptions (if any)

This issue causes our application not to correctly instantiate the COM objects, because of "Class not registered" error.
Without marking the NativeReference as a dependent assembly, the application doesn't load and register the COM objects.

```
Error: Unable to initialise TypeFromComReference.

System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {AAA44754-CC81-4692-91AF-7064E58EB22A} failed due to the following error: 80040154 Class not registered (0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.AllocateComObject(Void* pClassFactory)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
```

### Further technical details
- dotnet --info

.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.1.421 [C:\Program Files\dotnet\sdk]
  7.0.214 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  8.0.101 [C:\Program Files\dotnet\sdk]
  6.0.107 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

- Visual Studio 2022 17.2.6

**Comment by sicil1ano** [comment]
Any updates on this issue?

**Comment by sicil1ano** [comment]
Any updates?

**Comment by marcpopMSFT** [comment]
Old issue triage: @merriemcgaw do you know how that file gets generated for a WPF application?

**Comment by merriemcgaw** [comment]
No, this is not something I'm directly familiar with but a little digging helped me understand what's happening:

### The Root Cause: Lossy Translation in SDK Build Targets

The issue here stems from a fundamental difference in how the **Legacy Project System** (.NET Framework) and the **Modern .NET SDK** handle native dependencies during the manifest generation phase.

**1. Legacy Behavior (.NET Framework / `ResolveComReference`)**
In the legacy project system, Registration-Free COM was often handled implicitly. The build system (via `ResolveComReference` and the `mt.exe` tool chain) was tightly coupled with the Windows side-by-side (SxS) loader rules. When a COM reference with an isolated manifest was detected, the build targets automatically promoted it to a **`<dependency>`** / **`<dependentAssembly>`** entry in the final application manifest.

**2. Modern SDK Behavior (`<NativeReference>`)**
In the modern .NET SDK, we rely on the **`<NativeReference>`** ItemGroup to explicitly declare these dependencies.
* **The Expectation:** The `ResolveNativeReference` target should inspect the referenced manifest, extract the identity, and pass this metadata to the `GenerateApplicationManifest` task as an `IsolatedComReference`.
* **The Failure:** There is a logic gap in the SDK targets. While the native file is being detected, the build system is failing to carry over the specific metadata required to classify it as a **dependency**. Instead, it falls back to the default behavior for native assets, which is to simply list it as a **`<file>`**.

**Summary of the Bug**
The `GenerateApplicationManifest` task is receiving the `NativeReference` item, but without the specific "type" indicator or metadata that tells it to wrap the item in a `<dependentAssembly>` block. As a result, the generated manifest tells Windows, "Here is a loose file," rather than, "Here is a COM component you need to load into the context."

So, I think this is something that would need to be dealt with at this level and not specifically in the WindowsDesktop SDK, so I'm going to close the one in the desktop repo.

**Comment by marcpopMSFT** [comment]
Triage: @dsplaisted please assign to copilot to see if it can resolve this.

**Comment by dsplaisted** [comment]
Turns out the ResolveNativeReference task is in MSBuild.

@rainersigwald, what are your thoughts on Merrie's analysis?  Could we fix this in the .NET SDK, or in MSBuild's ResolveNativeReference task?
