### ISSUE TITLE
Workload install always fail

### ISSUE THREAD

**Issue by NashiraDeer** [dotnet/sdk#27075]
### Describe the bug
The command "dotnet workload install" always fail, whenever I try to install with it, even after I repair and reinstall the dotnet SDK from the dotnet.microsoft.com website.

I am trying to install the workloads necessary for the Uno Platform, but the workloads command fails for everything.

I already have removed the dotnet folder in Program Files and reinstalled the .NET SDK, but nothing changes.

"dotnet workload update -v d"
```

Nenhuma carga de trabalho instalada para esta faixa de recursos. Para atualizar cargas de trabalho instaladas com versões anteriores do SDK, inclua a opção --from-previous-sdk.
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.sdk.ios.manifest-6.0.400.msi.x64/index.json
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.sdk.maccatalyst.manifest-6.0.400.msi.x64/index.json
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.sdk.macos.manifest-6.0.400.msi.x64/index.json
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.sdk.maui.manifest-6.0.400.msi.x64/index.json
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.sdk.tvos.manifest-6.0.400.msi.x64/index.json
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.workload.emscripten.manifest-6.0.400.msi.x64/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.sdk.macos.manifest-6.0.400.msi.x64/index.json 697 ms
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.sdk.maui.manifest-6.0.400.msi.x64/index.json 700 ms
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.sdk.tvos.manifest-6.0.400.msi.x64/index.json 699 ms
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.sdk.maccatalyst.manifest-6.0.400.msi.x64/index.json 705 ms
[NuGet Manager] [Info]   NotFound https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.workload.emscripten.manifest-6.0.400.msi.x64/index.json 710 ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.workload.emscripten.manifest-6.0.300.msi.x64/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.sdk.ios.manifest-6.0.400.msi.x64/index.json 776 ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.macos.manifest-6.0.400.msi.x64/index.json
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.maui.manifest-6.0.400.msi.x64/index.json
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.maccatalyst.manifest-6.0.400.msi.x64/index.json
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.tvos.manifest-6.0.400.msi.x64/index.json
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.ios.manifest-6.0.400.msi.x64/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/microsoft.net.workload.emscripten.manifest-6.0.300.msi.x64/index.json 564 ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/microsoft.net.workload.emscripten.manifest-6.0.300.msi.x64/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.maccatalyst.manifest-6.0.400.msi.x64/index.json 560 ms
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.ios.manifest-6.0.400.msi.x64/index.json 560 ms
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.tvos.manifest-6.0.400.msi.x64/index.json 561 ms
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.maui.manifest-6.0.400.msi.x64/index.json 576 ms
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.macos.manifest-6.0.400.msi.x64/index.json 577 ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.maccatalyst.manifest-6.0.400.msi.x64/15.4.447/microsoft.net.sdk.maccatalyst.manifest-6.0.400.msi.x64.15.4.447.nupkg
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.tvos.manifest-6.0.400.msi.x64/15.4.447/microsoft.net.sdk.tvos.manifest-6.0.400.msi.x64.15.4.447.nupkg
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.maui.manifest-6.0.400.msi.x64/6.0.486/microsoft.net.sdk.maui.manifest-6.0.400.msi.x64.6.0.486.nupkg
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.ios.manifest-6.0.400.msi.x64/15.4.447/microsoft.net.sdk.ios.manifest-6.0.400.msi.x64.15.4.447.nupkg
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.macos.manifest-6.0.400.msi.x64/12.3.447/microsoft.net.sdk.macos.manifest-6.0.400.msi.x64.12.3.447.nupkg
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.ios.manifest-6.0.400.msi.x64/15.4.447/microsoft.net.sdk.ios.manifest-6.0.400.msi.x64.15.4.447.nupkg 46 ms
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.macos.manifest-6.0.400.msi.x64/12.3.447/microsoft.net.sdk.macos.manifest-6.0.400.msi.x64.12.3.447.nupkg 50 ms
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.maui.manifest-6.0.400.msi.x64/6.0.486/microsoft.net.sdk.maui.manifest-6.0.400.msi.x64.6.0.486.nupkg 51 ms
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.tvos.manifest-6.0.400.msi.x64/15.4.447/microsoft.net.sdk.tvos.manifest-6.0.400.msi.x64.15.4.447.nupkg 61 ms
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/microsoft.net.sdk.maccatalyst.manifest-6.0.400.msi.x64/15.4.447/microsoft.net.sdk.maccatalyst.manifest-6.0.400.msi.x64.15.4.447.nupkg 71 ms
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/microsoft.net.workload.emscripten.manifest-6.0.300.msi.x64/index.json 562 ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3-flatcontainer/microsoft.net.workload.emscripten.manifest-6.0.300.msi.x64/6.0.4/microsoft.net.workload.emscripten.manifest-6.0.300.msi.x64.6.0.4.nupkg
[NuGet Manager] [Info]   OK https://api.nuget.org/v3-flatcontainer/microsoft.net.workload.emscripten.manifest-6.0.300.msi.x64/6.0.4/microsoft.net.workload.emscripten.manifest-6.0.300.msi.x64.6.0.4.nupkg 45 ms
Falha ao atualizar o manifesto de publicidade microsoft.net.sdk.ios: Falha ao extrair informações do MSI: C:\Users\nashi\AppData\Local\Temp\126fa09b-ebdf-4006-ae30-3e8015fad17f\data\Microsoft.NET.Sdk.iOS.Manifest-6.0.400.15.4.447-x64.msi.
Falha ao atualizar o manifesto de publicidade microsoft.net.sdk.maccatalyst: Falha ao extrair informações do MSI: C:\Users\nashi\AppData\Local\Temp\f31f0fd9-acd2-495e-9c1d-9b493a2406ed\data\Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.15.4.447-x64.msi.
Manifesto de publicidade atualizado microsoft.net.sdk.tvos.
Falha ao atualizar o manifesto de publicidade microsoft.net.sdk.maui: Falha ao extrair informações do MSI: C:\Users\nashi\AppData\Local\Temp\b5094f6d-eab5-455c-95b7-7ee8b36d078d\data\Microsoft.NET.Sdk.Maui.Manifest-6.0.400.6.0.486-x64.msi.
Manifesto de publicidade atualizado microsoft.net.sdk.macos.
Manifesto de publicidade atualizado microsoft.net.workload.emscripten.
Nenhuma carga de trabalho instalada para esta faixa de recursos. Para atualizar cargas de trabalho instaladas com versões anteriores do SDK, inclua a opção --from-previous-sdk.

Carga(s) de trabalho atualizada(s) com êxito: .
```

"dotnet workload install -v d maui"
```
Unhandled exception: Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Não foi possível localizar a carga de trabalho 'microsoft-net-runtime-ios' estendida pela carga de trabalho 'ios' no manifesto 'microsoft.net.sdk.ios' [C:\Program Files\dotnet\sdk-manifests\6.0.400\microsoft.net.sdk.ios\WorkloadManifest.json]
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.<>c__DisplayClass24_0.<<EnumerateWorkloadWithExtends>g__EnumerateWorkloadWithExtendsRec|0>d.MoveNext()
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.GetAvailableWorkloadDefinitions()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand.ValidateWorkloadIdsInput()
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String dotnetDir, String userProfileDir, String tempDirPath, String version, IReadOnlyCollection`1 workloadIds, String installedFeatureBand)
   at Microsoft.DotNet.Cli.WorkloadInstallCommandParser.<>c.<ConstructCommand>b__6_0(ParseResult parseResult)
   at Microsoft.DotNet.Cli.ParseResultCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### To Reproduce
1. Install .NET SDK 6.0.8 (6.0.400) for Windows.
2. Run "dotnet workload install maui".

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
  ```

**Comment by baronfel** [comment]
Hello, I tried these same commands on a fresh 6.0.400 install this morning and could not reproduce the errors.

For `dotnet workload update -v d` I do see the advertising manifest load errors, but we're already tracking that and it doesn't impact the actual download of the workloads.

For `dotnet workload install -v d maui`, The install worked as expected, downloading the following packs:

```
Microsoft.Android.Ref.31                                                      Microsoft.Android.Runtime.31.android-arm
Microsoft.Android.Runtime.31.android-arm64                                    Microsoft.Android.Runtime.31.android-x64
Microsoft.Android.Runtime.31.android-x86                                      Microsoft.Android.Sdk.Windows
Microsoft.AspNetCore.App.Ref                                                  Microsoft.iOS.Ref
Microsoft.iOS.Runtime.ios-arm                                                 Microsoft.iOS.Runtime.ios-arm64
Microsoft.iOS.Runtime.iossimulator-arm64                                      Microsoft.iOS.Runtime.iossimulator-x64
Microsoft.iOS.Runtime.iossimulator-x86                                        Microsoft.iOS.Sdk
Microsoft.iOS.Windows.Sdk                                                     Microsoft.MacCatalyst.Ref
Microsoft.MacCatalyst.Runtime.maccatalyst-arm64                               Microsoft.MacCatalyst.Runtime.maccatalyst-x64
Microsoft.MacCatalyst.Sdk                                                     Microsoft.Maui.Controls.Ref.android
Microsoft.Maui.Controls.Ref.any                                               Microsoft.Maui.Controls.Ref.ios
Microsoft.Maui.Controls.Ref.maccatalyst                                       Microsoft.Maui.Controls.Ref.tizen
Microsoft.Maui.Controls.Ref.win                                               Microsoft.Maui.Controls.Runtime.android
Microsoft.Maui.Controls.Runtime.any                                           Microsoft.Maui.Controls.Runtime.ios
Microsoft.Maui.Controls.Runtime.maccatalyst                                   Microsoft.Maui.Controls.Runtime.tizen
Microsoft.Maui.Controls.Runtime.win                                           Microsoft.Maui.Core.Ref.android
Microsoft.Maui.Core.Ref.any                                                   Microsoft.Maui.Core.Ref.ios
Microsoft.Maui.Core.Ref.maccatalyst                                           Microsoft.Maui.Core.Ref.tizen
Microsoft.Maui.Core.Ref.win                                                   Microsoft.Maui.Core.Runtime.android
Microsoft.Maui.Core.Runtime.any                                               Microsoft.Maui.Core.Runtime.ios
Microsoft.Maui.Core.Runtime.maccatalyst                                       Microsoft.Maui.Core.Runtime.tizen
Microsoft.Maui.Core.Runtime.win                                               Microsoft.Maui.Essentials.Ref.android
Microsoft.Maui.Essentials.Ref.any                                             Microsoft.Maui.Essentials.Ref.ios
Microsoft.Maui.Essentials.Ref.maccatalyst                                     Microsoft.Maui.Essentials.Ref.tizen
Microsoft.Maui.Essentials.Ref.win                                             Microsoft.Maui.Essentials.Runtime.android
Microsoft.Maui.Essentials.Runtime.any                                         Microsoft.Maui.Essentials.Runtime.ios
Microsoft.Maui.Essentials.Runtime.maccatalyst                                 Microsoft.Maui.Essentials.Runtime.tizen
Microsoft.Maui.Essentials.Runtime.win                                         Microsoft.Maui.Resizetizer.Sdk
Microsoft.Maui.Sdk                                                            Microsoft.NET.Runtime.MonoAOTCompiler.Task
Microsoft.NET.Runtime.MonoTargets.Sdk                                         Microsoft.NETCore.App.Host.win-arm
Microsoft.NETCore.App.Host.win-arm64                                          Microsoft.NETCore.App.Host.win-x64
Microsoft.NETCore.App.Host.win-x86                                            Microsoft.NETCore.App.Ref
Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm                   Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64
Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64                   Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86
Microsoft.NETCore.App.Runtime.Mono.android-arm                                Microsoft.NETCore.App.Runtime.Mono.android-arm64
Microsoft.NETCore.App.Runtime.Mono.android-x64                                Microsoft.NETCore.App.Runtime.Mono.android-x86
Microsoft.NETCore.App.Runtime.Mono.ios-arm                                    Microsoft.NETCore.App.Runtime.Mono.ios-arm64
Microsoft.NETCore.App.Runtime.Mono.iossimulator-arm64                         Microsoft.NETCore.App.Runtime.Mono.iossimulator-x64
Microsoft.NETCore.App.Runtime.Mono.iossimulator-x86                           Microsoft.NETCore.App.Runtime.Mono.maccatalyst-arm64
Microsoft.NETCore.App.Runtime.Mono.maccatalyst-x64                            Microsoft.WindowsDesktop.App.Ref
NETStandard.Library.Ref
```

@joeloff @dsplaisted are there any debug logs we can get from @NashiraDeer to get more info?

**Comment by joeloff** [comment]
Based on the error it looks like it failed to extract some of the MSIs. There should be some logs in %temp% if this was an MSI based workload install (which it seems it was). Look for files similar to `%temp%\Microsoft.NET.Workload*.log`

**Comment by NashiraDeer** [comment]
After I install .NET 6.0.303 and reinstall Visual Studio 2022 (with .NET MAUI workload), the problem disappeared.

"dotnet workload install maui"
```
Falha ao atualizar o manifesto de publicidade microsoft.net.sdk.ios: Falha ao extrair informações do MSI: C:\Users\nashi\AppData\Local\Temp\4d3544f2-c76d-45ce-9e75-c1ec3c435ecc\data\Microsoft.NET.Sdk.iOS.Manifest-6.0.400.15.4.447-x64.msi.
Falha ao atualizar o manifesto de publicidade microsoft.net.sdk.android: Falha ao extrair informações do MSI: C:\Users\nashi\AppData\Local\Temp\93359fd2-940b-4837-a98b-3aa0b5875ba9\data\Microsoft.NET.Sdk.Android.Manifest-6.0.400.32.0.448-x64.msi.
Falha ao atualizar o manifesto de publicidade microsoft.net.sdk.macos: Falha ao extrair informações do MSI: C:\Users\nashi\AppData\Local\Temp\aad59dcd-86a8-4b41-b4d2-f87f6f163ab8\data\Microsoft.NET.Sdk.macOS.Manifest-6.0.400.12.3.447-x64.msi.
Falha ao atualizar o manifesto de publicidade microsoft.net.sdk.tvos: Falha ao extrair informações do MSI: C:\Users\nashi\AppData\Local\Temp\b48a1a93-6dd8-4611-bdc3-529b7154c959\data\Microsoft.NET.Sdk.tvOS.Manifest-6.0.400.15.4.447-x64.msi.
Falha ao atualizar o manifesto de publicidade microsoft.net.workload.mono.toolchain: Falha ao extrair informações do MSI: C:\Users\nashi\AppData\Local\Temp\bb34118d-2d97-4099-9792-6b41c032f05c\data\Microsoft.NET.Workload.Mono.ToolChain.Manifest-6.0.300.6.0.8-x64.msi.
A máquina tem uma reinicialização pendente. A instalação vai continuar, mas talvez seja necessário reiniciar.
Downloading microsoft.net.sdk.maccatalyst.manifest-6.0.400.msi.x64 (15.4.447)
Instalando Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.400.15.4.447-x64.msi .... Done
Downloading Microsoft.Maui.Core.Ref.android.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Core.Runtime.android.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Controls.Ref.android.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Controls.Runtime.android.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Essentials.Ref.android.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Essentials.Runtime.android.Msi.x64 (6.0.486)
Downloading Microsoft.AspNetCore.Components.WebView.Maui.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Dependencies.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Sdk.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Extensions.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Graphics.Msi.x64 (6.0.403)
Downloading Microsoft.Maui.Resizetizer.Sdk.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Templates-6.0.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Core.Ref.any.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Core.Runtime.any.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Controls.Ref.any.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Controls.Runtime.any.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Essentials.Ref.any.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Essentials.Runtime.any.Msi.x64 (6.0.486)
Downloading Microsoft.Android.Sdk.Windows.Msi.x64 (32.0.448)
Downloading Microsoft.Android.Ref.31.Msi.x64 (32.0.448)
Downloading Microsoft.Android.Runtime.31.android-arm.Msi.x64 (32.0.448)
Downloading Microsoft.Android.Runtime.31.android-arm64.Msi.x64 (32.0.448)
Downloading Microsoft.Android.Runtime.31.android-x86.Msi.x64 (32.0.448)
Downloading Microsoft.Android.Runtime.31.android-x64.Msi.x64 (32.0.448)
Downloading Microsoft.Android.Templates.Msi.x64 (32.0.448)
Downloading Microsoft.NETCore.App.Runtime.Mono.android-arm.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.android-arm64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.android-x64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.android-x86.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x86.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-x64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.android-arm64.Msi.x64 (6.0.8)
Downloading Microsoft.Maui.Core.Ref.ios.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Core.Runtime.ios.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Controls.Ref.ios.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Controls.Runtime.ios.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Essentials.Ref.ios.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Essentials.Runtime.ios.Msi.x64 (6.0.486)
Downloading Microsoft.iOS.Sdk.Msi.x64 (15.4.446-ci.-release-6-0-4xx.446)
Downloading Microsoft.iOS.Windows.Sdk.Msi.x64 (15.4.446-ci.-release-6-0-4xx.446)
Downloading Microsoft.iOS.Ref.Msi.x64 (15.4.446-ci.-release-6-0-4xx.446)
Downloading Microsoft.iOS.Runtime.ios-arm.Msi.x64 (15.4.446-ci.-release-6-0-4xx.446)
Downloading Microsoft.iOS.Runtime.ios-arm64.Msi.x64 (15.4.446-ci.-release-6-0-4xx.446)
Downloading Microsoft.iOS.Runtime.iossimulator-x86.Msi.x64 (15.4.446-ci.-release-6-0-4xx.446)
Downloading Microsoft.iOS.Runtime.iossimulator-x64.Msi.x64 (15.4.446-ci.-release-6-0-4xx.446)
Downloading Microsoft.iOS.Runtime.iossimulator-arm64.Msi.x64 (15.4.446-ci.-release-6-0-4xx.446)
Downloading Microsoft.iOS.Templates.Msi.x64 (15.4.446-ci.-release-6-0-4xx.446)
Downloading Microsoft.NETCore.App.Runtime.Mono.ios-arm.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.ios-arm64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.iossimulator-arm64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.iossimulator-x64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.iossimulator-x86.Msi.x64 (6.0.8)
Downloading Microsoft.Maui.Core.Ref.tizen.Msi.x64 (6.0.486)
Instalando Microsoft.Maui.Core.Ref.tizen.6.0.486.0-x64.msi ..... Done
Downloading Microsoft.Maui.Core.Runtime.tizen.Msi.x64 (6.0.486)
Instalando Microsoft.Maui.Core.Runtime.tizen.6.0.486.0-x64.msi .... Done
Downloading Microsoft.Maui.Controls.Ref.tizen.Msi.x64 (6.0.486)
Instalando Microsoft.Maui.Controls.Ref.tizen.6.0.486.0-x64.msi .... Done
Downloading Microsoft.Maui.Controls.Runtime.tizen.Msi.x64 (6.0.486)
Instalando Microsoft.Maui.Controls.Runtime.tizen.6.0.486.0-x64.msi ...... Done
Downloading Microsoft.Maui.Essentials.Ref.tizen.Msi.x64 (6.0.486)
Instalando Microsoft.Maui.Essentials.Ref.tizen.6.0.486.0-x64.msi .... Done
Downloading Microsoft.Maui.Essentials.Runtime.tizen.Msi.x64 (6.0.486)
Instalando Microsoft.Maui.Essentials.Runtime.tizen.6.0.486.0-x64.msi ..... Done
Downloading Microsoft.Maui.Core.Ref.maccatalyst.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Core.Runtime.maccatalyst.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Controls.Ref.maccatalyst.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Controls.Runtime.maccatalyst.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Essentials.Ref.maccatalyst.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Essentials.Runtime.maccatalyst.Msi.x64 (6.0.486)
Downloading Microsoft.MacCatalyst.Sdk.Msi.x64 (15.4.447)
Instalando Microsoft.MacCatalyst.Sdk.15.4.447.447-x64.msi ..... Done
Downloading Microsoft.MacCatalyst.Ref.Msi.x64 (15.4.447)
Instalando Microsoft.MacCatalyst.Ref.15.4.447.447-x64.msi .... Done
Downloading Microsoft.MacCatalyst.Runtime.maccatalyst-arm64.Msi.x64 (15.4.447)
Instalando Microsoft.MacCatalyst.Runtime-arm64.15.4.447.447-x64.msi ..... Done
Downloading Microsoft.MacCatalyst.Runtime.maccatalyst-x64.Msi.x64 (15.4.447)
Instalando Microsoft.MacCatalyst.Runtime-x64.15.4.447.447.msi ..... Done
Downloading Microsoft.MacCatalyst.Templates.Msi.x64 (15.4.447)
Instalando Microsoft.MacCatalyst.Templates.15.4.447.447-x64.msi .... Done
Downloading Microsoft.NETCore.App.Runtime.Mono.maccatalyst-arm64.Msi.x64 (6.0.8)
Downloading Microsoft.NETCore.App.Runtime.Mono.maccatalyst-x64.Msi.x64 (6.0.8)
Downloading Microsoft.Maui.Core.Ref.win.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Core.Runtime.win.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Controls.Ref.win.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Controls.Runtime.win.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Essentials.Ref.win.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Essentials.Runtime.win.Msi.x64 (6.0.486)
Downloading Microsoft.Maui.Graphics.Win2D.WinUI.Desktop.Msi.x64 (6.0.403)

Carga(s) de trabalho(s) instalada(s) com êxito maui.
```
