### ISSUE TITLE
NRE from GenerateDepsFile during Roslyn build

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#2716]
This is a non-standard build with my local changes. Not sure how to repro this exactly.

```
C:\Program Files\dotnet\sdk\2.1.600-preview-009426\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(129,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NET.Build.Tasks.ReferenceInfo.GetVersion(ITaskItem referencePath)
   at Microsoft.NET.Build.Tasks.ReferenceInfo.CreateReferenceInfo(ITaskItem referencePath)
   at Microsoft.NET.Build.Tasks.ReferenceInfo.CreateReferenceInfos(IEnumerable`1 referencePaths)
   at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [D:\R3\src\Workspaces\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Workspaces.csproj]
```

binlog:
[Binlog.zip](https://github.com/dotnet/sdk/files/2646153/Binlog.zip)

`Binaries\Obj\Microsoft.CodeAnalysis.CSharp.Workspaces\project.assets.json`
[project.assets.zip](https://github.com/dotnet/sdk/files/2646158/project.assets.zip)

**Comment by livarcocc** [comment]
@nguerrera is this in the cache code?

@tmat what version of the .net core SDK does this happen?

**Comment by nguerrera** [comment]
Not assets cache code of that's what you're asking.

**Comment by nguerrera** [comment]
What does non standard with local changes mean?

**Comment by tmat** [comment]
@nguerrera I was changing some of the build scripts to port to Arcade and this was built with incorrect combination of switches. If the issue is not obvious from the above info I can try to recreate the repro.

**Comment by nguerrera** [comment]
I'll check the binlog and source at that stack and let you know if that's enough.

**Comment by nguerrera** [comment]
Sorry for letting this sit. The binlog doesn't give a hint. Closing until we see another instance with repro.

**Comment by calvin-charles** [comment]
I ran into a similar issue when I add c++/cli project conditionally in a sdk style project. Build succeeds, but rebuild always fail on VS 2022:
`Error	MSB4018	The "GenerateDepsFile" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NET.Build.Tasks.ReferenceInfo.GetVersion(ITaskItem referencePath)
   at Microsoft.NET.Build.Tasks.ReferenceInfo.CreateReferenceInfo(ITaskItem referencePath)
   at Microsoft.NET.Build.Tasks.ReferenceInfo.CreateFilteredReferenceInfos(IEnumerable`1 referencePaths, IEnumerable`1 referenceSatellitePaths)
   at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath)
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.NET.Build.Tasks.TaskWithAssemblyResolveHooks.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	CPPCLI.Net60	C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	172`
   
   csproj:
  `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net6.0</TargetFrameworks>
  <Platforms>x64;x86</Platforms>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>	
	
 
  <ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">
    <ProjectReference Include="..\CPPCLI.Net462.vcxproj" />
  </ItemGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
    <ProjectReference Include="..\CPPCLI.Net60.vcxproj" />
  </ItemGroup>
  <ItemGroup>
</Project>`

  what am I doing wrong?

**Comment by ericstj** [comment]
We see repros of this issue, [here](https://github.com/dotnet/runtime/issues/67091) and [here](https://github.com/dotnet/runtime/issues/40159)

We noticed it happened here: https://github.com/dotnet/sdk/blob/a5f5bb5183517cb301050288b25c9c727e52e8a6/src/Tasks/Microsoft.NET.Build.Tasks/ReferenceInfo.cs#L150

RAR was setting FusionName to a simple name.

**Comment by Linlccc** [comment]
@ericstj https://github.com/dotnet/runtime/issues/67091#issuecomment-1077866445 The two issues mentioned here,
1. The project I have built in advance to restore
2. I don't see any missing items from the log, I haven't modified sln yet

I uploaded the binary log file
[binlog.zip](https://github.com/dotnet/sdk/files/8346826/binlog.zip)
