### ISSUE TITLE
HttpClient fails to connect over SSL when running `dotnet 3.1` on Fedora:36

### ISSUE THREAD

**Issue by mjhilton** [dotnet/sdk#27360]
### Describe the bug
When [installing the dotnet 3.1 SDK using the package manager](https://docs.microsoft.com/en-us/dotnet/core/install/linux-fedora#install-net-core-31) on Fedora v36, the installation runs smoothly. 

However, at runtime, dotnet classes such as `HttpClient` that rely on underlying SSL implementations provided by the OS and dependent packages fail when attempting to connect to an SSL endpoint. 

### To Reproduce
1. On Fedora 36, install dotnet 3.1 SDK using `dnf install -y dotnet-sdk-3.1`.
2. Create a simple app which uses `HttpClient` to try to retrieve a publicly available page over SSL
3. Run the app

**Expected**: Should be able to make an SSL connection and retrieve the page
**Actual**: App fails with `Interop+Crypto+OpenSslCryptographicException: error:0E076071:configuration file routines:module_run:unknown module name`

---

Here is a simple Docker image, which performs the above steps:
```Dockerfile
FROM fedora:36

RUN dnf install -y dotnet-sdk-3.1

RUN mkdir /app
WORKDIR /app
RUN dotnet new console && \
    echo "using System; namespace TestSsl { class Program { async static System.Threading.Tasks.Task Main(string[] args) { var client = new System.Net.Http.HttpClient(); await client.GetAsync(\"https://www.google.com\"); } } }" > Program.cs

ENTRYPOINT dotnet run
```
You can use this for a quick repro, with:
1. Save the above dockerfile as Fedora36.dockerfile
2. `docker build -f Fedora36.dockerfile -t fedora36sslproblem .`
3. `docker run --rm fedora36sslproblem`

### Exceptions (if any)
The following stacktrace is received when running the simple repro above:
```
Unhandled exception. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.TypeInitializationException: The type initializer for 'SslMethods' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Ssl' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SslInitializer' threw an exception.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0E076071:configuration file routines:module_run:unknown module name
   at Interop.SslInitializer..cctor() in /_/src/Common/src/Interop/Unix/System.Net.Security.Native/Interop.Initialization.cs:line 33
   --- End of inner exception stack trace ---
   at Interop.Ssl..cctor() in /_/src/Common/src/Interop/Unix/System.Net.Security.Native/Interop.Initialization.cs:line 16
   --- End of inner exception stack trace ---
   at Interop.Ssl.SslV2_3Method()
   at Interop.Ssl.SslMethods..cctor() in /_/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.Ssl.cs:line 194
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.AllocateSslContext(SslProtocols protocols, SafeX509Handle certHandle, SafeEvpPKeyHandle certKeyHandle, EncryptionPolicy policy, SslAuthenticationOptions sslAuthenticationOptions) in /_/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs:line 60
   at System.Net.Security.SafeDeleteSslContext..ctor(SafeFreeSslCredentials credential, SslAuthenticationOptions sslAuthenticationOptions) in /_/src/Common/src/System/Net/Security/Unix/SafeDeleteSslContext.cs:line 30
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions) in /_/src/System.Net.Security/src/System/Net/Security/SslStreamPal.Unix.cs:line 111
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 713
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 557
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.Implementa   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/TaskFactory.cs:line 1015   at System.Net.Security.SslStream.AuthenticateAsClientAsync(SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken) in /_/src/System.Net.Security/src/System/Net/Security/SslStream.cs:line 402   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 145   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs:line 161
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 651
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 666
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 332
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 524
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in /_/src/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 521   at TestSsl.Program.Main(String[] args) in /app/Program.cs:line 1
   at TestSsl.Program.<Main>(String[] args)
```

### Further technical details
I originally encountered this issue when installing using the [Scripted Install approach](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install). 

When not using a package manager, you're directed by the documentation to [install a few dependencies](https://docs.microsoft.com/en-us/dotnet/core/install/linux-fedora#dependencies). The documentation also says:
> If the target runtime environment's OpenSSL version is 1.1 or newer, you'll need to install `compat-openssl10`

However, there is no stable version of this package available in Fedora 36's repositories. They [say it was "retired due to security issues and general obsolescence"](https://src.fedoraproject.org/rpms/compat-openssl10).

I suspect that this is why things are no longer working on Fedora 36; it might have been an implicit dependency in the package graph which no longer exists.

**Comment by danmoseley** [comment]
@bartonjs were we already aware of this omission from Fedora 36? What is our guidance?

@mjhilton note that 3.1 is going out of support this year. Does 6.0 work OK for you instead?

**Comment by mjhilton** [comment]
> @mjhilton note that 3.1 is going out of support this year. Does 6.0 work OK for you instead?

That's where my head was going, as 6.0 does seem to work fine on Fedora 36. If someone with better knowledge of the internals of how dotnet talks to the TLS libraries in the machine was able to suggest an easy fix we could make until we can prioritise that upgrade work, that would be optimal for us.

**Comment by danmoseley** [comment]
https://github.com/dotnet/runtime/issues/27792#issuecomment-435118249 looks like it possibly may help

**Comment by mjhilton** [comment]
Haven't tried 35 just yet.

As a workaround until we get the `netcoreapp3.1` -> `net6.0` upgrade done for this specific app, we've discovered that installing from Script (not package manager), and then manually installing `openssl-compat10` from the CentOS repositories is a way to get things working for us.

```Dockerfile
FROM fedora:36

# Install dotnet dependencies 
RUN dnf install -y krb5-libs libicu openssl-libs zlib wget

# Install dotnet3.1 from script
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc 
RUN wget -O /etc/yum.repos.d/microsoft-fedora36.repo https://packages.microsoft.com/config/fedora/36/prod.repo 
RUN curl --silent --fail -L -O https://dot.net/v1/dotnet-install.sh
RUN chmod +x dotnet-install.sh
RUN ./dotnet-install.sh --install-dir /usr/share/dotnet --channel 3.1
RUN rm -f dotnet-install.sh
RUN ln -s /usr/share/dotnet/dotnet /usr/local/bin

# Install OpenSSL
RUN dnf install -y openssl make

# Install compat-openssl10 from CentOS repositories
RUN rpm --import https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official
RUN wget https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/compat-openssl10-1.0.2o-3.el8.x86_64.rpm
RUN rpm -i compat-openssl10-1.0.2o-3.el8.x86_64.rpm
RUN rm -f compat-openssl10-1.0.2o-3.el8.x86_64.rpm

# Run test app
RUN mkdir /app
WORKDIR /app
RUN dotnet new console && \
    echo "using System; namespace TestSsl { class Program { async static System.Threading.Tasks.Task Main(string[] args) { var client = new System.Net.Http.HttpClient(); await client.GetAsync(\"https://www.google.com\"); Console.WriteLine(\"SSL Works\"); } } }" > Program.cs

ENTRYPOINT dotnet run
```

**Comment by mjhilton** [comment]
> Actually, I really just made that up.
😆

Yeah... I think we've done a reasonable job of trawling the existing issues (including that one you linked), and weren't able to use any of those suggestions to get success. They're all a little out of date, from pre-dotnet-6.0 days. But the [above workaround](https://github.com/dotnet/sdk/issues/27360#issuecomment-1230956384) has got us working for now.

**Comment by bartonjs** [comment]
Sounds like Fedora 36 comes with something specified in the openssl.cnf that causes whichever version of OpenSSL we're binding on to fail.

For 3.1 we work with 1.0.2/1.1.0/1.1.1, and the probe order for portable is ".so.1.1", ".so.1.0.2", ".so.1.0.0", ".so.10".

**Comment by danmoseley** [comment]
OK, since we're not going to make any changes to 3.1 at this point for Fedora 36, I'm closing. Thanks for pasting the workaround.

**Comment by mjhilton** [comment]
Note for anyone else coming to this: [the workaround pasted above](https://github.com/dotnet/sdk/issues/27360#issuecomment-1230956384) _does not_ work if you install dotnet 3.1 using a package manager, only if you install manually or from a script. I suspect the `dnf` install adds some conflicting dependencies related to TLS which would need to be removed for the workaround to work.
