### ISSUE TITLE
TestGlobalPropertyFlowInSolution failed in CI with UnauthorizedAccessException

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#27708]
Microsoft.NET.Build.Tests.GlobalPropertyFlowTests.TestGlobalPropertyFlowInSolution test is failed here:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=5947&view=ms.vss-test-web.build-test-results-tab&runId=106648&resultId=102733&paneView=debug

```
StdErr:
Unhandled exception: System.UnauthorizedAccessException: Access to the path '/Users/helix-runner/.templateengine/dotnetcli/v7.0.100-ci' is denied.
---> System.IO.IOException: Permission denied
--- End of inner exception stack trace ---
at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
at System.IO.Directory.CreateDirectory(String path)
at Microsoft.TemplateEngine.Utils.PhysicalFileSystem.CreateDirectory(String path)
at Microsoft.TemplateEngine.Edge.EngineEnvironmentSettings..ctor(ITemplateEngineHost host, Boolean virtualizeSettings, String settingsLocation, IEnvironment environment, IComponentManager componentManager, IPathInfo pathInfo)
at Microsoft.TemplateEngine.Cli.Commands.BaseCommand.CreateEnvironmentSettings(GlobalArgs args, ParseResult parseResult) in //src/Cli/Microsoft.TemplateEngine.Cli/Commands/BaseCommand.cs:line 39
at Microsoft.TemplateEngine.Cli.Commands.BaseCommand1.InvokeAsync(InvocationContext context) in /_/src/Cli/Microsoft.TemplateEngine.Cli/Commands/BaseCommand.cs:line 62 at Microsoft.TemplateEngine.Cli.Commands.BaseCommand1.Invoke(InvocationContext context) in //src/Cli/Microsoft.TemplateEngine.Cli/Commands/BaseCommand.cs:line 117
at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.DotNet.Cli.Parser.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext() in /_/src/Cli/dotnet/Parser.cs:line 177
--- End of stack trace from previous location ---
at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by marcpopMSFT** [comment]
@tmat every test that uses dotnet new in helix needs to have "--debug:ephemeral-hive" included. The location we include the dotnet install uses a hive on helix machines that we don't have access to.

**Comment by marcpopMSFT** [comment]
https://github.com/dotnet/sdk/commit/ab395b23830dfa15748b5abe7e8bb815f923f697
