### ISSUE TITLE
Test Microsoft.NET.Publish.Tests.GivenThatWeWantToPublishAClickOnceProject.PublishClickOnceWithPublishProfile failed in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#27766]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=8237&view=ms.vss-test-web.build-test-results-tab&runId=162136&resultId=102915&paneView=debug

```
Expected File "app.Publish\setup.exe" cannot be found in directory "C:\h\w\AB350945\t\dotnetSdkTests\05i4aq0f.jsi\PublishClickO---745C2E29\ConsoleWithPublishProfile\bin\Debug\net7.0\win10-x64".
```

```
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at Microsoft.NET.TestFramework.Assertions.DirectoryInfoAssertions.HaveFile(String expectedFile) in /_/src/Tests/Microsoft.NET.TestFramework/Assertions/DirectoryInfoAssertions.cs:line 43
   at Microsoft.NET.TestFramework.Assertions.DirectoryInfoAssertions.HaveFiles(IEnumerable`1 expectedFiles) in /_/src/Tests/Microsoft.NET.TestFramework/Assertions/DirectoryInfoAssertions.cs:line 60
   at Microsoft.NET.Publish.Tests.GivenThatWeWantToPublishAClickOnceProject.PublishClickOnceWithPublishProfile(Nullable`1 publishSingleFile) in /_/src/Tests/Microsoft.NET.Publish.Tests/GivenThatWeWantToPublishToClickOnce.cs:line 88
   at InvokeStub_GivenThatWeWantToPublishAClickOnceProject.PublishClickOnceWithPublishProfile(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by marcpopMSFT** [comment]
This appears to be because Sujit added a clickoncepublishdir in the msbuild repo here: [Ensure trailing slash is present for clickonce publish's output locat… by sujitnayak · Pull Request #7841 · dotnet/msbuild (github.com)](https://github.com/dotnet/msbuild/pull/7841/files)  But the clickonce target in the sdk overrides the publishdir later on in the build evaluation: [sdk/Microsoft.NET.ClickOnce.targets at main · dotnet/sdk (github.com)](https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.ClickOnce.targets#L14) so the two get out of sync...  Not sure the right solution as the clickoncepublishdir is used in the msbuild targets.  

 Maybe set it only in the sdk clickonce target?  I assume it would be set during evaluation and used after.
