### ISSUE TITLE
[NetSDKE2E][Regression] With 3.1.424 SDK, building a project with multi referring classlib failed with error MSB1025 on Mac/Linux

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/sdk#28190]
**Repro steps:**
1. Install SDK 3.1.424 on Mac or any Linux distros.
2. In cmd, create a solution within a console app and **2** classlib. Take below cmd for example.
```
mkdir ~/mysln
cd ~/mysln
dotnet new sln
dotnet new classlib -o myclass1 -f netstandard2.1
dotnet new classlib -o myclass2
dotnet sln add ./myclass1/myclass1.csproj
dotnet sln add ./myclass2/myclass2.csproj
dotnet new console -o myconsole
dotnet sln add ./myconsole/myconsole.csproj
cd myconsole/
dotnet add reference ../myclass1/myclass1.csproj
dotnet add reference ../myclass2/myclass2.csproj
```
3. Run 'dotnet build' or 'dotnet run' and observe

**Expected Result:**

 Build successfully.

**Actual Result;**

> Build failed witherror MSB1025 Internal MSBuild Error: Guid should be unique.
> nicole@OpenSUSE154:~/mysln/myconsole> dotnet build
> Microsoft (R) Build Engine version 16.7.3+a2130f262 for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Determining projects to restore...
>   All projects are up-to-date for restore.
> 
> Build FAILED.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:00.49
> MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
> Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Guid should be unique
>    at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
>    at Microsoft.Build.Shared.FileUtilities.GetTemporaryFile(String directory, String fileName, String extension, Boolean createFile)
>    at Microsoft.Build.Shared.NamedPipeUtil.GetPipeNameOrPath(String pipeName)
>    at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.TryConnectToProcess(Int32 nodeProcessId, Int32 timeout, Int64 hostHandshake, Int64 clientHandshake)
>    at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.GetNode(String msbuildLocation, String commandLineArgs, Int32 nodeId, INodePacketFactory factory, Int64 hostHandshake, Int64 clientHandshake, NodeContextTerminateDelegate terminateNode)
>    at Microsoft.Build.BackEnd.NodeProviderOutOfProc.CreateNode(Int32 nodeId, INodePacketFactory factory, NodeConfiguration configuration)
>    at Microsoft.Build.BackEnd.NodeManager.AttemptCreateNode(INodeProvider nodeProvider, NodeConfiguration nodeConfiguration)
>    at Microsoft.Build.BackEnd.NodeManager.CreateNode(NodeConfiguration configuration, NodeAffinity nodeAffinity)
>    at Microsoft.Build.Execution.BuildManager.PerformSchedulingActions(IEnumerable`1 responses)
>    at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
>    at Microsoft.Build.Execution.BuildManager.ProcessPacket(Int32 node, INodePacket packet)
>    at Microsoft.Build.Execution.BuildManager.<>c__DisplayClass70_0.<Microsoft.Build.BackEnd.INodePacketHandler.PacketReceived>b__0()
>    at Microsoft.Build.Execution.BuildManager.ProcessWorkQueue(Action action)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Build.Execution.BuildManager.EndBuild()
>    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)
> 
> MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
> Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Guid should be unique
>    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)
>    at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
> Unhandled exception. Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Guid should be unique
>    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)
>    at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
>    at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
 
**Note:**
  1. This issue is not repro on a solution within 1 console app and **1** classlib
  2. This issue is not repro on Windows X64
  3. This issue is not repro on 3.1.423 SDK

**Dotnet --info**

>  .NET Core SDK (reflecting any global.json):
>  Version:   3.1.424
>  Commit:    f7a7e5b215
> 
> Runtime Environment:
>  OS Name:     opensuse-leap
>  OS Version:  15.4
>  OS Platform: Linux
>  RID:         linux-x64
>  Base Path:   /home/nicole/mytest/sdk/3.1.424/
> 
> Host (useful for support):
>   Version: 3.1.30
>   Commit:  e96b8e2d47
> 
> .NET Core SDKs installed:
>   3.1.424 [/home/nicole/mytest/sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.App 3.1.30 [/home/nicole/mytest/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.30 [/home/nicole/mytest/shared/Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download
>

**Comment by NicoleWang001** [comment]
This issue is not repro on SDK 3.1.426 and 3.1.427
