### ISSUE TITLE
`dotnet publish --os Linux` in .NET 7 references .NET 6

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/sdk#28350]
```
@TanayParikh ➜ /workspaces $ dotnet new console -o console
The template "Console App" was created successfully.

Processing post-creation actions...
Restoring /workspaces/console/console.csproj:
  Determining projects to restore...
  Restored /workspaces/console/console.csproj (in 0.7 ms).
Restore succeeded.


@TanayParikh ➜ /workspaces $ cd console/
@TanayParikh ➜ /workspaces/console $ dotnet publish console.csproj --os linux
Unhandled exception: System.IO.DirectoryNotFoundException: Could not find a part of the path '/usr/local/dotnet/6/dotnet/sdk'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at Microsoft.DotNet.Cli.CommonOptions.GetCurrentRuntimeId()
   at Microsoft.DotNet.Cli.CommonOptions.ResolveRidShorthandOptionsToRuntimeIdentifier(String os, String arch)
   at Microsoft.DotNet.Cli.CommonOptions.ResolveRidShorthandOptions(String os, String arch, Boolean userSpecifiedSelfContainedOption)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.FromParseResult(ParseResult parseResult, String msbuildPath)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.Run(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Cli.Parser.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

```
@TanayParikh ➜ /workspaces/wasmhosted $ dotnet --version
7.0.100-rtm.22505.9
@TanayParikh ➜ /workspaces/wasmhosted $ dotnet publish Server/wasmhosted.Server.csproj --os linux
Unhandled exception: System.IO.DirectoryNotFoundException: Could not find a part of the path '/usr/local/dotnet/6/dotnet/sdk'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at Microsoft.DotNet.Cli.CommonOptions.GetCurrentRuntimeId()
   at Microsoft.DotNet.Cli.CommonOptions.ResolveRidShorthandOptionsToRuntimeIdentifier(String os, String arch)
   at Microsoft.DotNet.Cli.CommonOptions.ResolveRidShorthandOptions(String os, String arch, Boolean userSpecifiedSelfContainedOption)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.FromParseResult(ParseResult parseResult, String msbuildPath)
   at Microsoft.DotNet.Tools.Publish.PublishCommand.Run(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Cli.Parser.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by baronfel** [comment]
This feels funny to me - that .NET SDK install path seems very non-standard. I'm wondering if you have some of the new ubuntu packages mixed up with the MS-official packages here.

**Comment by TanayParikh** [comment]
This was within a relatively clean GitHub codespaces environment. Repro can be achieved using a new codespaces env in the https://github.com/dotnet/aspnetcore repo.

**Comment by TanayParikh** [comment]
Oh and I installed .NET 7 using the dotnetinstall shell script.

**Comment by marcpopMSFT** [comment]
Definitely think it's something with your install.  From the code, this is where it's failing:
https://github.com/dotnet/sdk/blob/release/7.0.1xx/src/Cli/dotnet/CommonOptions.cs#L245

So the call to GetDotnetExeDirectory() is finding the 6.0 path for dotnet root path.  From that method, it's gets the directory of the current process (dotnet in this case) and then has a bunch fallbacks for finding the rootpath
           dotnetRootPath = Path.GetFileName(dotnetRootPath).Contains("dotnet") || Path.GetFileName(dotnetRootPath).Contains("x64") || Path.GetFileName(dotnetRootPath).Equals("d") ? dotnetRootPath : Path.Combine(dotnetRootPath, "dotnet");

Any idea which of these is being picked on your box as you know your directory structure?  Also, is this still happening?
