### ISSUE TITLE
Publish self contained app with RIDs that refs a classlib without RIDs results in ArgumentNullException in ResolveFrameworkReferences

### ISSUE THREAD

**Issue by 0xd4d** [dotnet/sdk#2851]
Version: Latest build of .NET Core SDK (3.0.100-preview-010137)

If you have an app with RIDs in the csproj file that references a class library with no RIDs in its csproj file, and you publish a self contained .NET Core 3.0 app, the build fails with an ArgumentNullException in ResolveFrameworkReferences.

https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/ResolveFrameworkReferences.cs#L132 calls `GetBestRuntimeIdentifier()` but this method assumes `AppHostRuntimeIdentifier` isn't `null`.

Stack trace:

```
The "ResolveFrameworkReferences" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at System.Collections.ObjectModel.ReadOnlyDictionary`2.ContainsKey(TKey key)
   at Microsoft.NET.Build.Tasks.NuGetUtils.GetBestMatchingRid(RuntimeGraph runtimeGraph, String runtimeIdentifier, IEnumerable`1 availableRuntimeIdentifiers, Boolean& wasInGraph) in /_/src/Tasks/Microsoft.NET.Build.Tasks/NuGetUtils.NuGet.cs:line 86
   at Microsoft.NET.Build.Tasks.ResolveFrameworkReferences.GetBestRuntimeIdentifier(String targetRuntimeIdentifier, String availableRuntimeIdentifiers, Boolean& wasInGraph) in /_/src/Tasks/Microsoft.NET.Build.Tasks/ResolveFrameworkReferences.cs:line 267
   at Microsoft.NET.Build.Tasks.ResolveFrameworkReferences.ExecuteCore() in /_/src/Tasks/Microsoft.NET.Build.Tasks/ResolveFrameworkReferences.cs:line 134
   at Microsoft.NET.Build.Tasks.TaskBase.Execute() in /_/src/Tasks/Common/TaskBase.cs:line 35
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

Repro:

- Clone https://github.com/0xd4d/ResolveFrameworkReferences_issue
- Use latest daily build of .NET Core SDK
- dotnet publish -c Release -f netcoreapp3.0 -r win-x86 --self-contained

**Comment by peterhuene** [comment]
Sure, I'll put up a PR.
