### ISSUE TITLE
Publish fails with locked file with web.config and hardlinks

### ISSUE THREAD

**Issue by rgroenewoudt** [dotnet/sdk#28616]
### Describe the bug
dotnet publish fails when web.config is prevent and CreateHardLinksForPublishFilesIfPossible property is set.

### To Reproduce
- Create new ASP.NET project
- Add web.config with any content.
- Execute `dotnet publish -c Release /p:CreateHardLinksForPublishFilesIfPossible=true`

[WebApplication1.zip](https://github.com/dotnet/sdk/files/9798711/WebApplication1.zip)

### Exceptions (if any)
```
C:\Program Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk.Publish\targets\TransformTargets\Microsoft.NET.Sdk.Publish.TransformFiles.targets(50,5): error MSB4018: The "TransformWebConfig" task failed unexpectedly.
C:\Program Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk.Publish\targets\TransformTargets\Microsoft.NET.Sdk.Publish.TransformFiles.targets(50,5): error MSB4018: System.IO.IOException: The process cannot access the file 'C:\Users\robbi\source\repos\WebApplication1\WebApplication1\test\web.config' because it is being used by another process.
C:\Program Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk.Publish\targets\TransformTargets\Microsoft.NET.Sdk.Publish.TransformFiles.targets(50,5): error MSB4018:    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
C:\Program Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk.Publish\targets\TransformTargets\Microsoft.NET.Sdk.Publish.TransformFiles.targets(50,5): error MSB4018:    at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
C:\Program Files\dotnet\sdk\6.0.402\Sdks\Microsoft.NET.Sdk.Publish\targets\TransformTargets\Microsoft.NET.Sdk.Publish.TransformFiles.targets(50,5): error MSB4018:    at Microsoft.NET.Sdk.Publish.Tasks.TransformWebConfig.Execute()
```

### Further technical details
```
.NET SDK (reflecting any global.json):
 Version:   6.0.402
 Commit:    6862418796

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.402\

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a
```

**Comment by Licho1** [comment]
Confirming this bug — we hit this exact issue after adding `CreateHardLinksForPublishFilesIfPossible=true` to our project.

**Root cause (confirmed):** `CopyFilesToPublishDirectory` hard-links the project's `Web.config` to `$(PublishDir)Web.config`, making both paths point to the same inode. Then `TransformWebConfig` opens the source `Web.config` for reading (with `FileShare.Read`), and tries to `File.Copy` to `$(PublishDir)Web.config` — the same inode. Windows rejects the write because the read handle doesn't allow concurrent writers on the same inode.

**Workaround** — add this to your web project `.csproj`:

```xml
<!-- Prevent CopyFilesToPublishDirectory from hard-linking Web.config;
     TransformWebConfig generates it independently anyway. -->
<ItemGroup>
  <Content Update="Web.config">
    <CopyToPublishDirectory>Never</CopyToPublishDirectory>
  </Content>
</ItemGroup>

<!-- Clean up any stale hard-linked Web.config from a previous publish run. -->
<Target Name="UnlinkPublishWebConfig"
        AfterTargets="CopyFilesToPublishDirectory"
        BeforeTargets="TransformWebConfig">
  <Delete Files="$(PublishDir)Web.config" TreatErrorsAsWarnings="true" />
</Target>
```

`CopyToPublishDirectory=Never` prevents the hard link from being created going forward. `TransformWebConfig` still generates `Web.config` in the publish output correctly — it operates independently of the copy pipeline. The `Delete` target handles any stale hard-linked `Web.config` left from a previous publish run.
