### ISSUE TITLE
CanInstallRemoteNuGetPackage_LatestVariations failed in CI

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#28802]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=65642&view=ms.vss-test-web.build-test-results-tab&runId=1338148&resultId=100064&paneView=debug

```
Assert.Equal() Failure\n                                   ↓ (pos 100)\nExpected: ···ojectTemplates.5.0\n\nSuccess: Microsoft.DotNet.Common.ProjectT···\nActual:   ···ojectTemplates.5.0\n\nRetrying 'FindPackagesByIdAsync' for sour···\n                                   ↑ (pos 100)
```

```
Stack trace
   at Microsoft.DotNet.Cli.New.IntegrationTests.DotnetNewInstallTests.CanInstallRemoteNuGetPackage_LatestVariations(String commandName) in /Users/runner/work/1/s/src/Tests/dotnet-new.Tests/DotnetNewInstallTests.cs:line 87
   at InvokeStub_DotnetNewInstallTests.CanInstallRemoteNuGetPackage_LatestVariations(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by marcpopMSFT** [comment]
@dotnet/templating-engine-maintainers to take a look.

**Comment by vlada-shubina** [comment]
@GangWang01 could you please take a look? thank you

**Comment by GangWang01** [comment]
From the directory path the test failed on macOS in CI. `Retrying 'FindPackagesByIdAsync' for sour···` told Nuget failed to get the package somehow during template installation. Probably it's the same problem as described in https://github.com/dotnet/sdk/issues/28801#issuecomment-1316828708. In CI on macOS Nuget hit the connection issue.
