### ISSUE TITLE
.Net7 dotnet watch regression: Failed to create MSBuildWorkspace for *.fsproj

### ISSUE THREAD

**Issue by En3Tho** [dotnet/sdk#28998]
I'm running BlazorServer app which has a dependency on F# project. Previously with .Net6 there was no problem running applying HotReload and some of stuff was changing instantly (for example applying a css class to blazor markup).

With .Net 7 I'm seeing an error "Cannot_open_project_0_because_the_file_extension_1_is_not_associated_with_a_language" error because only csproj and vbproj are supported.

Now it does full rebuild even if only C# parts are changed. Before it worked fine.

To repro:
Create an empty blazor server project and reference an F# project with some data. Run dotnet watch. Change something trivial like css/markup.

Expected: hot reload works and page is updated immediately
Result: hot reload fails with this error and full rebuild is issued

**Comment by En3Tho** [comment]
While debugging dotnet watch in main I've noticed that no LanguageService was registered for F#. C#, VB and TypeScript are there, but F# is missing. I'm not sure how to register this thing.

**Comment by vzarytovskii** [comment]
Afaik, msbuildworkspaces never supported fsproj/shproj projects.

@baronfel do you know what may have changed in watch?

**Comment by baronfel** [comment]
No idea. @tmat is listed as a code owner for watch, any ideas?

**Comment by tmat** [comment]
I'm guessing it used to work before Hot Reload was implemented in `dotnet watch`. Can you try `dotnet watch --no-hot-reload`?

**Comment by En3Tho** [comment]
dotnet watch --no-hot-reload no longer displays that error but not suprisingly there is no hot reload and every edit results in a rebuild.

> I'm guessing it used to work before Hot Reload was implemented in dotnet watch

I'm not sure I correctly understood. Do you mean in Net6 there was no hot-reload in dotnet watch? Did dotnet watch use some other mechanism to apply changes instantly?

**Comment by En3Tho** [comment]
Issue magically resolved itself after git clean -xdf . Now this error doesnt get shown and dotnet watch is working as usual. Meaning change C# files -> hot reload applies when possible, change F# file -> rebuild

**Comment by En3Tho** [comment]
Oh, no. I'm mistaken. Sorry. It applied a change only once for a static file and then failed to apply C# changes. Issue still persists

**Comment by En3Tho** [comment]
One thing I can say is that while debugging 6.0  dotnet-watch it noticed that fsproj references somehow never get added to C# projects. In "main" they do.

I don't know if it's a bug or not but it made 6.0 work

**Comment by En3Tho** [comment]
I've trried 2 things:
1: simply ignore msbuild error
2. remove unresolved references from solution object to simulate net6 behavior

![image](https://user-images.githubusercontent.com/37334640/203366826-cbc4eaad-a994-4fd7-b76c-fc226292b028.png)

Both cases result in:

dotnet watch ⌚ Caught top-level exception from hot reload: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Immutable.ImmutableArray`1.get_Item(Int32 index)
   at Microsoft.CodeAnalysis.NodeStateTable`1.Single()
   at Microsoft.CodeAnalysis.CombineNode`2.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source)
   at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source)
   at Microsoft.CodeAnalysis.CombineNode`2.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source)
   at Microsoft.CodeAnalysis.CombineNode`2.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source)
   at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source)
   at Microsoft.CodeAnalysis.SourceOutputNode`1.UpdateStateTable(Builder graphState, NodeStateTable`1 previousTable, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.DriverStateTable.Builder.GetLatestStateTableForNode[T](IIncrementalGeneratorNode`1 source)
   at Microsoft.CodeAnalysis.SourceOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GeneratorDriver.UpdateOutputs(ImmutableArray`1 outputNodes, IncrementalGeneratorOutputKind outputKind, Builder generatorRunStateBuilder, CancellationToken cancellationToken, Bui
lder driverStateBuilder)
   at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsCore(Compilation compilation, DiagnosticBag diagnosticsBag, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GeneratorDriver.RunGenerators(Compilation compilation, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(SolutionState solution, Compilation compilationWithoutGenerators, CompilationTrackerGeneratorInfo generatorInfo, Compil
ation compilationWithStaleGeneratedTrees, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildFinalStateFromInProgressStateAsync(SolutionState solution, InProgressState state, Compilation inProgressCompilation, CancellationToken canc
ellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.BuildCompilationInfoAsync(SolutionState solution, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(SolutionState solution, Boolean lockGate, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetSourceGeneratedDocumentStatesAsync(SolutionState solution, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.PopulateChangedAndAddedDocumentsAsync(Project oldProject, Project newProject, ArrayBuilder`1 changedOrAddedDocuments, CancellationToken cancellationT
oken)
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.EmitSolutionUpdateAsync(Solution solution, ActiveStatementSpanProvider solutionActiveStatementSpanProvider, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.DebuggingSession.EmitSolutionUpdateAsync(Solution solution, ActiveStatementSpanProvider activeStatementSpanProvider, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExternalAccess.Watch.Api.WatchHotReloadService.EmitSolutionUpdateAsync(Solution solution, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.CompilationHandler.TryHandleFileChange(DotNetWatchContext context, FileItem[] files, CancellationToken cancellationToken) in G:\source\repos\dotnet\sdk\src\BuiltInTools\
dotnet-watch\HotReload\CompilationHandler.cs:line 125
   at Microsoft.DotNet.Watcher.Tools.HotReload.TryHandleFileChange(DotNetWatchContext context, FileItem[] files, CancellationToken cancellationToken) in G:\source\repos\dotnet\sdk\src\BuiltInTools\dotnet-wa
tch\HotReload\HotReload.cs:line 46
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(DotNetWatchContext context, CancellationToken cancellationToken) in G:\source\repos\dotnet\sdk\src\BuiltInTools\dotnet-watch\HotReloadDotNetW
atcher.cs:line 184

This is happening in 
![image](https://user-images.githubusercontent.com/37334640/203367488-4c8ddb9a-2c7b-4224-89d4-4a6de56615fb.png)

I guess this is sorta similar to https://github.com/dotnet/roslyn/issues/54470

What can I do next? Try to manually build CodeServices and tinker with it?

@tmat @chsienki Any ideas why this might be happening?

**Comment by chsienki** [comment]
The `IndexOutOfRangeException` should now be fixed by https://github.com/dotnet/roslyn/pull/65223

**Comment by En3Tho** [comment]
@chsienki Thanks. Lines from that PR are missing in decompiled code. I guess I will have to wait until sdk's dependencies go up a little. This gives me some hope bringing back proper behavior.

**Comment by baronfel** [comment]
@tmat can your team take a look? Is hot reload simply incompatible with cross-language references?

**Comment by En3Tho** [comment]
@baronfel I may be wrong, but It seems like there is no proper workspace implemented for F#. That's why this error is appearing. The quirky way is to simply ignore F#-related errors. But maybe some kind of workspace shim can be used instead? Something like generic workspace that is suitable for all other projects?

If I do this workaround then everything is back to normal: C# supports hot reload and F# requires restart every time. And this is okay considering there is no F# hot reload support anyway.

**Comment by mrakgr** [comment]
@En3Tho Where should this workaround be put? I also wish for this issue to be resolved, as I am using F# projects along with Blazor.

**Comment by En3Tho** [comment]
@mrakgr Inside the code dotnet watch itself. This is the most annoying part. You have to donwload sdk repo and tinker with it manually.
