### ISSUE TITLE
Test failed in CI: Microsoft.DotNet.Cli.New.IntegrationTests.DotnetNewUpdateTests.DoesNotPrintUpdateInfoOnCreation_WhenLatestVersionIsInstalled

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#29006]
branch: release/7.0.1xx

https://dev.azure.com/dnceng-public/public/_build/results?buildId=78809&view=results

```
Microsoft.DotNet.Cli.New.IntegrationTests.DotnetNewUpdateTests.DoesNotPrintUpdateInfoOnCreation_WhenLatestVersionIsInstalled
The command output matched a pattern it should not have. Pattern: An update for template package 'Microsoft.DotNet.Common.ProjectTemplates.5.0::([\\d\\.a-z-])+' is available\n\nFile Name: /Users/runner/work/1/s/artifacts/bin/redist/Release/dotnet/dotnet\nArguments: new console --debug:custom-hive /Users/runner/work/1/s/artifacts/tmp/Release/dotnet-new.IntegrationTests/DoesNotPrintUpdateInfoOnCreation_WhenLatestVersionIsInstalled/Home/20221110044220496 --debug:disable-sdk-templates\nExit Code: 0\nStdOut:\nThe template \"Console App\" was created successfully.\n\nProcessing post-creation actions...\nRestoring /Users/runner/work/1/s/artifacts/tmp/Release/dotnet-new.IntegrationTests/DoesNotPrintUpdateInfoOnCreation_WhenLatestVersionIsInstalled/20221110044229530/20221110044229530.csproj:\n  Determining projects to restore...\n/Users/runner/work/1/s/artifacts/bin/redist/Release/dotnet/sdk/7.0.101-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'net5.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/runner/work/1/s/artifacts/tmp/Release/dotnet-new.IntegrationTests/DoesNotPrintUpdateInfoOnCreation_WhenLatestVersionIsInstalled/20221110044229530/20221110044229530.csproj]\n/Users/runner/work/1/s/artifacts/bin/redist/Release/dotnet/sdk/7.0.101-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'net5.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/runner/work/1/s/artifacts/tmp/Release/dotnet-new.IntegrationTests/DoesNotPrintUpdateInfoOnCreation_WhenLatestVersionIsInstalled/20221110044229530/20221110044229530.csproj]\n  Restored /Users/runner/work/1/s/artifacts/tmp/Release/dotnet-new.IntegrationTests/DoesNotPrintUpdateInfoOnCreation_WhenLatestVersionIsInstalled/20221110044229530/20221110044229530.csproj (in 288 ms).\nRestore succeeded.\n\n\nAn update for template package 'Microsoft.DotNet.Common.ProjectTemplates.5.0::6.0.100-rtm.21521.1' is available.\nTo update the package use:\n   dotnet new install Microsoft.DotNet.Common.ProjectTemplates.5.0::6.0.403\nStdErr:\n\n
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at Microsoft.NET.TestFramework.Assertions.CommandResultAssertions.NotHaveStdOutMatching(String pattern, RegexOptions options) in /_/src/Tests/Microsoft.NET.TestFramework/Assertions/CommandResultAssertions.cs:line 107
   at Microsoft.DotNet.Cli.New.IntegrationTests.DotnetNewUpdateTests.DoesNotPrintUpdateInfoOnCreation_WhenLatestVersionIsInstalled() in /Users/runner/work/1/s/src/Tests/dotnet-new.Tests/DotnetNewUpdateTests.cs:line 205
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
Output:
> /Users/runner/work/1/s/artifacts/bin/redist/Release/dotnet/dotnet new install Microsoft.DotNet.Common.ProjectTemplates.5.0 --debug:custom-hive /Users/runner/work/1/s/artifacts/tmp/Release/dotnet-new.IntegrationTests/DoesNotPrintUpdateInfoOnCreation_WhenLatestVersionIsInstalled/Home/20221110044220496 --debug:disable-sdk-templates
The following template packages will be installed:
   Microsoft.DotNet.Common.ProjectTemplates.5.0

Success: Microsoft.DotNet.Common.ProjectTemplates.5.0::6.0.100-rtm.21521.1 installed the following templates:
Template Name  Short Name  Language    Tags          
-------------  ----------  ----------  --------------
Class Library  classlib    [C#],F#,VB  Common/Library
Console App    console     [C#],F#,VB  Common/Console
> /Users/runner/work/1/s/artifacts/bin/redist/Release/dotnet/dotnet new console --debug:custom-hive /Users/runner/work/1/s/artifacts/tmp/Release/dotnet-new.IntegrationTests/DoesNotPrintUpdateInfoOnCreation_WhenLatestVersionIsInstalled/Home/20221110044220496 --debug:disable-sdk-templates
The template "Console App" was created successfully.

Processing post-creation actions...
Restoring /Users/runner/work/1/s/artifacts/tmp/Release/dotnet-new.IntegrationTests/DoesNotPrintUpdateInfoOnCreation_WhenLatestVersionIsInstalled/20221110044229530/20221110044229530.csproj:
  Determining projects to restore...
/Users/runner/work/1/s/artifacts/bin/redist/Release/dotnet/sdk/7.0.101-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'net5.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/runner/work/1/s/artifacts/tmp/Release/dotnet-new.IntegrationTests/DoesNotPrintUpdateInfoOnCreation_WhenLatestVersionIsInstalled/20221110044229530/20221110044229530.csproj]
/Users/runner/work/1/s/artifacts/bin/redist/Release/dotnet/sdk/7.0.101-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'net5.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/runner/work/1/s/artifacts/tmp/Release/dotnet-new.IntegrationTests/DoesNotPrintUpdateInfoOnCreation_WhenLatestVersionIsInstalled/20221110044229530/20221110044229530.csproj]
  Restored /Users/runner/work/1/s/artifacts/tmp/Release/dotnet-new.IntegrationTests/DoesNotPrintUpdateInfoOnCreation_WhenLatestVersionIsInstalled/20221110044229530/20221110044229530.csproj (in 288 ms).
Restore succeeded.


An update for template package 'Microsoft.DotNet.Common.ProjectTemplates.5.0::6.0.100-rtm.21521.1' is available.
To update the package use:
   dotnet new install Microsoft.DotNet.Common.ProjectTemplates.5.0::6.0.403
```

**Comment by marcpopMSFT** [comment]
@dotnet/templating-engine-maintainers to take a look.

**Comment by vlada-shubina** [comment]
@GangWang01 could you please take a look? thank you

**Comment by GangWang01** [comment]
It's not reproduced on my local Windows machine.

From directory path the test failed on macOS in CI.
By checking https://github.com/dotnet/sdk/blob/main/NuGet.config that is used by our tests, `6.0.100-rtm.21521.1` is the latest version in package source `dotnet6`, and `6.0.403` is the latest version in package source `dotnet-public`. Other sources don't have this package. It seems Nuget hit something wrong while pulling the the latest version. Such as connecting to source `dotnet-public` failed, then this issue happened.

Perhaps this is related to https://github.com/dotnet/sdk/issues/28801#issuecomment-1316828708.

**Comment by vlada-shubina** [comment]
Closing for now, we might want to reopen if the issue will reappear.
Also we drastically decreased number of tests thanks to snapshot testing now, so issues hopefully are less likely.

**Comment by tmat** [comment]
@vlada-shubina 

> . Setting up retries on all the tests that may touch external resources are not reasonable, and may not help.

Why do test touch external resources? Isn't it possible to configure NuGet in the test so that it only works against feed backed by local storage?

**Comment by vlada-shubina** [comment]
@tmat some of template packages used in tests are downloaded from external sources. In this example we need 6.0 templates, and they are only accessible in external feeds.

we can prepare local feed in theory but then the packages are downloaded when it's getting prepared and it just moves the issue to a different location. So far, we agreed not to take an action on it.

**Comment by tmat** [comment]
> we can prepare local feed in theory but then the packages are downloaded when it's getting prepared 

Yes, that's what I'd expect to happen. All external assets should be downloaded during `restore` phase of the build and then tests should be able to run offline.

**Comment by vlada-shubina** [comment]
> > we can prepare local feed in theory but then the packages are downloaded when it's getting prepared
> 
> Yes, that's what I'd expect to happen. All external assets should be downloaded during `restore` phase of the build and then the rest of the build, including tests should be able to run offline.

The template packages cannot be restored - they are not part of the any project.

**Comment by tmat** [comment]
If they are tests assets they are already checked into the repo or produced by the build, no? In that case the test harness could configure nuget to fetch them from the local directory for the test.
