### ISSUE TITLE
[release/7.0.2xx] System.NullReferenceException when running dotnet watch run

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/sdk#29085]
**Repro Steps**
1. Install 7.0.2xx build.  I'm running

  ```
  .NET SDK:
   Version:   7.0.200
   Commit:    1e1965db1f
  ```

2. mkdir temp
3. dotnet new console -o temp
4. cd temp
5. dotnet watch run

**Results**

```
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  temp -> /repos/temp/bin/Debug/net7.0/temp.dll
dotnet watch ❌ System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Cli.EnvironmentVariableNames.TryParseArchitecture(String runtimeIdentifier, Architecture& architecture)
   at Microsoft.DotNet.Cli.EnvironmentVariableNames.TryGetDotNetRootVariableNameImpl(String runtimeIdentifier, String defaultAppHostRuntimeIdentifier, Version targetFrameworkVersion, Architecture currentArchitecture, Boolean is64bit)
   at Microsoft.DotNet.Cli.EnvironmentVariableNames.TryGetDotNetRootVariableName(String runtimeIdentifier, String defaultAppHostRuntimeIdentifier, Version targetFrameworkVersion)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.ConfigureExecutable(DotNetWatchContext context, ProcessSpec processSpec)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(DotNetWatchContext context, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Program.MainInternalAsync(CommandLineOptions options, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Program.MainInternalAsync(CommandLineOptions options, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Program.HandleWatch(CommandLineOptions options)
dotnet watch ❌ An unexpected error occurred
```

**Notes:**
source-build unit tests caught this issue

**Comment by eerhardt** [comment]
cc @tmat - the code throwing an exception appears to be added in https://github.com/dotnet/sdk/commit/e250cd7ba1ca927d3048c294578f2ff71e8c531e

**Comment by eerhardt** [comment]
Was this fixed with https://github.com/dotnet/sdk/pull/29128?

**Comment by tmat** [comment]
Yes. Fixed by https://github.com/dotnet/sdk/pull/29128
