### ISSUE TITLE
"CreateAppHost" task failed unexpectedly

### ISSUE THREAD

**Issue by Zameer-codes** [dotnet/sdk#29188]
Error	MSB4018	The "CreateAppHost" task failed unexpectedly.
Microsoft.NET.HostModel.HResultException: 80070005
   at Microsoft.NET.HostModel.ResourceUpdater.ThrowExceptionForLastWin32Error()
   at Microsoft.NET.HostModel.ResourceUpdater.AddResourcesFromPEImage(String peFile)
   at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass2_0.<CreateAppHost>g__UpdateResources|1()
   at Microsoft.NET.HostModel.RetryUtil.RetryOnWin32Error(Action func)
   at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom, Boolean enableMacOSCodeSign)
   at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ApiPayroll	C:\Program Files\dotnet\sdk\6.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	554

**Comment by marcpopMSFT** [comment]
didn't notice the host label. unassigning to leave for @vitek-karas and @elinor-fung

**Comment by vitek-karas** [comment]
@Zameer-codes would it be possible to get a repro project?
What command line command did you run? (or was it from VS?)
Anything special about project/app?

Unfortunately the error code is just the most general "Failed", so it's really hard to tell what's going on here.
