### ISSUE TITLE
Forms dll not found when using Forms in a dependent DLL referenced by a project without Microsoft.NET.Sdk.WindowsDesktop

### ISSUE THREAD

**Issue by bitbonk** [dotnet/sdk#2921]
We have some .NET Core applications that reference 3rd party assemblies (initially made for .NET Classic) that occasionally open a custom message box and therefore references Windows Forms.

Now that .NET Core 3.0 supports Windows Forms we can finally use those assemblies in .NET Core applications who themselves do not use Windows Forms at all.

However currently (SDK 3.0.100-preview-010184), the main application csproj that references this 3rd party assembly must be set to `<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">` event though it is just a simple console app and has no knowledge of the fact that one of its dependencies uses windows forms. If I do not set the SDK as above, I get the following exception: 

> System.IO.FileNotFoundException
>   HResult=0x80070002
>   Message=Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
>   Source=winformslib
>   StackTrace:
>    at winforms.PublicApi.Show() in C:\temp\winforms\winformslib\Form1.cs:line 32
>    at app.Program.Main(String[] args) in C:\temp\winforms\app\Program.cs:line 11

Here is the code that can be used to reproduce the issue:

*app.csproj*
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\winformslib\winformslib.csproj" />
  </ItemGroup>

</Project>
```

*Program.cs*
```
using System;
using winforms;

namespace app
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("I will now open a windos form");
            PublicApi.Show();
            Console.WriteLine("It should be open now");
            Console.ReadLine();
        }
    }
}
```

*winformslib.csproj*
```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
```

*Form1.cs*
```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace winforms
{
    internal partial class Form1 : Form
    {
        public Form1()
        {
            this.InitializeComponent();
        }

        private void buttonExit_Click(object sender, EventArgs e)
        {
            Application.Exit();
        }
    }

    public static class PublicApi
    {
        public static void Show()
        {
            var form = new Form1();
            form.Show();
        }

    }

}
```

**Comment by livarcocc** [comment]
I believe you need to add a FrameworkReference to Microsoft.WindowsDesktop.App, without it you are missing references like the one above. There is no way for us to transitively find dependencies of a reference assembly like that. You need to tell us which framework you want to use.

When you use the Microsoft.NET.Sdk.WindowsDesktop that is done implicitly for you.

Please try that out and let us know.

**Comment by livarcocc** [comment]
Actually, I see now your repro setup. Yeah, flowing transitive FrameworkReferences is something that we are still working on. Something we will do for 3.0 RTM but is not available in any of the previews or nightlies yet.

My suggestion above should still work for you.

Other than that, @dsplaisted can you link to the issue we have tracking adding transitive framework references and close this one as a dup?

**Comment by livarcocc** [comment]
Didn't mean to close it, I want @dsplaisted to close once he links to the other issue.

**Comment by bitbonk** [comment]
> I believe you need to add a FrameworkReference to Microsoft.WindowsDesktop.App, without it you are missing references like the one above. There is no way for us to transitively find dependencies of a reference assembly like that. You need to tell us which framework you want to use.

The problem with this is that `winformslib.dll` is actually a 3rd party dependency somewhere deep down in our dependency graph and we don‘t really know that it it depended on Windows Forms until at some point it tried to open a messagebox (which resulted in the above exception). 

That assembly was built for .NET Classic where Windows Forms will *always* be present. So it just worked. 

I was hoping that there would be some tooling to discover such „hidden“ dependencies.

**Comment by bitbonk** [comment]
Also: I could be loading `winformslib.dll` dynamically via reflection. If we are on .NET Core 3 and on Windows, ideally it should just work.

**Comment by dsplaisted** [comment]
https://github.com/dotnet/cli/issues/10666 is the issue that Livar was referring to.

However, it doesn't cover the case when you are referencing a .NET Framework DLL or NuGet package that doesn't have a FrameworkReference to Microsoft.WindowsDesktop.App.

**Comment by Meccuz** [comment]
Do you have any news on this issue?
Thank you.

**Comment by dsplaisted** [comment]
If you have a dependency coming in via a NuGet package reference or a project reference that targets .NET Core and uses Windows Forms, then the dependency on Windows Forms should flow to your app and it should just work.

If you depend on a .NET Framework library that depends on Windows Forms, then it doesn't express that dependency in the same way, and you will have to explicitly refer to Windows Forms in your main app.  We don't currently plan to change this.
