### ISSUE TITLE
CI test failure: Microsoft.DotNet.Cli.New.IntegrationTests.CommonTemplatesTests.AllCommonItemsCreate

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#29259]
The test failed in CI:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=95483&view=ms.vss-test-web.build-test-results-tab&runId=2017988&resultId=100007&paneView=debug

```
Microsoft.DotNet.Cli.New.IntegrationTests.CommonTemplatesTests.AllCommonItemsCreate(expectedTemplateName: \"global.json file\", templateShortName: \"globaljson\", args: null)
```

```
System.ArgumentNullException : Value cannot be null. (Parameter 'directory')
```

Stack trace
```
   at Guard.AgainstEmpty(String value, String argumentName) in /_/src/Verify/Guard.cs:line 108
   at Guard.BadDirectoryName(String name, String argumentName) in /_/src/Verify/Guard.cs:line 59
   at VerifyTests.PathInfo..ctor(String directory, String typeName, String methodName) in /_/src/Verify/DerivePaths/PathInfo.cs:line 15
   at VerifyXunit.Verifier.<>c.<.cctor>b__37_0(String sourceFile, String projectDirectory, Type type, MethodInfo method) in /_/src/Verify.Xunit/DerivePaths/VerifierSettings.cs:line 10
   at VerifyXunit.Verifier.GetPathInfo(String sourceFile, Type type, MethodInfo method) in /_/src/Verify.Xunit/DerivePaths/VerifierSettings.cs:line 18
   at VerifyXunit.Verifier.GetVerifier(VerifySettings settings, String sourceFile, Boolean useUniqueDirectory) in /_/src/Verify.Xunit/Verifier.cs:line 23
   at VerifyXunit.Verifier.<>c__DisplayClass6_0.<<Verify>b__0>d.MoveNext() in /_/src/Verify.Xunit/Verifier.cs:line 63
--- End of stack trace from previous location ---
   at Microsoft.TemplateEngine.Authoring.TemplateVerifier.VerificationEngine.VerifyResult(TemplateVerifierOptions args, CommandResultData commandResultData, String callerDir, String callerMethodName)
   at Microsoft.TemplateEngine.Authoring.TemplateVerifier.VerificationEngine.Execute(IOptions`1 optionsAccessor, CancellationToken cancellationToken, String sourceFile, String callerMethod)
   at Microsoft.DotNet.Cli.New.IntegrationTests.CommonTemplatesTests.AllCommonItemsCreate(String expectedTemplateName, String templateShortName, String[] args) in /Users/runner/work/1/s/src/Tests/dotnet-new.Tests/CommonTemplatesTests.cs:line 93
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
```

**Comment by vlada-shubina** [comment]
https://github.com/dotnet/sdk/pull/29353 should fix it.
