### ISSUE TITLE
CI test failure: Microsoft.DotNet.Cli.SdkCheck.Tests.GivenDotnetSdkCheck.WhenABundleIsOutOfSupportItPrintsWarning

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#29382]
`Microsoft.DotNet.Cli.SdkCheck.Tests.GivenDotnetSdkCheck.WhenABundleIsOutOfSupportItPrintsWarning(sdkVersions: [\"1.0.10\", \"1.0.9\", \"2.0.308\", \"2.1.804\", \"3.0.309\", ...], runtimeVersions: [], outOfSupportVersions: [\"1.0.10\", \"1.0.9\", \"2.0.308\", \"2.1.804\"])` failed in

https://dev.azure.com/dnceng-public/public/_build/results?buildId=100792&view=ms.vss-test-web.build-test-results-tab&runId=2158178&resultId=102434&paneView=debug

Error message
```
Did not expect string ".NET SDKs: Version      Status                                 --------------------------------------------------- 1.0.9        .NET 1.0 is out of support.            1.0.10       .NET 1.0 is out of support.            2.0.308      .NET 2.0 is out of support.            2.1.804      .NET 2.1 is out of support.            3.0.309      .NET 3.0 is going out of support soon. 3.1.401      .NET 3.1 is out of support.             Try out the newest .NET SDK features with .NET 5.0.100.  .NET Runtimes: Name      Version      Status -----------------------------   The latest versions of .NET can be installed from https://aka.ms/dotnet-core-download. For more information about .NET lifecycles, see https://aka.ms/dotnet-core-support. " to contain ".NET 3.1 is out of support.".
```

Stack trace
```
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.StringAssertions`1.NotContain(String unexpected, String because, Object[] becauseArgs)
   at Microsoft.DotNet.Cli.SdkCheck.Tests.GivenDotnetSdkCheck.WhenABundleIsOutOfSupportItPrintsWarning(String[] sdkVersions, String[] runtimeVersions, String[] outOfSupportVersions) in /_/src/Tests/dotnet-sdk-check.Tests/GivenDotnetSdkCheck.cs:line 159
   at InvokeStub_GivenDotnetSdkCheck.WhenABundleIsOutOfSupportItPrintsWarning(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by joeloff** [comment]
I'm investigating the failures. It's like related to recent changes in the release JSON data

**Comment by tmat** [comment]
@joeloff Can we skip the test while you're working on the fix to unblock other PRs? See https://github.com/dotnet/sdk/pull/29383

**Comment by tmat** [comment]
@joeloff BTW, how did the change in the JSON data get it while the test has been failing?

**Comment by joeloff** [comment]
The static copy we used for the tests show that 3.1 goes out of support on 12/3/2022, so that triggered additional EOL values. 

Agree, there's quite a few PRs backed up. I approved and merged 29383.

**Comment by marcpopMSFT** [comment]
I assume this affects all versions that have the sdk check feature so most of them.

**Comment by joeloff** [comment]
Yup, there are a number of issues. The release data is old and needs to be updated to account for the new changes we made a few weeks back. The tests though were failing because it listed 12/3 as the EOL date. That caused the tests to fail because the command doesn't offer latest patches for EOL versions. The date is technically wrong because it was moved to 12/13, but it would still trigger.

The impact of it should not be too bad. While the LTS support phase was removed, we have no checks using that. Still, the old releases library may fail to correctly parse the updated format so we should get it fixed. My workaround in 7.0.2xx was to simply set the EOL date to `null` so that it never considers it to be out of support for the test case.
