### ISSUE TITLE
Test failed in CI: Microsoft.NET.Build.Tests.GlobalPropertyFlowTests.TestGlobalPropertyFlowInSolution

### ISSUE THREAD

**Issue by tmat** [dotnet/sdk#29478]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=107768&view=ms.vss-test-web.build-test-results-tab&runId=2298146&resultId=102721&paneView=debug

OS: Ubuntu

 System.IO.IOException: The process cannot access the file '/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/bin/Debug/net7.0/ReferencedProject.deps.json' because it is being used by another process.

```
Error message
Expected command to pass but it did not.
File Name: /root/helix/work/correlation/d/dotnet
Arguments: build --self-contained
Exit Code: 1
StdOut:
MSBuild version 17.5.0-preview-22608-02+c81f58b45 for .NET
Determining projects to restore...
Restored /root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/TestProject/TestProject.csproj (in 186 ms).
Restored /root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj (in 187 ms).
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(275,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(275,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/TestProject/TestProject.csproj]
ReferencedProject -> /root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/bin/Debug/net7.0/ReferencedProject.dll
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018: System.IO.IOException: The process cannot access the file '/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/bin/Debug/net7.0/ReferencedProject.deps.json' because it is being used by another process. [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions) [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func4 createOpenException) [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj] /root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018: at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable1 unixCreateMode) [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at System.IO.File.Create(String path) [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath) in //src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs:line 253 [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore() in //src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs:line 262 [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() in /_/src/Tasks/Common/TaskBase.cs:line 43 [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]

Build FAILED.

/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018: System.IO.IOException: The process cannot access the file '/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/bin/Debug/net7.0/ReferencedProject.deps.json' because it is being used by another process. [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions) [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func4 createOpenException) [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj] /root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018: at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable1 unixCreateMode) [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at System.IO.File.Create(String path) [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath) in //src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs:line 253 [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore() in //src/Tasks/Microsoft.NET.Build.Tasks/GenerateDepsFile.cs:line 262 [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() in /_/src/Tasks/Common/TaskBase.cs:line 43 [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
/root/helix/work/correlation/d/sdk/8.0.100-ci/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(197,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/root/helix/work/workitem/e/testExecutionDirectory/TestGlobalPro---C1827734/ReferencedProject/ReferencedProject.csproj]
0 Warning(s)
1 Error(s)
```

Stack trace
```
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at Microsoft.NET.TestFramework.Assertions.CommandResultAssertions.Pass() in /_/src/Tests/Microsoft.NET.TestFramework/Assertions/CommandResultAssertions.cs:line 33
   at Microsoft.NET.Build.Tests.GlobalPropertyFlowTests.TestGlobalPropertyFlowInSolution(Boolean passSelfContained, Boolean passRuntimeIdentifier) in /_/src/Tests/Microsoft.NET.Build.Tests/GlobalPropertyFlowTests.cs:line 243
   at InvokeStub_GlobalPropertyFlowTests.TestGlobalPropertyFlowInSolution(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by marcpopMSFT** [comment]
#28442

**Comment by marcpopMSFT** [comment]
it looks like our flow of self-contained breaks parallel builds of solutions. Have not decided on a path forward for fixing this.
