### ISSUE TITLE
"MSB4018 ResolveTargetingPackAssets task failed unexpectedly" after updating to 7.0.100

### ISSUE THREAD

**Issue by sigurdhj** [dotnet/sdk#29517]
### Describe the bug
Updated dotnet via dnf (ms repo) this morning and I cannot build any of my projects anymore.

Error:
```
  Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(376, 5): [MSB4018] The "ResolveTargetingPackAssets" task failed unexpectedly.
System.IO.FileNotFoundException: Could not find file '/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.0/data/FrameworkList.xml'.
File name: '/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/7.0.0/data/FrameworkList.xml'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Microsoft.NET.Build.Tasks.ResolveTargetingPackAssets.AddItemsFromFrameworkList(FrameworkListDefinition definition, IBuildEngine4 buildEngine4, List`1 referenceItems, List`1 analyzerItems)
   at Microsoft.NET.Build.Tasks.ResolveTargetingPackAssets.Resolve(StronglyTypedInputs inputs, IBuildEngine4 buildEngine)
   at Microsoft.NET.Build.Tasks.ResolveTargetingPackAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

The folder /usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/***7.0.0*** does not exist, /usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/***7.0.1*** does exist.

### Exceptions (if any)
Able to build my projects.

### Further technical details
dotnet --info output:
```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     fedora
 OS Version:  37
 OS Platform: Linux
 RID:         fedora.37-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.100/

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by sigurdhj** [comment]
Saw you just released new packages for aspnetcore-runtime-7.0, dotnet-runtime-7.0 and dotnet-sdk-7.0 and everything is now working again. :thumbsup:
