### ISSUE TITLE
[NETSDKE2E][Intermittent]With NET8 preview 1 SDK installed, "Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object." happens when installing Andriod workload in CLI

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#30545]
Repro steps:

1.Install .NET 8 SDK ( 8.0.100-preview.1.23108.10) from main branch of https://github.com/dotnet/installer
2.Install workload in CLI
dotnet workload install android --skip-manifest-update

Expected Result:
 Android workload Install successfully and the output shows correctly.

Actual Result:
**Install Android workload successfully, but below message displayed.**

![image](https://user-images.githubusercontent.com/65637796/218363308-0faff7f8-c0d0-440f-b5dc-6e48f071dd9c.png)

Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Collections.Concurrent.BlockingCollection`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
   at Microsoft.DotNet.Installer.Windows.TimestampedFileLogger.WriteMessage(String message)
   at Microsoft.DotNet.Installer.Windows.TimestampedFileLogger.ProcessLogRequests(Object logPipeName)

[install log in temp folder.zip](https://github.com/dotnet/sdk/files/10718342/install.log.in.temp.folder.zip)
dotnet --info:
.NET SDK:
 Version:   8.0.100-preview.1.23108.10
 Commit:    5725657a6b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.1.23108.10\

Host:
  Version:      8.0.0-preview.1.23106.5
  Architecture: x64
  Commit:       9f654effb1

.NET SDKs installed:
  8.0.100-preview.1.23108.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.0-preview.1.23107.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.0-preview.1.23106.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.1.23107.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:

  https://aka.ms/dotnet/download

**Comment by dsplaisted** [comment]
@joeloff Looks like TimestampedFileLogger is trying to log after it's been disposed.  Not sure what's going on, I didn't see anything that might have changed with this recently.

**Comment by joeloff** [comment]
I'll take a look.

**Comment by vdanche** [comment]
We met it again in NET8 preview 2(8.0.100-preview.2.23151.8)
![image](https://user-images.githubusercontent.com/65637796/222640508-b4d8f731-0822-4a79-92e0-e072db03f736.png)

**Comment by joeloff** [comment]
Hmm, this is definitely some sort of race condition.

**Comment by v-ainigao** [comment]
Also repro on .net8.0.100-preview.4.23206.10 (runtime-8.0.0-preview.4.23181.2) SDK 
![image](https://user-images.githubusercontent.com/106054229/230567812-ba412b57-bd9d-4374-ab81-a549b2231ee9.png)

**Comment by vdanche** [comment]
Also met it on net8 preview 5 SDK
![image](https://github.com/dotnet/sdk/assets/65637796/746b9d3c-3ad2-4491-8b4c-fbb315d2b076)

**Comment by WenJunJi01** [comment]
We met this issue with .NET 8 RC1 SDK: 8.0.100-rc.1.23423.3 (runtime-8.0.0-rc.1.23419.4) installed on Windows Server 2022(ARM64).
![image](https://github.com/dotnet/sdk/assets/87680983/2ee6e073-4a2a-40fb-b87a-33119a5a2d58)

**Comment by v-ainigao** [comment]
We met this issue with .NET 8.0.100 SDK installed on Windows Server 2022(ARM64).
![image](https://github.com/dotnet/sdk/assets/106054229/94c011a6-a081-4570-815b-0a9c48c9ce9c)

**Comment by WenJunJi01** [comment]
Repro with .NET SDK 9.0.100-alpha.1.23564.26 (runtime-9.0.0-alpha.1.23558.17) installed.
![image](https://github.com/dotnet/sdk/assets/87680983/7bbf24ef-3936-4e3f-a3bd-743799b6eef9)

**Comment by v-ainigao** [comment]
We met this issue with .NET 9.0.100-alpha.1.23618.4(runtime-9.0.0-alpha.1.23617.4) SDK installed on ARM64 OS.
![image](https://github.com/dotnet/sdk/assets/106054229/be4aeba9-56cd-41ae-9396-44326f2524d3)

**Comment by vdanche** [comment]
Also meet it on 6.0.425
![image](https://github.com/user-attachments/assets/a0e9f1e1-be28-4ea2-b41e-fd1151b9ab2e)

**Comment by KirillOsenkov** [comment]
Just ran into this too:
```
Removing Microsoft.NETCore.App.Runtime.Mono.maccatalyst-x64.Msi.x64 .......... Done
Removing Microsoft.NETCore.App.Runtime.Mono.maccatalyst-x64.Msi.x64 .......... Done

Successfully installed workload(s) tvos wasm-tools.

Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Collections.Concurrent.BlockingCollection`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
   at Microsoft.DotNet.Installer.Windows.TimestampedFileLogger.WriteMessage(String message)
   at Microsoft.DotNet.Installer.Windows.TimestampedFileLogger.ProcessLogRequests(Object logPipeName)
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Collections.Concurrent.BlockingCollection`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
   at Microsoft.DotNet.Installer.Windows.SetupLoggerBase.LogMessage(String message)
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.CompletionCallback(Object waitHandleContext, Boolean wasSignaled)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.PortableThreadPool.CompleteWait(RegisteredWaitHandle handle, Boolean timedOut)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by KirillOsenkov** [comment]
@marcpopMSFT @joeloff any chance we could prioritize this?

**Comment by marcpopMSFT** [comment]
@KirillOsenkov this is a pretty old issue and before you, all the reports were from vendor testing. What version of the SDK are you seeing it in and does it happen every time?

**Comment by KirillOsenkov** [comment]
I had versions 9 and 10 installed, installing SDK 8 today had this issue. I haven't tried it again because I was busy with other stuff.

Looking at the callstack the fix should be pretty straightforward. My gut feeling is that a ton of people are seeing this, but nobody bothers to report it, as the workloads end up installing fine. It just crashes at the very end when it tries to log after the logger has been disposed.

**Comment by marcpopMSFT** [comment]
Fixed by #53241
