### ISSUE TITLE
ValueFactory attempted to access the Value property of this instance

### ISSUE THREAD

**Issue by kemsky** [dotnet/sdk#31048]
### Describe the bug
The code below throws:

_System.InvalidOperationException : ValueFactory attempted to access the Value property of this instance._

This is obviously not true, looks like some concurrency issue.
 
### To Reproduce
```csharp
    [Test]
    public async Task Test()
    {
        var innerLazy = new Lazy<string>(() =>
        {
            // simulate some heavy operation
            Thread.Sleep(10);
            return "lazy";
        }, LazyThreadSafetyMode.None);

        var outerLazy = new Lazy<string>(() => innerLazy.Value, LazyThreadSafetyMode.PublicationOnly);

        var task1 = new Task<string>(() => outerLazy.Value);
        task1.Start();
        var task2 = new Task<string>(() => outerLazy.Value);
        task2.Start();

        await Task.WhenAll(task1, task2);

        Assert.That(outerLazy.Value, Is.EqualTo("lazy"));
    }
```

### Exceptions (if any)
```
System.InvalidOperationException : ValueFactory attempted to access the Value property of this instance.
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.CreateValue()
   at Test.<>c__DisplayClass0_0.<Test>b__1() in Test.cs:line 19
   at System.Lazy`1.CreateValue()
```

### Further technical details

```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /home//.dotnet/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  3.1.422 [/home//.dotnet/sdk]
  6.0.400 [/home//.dotnet/sdk]
  7.0.100 [/home//.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.28 [/home//.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [/home//.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/home//.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [/home//.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [/home//.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/home//.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home//.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

```

**Comment by nagilson** [comment]
@marcpopMSFT  Shall we move this to the runtime?
