### ISSUE TITLE
System.Buffers, System.Runtime.CompilerServices.Unsafe, etc cannot be loaded

### ISSUE THREAD

**Issue by jstedfast** [dotnet/sdk#31147]
### Describe the bug
I keep getting reports of my [MimeKit](https://github.com/jstedfast/MimeKit) and [MailKit](https://github.com/jstedfast/MailKit) libraries throwing Exceptions trying to load System.Buffers and System.Runtime.CompilerServices.Unsafe.

Some examples:
* System.Runtime.CompilerServices.Unsafe
  * https://github.com/jstedfast/MimeKit/issues/872
  * https://github.com/jstedfast/MailKit/issues/1495
  * https://github.com/jstedfast/MailKit/issues/1462
* System.Buffers:
  * https://github.com/jstedfast/MailKit/issues/1524

### To Reproduce

Apparently it's enough to add the MimeKit nuget package to a project and then create a new MimeMessage:

```
Install-Package MimeKit
```

```csharp
void Main()
{
    var message = new MimeKit.MimeMessage ();
}
```

We may close this issue if:
- the repro project you share with us is complex. We can't investigate custom projects, so don't point us to such, please.
- if we will not be able to repro the behavior you're reporting
-->

### Exceptions (if any)
```
System.IO.FileLoadException
HResult=0x80131040
Message=Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Source=System.Memory
StackTrace:
at System.Span`1..ctor(T[] array)
at MimeKit.Utils.ValueStringBuilder..ctor(Int32 initialCapacity)
at MimeKit.Utils.Rfc2047.Encode(FormatOptions options, Encoding charset, String text, Boolean phrase)
at MimeKit.Header.EncodeUnstructuredHeader(ParserOptions options, FormatOptions format, Encoding encoding, String field, String value)
at MimeKit.Header.EncodeAddressHeader(ParserOptions options, FormatOptions format, Encoding encoding, String field, String value)
at MimeKit.Header.FormatRawValue(FormatOptions format, Encoding encoding, String value)
at MimeKit.Header.SetValue(FormatOptions format, Encoding encoding, String value)
at MimeKit.Header..ctor(Encoding encoding, HeaderId id, String value)
at MimeKit.HeaderList.set_Item(HeaderId id, String value)
at MimeKit.MimeMessage..ctor()
at SharpLibTestApp.MailKitForm.button1_Click(Object sender, EventArgs e) in C:\Users\Jamal\Documents\Visual Studio 2022\Projects\SharpLib\SharpLibTestApp\MailKitForm.cs:line 75
at System.Windows.Forms.Control.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Message& m)
at System.Windows.Forms.ButtonBase.WndProc(Message& m)
at System.Windows.Forms.Button.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
at LimoWizCSharpLibTestApp.Program.Main() in C:\Users\Jamal\Documents\Visual Studio 2022\Projects\SharpLib\CSharpLibTestApp\Program.cs:line 25
```

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by joperezr** [comment]
Our guidance for end applications is usually to use PackageReference if they are not in order to have RAR be able to see transitive dependencies, and to make sure they have auto-binding redirects turned on (which are by default). I suppose main issue here is that IN the case of MimeKit and MailKit they are libraries, not end applications, which don't have binding redirects on by default. One advise that could help would be to a) cross-compile for a .NET Framework TFM in case they are currently only targeting .NET Standard, and B) turn on generation of binding redirects for the library project and pack the .dll.config with the NuGet package.

**Comment by joperezr** [comment]
You are right in that .NET Framework doesn't read the .dll.config by default, it would be up-to the host process loading the assemblies to do so. That said, most applications models will do so automatically (as the loader is the one in charge of lazy loading the assemblies), and so will most of the test runners (which usually Load the assembly into an appdomain but most do make sure that they read a config file if there is one) as well.

**Comment by jstedfast** [comment]
I've added `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>` to my .csproj but it doesn't seem to generate any \*.dll.config files.

**Comment by marcpopMSFT** [comment]
Old issue triage: It looks like mimekit updated it's dependencies since this was filed and likely the issue has gone away so closing.
