### ISSUE TITLE
dotnet compiler crashes when compiling inside a sandbox

### ISSUE THREAD

**Issue by JoelNiemela** [dotnet/sdk#31668]
### Describe the bug
The compiler crashes without a helpful error message when running inside a Linux control-groups-based sandbox (specifically, [isolate](https://github.com/ioi/isolate)).

### To Reproduce
- Install `dotnet` to `/opt/dotnet` (Further setup might be required; I honestly don't remember all the hoops I had to jump through to get .NET working properly.)
- Run:
```sh
sudo /usr/local/bin/isolate --processes=128 \
	--env=HOME=/ --env=PATH --env=DOTNET_CLI_HOME=/opt/dotnet --env=DOTNET_CLI_TELEMETRY_OPTOUT=1 \
	--dir=/proc --dir=/src=/home/joel-niemela/test:rw:noexec \
	--dir=/opt/dotnet --dir='/.local'='/opt/dotnet/.local' \
	--run -- /opt/dotnet/dotnet build --no-restore -p:TargetFramework=net6.0 -p:OutputType=Exe
```

### Exceptions
```
Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Cli.Utils.Muxer..ctor()
   at Microsoft.DotNet.Cli.Utils.MSBuildForwardingAppWithoutLogging..ctor(IEnumerable`1 argsToForward, String msbuildPath)
   at Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingApp..ctor(IEnumerable`1 argsToForward, String msbuildPath)
   at Microsoft.DotNet.Tools.RestoringCommand..ctor(IEnumerable`1 msbuildArgs, Boolean noRestore, String msbuildPath, String userProfileDir, Boolean advertiseWorkloadUpdates)
   at Microsoft.DotNet.Tools.Build.BuildCommand.FromParseResult(ParseResult parseResult, String msbuildPath)
   at Microsoft.DotNet.Tools.Build.BuildCommand.Run(ParseResult parseResult)
   at Microsoft.DotNet.Cli.ParseResultCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
   ```

### Further technical details
```
$ dotnet --info     
.NET SDK (reflecting any global.json):
 Version:   6.0.113
 Commit:    4a23b50f97

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/6.0.113/

global.json file:
  Not found

Host:
  Version:      6.0.13
  Architecture: x64
  Commit:       1af80ba017

.NET SDKs installed:
  6.0.113 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.13 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

I'm _not_ using an IDE.

**Comment by baronfel** [comment]
Is there an easy way to set this up reliably? We probably expect
* read access to all of the dotnet install location
* write access to parts of /tmp and the user's home directory
* write access to the existing project directory and all directories underneath it
* read access from the entrypoint directory all the way up the file system heirarchy to the root

**Comment by tmds** [comment]
This issue was fixed in .NET 8. It should be reproducible with .NET 6 in an environment where the proc and pid namespaces don't match (`sudo unshare -p --fork /bin/sh.`).

**Comment by marcpopMSFT** [comment]
Old issue triage: Closing per comment that this was fixed in net8.
