### ISSUE TITLE
XML is not being published through the Docker container

### ISSUE THREAD

**Issue by RiteshKo** [dotnet/sdk#3175]
I am running a .net core 2.1 application through Docker ToolBox and Kitematic. I am new to the Docker world. In the application, I am loading an XML file in the application like below:

XDocument xmlFile = XDocument.Load(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "XML\\Lookup.xml"));

My Docker file is: 

FROM microsoft/dotnet:2.1-runtime

WORKDIR /app
COPY . /app

ENTRYPOINT ["dotnet", "ConsoleApp.dll"]

An image got created for this application but while running the same image through Kitematic I am getting below error:

Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/app/XML\ObjectInfoLookup.xml'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)

Can anyone help me here?

**Comment by livarcocc** [comment]
I don't believe this is an issue with .net core nor the SDK but rather with your kitematic setup. Unfortunately, I am not really familiar with it.

I suggest you find some Kitematic docs to learn how to setup your container.
