### ISSUE TITLE
Self contained Publish of .Net Core 3 app for win-x86 is missing files

### ISSUE THREAD

**Issue by MSLukeWest** [dotnet/sdk#3210]
1. Create a .NET Core 3 WPF app
2. Publish to folder, change "Deployment Mode" to "Self-Contained" and "Target Runtime" to "win-x86"
3. Copy the created folder to a completely clean win10 machine (no VS or anything else installed)
4. Attempt to run the app

Result: It immediately crashes.  Here's the exception from the event log (full stack below):

Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.Marshal' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

When I debug this app on a machine with VS installed (where it works) I see two loaded assemblies that aren't present on the clean machine:

Windows\SysWOW64\msvcp140.dll
Windows\SysWOW64\vcruntime140.dll

I'm guessing the vc runtime is required, if so these assemblies should be copied to the package folder when doing self-contained publishing.

Full exception stack:

Application: WpfApp23.exe
CoreCLR Version: 4.6.27622.75
.NET Core Version: 3.0.0-preview5-27626-15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.Marshal' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at ___CxxCallUnwindDtor(IntPtr pDtor, Void* pThis)
   at .cctor()
   --- End of inner exception stack trace ---
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.UIElement.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at WpfApp23.App.Main()

**Comment by peterhuene** [comment]
cc @dotnet/wpf-developers

@nguerrera believes this to be a known issue regarding a dependency on the VC++ redist that is actively being worked on.

I wanted to confirm before duping this (do we have an existing issue for this we're tracking?).

**Comment by nguerrera** [comment]
Now that I look closer, the stack trace looks different. I know there was an issue tracking the VC lib dependency, but it's not clear to me how that would have anything to do with the Marshal type failing to load.

**Comment by nguerrera** [comment]
Hmm, nevermind, the top frame is in WPF calling into ___CxxCallUnwindDtor. I guess this is the missing VC lib dependency.

**Comment by vatsan-madhavan** [comment]
This is not a missing VC lib dependency. This is due to a C++ compiler bug. 

https://github.com/dotnet/wpf/issues/634

**Comment by peterhuene** [comment]
@MSLukeWest Thanks for filing this issue.  As the problem is with the native dependencies of WPF and not with the publishing feature of the .NET Core SDK, I'm going to close this as a dupe of the above WPF bug.

**Comment by vatsan-madhavan** [comment]
@miguep - Can we look into how we can catch these proactively in our testing? 

/cc @rladuca
