### ISSUE TITLE
Regression using dotnet format when upgrading from 7.0.203 to 7.0.302

### ISSUE THREAD

**Issue by adam-knights** [dotnet/sdk#32598]
### Describe the bug
Running `dotnet format` or `dotnet format --verify-no-changes` on a plain webapi c# generated dotnet project errors on 7.0.302 with:

Unhandled exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFinderHelpers.<>c.<LoadAnalyzersAndFixers>b__0_0(Assembly assembly)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFinderHelpers.LoadAnalyzersAndFixers(IEnumerable`1 assemblies)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerReferenceInformationProvider.GetAnalyzersAndFixers(Project project)
   at System.Collections.Immutable.ImmutableDictionary.<>c__DisplayClass9_0`3.<ToImmutableDictionary>b__0(TSource element)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 keyComparer, IEqualityComparer`1 valueComparer)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerReferenceInformationProvider.GetAnalyzersAndFixers(Solution solution, FormatOptions formatOptions, ILogger logger)
   at Microsoft.CodeAnalysis.Tools.Analyzers.AnalyzerFormatter.FormatAsync(Solution solution, ImmutableArray`1 formattableDocuments, FormatOptions formatOptions, ILogger logger, List`1 formattedFiles, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.RunCodeFormattersAsync(Solution solution, ImmutableArray`1 formattableDocuments, FormatOptions formatOptions, ILogger logger, List`1 formattedFiles, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, String binaryLogPath)
   at Microsoft.CodeAnalysis.Tools.FormatCommandCommon.FormatAsync(FormatOptions formatOptions, ILogger`1 logger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.Commands.RootFormatCommand.FormatCommandDefaultHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__4_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'Microsoft.CodeAnalysis, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'Microsoft.CodeAnalysis, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Microsoft.CodeAnalysis.DefaultAnalyzerAssemblyLoader.DirectoryLoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'Microsoft.CodeAnalysis, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

File name: 'Microsoft.CodeAnalysis, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Microsoft.CodeAnalysis.DefaultAnalyzerAssemblyLoader.DirectoryLoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)

I have verified this happening on both linux and Mac (M1, arm64). The same project with 7.0.203 works.

### To Reproduce
1. Run `dotnet new webapi`
2. Add the following `global.json` to the root
`{
  "sdk": {
    "version": "7.0.203",
    "rollForward": "major",
    "allowPrerelease": false
  }
}`
3. Run `dotnet format`, observe it works
4. Adjust `global.json` to `7.0.302`
5. Run `dotnet format`, observe the error above

Reproduced on Mac arm64 and linux.

### Exceptions (if any)
See full exception of `Unhandled exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.` above

### Further technical details
- Include the output of `dotnet --info`:

`.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.302/

Host:
  Version:      7.0.5
  Architecture: arm64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.408 [/usr/local/share/dotnet/sdk]
  8.0.203 [/usr/local/share/dotnet/sdk]
  7.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /Users/adam.knights/testregs/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download`

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:
Running `dotnet format` in the terminal

**Comment by Shane32** [comment]
I'm experiencing the same issue in a GitHub Actions runner.  See script below.  Worked fine with 7.0.203.

```yml
name: Check formatting

on:
  pull_request:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Use .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Check formatting
        run: dotnet format --no-restore --verify-no-changes --severity error
```

Error:

```
Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```

I can provide a full copy of the stack trace if desired.

**Comment by acrelle** [comment]
Also experiencing this when running `dotnet format` inside a Windows build environment

Error
```
Unhandled exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```

dotnet --info
```
.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\a\_tool\dotnet\sdk\7.0.302\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  2.1.818 [C:\a\_tool\dotnet\sdk]
  6.0.106 [C:\a\_tool\dotnet\sdk]
  6.0.408 [C:\a\_tool\dotnet\sdk]
  7.0.302 [C:\a\_tool\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\a\_tool\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\a\_tool\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\a\_tool\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\a\_tool\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\a\_tool\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\a\_tool\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\a\_tool\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\a\_tool\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\a\_tool\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\a\_tool\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\a\_tool\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\a\_tool\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [C:\a\_tool/dotnet]

global.json file:
  Not found
```

**Comment by trampster** [comment]
We are having this issue on a linux builder machine (via docker) and on our linux dev boxes. 

We are unable to downgrade a the microsoft ubuntu ppa doesn't seem to have the old version.

**Comment by ViktorHofer** [comment]
cc @sharwell @marcpopMSFT @jaredpar

**Comment by dtemme** [comment]
The update to 7.0.302 broke all of our build pipelines because we are validating the code format with `dotnet format` for Pull Requests in Azure DevOps Server.

**Comment by Shane32** [comment]
@sharwell `dotnet format` is an integral part of the .NET SDK starting with .NET 6, not a separate tool.  See documentation here https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-format .  AFAIK, all tools included with the SDK should be provided in full within the SDK installer.  So whatever dependencies `dotnet format` has should be included with the SDK, not distributed on demand.

> Some of the dependencies are omitted from distribution by long-standing design.

`dotnet format` works fine with prior versions of the .NET SDK.  There is simply an issue with .NET SDK 7.0.302, where it appears that the SDK installation did not include all of the necessary dependencies of `dotnet format`.

If a dependency was introduced with `dotnet format` which is disallowed to be distributed with the SDK, then the change within `dotnet format` should be reverted so it only uses dependencies known to be included with the SDK.  Otherwise, the dependency should be added to the SDK distribution.

**Comment by jaredpar** [comment]
@adam-knights, @Shane32 thanks for reporting. I'm able to reproduce this following the steps in the original post. Effectively use a global.json with the contents

```json
{
  "sdk": {
    "version": "7.0.302",
    "allowPrerelease": false,
    "rollForward": "latestPatch"
  }
}
```

Then simply 

```
> dotnet new webapi
> dotnet format
Crash
```

We're looking into this.

**Comment by JoeRobich** [comment]
Builds with updated Roslyn has inserted into the [7.0.3xx](https://github.com/dotnet/sdk/pull/32692), [.1xx](https://github.com/dotnet/sdk/pull/32694), and [.4xx](https://github.com/dotnet/sdk/pull/32693) branches.

**Comment by ViktorHofer** [comment]
@jaredpar and others, can you please provide a root cause analysis? Also, what can we do to avoid potential version mismatches in the future?

**Comment by AnthonySteele-NewDay** [comment]
It looks like installing a recent dotnet 7 SDK has broken `dotnet format` across my machine, including in pre-commit automation that has to be disabled for now if I want to commit code.

I don't think that I can uninstall all dotnet 7 sdks as it comes with latest visual studio.

If there's a fix that's more fine-grained than "stop formatting code" I'd like to know.

**Comment by Shane32** [comment]
> Builds with updated Roslyn has inserted into the [7.0.3xx](https://github.com/dotnet/sdk/pull/32692), [.1xx](https://github.com/dotnet/sdk/pull/32694), and [.4xx](https://github.com/dotnet/sdk/pull/32693) branches.

What's the expected release date for the next SDK that will contain the fixes?

**Comment by joeloff** [comment]
I'd expect them to be available in the June servicing release

**Comment by jmpompeo** [comment]
> I'd expect them to be available in the June servicing release

Is there an estimated release date for this?

**Comment by adam-knights** [comment]
> > I'd expect them to be available in the June servicing release
> 
> Is there an estimated release date for this?

https://learn.microsoft.com/en-us/dotnet/core/releases-and-support#servicing-updates

**Comment by martincostello** [comment]
The second Tuesday of the month is the standard cadence, so likely this time next week.

**Comment by AnthonySteele-NewDay** [comment]
[The new bits are out, on schedule: SDK 7.0.304](https://dotnet.microsoft.com/en-us/download/dotnet/7.0)

This release appears, with a quick test, to fix the issues that I was having with dotnet format.

**Comment by jeremy-visionaid** [comment]
Well, that turned out to be a bust for me :(. The original ReflectionTypeLoadException error is gone, but now fails for me resolving third-party dependencies were previously it succeeded (the only change is going from Build Tools 17.4.7 to 17.6.3 in CI)

`error CS0246: The type or namespace name 'ILoggerFactory' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by jeremy-visionaid** [comment]
Running a restore/build allows it to work for nuget references, but even then, dotnet format in SDK 7.0.304 seems unable to resolve types from:

- COM interop references
- C++/CLI projects
- Third-party assemblies referenced from the filesystem

**Comment by jeremy-visionaid** [comment]
For anyone that encounters the new type resolution issue (when using EnforceCodeStyleInBuild) that was uncovered by this, a new issue is available here:

https://github.com/dotnet/sdk/issues/33260
