### ISSUE TITLE
Error `dotnet new blazorserver BlazorTestApp --no-https -f net7.0` on Windows 11 WSL

### ISSUE THREAD

**Issue by Eksno** [dotnet/sdk#33232]
### Describe the bug
I was following [Blazor Tutorial](https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create) and got to the create part where I ran into this error:
```
user@ubuntulinux:/mnt/c/path/to/project/folder$ dotnet new blazorserver BlazorTestApp --no-https -f net7.0
Unable to cast object of type 'System.Boolean' to type 'System.String'.
   at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
   at Microsoft.TemplateEngine.Cli.Commands.TemplateOptionResult.FromParseResult(TemplateOption option, ParseResult parseResult)
   at Microsoft.TemplateEngine.Cli.Commands.TemplateResult.FromParseResult(TemplateCommand templateCommand, ParseResult parseResult)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.CollectTemplateMatchInfo(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.HandleNoTemplateFoundResult(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, IReporter reporter)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.HandleTemplateInstantationAsync(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ExecuteIntAsync(InstantiateCommandArgs instantiateArgs, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, InvocationContext context)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand`1.InvokeAsync(InvocationContext context)

For details on the exit code, refer to https://aka.ms/templating-exit-codes#70
```

### To Reproduce

1. Install WSL with `wsl --install`
2. Install Ubuntu in WSL with `wsl --install -d Ubuntu`
3. Open the WSL terminal and install .NET SDK 7.0. [DotNET Core Install Ubuntu 22.04 LTS](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-2204)
4. Run `dotnet new blazorserver BlazorTestApp --no-https -f net7.0` [Blazor Tutorial Create](https://dotnet.microsoft.com/en-us/learn/aspnet/blazor-tutorial/create)

### Further technical details
```
.NET SDK:
 Version:   7.0.107
 Commit:    bf72c06963

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.107/

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  7.0.107 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.7 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
- WSL2 Ubuntu Terminal

#### Neofetch
OS: Ubuntu 22.04.2 LTS on Windows 11 x86_64
Kernel: 5.15.90.1-microsoft-standard-WSL2
Uptime: 32 mins
Packages: 544 (dpkg)
Shell: bash 5.1.16
Terminal: Relay(2113)
CPU: 11th Gen Intel i7-1185G7 (8) @ 2.995GHz
GPU: 6bca:00:00.0 Microsoft Corporation Device 008e
Memory: 328MiB / 15849MiB

**Comment by Eksno** [comment]
For anyone else having this problem easy workaround is to navigate to the WSL folder on the host system and run the command from there.

Haven't had problems otherwise in WSL but if they were to arise I would assume the same workaround works for them too otherwise it wouldn't be a WSL problem.
