### ISSUE TITLE
stack dump in VS from ValidateAssembliesTask on input not found

### ISSUE THREAD

**Issue by danmoseley** [dotnet/sdk#33396]
repro
```
git clone https://github.com/dotnet/runtime
cd into it
git checkout 4542e09ba0494eb29c86c6255fcba7fd9db897b7 #probably doesn't matter, it's just current head
build libs -c Release
devenv src\coreclr\System.Private.CoreLib\System.Private.CoreLib.sln
hit build
```

result -- the task should not dump a callstack for a missing input file. it should just provide the message only.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "Microsoft.DotNet.ApiCompat.Task.ValidateAssembliesTask" task failed unexpectedly.
System.IO.FileNotFoundException: Could not find the provided path 'C:\git\runtime\artifacts\bin\System.Private.CoreLib\ref\Debug\net8.0\System.Private.CoreLib.dll' to load binaries from.
   at Microsoft.DotNet.ApiSymbolExtensions.AssemblySymbolLoader.LoadFromPaths(IEnumerable`1 paths, ImmutableHashSet`1 referenceAssemblyNamesToIgnore) in /_/src/Microsoft.DotNet.ApiSymbolExtensions/AssemblySymbolLoader.cs:line 268
   at Microsoft.DotNet.ApiSymbolExtensions.AssemblySymbolLoader.LoadAssemblies(String[] paths) in /_/src/Microsoft.DotNet.ApiSymbolExtensions/AssemblySymbolLoader.cs:line 101
   at Microsoft.DotNet.ApiCompatibility.Runner.ApiCompatRunner.CreateAssemblySymbols(IReadOnlyList`1 metadataInformation, ApiCompatRunnerOptions options, Boolean& resolvedExternallyProvidedAssemblyReferences) in /_/src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Runner/ApiCompatRunner.cs:line 138
   at Microsoft.DotNet.ApiCompatibility.Runner.ApiCompatRunner.ExecuteWorkItems() in /_/src/ApiCompat/Microsoft.DotNet.ApiCompatibility/Runner/ApiCompatRunner.cs:line 49
   at Microsoft.DotNet.ApiCompat.ValidateAssemblies.Run(Func`2 logFactory, Boolean generateSuppressionFile, String[] suppressionFiles, String suppressionOutputFile, String noWarn, Boolean respectInternals, Boolean enableRuleAttributesMustMatch, String[] excludeAttributesFiles, Boolean enableRuleCannotChangeParameterName, String[] leftAssemblies, String[] rightAssemblies, Boolean enableStrictMode, String[][] leftAssembliesReferences, String[][] rightAssembliesReferences, Boolean createWorkItemPerAssembly, ValueTuple`2[] leftAssembliesTransformationPatterns, ValueTuple`2[] rightAssembliesTransformationPatterns) in /_/src/ApiCompat/Microsoft.DotNet.ApiCompat.Shared/ValidateAssemblies.cs:line 90
   at Microsoft.DotNet.ApiCompat.Task.ValidateAssembliesTask.ExecuteCore() in /_/src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidateAssembliesTask.cs:line 127
   at Microsoft.NET.Build.Tasks.TaskBase.Execute() in /_/src/Tasks/Common/TaskBase.cs:line 52
   at Microsoft.DotNet.ApiCompat.Task.ValidateAssembliesTask.Execute() in /_/src/ApiCompat/Microsoft.DotNet.ApiCompat.Task/ValidateAssembliesTask.cs:line 117
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	System.Private.CoreLib	C:\Users\danmose\.nuget\packages\microsoft.dotnet.apicompat.task\8.0.100-preview.6.23313.1\build\Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets	16	
```

**Comment by ericstj** [comment]
Agree with Dan that bad inputs should not cause a task to dump a stack.  Input validation is something that should result in an actionable error message.

Of the options you list I'd lean on wrapping common failure points with our own exception type.  That lets you identify and address specific failure points that might be caused by bad inputs without introducing a catch statement that might catch more exceptions than you want.  I see MSBuild does this: https://github.com/search?q=repo%3Adotnet%2Fmsbuild%20%22%3A%20Exception%22&type=code

Another option would be to validate all user inputs up front - to make sure that common cases like missing paths fail early.  This might allow you to have a better error message that refers to a specific input to the task.  Here's a case of that: https://github.com/dotnet/roslyn/blob/1418690ab283793bfe5fc3da00f7533683f5f56b/src/Compilers/Core/MSBuildTask/ManagedCompiler.cs#L1168
