### ISSUE TITLE
Can't install tool with version containing a capital letter on Linux

### ISSUE THREAD

**Issue by svick** [dotnet/sdk#33580]
### Describe the bug

If you try to install a .Net tool with version number that contains a capital on Linux, it fails with:

```
The settings file in the tool's NuGet package is invalid: Failed to retrieve tool configuration: Could not find a part of the path '/home/petro/.dotnet/tools/.store/dotnetsay/2.1.8-capital/dotnetsay/2.1.8-Capital/tools/netcoreapp2.1/any/DotnetToolSettings.xml'.
Tool 'dotnetsay' failed to install. Contact the tool author for assistance.
```

### To Reproduce

0. Be on Linux.
1. Clone [dotnetsay](https://github.com/dotnet/core/tree/main/samples/dotnetsay).
2. Change the version in .csproj to (it's :

    ```csproj
    <VersionPrefix>2.1.8</VersionPrefix>
    <VersionSuffix>Capital</VersionSuffix>
    ````
3. Run `dotnet pack /p:ContinuousIntegrationBuild=true`.
4. Run `dotnet tool install -g dotnetsay --prerelease --add-source bin/Debug/`.

### Further technical details
This behavior happens on the `dotnet/sdk:7.0` Docker image, and also on Ubuntu 22.04 with .Net SDK 7.0.305 installed

**Comment by JL03-Yue** [comment]
We changed the implementation of tool install and restore in .NET 8. We will need to verify to see if the error still reproduces.

**Comment by Forgind** [comment]
I tried this with net8.0 just now (on Ubuntu) and got a different error, but it seems like it's the same bug:
```
Unhandled exception: System.IO.FileNotFoundException: Could not find file '/home/forgind/.dotnet/tools/.store/.stage/5mzjqcpb.htz/microsoft.botsay/2.1.8-capital/microsoft.botsay.2.1.8-capital.nupkg'.
File name: '/home/forgind/.dotnet/tools/.store/.stage/5mzjqcpb.htz/microsoft.botsay/2.1.8-capital/microsoft.botsay.2.1.8-capital.nupkg'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.Protocol.LocalFolderUtility.<>c__DisplayClass48_0.<GenerateNupkgMetadataFile>b__0()
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLocked(String filePath, Action action)
   at NuGet.Protocol.LocalFolderUtility.GenerateNupkgMetadataFile(String nupkgPath, String installPath, String hashPath, String nupkgMetadataPath)
   at NuGet.Repositories.NuGetv3LocalRepository.GetPackage(String packageId, NuGetVersion version, String path)
   at NuGet.Repositories.NuGetv3LocalRepository.FindPackageImpl(String packageId, NuGetVersion version)
   at NuGet.Repositories.NuGetv3LocalRepository.FindPackage(String packageId, NuGetVersion version)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.CreateAssetFile(PackageId packageId, NuGetVersion version, DirectoryPath packagesRootPath, DirectoryPath assetFileDirectory, String runtimeJsonGraph, String targetFramework)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.<>c__DisplayClass8_0.<InstallPackage>b__0()
   at Microsoft.DotNet.Cli.TransactionalAction.Run[T](Func`1 action, Action commit, Action rollback)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

**Comment by bstordrup** [comment]
@Forgind, I know it is a late comment, but what is the actual path in the file system that it throws the exception on? If the `Capital` part of the filename is generated in the file system with the exact content of `VersionSuffix` tag, then the filename would be `microsoft.botsay.2.1.8-Capital.nupkg`.

Searching for the filename `microsoft.botsay.2.1.8-capital.nupkg` will then fail because Linux file system is case sensitive.
