### ISSUE TITLE
`dotnet help` dumps stack in GitHub Codespaces

### ISSUE THREAD

**Issue by rainersigwald** [dotnet/sdk#35248]
### To Reproduce
In a Codespace, run `dotnet help pack`.

### Exceptions (if any)

```sh-session
$ dotnet help pack
Unhandled exception: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'xdg-open' with working directory '/workspaces/source-build-externals'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Tools.Help.HelpCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Cli.Parser.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Further technical details
- Include the output of `dotnet --info`
```
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/local/dotnet/7.0.306/sdk/7.0.306/

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  7.0.306 [/usr/local/dotnet/7.0.306/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.9 [/usr/local/dotnet/7.0.306/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.9 [/usr/local/dotnet/7.0.306/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/local/dotnet/current]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by baronfel** [comment]
interesting, what base image are you using in codespaces? I'd have thought that `xdg-open` is pretty prevalent.

the `help` command should probably

a) stop manually coding what shell to launch applications with and instead let the runtime's shell handlers open the documentation urls
b) have a last-chance catch-all that just calls `--help` for the specified command instead of opening the HTML help.

**Comment by rainersigwald** [comment]
It's whatever the defaults were on https://github.com/dotnet/source-build-externals, which doesn't appear to have any special configuration.

**Comment by baronfel** [comment]
While you have that environment, can you check if any of these are on your PATH? `{ "xdg-open", "gnome-open", "kfmclient" }`

**Comment by rainersigwald** [comment]
Nope:

```sh-session
$ which xdg-open
$ which gnome-open
$ which kfmclient
```

**Comment by marcpopMSFT** [comment]
Old issue triage: <img width="2086" height="127" alt="Image" src="https://github.com/user-attachments/assets/97832814-854d-4b63-81b8-88cf0b467d94" /> <-- current behavior. Not the best error but not worth fixing in my mind.
