### ISSUE TITLE
SDK resolver failure when an older SDK is also installed 

### ISSUE THREAD

**Issue by sebastienros** [dotnet/sdk#35334]
We are getting this error message when build with 8-rc2 while an 8-alpha1 sdk was previously installed:

```
c:\code\1whpqxaj.s54\src\BenchmarksApps\TechEmpower\PlatformBenchmarks\PlatformBenchmarks.csproj : error MSB4242: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.Sdk.Web". Exception: "Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten.net6' version '8.0.0-alpha.1.22510.1' is lower than version '8.0.0-rc.1.23415.5' required by manifest 'microsoft.net.workload.mono.toolchain.net6' [c:\code\gcn3xuv4.r4w\sdk-manifests\8.0.100-rc.2\microsoft.net.workload.mono.toolchain.net6\8.0.0-rc.2.23431.9\WorkloadManifest.json]
c:\code\1whpqxaj.s54\src\BenchmarksApps\TechEmpower\PlatformBenchmarks\PlatformBenchmarks.csproj : error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.ComposeWorkloadManifests()
c:\code\1whpqxaj.s54\src\BenchmarksApps\TechEmpower\PlatformBenchmarks\PlatformBenchmarks.csproj : error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir)
c:\code\1whpqxaj.s54\src\BenchmarksApps\TechEmpower\PlatformBenchmarks\PlatformBenchmarks.csproj : error MSB4242:    at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir, String globalJsonPath)
c:\code\1whpqxaj.s54\src\BenchmarksApps\TechEmpower\PlatformBenchmarks\PlatformBenchmarks.csproj : error MSB4242:    at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
c:\code\1whpqxaj.s54\src\BenchmarksApps\TechEmpower\PlatformBenchmarks\PlatformBenchmarks.csproj : error MSB4242:    at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IList`1 resolvers, Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio, SdkResult& sdkResult, IEnumerable`1& errors, IEnumerable`1& warnings)""
```

The only mitigation is to not have the alpha1 sdk installed.

**Comment by marcpopMSFT** [comment]
Either this is a semver issue or a weird SxS manifest downgrade issue. CC @dsplaisted  but I'm not sure this is high priority at the moment. We should watch out for whether this will impact 9 preview 1 SxS with 9 alpha builds (as that's more likely that folks still having 8 alpha builds installed).

**Comment by dsplaisted** [comment]
I think there were some early .NET 8 builds where we hadn't switched to preview feature bands, right?  That is probably what is causing this issue.

@sebastienros Would you be able to zip up and share the contents of the `sdk-manifests` folder from an installation where this is ocurring?

**Comment by marcpopMSFT** [comment]
I think Daniel is right that we changed things around preview 1 or 2 for the preview bands so it's likely that. I'm going to close this out as it's likely uncommon.

**Comment by sebastienros** [comment]
Fine as long as we think it's fixed
