### ISSUE TITLE
`MSBuild` Code Analysis formatting

### ISSUE THREAD

**Issue by cschuchardt88** [dotnet/sdk#35388]
### Describe the bug
The problem is character case problem. This file `Crontab.csproj` does clear exist in the repo, but its called `CronTab.csproj` The `T` is capitalized in the repo but i renamed it in visual studio. But i guess `git` didn't pick it up, because the name didn't change?

### To Reproduce
https://github.com/cschuchardt88/neo-cron-plugin/pull/8
or
https://github.com/cschuchardt88/neo-cron-plugin/tree/dev

### Exceptions (if any)
```
dotnet format --verify-no-changes --verbosity diagnostic
  shell: /usr/bin/bash -e {0}
  env:
    DOTNET_VERSION: 7.0.x
    DOTNET_ROOT: /usr/share/dotnet
  The dotnet runtime version is '7.0.11'.
  The dotnet CLI version is '7.0.401'.
  Using MSBuild.exe located in '/usr/share/dotnet/sdk/7.0.401/'.
  Formatting code files in workspace '/home/runner/work/neo-cron-plugin/neo-cron-plugin/ALL.sln'.
  Loading workspace.
  /usr/share/dotnet/sdk/7.0.401/NuGet.targets(400,5): error MSB[3](https://github.com/cschuchardt88/neo-cron-plugin/actions/runs/6185051776/job/16789880870?pr=8#step:4:3)202: The project file "/home/runner/work/neo-cron-plugin/neo-cron-plugin/src/Neo.Plugins.Cron/Crontab.csproj" was not found. [/home/runner/work/neo-cron-plugin/neo-cron-plugin/ALL.sln]
Unhandled exception: System.Exception: Restore operation failed.
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.OpenMSBuildWorkspaceAsync(String solutionOrProjectPath, WorkspaceType workspaceType, Boolean noRestore, Boolean requiresSemantics, String binaryLogPath, Boolean logWorkspaceWarnings, ILogger logger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.CodeFormatter.FormatWorkspaceAsync(FormatOptions formatOptions, ILogger logger, CancellationToken cancellationToken, String binaryLogPath)
   at Microsoft.CodeAnalysis.Tools.FormatCommandCommon.FormatAsync(FormatOptions formatOptions, ILogger`1 logger, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Tools.Commands.RootFormatCommand.FormatCommandDefaultHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass[4](https://github.com/cschuchardt88/neo-cron-plugin/actions/runs/6185051776/job/16789880870?pr=8#step:4:4)_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass1[5](https://github.com/cschuchardt88/neo-cron-plugin/actions/runs/6185051776/job/16789880870?pr=8#step:4:5)_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__4_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass[7](https://github.com/cschuchardt88/neo-cron-plugin/actions/runs/6185051776/job/16789880870?pr=8#step:4:8)_0.<<UseExceptionHandler>b__0>d.MoveNext()
Error: Process completed with exit code 1.
```

### Further technical details
- The dotnet runtime version is '7.0.11'.
-  The dotnet CLI version is '7.0.401'.

**Comment by cschuchardt88** [comment]
The reason it happened is because the solution file has a different case of characters for the project filename then what is on the disk. In this case the output you are seeing from main post of this issue and was built on github. Also this happened on my computer as well. Visual studio does case about the case of characters for the filename in a solution file, but `dotnet format` does. I don't know if this affects `*.proj` file as well with different case of characters for the name of files on disk.
