### ISSUE TITLE
.NET8 RC1 dotnet tool install <package> does not work when nuget.org is blocked

### ISSUE THREAD

**Issue by pokdeep** [dotnet/sdk#35517]
### Describe the bug
When nuget.org is blocked and a private nuget feed is being used `dotnet tool install <package>` does not work as it tries to search for the package versions on nuget.org
Specifying a version via `--version` works around this issue

### To Reproduce

Add an entry to your `hosts` file to simulate blocking nuget.org `0.0.0.0 api.nuget.org`
run in a terminal `dotnet tool install coverlet.console -g`

if you want to reproduce through docker update `<Private feed url>` with your private nuget feed
```
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine3.18

RUN --mount=type=secret,id=USERNAME --mount=type=secret,id=PASSWORD  \
    USERNAME=$(cat /run/secrets/USERNAME) PASSWORD=$(cat /run/secrets/PASSWORD) export USERNAME PASSWORD && \
    dotnet nuget add source "https://<Private feed url>" -u "${USERNAME}" -p "${PASSWORD}" --store-password-in-clear-text -n NewNuget && \
    dotnet nuget remove source nuget.org && \
    dotnet tool install coverlet.console -g && \
    dotnet nuget remove source NewNuget
```
and run with the command `docker build --secret id=USERNAME,src=username.txt --secret id=PASSWORD,src=password.txt --progress=plain --no-cache .`
this command assumes you have txt files in the same directory, `username.txt` which contains your username, `password.txt` which has your apikey/password for the private nuget feed

if you include `--version 6` to the `dotnet install tool coverlet.console -g` command then it will work
### Exceptions (if any)

```
#5 6.804 Unhandled exception: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://api.nuget.org/v3/index.json.
#5 6.824  ---> System.Net.Http.HttpRequestException: Address not available (api.nuget.org:443)
#5 6.824  ---> System.Net.Sockets.SocketException (99): Address not available
#5 6.824    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
#5 6.824    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
#5 6.824    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
#5 6.824    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
#5 6.824    --- End of inner exception stack trace ---
#5 6.824    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
#5 6.824    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
#5 6.824    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
#5 6.824    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
#5 6.824    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
#5 6.824    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
#5 6.824    at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
#5 6.824    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
#5 6.824    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
#5 6.824    at NuGet.Protocol.ServerWarningLogHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
#5 6.824    at NuGet.Protocol.HttpSourceAuthenticationHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
#5 6.824    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
#5 6.824    at NuGet.Protocol.HttpRetryHandler.<>c__DisplayClass5_1.<<SendAsync>b__0>d.MoveNext()
#5 6.824 --- End of stack trace from previous location ---
#5 6.824    at NuGet.Protocol.TimeoutUtility.StartWithTimeout[T](Func`2 getTask, TimeSpan timeout, String timeoutMessage, CancellationToken token)
#5 6.824    at NuGet.Protocol.HttpRetryHandler.SendAsync(HttpRetryHandlerRequest request, String source, ILogger log, CancellationToken cancellationToken)
#5 6.824    at NuGet.Protocol.HttpSource.GetThrottledResponse(Func`1 requestFactory, TimeSpan requestTimeout, TimeSpan downloadTimeout, Int32 maxTries, Boolean isRetry, Boolean isLastAttempt, Guid sessionId, ILogger log, CancellationToken cancellationToken)
#5 6.824    at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
#5 6.824 --- End of stack trace from previous location ---
#5 6.824    at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
#5 6.824    at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
#5 6.824    at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
#5 6.824    at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
#5 6.824    --- End of inner exception stack trace ---
#5 6.824    at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
#5 6.824    at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
#5 6.824    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
#5 6.824    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
#5 6.824    at Microsoft.DotNet.NugetSearch.NugetToolSearchApiRequest.DomainAndPath()
#5 6.824    at Microsoft.DotNet.NugetSearch.NugetToolSearchApiRequest.ConstructUrl(String searchTerm, Nullable`1 skip, Nullable`1 take, Boolean prerelease, Uri domainAndPathOverride)
#5 6.824    at Microsoft.DotNet.NugetSearch.NugetToolSearchApiRequest.GetResult(NugetSearchApiParameter nugetSearchApiParameter)
#5 6.824    at Microsoft.DotNet.Tools.Tool.Install.ParseResultExtension.GetVersionRange(ParseResult parseResult)
#5 6.824    at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
#5 6.824    at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
#5 6.824    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```
below is a stacktrace from the build infrastructure I use which first highlighted this issue
```
Unhandled exception: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://api.nuget.org/v3/index.json.
#12 44.57  ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
#12 44.57  ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
#12 44.57  ---> System.Net.Sockets.SocketException (104): Connection reset by peer
#12 44.57    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
#12 44.58    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken)
#12 44.58    at System.Net.Sockets.Socket.ReceiveAsync(Memory`1 buffer, SocketFlags socketFlags, Boolean fromNetworkStream, CancellationToken cancellationToken)
#12 44.58    at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
#12 44.58    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
#12 44.58    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.ExecutionContextCallback(Object s)
#12 44.58    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
#12 44.58    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.MoveNext()
#12 44.58    at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32 bytesTransferred, Memory`1 socketAddress, SocketFlags receivedFlags, SocketError socketError)
#12 44.58    at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
#12 44.58    at System.Threading.ThreadPoolWorkQueue.Dispatch()
#12 44.58    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
#12 44.58 --- End of stack trace from previous location ---
#12 44.58
#12 44.58    --- End of inner exception stack trace ---
#12 44.58    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
#12 44.58    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
#12 44.58    at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
#12 44.58    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
#12 44.58    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
#12 44.58    --- End of inner exception stack trace ---
#12 44.58    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
#12 44.58    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
#12 44.58    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
#12 44.58    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
#12 44.58    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
#12 44.58    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
#12 44.58    at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
#12 44.58    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
#12 44.58    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
#12 44.58    at NuGet.Protocol.ServerWarningLogHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
#12 44.58    at NuGet.Protocol.HttpSourceAuthenticationHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
#12 44.58    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
#12 44.58    at NuGet.Protocol.HttpRetryHandler.<>c__DisplayClass5_1.<<SendAsync>b__0>d.MoveNext()
#12 44.58 --- End of stack trace from previous location ---
#12 44.58    at NuGet.Protocol.TimeoutUtility.StartWithTimeout[T](Func`2 getTask, TimeSpan timeout, String timeoutMessage, CancellationToken token)
#12 44.58    at NuGet.Protocol.HttpRetryHandler.SendAsync(HttpRetryHandlerRequest request, String source, ILogger log, CancellationToken cancellationToken)
#12 44.58    at NuGet.Protocol.HttpSource.GetThrottledResponse(Func`1 requestFactory, TimeSpan requestTimeout, TimeSpan downloadTimeout, Int32 maxTries, Boolean isRetry, Boolean isLastAttempt, Guid sessionId, ILogger log, CancellationToken cancellationToken)
#12 44.58    at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
#12 44.58 --- End of stack trace from previous location ---
#12 44.58    at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
#12 44.58    at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
#12 44.58    at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
#12 44.58    at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
#12 44.58    --- End of inner exception stack trace ---
#12 44.58    at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
#12 44.58    at NuGet.Protocol.ServiceIndexResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
#12 44.58    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T](CancellationToken token)
#12 44.58    at NuGet.Protocol.Core.Types.SourceRepository.GetResourceAsync[T]()
#12 44.58    at Microsoft.DotNet.NugetSearch.NugetToolSearchApiRequest.DomainAndPath()
#12 44.58    at Microsoft.DotNet.NugetSearch.NugetToolSearchApiRequest.ConstructUrl(String searchTerm, Nullable`1 skip, Nullable`1 take, Boolean prerelease, Uri domainAndPathOverride)
#12 44.58    at Microsoft.DotNet.NugetSearch.NugetToolSearchApiRequest.GetResult(NugetSearchApiParameter nugetSearchApiParameter)
#12 44.58    at Microsoft.DotNet.Tools.Tool.Install.ParseResultExtension.GetVersionRange(ParseResult parseResult)
#12 44.58    at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
#12 44.58    at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
#12 44.58    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```
### Further technical details
- Include the output of `dotnet --info`
.NET SDK:
 Version:   8.0.100-rc.1.23463.5
 Commit:    e7f4de8816

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.100-rc.1.23463.5/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.1.23419.4
  Architecture: x64
  Commit:       92959931a3
  RID:          osx-x64

.NET SDKs installed:
  6.0.412 [/usr/local/share/dotnet/sdk]
  8.0.100-rc.1.23463.5 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
iTerm2 3.4.20

**Comment by pokdeep** [comment]
I think this issue was introduced through this PR #28951

**Comment by JL03-Yue** [comment]
I think this issue will be fixed in the GA release of .NET 8.
