### ISSUE TITLE
[NETSDKE2E]With upgrade install from SDK 6.0.317 to 6.0.318(Oct update), publish blazorwasm project with AOT compilation enabled failed

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#35645]
**Repro steps:**

1. Install SDK 6.0.317 on windows from offical website
2. Install SDK 6.0.318 [Pipelines - Run 20230919.1-6.0.415-servicing.23469.11,6.0.318-servicing.23469.12,6.0.123-servicing.23469.13-193342,193357,193358 artifacts](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D2271474%26view%3Dartifacts%26pathAsName%3Dfalse%26type%3DpublishedArtifacts&data=05%7C01%7Cv-huwang%40microsoft.com%7Ca53a249800a54c3ff61308dbb9f9bfd2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638308254813753305%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9rSsnqEhKZnIv8gljaxDcGXB0DJYbGSdd6BWouMukvU%3D&reserved=0)
3. Install wasm-tools
dotnet workload install wasm-tools --skip-manifest-update

4. New blazorWasm
dotnet new blazorwasm
add below code to csproj file to use AOT compilation
 <RunAOTCompilation>true</RunAOTCompilation>
5. dotnet publish

Expected Result:
publish successfully

Actual Result:
Publish failed

![image](https://github.com/dotnet/sdk/assets/65637796/962d0060-1dee-4eab-958e-1da1f29bd914)

EXEC : error : UNKNOWN: unknown error, open 'C:\Users\v-danche\AppData\Local\Temp\tmpeaju9ghr.js' [C:\Users\v-danche\my
wasm\mywasm.csproj]
      at Object.openSync (fs.js:476:3)
      at Object.readFileSync (fs.js:377:35)
      at read (C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.4\tools\emscripten
  \tools\acorn-optimizer.js:16:13)
      at Object.<anonymous> (C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.4\to
  ols\emscripten\tools\acorn-optimizer.js:1818:13)
      at Module._compile (internal/modules/cjs/loader.js:1063:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
      at Module.load (internal/modules/cjs/loader.js:928:32)
      at Function.Module._load (internal/modules/cjs/loader.js:769:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
      at internal/main/run_main_module.js:17:47 {
    errno: -4094,
    syscall: 'open',
    code: 'UNKNOWN',
    path: 'C:\\Users\\v-danche\\AppData\\Local\\Temp\\tmpeaju9ghr.js'
  }
emcc : error : '"C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Node.win-x64\6.0.4\tools\bin\nod
e.exe" "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.win-x64\6.0.4\tools\emscripten\tools\
acorn-optimizer.js" C:\Users\v-danche\AppData\Local\Temp\tmpeaju9ghr.js applyImportAndExportNameChanges minifyWhitespac
e' failed (returned 1) [C:\Users\v-danche\mywasm\mywasm.csproj]
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.4\Sdk\WasmApp.Native.targets(379,5): error MSB3
073: The command "emcc "@C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\6.0.4\runtimes\b
rowser-wasm\native\src\emcc-default.rsp" "@C:\Users\v-danche\mywasm\obj\Debug\net6.0\wasm\for-publish\emcc-link.rsp"" e
xited with code 1. [C:\Users\v-danche\mywasm\mywasm.csproj]

dotnet --info:
.NET SDK (reflecting any global.json):
 Version:   6.0.318
 Commit:    3b8fbbea7f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.25398
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.318\

global.json file:
  Not found

Host:
  Version:      6.0.23
  Architecture: x64
  Commit:       ca8b53290a

.NET SDKs installed:
  7.0.318 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by vdanche** [comment]
Not repro on Fresh install(6.0.318)
![image](https://github.com/dotnet/sdk/assets/65637796/5c82a64d-5b72-4e4e-94e3-be53d75ecb8d)

**Comment by marcpopMSFT** [comment]
@lewing @steveisok

**Comment by lewing** [comment]
So a fresh install of 6.0.318 works, but it did not work when 6.0.317 was previously installed without workloads, then 6.0.18 was installed and the workload was installed?

**Comment by lewing** [comment]
Are you able recreate the problem from scratch using specific steps?

**Comment by joeloff** [comment]
I tried this on a sandbox with the 6.0.317-->6.0.318 upgrade and it worked fine for me

**Comment by vdanche** [comment]
@lewing @joeloff today we tried again with upgrade stall(6.0.317 to 6.0.318) in a clean OS, a threat found prompt display after publish failed,  is it expected? after allowing it, dotnet publish successfully.
![image](https://github.com/dotnet/sdk/assets/65637796/3aa9a794-2be4-414c-add8-bb866eebe0f4)

![image](https://github.com/dotnet/sdk/assets/65637796/022058f2-273f-4938-ba3d-3d25778c7fed)

Note:
publish successfully in fresh install without threat found prompt displaying

FYI @richaverma1

**Comment by vdanche** [comment]
today we also meet it on 6.0.416 SDK

**Comment by lewing** [comment]
if you keep passing '--skip-manifest-update' and the 6.0.3xx sdk does not update the baselines yes it will still be there.  If you drop `--skip-manifest-update` it should install the correct runtime and there should be no problem cc @marcpopMSFT

**Comment by marcpopMSFT** [comment]
Per offline conversation, we're going to update the baseline manifest for 3xx and 4xx in a future servicing release:
https://github.com/dotnet/installer/pull/17601
https://github.com/dotnet/installer/pull/17600

**Comment by vdanche** [comment]
This issue still repro on 6.0.420 SDK

**Comment by marcpopMSFT** [comment]
Old issue triage: likely a point in time problem so closing out.
