### ISSUE TITLE
NETSDK1202 should be a warning and not an error to prevent breaking changes

### ISSUE THREAD

**Issue by Perksey** [dotnet/sdk#35811]
### Describe the bug
[dotnet/Silk.NET](https://github.com/dotnet/Silk.NET) is investigating upgrading to .NET 8

We support multiple out-of-support TFMs just like the BCL's extension packages do (they weren't out-of-support when we added them, but now they're added we can't remove them). We're not prepared to start removing support for older TFMs because our users are using them. It is our end user's responsibility to not use out-of-support TFMs.

Similar diagnostics, such as the warning you get when targeting .NET 5, are warnings and not errors.

### To Reproduce
1. Create a library that targets `net8.0` and `net6.0-android`
2. Set the global.json to point at .NET 8
3. Install workloads (this can be done beforehand but this is the steps CI is working through)
4. `dotnet build`
5. Observe NETSDK1202

### Error
```
  Error: /Users/runner/.dotnet/sdk/8.0.100-rc.1.23463.5/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(35,5): error NETSDK1202: The workload 'android' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/maui-support-policy for more information about the support policy. [/Users/runner/work/Silk.NET/Silk.NET/src/Maths/Silk.NET.Maths/Silk.NET.Maths.csproj::TargetFramework=net6.0-android]
```

**Comment by Perksey** [comment]
The error I'm thinking of is NETSDK1138 - the EOL TFM warning. This does not break downstream consumers when a framework goes out-of-support as it is not an error.

**Comment by marcpopMSFT** [comment]
@Perksey both 1138 and 1202 appear to be warnings: https://github.com/dotnet/sdk/blob/release/8.0.1xx/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.EolTargetFrameworks.targets

You can set CheckEolWorkloads to false to avoid this particular check . 

@jonathanpeppers did a breaking change document get created for this to cover that workaround if customers didn't want to get the warning?

**Comment by jonathanpeppers** [comment]
@Perksey if you have a .NET 7 SDK, it is still just a warning. It is not possible to build `net6.0-ios` or `net6.0-android` apps with the .NET 8 SDK, however.

This is due to the MAUI support policy having a shorter timeline. It is basically the same policy Xamarin had:

* https://dotnet.microsoft.com/en-us/platform/support/policy/maui

@marcpopMSFT I don't know if this qualifies as a breaking change -- or not, but I'm willing to document this somewhere if it makes sense. This is the first time a MAUI target framework has gone out of support.

**Comment by marcpopMSFT** [comment]
Pinging @PriyaPurkayastha as she owns compat in case she has an opinion on where and how to document this.

**Comment by PriyaPurkayastha** [comment]
Just chatted with @gewarren and she mentioned that an article can be created for the warnings(NETSDK1138 and NETSDK1202) describing the workaround the use CheckEolWorkloads if the warning needs to be suppressed for this scenario. The description would look something similar to [this](https://learn.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1206).

**Comment by jonathanpeppers** [comment]
Sounds good, I added NETSDK1202: https://github.com/dotnet/docs/pull/37422

**Comment by Perksey** [comment]
Interesting, I'm not entirely sure why we're seeing this as an error - believe me I don't have warnings as errors on, but happy with this behaviour being documented.

**Comment by jonathanpeppers** [comment]
We set `<WarningsAsErrors>NETSDK1202</WarningsAsErrors>` in the .NET 8 workloads when targeting `net6.0`, because we don't actually support building `net6.0` projects at all with those versions.

**Comment by Perksey** [comment]
Makes sense! Did not know that!

**Comment by Gaburiere-Remira** [comment]
Good morning, just yesterday our pipeline that builds net maui apps with target framework 8 stopped working, with error NETSDK1202 (not a warning), specifically in the restore step. I put 

```
<CheckEolWorkloads>false</CheckEolWorkloads>
```
in the csproj and it passed the restore step but failed on the build with a version mismatch:

```
error NETSDK1135: SupportedOSPlatformVersion 12.2 cannot be higher than TargetPlatformVersion 1.0.
```

In the csproj of the maui app, I have

```
<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier(‘$(TargetFramework)’)) == ‘ios’">12.2</SupportedOSPlatformVersion>
<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier(‘$(TargetFramework)’)) == ‘android’">21.0</SupportedOSPlatformVersion>
```


It would appear that net8.0-ios is unable to infer the correct target framework.

This prevents me from building all my apps that target net8.0.

Any ideas?

**Comment by rolfbjarne** [comment]
> Any ideas?

Try using a `global.json` to force .NET 8 to be used:

```json
{
  "sdk": {
    "version": "8.0.400"
  }
}
```

**Comment by Gaburiere-Remira** [comment]
> > Any ideas?
> 
> Try using a `global.json` to force .NET 8 to be used:
> 
> {
>   "sdk": {
>     "version": "8.0.400"
>   }
> }

using global.json  select version 8.0.414, however fails:

```
      /Users/runner/.dotnet/sdk/8.0.414/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To build this project, the following workloads must be installed: maui-android [/Users/runner/work/1/s/src/XXX/XXX/XXX.csproj::TargetFramework=net8.0-android]
       /Users/runner/.dotnet/sdk/8.0.414/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1147: To install these workloads, run the following command: dotnet workload restore [/Users/runner/work/1/s/src/XXX/XXX/XXX.csproj::TargetFramework=net8.0-android]

```

maybe should i include in global.json also the worlkflow version like below?

```
{
  "sdk": {
    "version": "8.0.400",
    "workloadVersion": "8.0.400",
    "allowPrerelease": false,
    "rollForward": "disable"
  }
}

```

**Comment by Gaburiere-Remira** [comment]
the previous comment did not work, however i was able to solve inside my azure pipeline using UseDotNet@2 task and forcing to use specific dot net version (8.0.414) as below:


```
  - ${{ if parameters.dotNetVersion }}:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: ${{ parameters.dotNetVersion }}
```

So building a net8.0-ios app with net8 sdk now recognize SupportedOSPlatformVersion and TargetPlatformVersion.

one issue remains: in multi target libraries, such the one i have, supporting both net8.0ios/droid and net9.0-ios/droid, which as yestarday were built once with net sdk 9, today they won't build anymore. 

Am I forced to make two different builds and two different releases for target frameworks?  I wouldn't like this solution very much, as it would lose the potential to be cross-framework.

**Comment by jonathanpeppers** [comment]
> supporting both net8.0ios/droid and net9.0-ios/droid, which as yestarday were built once with net sdk 9, today they won't build anymore.

We don't support net8.0 anymore, so you probably wouldn't need to either: https://aka.ms/maui-support-policy

You could start multitargeting `net9.0-*;net10.0-*` if you want to do that for mobile.

**Comment by RDI-Blake** [comment]
I understand not supporting net8,0 anymore, but a patch update to the SDK was a breaking change.

**Comment by jonathanpeppers** [comment]
This issue is from 2023 mentioning .NET 6. This is so long ago, I have no idea?

Can you explain a bit more on what you'd like to happen different that applies to .NET 8? It sounds like a different issue? (the issue is describing net6.0 projects)

**Comment by RDI-Blake** [comment]
I agree this is an old issue, but I saw it was active and related to the latest patch (9.0.306).

From what I gathered, users targeting net8.0 workloads using the net9.0 SDK now receive an error NETSDK1202. This is new in SDK version 9.0.306. The release notes do not mention this: https://github.com/dotnet/core/blob/main/release-notes/9.0/9.0.10/9.0.10.md

As @Gaburiere-Remira stated, adding `<CheckEolWorkloads>false</CheckEolWorkloads>` will bypass this breaking change.

There is a separate issue with latest workload 9.0.306 that produces the error NETSDK1135. This thread mentions a workaround which successfully worked for me https://github.com/dotnet/macios/issues/24005.

It's possible to use the latest SDK 9.0.306 with workload version 9.0.305 and continue builds as before, at least in my case.

**Comment by jonathanpeppers** [comment]
I am not aware of anything we changed in the .NET 9.0.306 SDK for workloads, end-of-life messages, etc.

Did something change in the `ios` workload? It would be unrelated to the .NET SDK version.

**Comment by RDI-Blake** [comment]
Apologies, I'm not familiar with the structure. But I did receive the message specifically for ios for a MAUI project targeting android/ios/windows

`C:\Program Files\dotnet\sdk\9.0.306\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(38,5): error NETSDK1202: The workload 'net8.0-ios' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/maui-support-policy for more information about the support policy.`

**Comment by jonathanpeppers** [comment]
Do you also have .NET 10 installed?

My guess is the presence of the .NET 10 workload is now warning you about .NET 8.

**Comment by RDI-Blake** [comment]
Yes, I have .NET 10 RC 1 and RC 2 installed with their respective MAUI workload sets. I use a global.json for .NET 8 MAUI applications. I agree this is probably not an SDK issue but a 9.0.306 workload issue.

**Comment by rolfbjarne** [comment]
> My guess is the presence of the .NET 10 workload is now warning you about .NET 8.

This is correct; if you have .NET 10 installed (and no `global.json`), using `net8.0-ios` won't work anymore.

You can choose to use .NET 8 (or .NET 9) using a `global.json` file, in which case `TargetFramework=net8.0-ios` should continue to work.

**Comment by RDI-Blake** [comment]
The issue is described in better detail here. It pertains to ios workload 9.0.306. https://github.com/dotnet/macios/issues/24057

**Comment by mfkl** [comment]
Can repro. For context:
- I build a variety of older and newer targets (including net9).
- I have a global.json with NET9 SDK pinned.
- I use MSBuild.Sdk.Extras.
- I use SLNX so I need NET9+ SDK.

Azure devops CI started failing on October 14th with error `NETSDK1202` without any code change on my part. Would be nice to know what environment change causes this error so I can revert it.

Adding `<CheckEolWorkloads>false</CheckEolWorkloads>` led to a different error (which sounds like an SDK bug to me)

```
/Users/runner/hostedtoolcache/dotnet/sdk/9.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(259,5): error NETSDK1140: 1.0 is not a valid TargetPlatformVersion for ios. Valid versions include: [/Users/runner/work/1/s/src/LibVLCSharp.MAUI/LibVLCSharp.MAUI.csproj::TargetFramework=net8.0-ios]
/Users/runner/hostedtoolcache/dotnet/sdk/9.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(259,5): error NETSDK1140: None [/Users/runner/work/1/s/src/LibVLCSharp.MAUI/LibVLCSharp.MAUI.csproj::TargetFramework=net8.0-ios]
/Users/runner/hostedtoolcache/dotnet/sdk/9.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(259,5): error NETSDK1140: 1.0 is not a valid TargetPlatformVersion for ios. Valid versions include: [/Users/runner/work/1/s/src/LibVLCSharp/LibVLCSharp.csproj::TargetFramework=net8.0-ios]
/Users/runner/hostedtoolcache/dotnet/sdk/9.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(259,5): error NETSDK1140: None [/Users/runner/work/1/s/src/LibVLCSharp/LibVLCSharp.csproj::TargetFramework=net8.0-ios]
/Users/runner/hostedtoolcache/dotnet/sdk/9.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(259,5): error NETSDK1140: 1.0 is not a valid TargetPlatformVersion for macos. Valid versions include: [/Users/runner/work/1/s/src/LibVLCSharp/LibVLCSharp.csproj::TargetFramework=net8.0-macos]
/Users/runner/hostedtoolcache/dotnet/sdk/9.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(259,5): error NETSDK1140: None [/Users/runner/work/1/s/src/LibVLCSharp/LibVLCSharp.csproj::TargetFramework=net8.0-macos]
/Users/runner/hostedtoolcache/dotnet/sdk/9.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(259,5): error NETSDK1140: 1.0 is not a valid TargetPlatformVersion for tvos. Valid versions include: [/Users/runner/work/1/s/src/LibVLCSharp/LibVLCSharp.csproj::TargetFramework=net8.0-tvos]
/Users/runner/hostedtoolcache/dotnet/sdk/9.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(259,5): error NETSDK1140: None [/Users/runner/work/1/s/src/LibVLCSharp/LibVLCSharp.csproj::TargetFramework=net8.0-tvos]
```

Attempting to set `TargetPlatformVersion` or supportedOSVersion failed.

Attempting to set workloadVersion like so (with match main sdk version):
```
{
  "sdk": {
    "workloadVersion": "9.0.305"
  }
}
```

Also fails since it's incompatible with MSBuild.Extras.

```
[error]src/LibVLCSharp/LibVLCSharp.csproj(0,0): Error MSB4242: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "MSBuild.Sdk.Extras". Exception: "System.IO.FileNotFoundException: Workload version 9.0.305, which was specified in /home/vsts/work/1/s/src/global.json, was not found. Run "dotnet workload restore" to install this workload version.
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.GetManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.LoadManifestsFromProvider(IWorkloadManifestProvider manifestProvider)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.InitializeManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.TryGetPackInfo(WorkloadPackId packId)
   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, IWorkloadManifestProvider manifestProvider, IWorkloadResolver workloadResolver)
   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userProfileDir, String globalJsonPath)
   at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory factory)
   at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IReadOnlyList`1 resolvers, Int32 submissionId, SdkReference sdk, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStudio, SdkResult& sdkResult, IEnumerable`1& errors, IEnumerable`1& warnings)""
```

Everything still runs fine locally but I've lost 2 days so far attempting to fix the CI.

**Comment by ajklotz** [comment]
I am back in this situation after I thought we resolved it by pinning some values in a global.json file of the project, that seemed to fix it, but the problem returned again. It was discussed here https://github.com/actions/runner-images/issues/13177#issuecomment-3411632857
