### ISSUE TITLE
TwitchDownloaderCLI.exe crashes when saving to APFS volume on Windows

### ISSUE THREAD

**Issue by superbonaci** [dotnet/sdk#36218]
Issue originated here: https://github.com/lay295/TwitchDownloader/issues/866
```
E:\> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.415
 Commit:    6963d2d1e0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.415\

Host:
  Version:      7.0.12
  Architecture: x64
  Commit:       4a824ef37c

.NET SDKs installed:
  6.0.415 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

To reproduce clone and compile the .NET program `TwitchDownloader` mentioned on top:
1. Format any USB storage device as APFS (Apple filesystem), from MacOS or other way.
2. Connect the USB memory to Windows, and mount it as a drive with APFS for [Windows by Paragon Software](https://www.paragon-software.com/home/apfs-windows/).
3. Copy TwitchDownloader.exe to drive and make TMP.
4. Open the command prompt 
5. cd to drive and run TwitchDownloader.exe
6. Check that always fails:
```
.\TwitchDownloaderCLI.exe videodownload -u 'https://www.twitch.tv/videos/1268600556' -q best --temp-path .\TMP\ -o output.mp4
TwitchDownloaderCLI 1.53.4 Copyright (c) lay295 and contributors
[STATUS] - Fetching Video Info [1/5]Unhandled exception. System.AggregateException: One or more errors occurred. (An invalid argument was supplied. (gql.twitch.tv:443))
 ---> System.Net.Http.HttpRequestException: An invalid argument was supplied. (gql.twitch.tv:443)
 ---> System.Net.Sockets.SocketException (10022): An invalid argument was supplied.
   at System.Net.Sockets.Socket..ctor(AddressFamily , SocketType , ProtocolType )
   at System.Net.Sockets.Socket..ctor(SocketType , ProtocolType )
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String , Int32 , HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage )
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken )
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage , Boolean , Boolean , CancellationToken )
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage , Boolean , CancellationToken )
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at TwitchDownloaderCore.TwitchHelper.GetVideoInfo(Int32 videoId)
   at TwitchDownloaderCore.VideoDownloader.DownloadAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean )
   at System.Threading.Tasks.Task.Wait(Int32 , CancellationToken )
   at System.Threading.Tasks.Task.Wait()
   at TwitchDownloaderCLI.Modes.DownloadVideo.Download(VideoDownloadArgs inputOptions)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at TwitchDownloaderCLI.Program.Main(String[] args)
```
Couple screenshots

![SSD1](https://github.com/lay295/TwitchDownloader/assets/8339596/d50ba5e1-6341-4ef8-b749-3702cc4f048c)

![SSD2](https://github.com/lay295/TwitchDownloader/assets/8339596/c52047c3-d0e5-4ad7-ab7a-dd9b5cfcdc3b)

**Comment by superbonaci** [comment]
Could happen to HFS/HFS+ too:
[HFS+ for Windows by Paragon Software](https://www.paragon-software.com/home/hfs-windows/)

**Comment by superbonaci** [comment]
> Does it also fail if the exe file is in the APFS volume but you tell it to save the video to an NTFS volume?
> 
> It seems bizarre to me that a file system driver would cause a socket exception; but if the executable file is on the file system in question, I imagine the driver could have an opportunity to corrupt something.
> 
> How about if you reboot the computer between copying the exe to APFS and running it? So that the driver has to page in the file content from the APFS volume instead of relying on data cached from the write operation. If that makes a difference, then maybe it gives a hint of where the problem is.

Before and after reboot, fails if the executable file is in the apfs drive.
If it's in the ntfs volume, the other files can be in either place and it works.

Checking with `Procmon64.exe`, it can be launched if executed from PowerShell, but double click from Windows Explorer shows error:

**Comment by superbonaci** [comment]
TwitchDownloaderCLI can write to apfs but fails as soon as tries to connect to the internet.
https://github.com/lay295/TwitchDownloader/issues/866

**Comment by marcpopMSFT** [comment]
Old issue triage: this is not an sdk issue, could be runtime but should be investigated in twitchdownloader first.
