### ISSUE TITLE
8.0.100 SDK installed by `dotnet-install.sh` contains rc2 files

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/sdk#36884]
### Describe the bug

Installing `8.0.100` with https://dot.net/v1/dotnet-install.sh contains rc2 files for mobile workloads, which prevents from installing 8.0.100 workloads.

<img width="325" alt="image" src="https://github.com/dotnet/sdk/assets/5839577/52b80f60-4800-42ed-8b95-3ef86a202871">

<img width="350" alt="image" src="https://github.com/dotnet/sdk/assets/5839577/e4424915-a1c0-49bd-9ab8-3fceb9a2cf72">

### To Reproduce

using a rollback file:
```
{
    "microsoft.net.sdk.android": "34.0.43/8.0.100",
    "microsoft.net.sdk.ios": "17.0.8478/8.0.100",
    "microsoft.net.sdk.maccatalyst": "17.0.8478/8.0.100",
    "microsoft.net.sdk.macos": "14.0.8478/8.0.100",
    "microsoft.net.sdk.maui": "8.0.3/8.0.100"
}
```

Run the following
```
sh "dotnet-install.sh" --install-dir "/Users/runner/.dotnet" --version "8.0.100"
dotnet workload install --from-rollback-file "fileabove.json" android ios maccatalyst macos maui --source 
"https://api.nuget.org/v3/index.json"
```

### Result

```
Unhandled exception: Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Could not find workload 'microsoft-net-runtime-android-net7' extended by workload 'android' in manifest 'microsoft.net.sdk.android' [/Users/runner/.dotnet/sdk-manifests/8.0.100-rc.2/microsoft.net.sdk.android/34.0.0-rc.2.468/WorkloadManifest.json]
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.<>c__DisplayClass26_0.<<EnumerateWorkloadWithExtends>g__EnumerateWorkloadWithExtendsRec|0>d.MoveNext()
   at System.Linq.Enumerable.AppendPrependIterator`1.LoadFromEnumerator()
   at System.Linq.Enumerable.AppendPrepend1Iterator`1.MoveNext()
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.GetAvailableWorkloadDefinitions()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand.ValidateWorkloadIdsInput()
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolverFactory workloadResolverFactory, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String tempDirPath, IReadOnlyCollection`1 workloadIds)
   at Microsoft.DotNet.Cli.WorkloadInstallCommandParser.<>c.<ConstructCommand>b__6_0(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

### Further technical details
Running in latest github actions, with 8.0.100 installed.

**Comment by jeromelaban** [comment]
Update, @jonathanpeppers (thanks for the help!) suggested running without a rollback file, and the error stays the same:

```
dotnet workload install android ios maccatalyst macos maui --source "https://api.nuget.org/v3/index.json"
```
Yields:
```
Unhandled exception: Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Could not find workload 'microsoft-net-runtime-android-net7' extended by workload 'android' in manifest 'microsoft.net.sdk.android' [/Users/runner/.dotnet/sdk-manifests/8.0.100-rc.2/microsoft.net.sdk.android/34.0.0-rc.2.468/WorkloadManifest.json]
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.<>c__DisplayClass26_0.<<EnumerateWorkloadWithExtends>g__EnumerateWorkloadWithExtendsRec|0>d.MoveNext()
   at System.Linq.Enumerable.AppendPrependIterator`1.LoadFromEnumerator()
   at System.Linq.Enumerable.AppendPrepend1Iterator`1.MoveNext()
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.GetAvailableWorkloadDefinitions()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand.ValidateWorkloadIdsInput()
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolverFactory workloadResolverFactory, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String tempDirPath, IReadOnlyCollection`1 workloadIds)
   at Microsoft.DotNet.Cli.WorkloadInstallCommandParser.<>c.<ConstructCommand>b__6_0(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

**Comment by jeromelaban** [comment]
After digging further down the issue, this behavior was caused by a old workaround from before .NET 6.0 (https://github.com/Redth/dotnet-maui-check/blob/c34fea4df460c495c3f57be03f4f1ce771c6314a/MauiCheck/DotNet/DotNetWorkloadManager.cs#L35). It cause workloads to be incorrectly cleaned and fails this way.

Removing this old workaround fixes the issue.

Apologies for the disturbance!
