### ISSUE TITLE
.NET 7->8 SDK upgrade breaks the build (in the Microsoft.VisualStudio.Extensibility.Build package)

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#37112]
`dotnet build` worked on our solution until we switched from the .NET 7 SDK to the .NET 8 SDK. Then we saw this:

```
C:\.tools\.nuget\packages\microsoft.visualstudio.extensibility.build\17.7.119-preview-2\build\Microsoft.VisualStudio.Extensibility.Build.targets(26,3): error MSB4018: The "WriteDeploymentAssetsManifest" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Newtonsoft.Json.Serialization.JsonTypeReflector.get_DynamicCodeGeneration()
   at Newtonsoft.Json.Serialization.JsonTypeReflector.get_ReflectionDelegateFactory()
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetDefaultCreator(Type createdType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContract(Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, Formatting formatting, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonSerializerSettings settings)
   at Microsoft.VisualStudio.Extensibility.Deploy.DeploymentManifestSerializer.Serialize(TextWriter writer, DeploymentManifest manifest)
   at Microsoft.VisualStudio.Extensibility.Build.Tasks.WriteDeploymentAssetsManifest.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\andarno\source\repos\VisualStudio.Conversations\src\Conversations.Service.Indexing\Conversations.Service.Indexing.csproj]
```

Because I use global.json to pin the SDK version, I detected this problem as a direct result of the SDK upgrade, and could hold off the upgrade until the Microsoft.VisualStudio.Extensibility.Build package issue was resolved (they already had found [the bug]((https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1906399)) and fixed it in a later version). 
Had I left the SDK un-pinned, this would have caused failures unpredictably in pipelines and on our dev machines around the team, and it would have taken a lot longer to understand why the build was failing.

I'm filing this mostly for awareness as the .NET team requested that I file issues whenever an SDK upgrade breaks our build.

**Comment by marcpopMSFT** [comment]
Old issue triage: 7 is out of support so closing. Let us know if this impacts a later upgrade.
