### ISSUE TITLE
Cannot load plugins with external dependencies in plugin interface

### ISSUE THREAD

**Issue by cezarypiatek** [dotnet/sdk#3814]
I'm having trouble with loading plugin that contains an external dependency in the plugin interface. Let's say that PluginBase project depends on System.Collections.Immutable package and my plugin interface looks as follows:

```csharp
public interface ICommand
    {
        string Name { get; }
        string Description { get; }
        int Execute(ImmutableArray&lt;string&gt; input);
    }
```
When I try to load my plugin type I'm getting the following exeception:

```
System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
Method 'Execute' in type 'PluginArchitectureDemo.SamplePlugins' from assembly 'PluginArchitectureDemo.SamplePlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

Here is a repository with a solution that reproduces that problem https://github.com/cezarypiatek/PluginArchitectureDemo - just run PluginArchitectureDemo with a path to PluginArchitectureDemo.SamplePlugins.dll as the parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06023407-704f-0ace-e89a-eedd9f95a007
* Version Independent ID: f25a6e1a-cb10-867b-0522-a377bf9d016b
* Content: [Create a .NET Core application with plugins - .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support#feedback)
* Content Source: [docs/core/tutorials/creating-app-with-plugin-support.md](https://github.com/dotnet/docs/blob/master/docs/core/tutorials/creating-app-with-plugin-support.md)
* Product: **dotnet-core**
* GitHub Login: @jkoritzinsky
* Microsoft Alias: **jekoritz**

**Comment by vitek-karas** [comment]
In the plugin's project please add `<ExcludeAssets>runtime</ExcludeAssets>` next to the `<Private>false</Private>`. Should look like this:
``` XML
  <ItemGroup>
    <ProjectReference Include="..\PluginArchitectureDemo.Contracts\PluginArchitectureDemo.Contracts.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
```

After that make sure you delete the output folder for the plugin (so that any left-over files are gone). With this change it works for me.

This is an issue we've learned about recently, I'm still working on putting some form to it and filing the right issues.

**Comment by livarcocc** [comment]
Let us know if @vitek-karas' suggestion works for you.

**Comment by vitek-karas** [comment]
Since whatever happens on the SDK side, it is unlikely to be fixed for 3.0 I filed these to update the docs:
https://github.com/dotnet/docs/issues/15811 to update the guide
https://github.com/dotnet/samples/issues/1760 to update the sample

**Comment by cezarypiatek** [comment]
The following way of referencing plugin contract package seems to solve the problem

```xml
 <PackageReference 
    Include="PluginArchitectureDemo.Contract" 
    PrivateAssets="all" 
    ExcludeAssets="runtime" 
    Private="true"
    Version="1.0.0" />
```

**Comment by cezarypiatek** [comment]
Changing these attributes doesn't seem to solve the issue

**Comment by vitek-karas** [comment]
@cezarypiatek Could you please describe in more detail what is the exact failure you get after the suggested workaround?

I cloned your repo https://github.com/cezarypiatek/PluginArchitectureDemo and made one change in the `PluginArchitectureDemo.SamplePlugins.csproj` adding the `<ExcludeAssets>runtime</ExcludeAssets>` metadata to the project reference, like this:
``` XML
  <ItemGroup>
    <ProjectReference Include="..\PluginArchitectureDemo.Contracts\PluginArchitectureDemo.Contracts.csproj">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>
```

Then I *Rebuild* the entire solution and the ran it - it works just fine for me.

**Comment by moh-hassan** [comment]
I tested the [project](https://github.com/cezarypiatek/PluginArchitectureDemo) and did the modification suggested by [@vitek-karas](https://github.com/dotnet/sdk/issues/3814#issuecomment-560403409) 
and I can confirm that it's working fine.

**Comment by ljani** [comment]
Does this help with reproduction:
https://github.com/ljani/dotnet-sdk-3814

I cleanup the sample a little bit and added some methods. Now it fails:

```text
temp > git clone https://github.com/ljani/dotnet-sdk-3814.git
Cloning into 'dotnet-sdk-3814'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 45 (delta 17), reused 38 (delta 13), pack-reused 0
Receiving objects: 100% (45/45), 8.33 KiB | 2.08 MiB/s, done.
Resolving deltas: 100% (17/17), done.
temp > cd .\dotnet-sdk-3814\
dotnet-sdk-3814 ❯❯❯ dotnet build
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\temp\dotnet-sdk-3814\PluginBase\PluginBase.csproj (in 170 ms).
  Restored C:\temp\dotnet-sdk-3814\HelloPlugin\HelloPlugin.csproj (in 170 ms).
  Restored C:\temp\dotnet-sdk-3814\AppWithPlugin\AppWithPlugin.csproj (in 170 ms).
  PluginBase -> C:\temp\dotnet-sdk-3814\PluginBase\bin\Debug\net5\PluginBase.dll
  HelloPlugin -> C:\temp\dotnet-sdk-3814\HelloPlugin\bin\Debug\net5\HelloPlugin.dll
  AppWithPlugin -> C:\temp\dotnet-sdk-3814\AppWithPlugin\bin\Debug\net5\AppWithPlugin.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.33
dotnet-sdk-3814 > dotnet run --project AppWithPlugin
Loading commands from: C:\temp\dotnet-sdk-3814\HelloPlugin\bin\Debug\net5\HelloPlugin.dll
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'ConfigureServices' in type 'HelloPlugin.HelloCommand' from assembly 'HelloPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at AppWithPlugin.Program.CreateCommands(Assembly assembly)+MoveNext() in C:\temp\dotnet-sdk-3814\AppWithPlugin\Program.cs:line 84
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AppWithPlugin.Program.Main(String[] args) in C:\temp\dotnet-sdk-3814\AppWithPlugin\Program.cs:line 27
System.TypeLoadException: Method 'ConfigureServices' in type 'HelloPlugin.HelloCommand' from assembly 'HelloPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

I thought it was because `System.CommandLine.Hosting` tries to pull v3.1.5 libs, but adding `<PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />` did not help. I did not have time to investigate this further.

**Comment by baronfel** [comment]
Closing because Vitek shared the correct resolution: for plugin components, the 'contracts' that the plugin compiles against need to exclude their runtime assets, and the plugin components' own dependencies need to be marked Private so that they are bundled as part of the publish output.
