### ISSUE TITLE
[9.0.100-alpha.1.24073.1] `dotnet workload install` fails for any workload on latest .NET 9 SDK

### ISSUE THREAD

**Issue by lbussell** [dotnet/sdk#38202]
### To Reproduce
With .NET SDK 9.0.100-alpha.1.24073.1, run the following

```
> dotnet workload install wasm-tools
```

It gives the exception below. It happens no matter which workload you specify. `dotnet workload install foo` will give the same exception.

### Exceptions (if any)
```
Unhandled exception: Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Could not find workload 'microsoft-net-runtime-android-net8' extended by workload 'android' in manifest 'microsoft.net.sdk.android' [/usr/share/dotnet/sdk-manifests/9.0.100-alpha.1/microsoft.net.sdk.android/34.99.0-preview.1.109/WorkloadManifest.json]
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.<>c__DisplayClass26_0.<<EnumerateWorkloadWithExtends>g__EnumerateWorkloadWithExtendsRec|0>d.MoveNext()
   at System.Linq.Enumerable.AppendPrependIterator`1.LoadFromEnumerator()
   at System.Linq.Enumerable.AppendPrepend1Iterator`1.MoveNext()
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.GetAvailableWorkloadDefinitions()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand.ValidateWorkloadIdsInput()
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadInstallCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolverFactory workloadResolverFactory, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String tempDirPath, IReadOnlyCollection`1 workloadIds)
   at Microsoft.DotNet.Cli.WorkloadInstallCommandParser.<>c.<ConstructCommand>b__6_0(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```
### Further technical details

Content of `/usr/share/dotnet/sdk-manifests/9.0.100-alpha.1/microsoft.net.sdk.android/34.99.0-preview.1.109/WorkloadManifest.json`

```
{
  "version": "34.99.0-preview.1.109",
  "workloads": {
    "android": {
      "description": ".NET SDK Workload for building Android applications.",
      "packs": [
        "Microsoft.Android.Sdk.net9",
        "Microsoft.Android.Sdk.net8",
        "Microsoft.Android.Ref.34",
        "Microsoft.Android.Runtime.34.android-arm",
        "Microsoft.Android.Runtime.34.android-arm64",
        "Microsoft.Android.Runtime.34.android-x86",
        "Microsoft.Android.Runtime.34.android-x64",
        "Microsoft.Android.Templates"
      ],
      "platforms": [ "win-x64", "win-arm64", "linux-x64", "linux-arm64", "osx-x64", "osx-arm64" ],
      "extends" : [
        "microsoft-net-runtime-android-net8",
        "microsoft-net-runtime-android-aot-net8",
        "microsoft-net-runtime-android",
        "microsoft-net-runtime-android-aot"
      ]
    }
  },
  "packs": {
    "Microsoft.Android.Sdk.net9": {
      "kind": "sdk",
      "version": "34.99.0-preview.1.109",
      "alias-to": {
        "osx-x64": "Microsoft.Android.Sdk.Darwin",
        "osx-arm64": "Microsoft.Android.Sdk.Darwin",
        "win-x86": "Microsoft.Android.Sdk.Windows",
        "win-x64": "Microsoft.Android.Sdk.Windows",
        "win-arm64": "Microsoft.Android.Sdk.Windows",
        "linux-x64": "Microsoft.Android.Sdk.Linux",
        "linux-arm64": "Microsoft.Android.Sdk.Linux"
      }
    },
    "Microsoft.Android.Sdk.net8": {
      "kind": "sdk",
      "version": "34.0.56",
      "alias-to": {
        "osx-x64": "Microsoft.Android.Sdk.Darwin",
        "osx-arm64": "Microsoft.Android.Sdk.Darwin",
        "win-x86": "Microsoft.Android.Sdk.Windows",
        "win-x64": "Microsoft.Android.Sdk.Windows",
        "win-arm64": "Microsoft.Android.Sdk.Windows",
        "linux-x64": "Microsoft.Android.Sdk.Linux",
        "linux-arm64": "Microsoft.Android.Sdk.Linux"
      }
    },
    "Microsoft.Android.Ref.34": {
      "kind": "framework",
      "version": "34.99.0-preview.1.109"
    },
    "Microsoft.Android.Runtime.34.android-arm": {
      "kind": "framework",
      "version": "34.99.0-preview.1.109"
    },
    "Microsoft.Android.Runtime.34.android-arm64": {
      "kind": "framework",
      "version": "34.99.0-preview.1.109"
    },
    "Microsoft.Android.Runtime.34.android-x86": {
      "kind": "framework",
      "version": "34.99.0-preview.1.109"
    },
    "Microsoft.Android.Runtime.34.android-x64": {
      "kind": "framework",
      "version": "34.99.0-preview.1.109"
    },
    "Microsoft.Android.Templates": {
      "kind": "template",
      "version": "34.99.0-preview.1.109"
    }
  }
}
```

- Include the output of `dotnet --info`

```
.NET SDK:
 Version:           9.0.100-alpha.1.24073.1
 Commit:            ae420bd385
 Workload version:  9.0.100-manifests.294a842f

Runtime Environment:
 OS Name:     debian
 OS Version:  12
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/9.0.100-alpha.1.24073.1/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.1.24072.9
  Architecture: x64
  Commit:       cd0a72c860

.NET SDKs installed:
  9.0.100-alpha.1.24073.1 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.2.24072.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.1.24072.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by marcpopMSFT** [comment]
Try a newer build. Runtime had updated to preview branding but the SDK had not yet. This should either be resolved with the branding update to install or resolved once the branding update to sdk flows through.
