### ISSUE TITLE
Warning: Workload garbage collection failed with error: Failed to remove Microsoft.Emscripten Error: 0x00000643. Fatal error during installation.

### ISSUE THREAD

**Issue by WhitWaldo** [dotnet/sdk#38280]
### Describe the bug
I'm trying to install the .NET Aspire workload. When I run `dotnet workload install aspire` in an elevated command prompt, it reads:
> PS C:\Users\whit_> dotnet workload install aspire

> Removing Microsoft.NET.Runtime.Emscripten.3.1.12.Cache.win-x64.Msi.x64 ...... Failed
Warning: Workload garbage collection failed with error: Failed to remove Microsoft.Emscripten.3.1.12.Cache.win-x64.7.0.3-x64.msi. Error: 0x00000643. Fatal error during installation..

> Successfully installed workload(s) aspire.

If I list aspire, it shows up. That's great, but why is this other package haunting my workload actions? If I run `dotnet workload update`, I get the following:
> PS C:\Users\whit_> dotnet workload update

> Updated advertising manifest microsoft.net.workload.emscripten.current.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.workload.mono.toolchain.net7.
Updated advertising manifest microsoft.net.workload.emscripten.net7.
Updated advertising manifest microsoft.net.sdk.aspire.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.workload.mono.toolchain.net6.
Updated advertising manifest microsoft.net.workload.mono.toolchain.current.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.workload.emscripten.net6.
Updated advertising manifest microsoft.net.sdk.ios.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Removing Microsoft.NET.Runtime.Emscripten.3.1.12.Cache.win-x64.Msi.x64 ...... Failed
Warning: Workload garbage collection failed with error: Failed to remove Microsoft.Emscripten.3.1.12.Cache.win-x64.7.0.3-x64.msi. Error: 0x00000643. Fatal error during installation..

> Successfully updated workload(s): aspire.

I tried running the cleanup utility: `dotnet workload clean`:

> PS C:\Users\whit_> dotnet workload clean
Removing Microsoft.NET.Runtime.Emscripten.3.1.12.Cache.win-x64.Msi.x64 ...... Failed
Unhandled exception: Microsoft.DotNet.Workloads.Workload.WorkloadException: Failed to remove Microsoft.Emscripten.3.1.12.Cache.win-x64.7.0.3-x64.msi. Error: 0x00000643. Fatal error during installation.
   at Microsoft.DotNet.Installer.Windows.InstallerBase.ExitOnError(UInt32 error, String message)
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkMsiInstallerClient.RemoveWorkloadPacks(List`1 packsToRemove, Nullable`1 offlineCache)
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkMsiInstallerClient.GarbageCollect(Func`2 getResolverForWorkloadSet, Nullable`1 offlineCache, Boolean cleanAllPacks)
   at Microsoft.DotNet.Workloads.Workload.Clean.WorkloadCleanCommand.ExecuteGarbageCollection()
   at Microsoft.DotNet.Cli.WorkloadCleanCommandParser.<>c.<ConstructCommand>b__3_0(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)

Thoughts?

### To Reproduce
I have no idea what caused this - only that I can't seem to get rid of it. Happy to provide any logs if you can tell me how to get them.

### Exceptions (if any)
> Removing Microsoft.NET.Runtime.Emscripten.3.1.12.Cache.win-x64.Msi.x64 ...... Failed
Unhandled exception: Microsoft.DotNet.Workloads.Workload.WorkloadException: Failed to remove Microsoft.Emscripten.3.1.12.Cache.win-x64.7.0.3-x64.msi. Error: 0x00000643. Fatal error during installation.
   at Microsoft.DotNet.Installer.Windows.InstallerBase.ExitOnError(UInt32 error, String message)
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkMsiInstallerClient.RemoveWorkloadPacks(List`1 packsToRemove, Nullable`1 offlineCache)
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkMsiInstallerClient.GarbageCollect(Func`2 getResolverForWorkloadSet, Nullable`1 offlineCache, Boolean cleanAllPacks)
   at Microsoft.DotNet.Workloads.Workload.Clean.WorkloadCleanCommand.ExecuteGarbageCollection()
   at Microsoft.DotNet.Cli.WorkloadCleanCommandParser.<>c.<ConstructCommand>b__3_0(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)

### Further technical details
- Include the output of `dotnet --info`

PS C:\Users\whit_> dotnet --info
.NET SDK:
 Version:           8.0.200-preview.23624.5
 Commit:            8065b9770c
 Workload version:  8.0.200-manifests.ba313bcd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200-preview.23624.5\

.NET workloads installed:
 Workload version: 8.0.200-manifests.ba313bcd
 [aspire]
   Installation Source: SDK 8.0.200-preview.23624, VS 17.9.34518.117
   Manifest Version:    8.0.0-preview.2.23619.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0-preview.2.23619.3\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.8.34511.84, VS 17.9.34518.117
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.8.34511.84, VS 17.9.34518.117
   Manifest Version:    34.0.52/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.52\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.8.34511.84, VS 17.9.34518.117
   Manifest Version:    8.0.3/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.3\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.8.34511.84, VS 17.9.34518.117
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8004\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.405 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.321 [C:\Program Files\dotnet\sdk]
  6.0.418 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]
  8.0.101 [C:\Program Files\dotnet\sdk]
  8.0.200-preview.23624.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
- Elevated Powershell terminal 7.3.11

**Comment by WhitWaldo** [comment]
Further, I'm not entirely sure aspire is installed correctly even though all the messages say so and it's in the workload list. This is because in VS when I try to build an Aspire app, it indicates that aspire isn't installed and prompts me to run `dotnet workload restore`. Here's the output of that:

> PS L:\Code\aspire-samples\samples\AspireWithDapr\AspireWithDapr.AppHost> dotnet workload restore
Installing workloads: aspire
Installing Aspire.Hosting.Orchestration.win-x64.Msi.x64 ............ Done
Installing Aspire.Hosting.Msi.x64 ..... Done
Removing Microsoft.NET.Runtime.Emscripten.3.1.12.Cache.win-x64.Msi.x64 ....... Failed
Warning: Workload garbage collection failed with error: Failed to remove Microsoft.Emscripten.3.1.12.Cache.win-x64.7.0.3-x64.msi. Error: 0x00000643. Fatal error during installation..

> Successfully installed workload(s) aspire.

And yet, when rebuilding again:
![image](https://github.com/dotnet/sdk/assets/2238529/c4db3df6-14e5-42ca-9bc9-7a70af6dfc00)

It seems like this fatal error is interrupting everything. How can I manually remove whatever the tool is failing to do here so I can get a fresh start?
