### ISSUE TITLE
Different .NET 8 runtime behaviour based on different SDK used

### ISSUE THREAD

**Issue by mashbrno** [dotnet/sdk#38325]
### Describe the bug
Using other SDK than Jammy cause following application to fail at runtime. Build behaviour reproducible on both MacOS (arm64) and Windows (amd64).

### To Reproduce
Simple application in .NET 8

``` c#
await new HttpClient().GetAsync("https://ws.pharmos.cz/wssupp/SupplierWS.asmx");
Console.WriteLine("success");
```

with `Dockerfile`

``` Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS publish
WORKDIR /src
COPY . .
RUN dotnet publish "Test.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Test.dll"]
```

SslLabs didn't show any issues with server certificate. With another URL like `https://example.com` it works.
Executing out of process command `Process.Start("/bin/bash" , "-c \"apt update && apt install curl -y && curl -v https://ws.pharmos.cz/wssupp/SupplierWS.asmx\"").WaitForExit();` also succeeds.

### Exceptions
During runtime of the built image.

```
Unhandled exception. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
```

### Workaround
Unfortunatelly even if this seems to be related to SSL, overriding `ServicePointManager.ServerCertificateValidationCallback` doesn't help, because the exception raises before this handler is called.

No changes in the project itself, just to change SDK which is used to build the image to `FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy AS publish`

**Comment by MiYanni** [comment]
@mashbrno Do you still have problems with this?

**Comment by mashbrno** [comment]
No, I used the workaround and didn't check whether it is accidentally fixed. Now I use SDK 9 and there is no such behavior.

**Comment by mashbrno** [comment]
The issue still persists. I've finished to upgrade my application to .NET 9 runtime and there is no `jammy` base image anymore. Reproducible sample:

``` Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

RUN echo 'await new System.Net.Http.HttpClient().GetStringAsync("https://ws.pharmos.cz/wssupp/SupplierWS.asmx");' > Program.cs
RUN echo '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework></PropertyGroup></Project>' > test.csproj
RUN dotnet build -o /app

# EOF Received an unexpected EOF or 0 bytes from the transport stream
#FROM mcr.microsoft.com/dotnet/runtime:8.0

# CORRECT 401 (Unauthorized)
FROM  mcr.microsoft.com/dotnet/runtime:8.0-jammy
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "test.dll"]
```

The issue is in the underlying OS image. Ubuntu 22.04 jammy is the only working. None of the .NET9 images work. I had to create one based on jammy Ubuntu to make my app run at .NET 9.

Still uncertain about the core problem. When I call `curl -vvvv https://ws.pharmos.cz/wssupp/SupplierWS.asmx` at any of existing images it works, TLS 1.2 connection established, certificate is valid, just .NET runtime doesn't coop.

**Comment by panagiotis-kanavos** [comment]
This isn't an OS or .NET issue at all. `curl -vvvv` shows the site uses the [weak cipher](https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA/)  `ECDHE-RSA-AES256-SHA` which, as documented in [Default TLS cipher suites for .NET on Linux](https://learn.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux) isn't enabled by default. 

Until the site upgrades its ciphers applications can use the documented workaround and specify the weak cipher through a `CipherSuitesPolicy` : 

```
using System.Net.Security;
using System.Net.Http;

var handler = new SocketsHttpHandler
{
    SslOptions =
    {
        CipherSuitesPolicy = new CipherSuitesPolicy(
            new[]
            {
                TlsCipherSuite.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
            }),
    },
};
var client=new HttpClient(handler);

var result=await client.GetStringAsync("https://ws.pharmos.cz/wssupp/SupplierWS.asmx");
```
