### ISSUE TITLE
dotnet restore no longer supports multiple runtimes

### ISSUE THREAD

**Issue by CumpsD** [dotnet/sdk#3843]
**Repo**
```
dotnet new console
dotnet restore -r win-x64 -r linux-x64
```

**Result**
```
error NETSDK1083: The specified RuntimeIdentifier 'win-x64;linux-x64' is not recognized.
```

**Speculation**
It seems the multiple runtimes are being passed in as RuntimeIdentifier instead of RuntimeIdentifiers?

This used to work on 2.2

As a workaround I can put `<RuntimeIdentifiers>....` in the csproj and exclude the `-r` switches, but I dont really want to do this, since it means updating *a lot* of csprojs.

**Comment by flcdrg** [comment]
Just hit the same problem trying to upgrade 2.2 to 3.0

**Comment by LanceMcCarthy** [comment]
I'm quite surprised to see this is 18 monlds old.

In the latest SDK, you get the following error:

```
System.InvalidOperationException: Option '--runtime' only accepts a single argument but 3 were provided.
   at System.CommandLine.Binding.ArgumentConverter.GetValueOrDefault[T](ArgumentConversionResult result)
   at System.CommandLine.Parsing.OptionResultExtensions.GetValueOrDefault[T](OptionResult optionResult)
   at System.CommandLine.Parsing.ParseResult.ValueForOption[T](String alias)
   at Microsoft.DotNet.Cli.Telemetry.TopLevelCommandNameAndOptionToLog.AllowList(ParseResult parseResult, Dictionary`2 measurements)
``

But the documentation clearly states it should be possible:

![image](https://user-images.githubusercontent.com/3520532/115635385-9a952280-a2d9-11eb-986d-52cf91e7005b.png)

**Comment by DamienDennehy** [comment]
Also surprised to see this as still an issue, and on the docs in 2022
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore

Using Sdk 5.0.303.

**Comment by mrhelmut** [comment]
Stumbled upon this documentation for ```dotnet restore``` while trying to restore multiple RIDs at once, which lead me here.
Still up as of SDK 6.

I assume that the suggested way to restore multiple RIDs without adding them to the csproj explicitly is to ```restore``` each RID before building for that RID? (e.g. ```restore ... ; build ... ; restore ... ; build ...```)

If that is so, it seems that calling ```restore``` before each build steps sometimes loose RIDs in the ```project.assets.json``` and building will not work because ```restore``` assumes that the project is up-to-date despite missing the asked RID in the latest ```restore``` call.
Though this is likely not related to this issue directly (if it is intended to restore RIDs individually before building, I'll try to figure out a repro and open another issue).

**Comment by benediktibk** [comment]
Just ran into the same issue:

```
dotnet restore --no-dependencies --runtime linux-x64 --runtime win-x64 blub.csproj
  Determining projects to restore...
/usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'linux-x64;win-x64' is not recognized. [blub.csproj]
```

**Comment by dperez83** [comment]
@nguerrera @marcpopMSFT @dsplaisted could you please take a look at this bug that was opened in 2019 and still current. Thank you

**Comment by dperez83** [comment]
@dsplaisted or @JL03-Yue are you able to help on this issue?

I saw that you added long time ago the `string[] RuntimeIdentifiers` on the `Microsoft.NET.Build.Tasks.Microsoft.NET.Build.Tasks` class but when passing multiple RuntimeIdentifiers it receives only one string with a semicolon ("win-x86;win-x64") and that does not work and it returns the error `NETSDK1083: The specified RuntimeIdentifier '{0}' is not recognized.`

https://github.com/dotnet/sdk/blob/47d0bbabbf4d0b1744d52f9d82f861196fb13ca6/src/Tasks/Microsoft.NET.Build.Tasks/ProcessFrameworkReferences.cs#L81

The `Microsoft.DotNet.Cli.RestoreCommandParser` class on the `RestoreRuntimeArgFunc` returns the Rids as one string separated by semicolon `return $"-property:RuntimeIdentifiers={string.Join("%3B", convertedRids)}";`

https://github.com/dotnet/sdk/blob/47d0bbabbf4d0b1744d52f9d82f861196fb13ca6/src/Cli/dotnet/Commands/Restore/RestoreCommandParser.cs#L104

I am not familiar with the code of .net CLI and I tried my best to understand how the `string[] RuntimeIdentifiers` was set in the code but I could not find any reference how it is set.

Thank you!

**Comment by marcpopMSFT** [comment]
Triage: Not urgent but it looks like it's potentially an issue in the parsing. Putting in the 10 bucket in case we find time for it:
https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/Commands/Restore/RestoreCommandParser.cs#L196

**Comment by musjj** [comment]
Also having the same issue. Are there any workarounds?
