### ISSUE TITLE
Cannot install globally a .NET tool on Linux when the version contains uppercase

### ISSUE THREAD

**Issue by meziantou** [dotnet/sdk#39105]
### Describe the bug

Cannot install globally a .NET tool on Linux when the version contains an uppercase character

### To Reproduce

Be sure to run `dotnet tool update` on Linux or a case-sensitive file-system

````
dotnet new console
dotnet pack /p:PackAsTool=true /p:version=1.0.0-abc
dotnet pack /p:PackAsTool=true /p:version=1.0.0-Dummy

# ✔️ works
dotnet tool update test --version 1.0.0-abc --global --add-source ./bin/Release/

# ❌ crash
dotnet tool update test --version 1.0.0-Dummy --global --add-source ./bin/Release/
````

### Exceptions (if any)

```
Skipping NuGet package signature verification.
Unhandled exception: System.IO.FileNotFoundException: Could not find file '/home/repro/.dotnet/tools/.store/.stage/pfgaxwyq.dh2/test/1.0.0-dummy/test.1.0.0-dummy.nupkg'.
File name: '/home/repro/.dotnet/tools/.store/.stage/pfgaxwyq.dh2/test/1.0.0-dummy/test.1.0.0-dummy.nupkg'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at NuGet.Protocol.LocalFolderUtility.<>c__DisplayClass48_0.<GenerateNupkgMetadataFile>b__0()
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLocked(String filePath, Action action)
   at NuGet.Repositories.NuGetv3LocalRepository.GetPackage(String packageId, NuGetVersion version, String path)
   at NuGet.Repositories.NuGetv3LocalRepository.FindPackageImpl(String packageId, NuGetVersion version)
   at NuGet.Repositories.NuGetv3LocalRepository.FindPackage(String packageId, NuGetVersion version)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.CreateAssetFile(PackageId packageId, NuGetVersion version, DirectoryPath packagesRootPath, DirectoryPath assetFileDirectory, String runtimeJsonGraph, String targetFramework)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.<>c__DisplayClass8_0.<InstallPackage>b__0()
   at Microsoft.DotNet.Cli.TransactionalAction.Run[T](Func`1 action, Action commit, Action rollback)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.<>c__DisplayClass18_0.<Execute>b__1()
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.RunWithHandlingInstallError(Action installAction)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
   at Microsoft.DotNet.Tools.Tool.Update.ToolUpdateGlobalOrToolPathCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

### Further technical details

````
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.cdf2cc8e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.200/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.200 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
````

Was originally opened on NuGet/Home: https://github.com/NuGet/Home/issues/13275

**Comment by Forgind** [comment]
@dsplaisted,

I looked into this, and I think the problem is just because PackageId's ToString method always calls ToLowerInvariant. I tried to see why, and the commit looked like it was just a repo merge commit, not a real commit. Do you know why we're calling ToLowerInvariant here? Can we just remove that?

**Comment by Forgind** [comment]
Place with ToLowerInvariant:
https://github.com/dotnet/sdk/blob/f6c64dcc881dbda28db6747d83ab061c8713582d/src/Cli/dotnet/ToolPackage/PackageId.cs#L12

**Comment by marcpopMSFT** [comment]
Triage: Per Daniel's understanding, NuGet treats package IDs as all lowercase (CC @nkolev92 ) so there is likely a different path where we didn't lowercase it.

**Comment by marcpopMSFT** [comment]
Follow-up: Per the semver spec the ID is lowercase but the version (prerelease part) is case sensitive so probably somewhere we're treating it as lowercase when we shouldn't be.
