### ISSUE TITLE
error NETSDK1083: The specified RuntimeIdentifier 'alpine.3.19-x64' is not recognized.

### ISSUE THREAD

**Issue by mrlioncub** [dotnet/sdk#39733]
Error with SDK 7.0.407-alpine3.19:
```
#16 2.046 + dotnet ef migrations bundle -p src/DataAccess -s src/Migrator --context DatabaseContext --configuration Bundle --runtime linux-musl-x64 --self-contained --verbose -f -o /app/efbundle.exe
...
#16 10.59 Building bundle...
#16 10.60 dotnet publish --runtime alpine.3.19-x64 --output /tmp/fvrtghv3.cir/publish --self-contained
#16 11.06 MSBuild version 17.7.4+3ebbd7c49 for .NET
...
#16 11.59 /usr/share/dotnet/sdk/7.0.407/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'alpine.3.19-x64' is not recognized. [/tmp/fvrtghv3.cir/efbundle.csproj]
#16 11.64 Microsoft.EntityFrameworkCore.Tools.CommandException: Build failed. Use --verbose to see errors.
#16 11.64    at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsBundleCommand.Execute(String[] args)
#16 11.64    at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
#16 11.64    at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
#16 11.64    at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
#16 11.64 Build failed. Use --verbose to see errors.
```
But there is no error with SDK 7.0.407-alpine3.18":
```
#16 2.114 + dotnet ef migrations bundle -p src/DataAccess -s src/Migrator --context DatabaseContext --configuration Bundle --runtime linux-musl-x64 --self-contained --verbose -f -o /app/efbundle.exe
...
#16 10.56 Building bundle...
#16 10.57 dotnet publish --runtime alpine.3.18-x64 --output /tmp/j54twywc.tzr/publish --self-contained
#16 11.03 MSBuild version 17.7.4+3ebbd7c49 for .NET
#16 15.18 Done. Migrations Bundle: /app/efbundle.exe
```

**Comment by MackinnonBuck** [comment]
Removing the AspNetCore area path since this doesn't appear to be related to ASP.NET Core.

**Comment by AugustoDeveloper** [comment]
I have same issue envolving the same Runtime Identifier. When the script runs in docker container `FROM mcr.microsoft.com/dotnet/sdk:8.0.203-alpine3.18` by dockerfile:
```bash
RUN dotnet publish ./app/App.csproj -r alpine.3.18-x86_64   --self-contained -c release -o /out/ -f net8.0
```
I have the output:
```bash
/usr/share/dotnet/sdk/8.0.203/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'alpine.3.18-x86_64' is not recognized. See https://aka.ms/netsdk1083 for more information. [/src/app/App
```

**Comment by marcpopMSFT** [comment]
Triage: We're not sure about the original issue but since 7 is out of support, we'd recommend  trying 8. For the person reporting a publish issue in 8, we changed the RID graph and you need to publish for linux-musl-x64 instead of alpine.  See here for more details:
https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/rid-graph
