### ISSUE TITLE
[dotnet 3.1] dotnet new: error on Fedora 31

### ISSUE THREAD

**Issue by Eznoka** [dotnet/sdk#4014]
Hi,

Steps to reproduce:

1. On Fedora 31, up to date ('dnf distrosync --refresh'), with dotnet repo enabled.
2. Remove dotnet-sdk (3.0) and its dependencies
3. Install dotnet-sdk-3.1 (dnf)
4. Run dotnet new ...
I got the following error message, same with different 'dotnet' new options.

```
`[eznoka@fedora-fpe-home ~]$ dotnet new
Getting ready...
Object reference not set to an instance of an object.
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save(TemplateCache cacheToSave)
   at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save()
   at Microsoft.TemplateEngine.Cli.Installer.InstallPackages(IEnumerable`1 installationRequests, IList`1 nuGetSources, Boolean debugAllowDevInstall)
   at Microsoft.TemplateEngine.Cli.Installer.InstallPackages(IEnumerable`1 installationRequests)
   at Microsoft.DotNet.Tools.New.NewCommandShim.FirstRun(IEngineEnvironmentSettings environmentSettings, IInstaller installer)
   at Microsoft.TemplateEngine.Cli.New3Command.ConfigureEnvironment()
   at Microsoft.TemplateEngine.Cli.New3Command.Initialize()
   at Microsoft.TemplateEngine.Cli.New3Command.ExecuteAsync()
   at Microsoft.TemplateEngine.Cli.CommandParsing.NewCommandInputCli.<>c__DisplayClass19_0.<<OnExecute>b__0>d.MoveNext()
`
```

Result of dotnet --info:
```
[eznoka@fedora-fpe-home ~]$ dotnet --info
SDK .NET Core (reflétant tous les global.json) :
 Version:   3.1.100
 Commit:    cd82f021f4

Environnement d'exécution :
 OS Name:     fedora
 OS Version:  31
 OS Platform: Linux
 RID:         fedora.31-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  3.1.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
`
```

**Comment by Eznoka** [comment]
After installing 3.0 SDK, it works. Even after removing it anew and keeping only 3.1.
Strange.
