### ISSUE TITLE
Build break after VS updates .NET SDK and rebuild without restore

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/sdk#40228]
VS updated .NET SDK from 6.0.28 to 6.0.29, and a build (without clean or restore) started failing with:

```
C:\Program Files\dotnet\sdk\6.0.420\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(358,5): error MSB4018: The "ResolveTargetingPackAssets" task failed unexpectedly.
System.IO.FileNotFoundException: Could not find file 'C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\6.0.28\data\FrameworkList.xml'.
File name: 'C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\6.0.28\data\FrameworkList.xml'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri)
   at Microsoft.NET.Build.Tasks.ResolveTargetingPackAssets.AddItemsFromFrameworkList(FrameworkListDefinition definition, IBuildEngine4 buildEngine4, List`1 referenceItems, List`1 analyzerItems)
   at Microsoft.NET.Build.Tasks.ResolveTargetingPackAssets.Resolve(StronglyTypedInputs inputs, IBuildEngine4 buildEngine)
   at Microsoft.NET.Build.Tasks.ResolveTargetingPackAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [Q:\Repos\foo\foo.csproj]
```

This is difficult to investigate, I wish we had better diagnostics for this case.

Binlog available upon request.

**Comment by dsplaisted** [comment]
@joeloff @marcpopMSFT Any thoughts here?  It sounds like the ASP.NET targeting pack (and maybe all of the targeting packs) got updated to 6.0.29 (and 6.0.28 was removed), but the .NET SDK was not updated to 6.0.421.

I think there are some install logs you can gather that could help @joeloff investigate.

**Comment by joeloff** [comment]
I'm following up offline

**Comment by KirillOsenkov** [comment]
Regardless of the potential installer bug, this shouldn't crash, but instead emit a nice error:

```
You're using SDK '6.0.420', and it specifies the LatestRuntimeFrameworkVersion='6.0.28', however the '6.0.28' targeting pack couldn't be found in 'C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\6.0.28'. It's likely that you need to install the latest version of the .NET SDK or update your Visual Studio.
```

**Comment by joeloff** [comment]
Based on the logs, the previous version of VS installed the 6.0 runtime component, which includes targeting packs. Those got removed as part of updating VS since the new VS version carried the 6.0.29 copies. I see logs for installing 6.0.421, but they all indicate that the install was cancelled and not completed.

I don't see any event logs that show that 6.0.420 was installed or removed.

Any chance you used the zip files to install 6.0.420 under Program Files?

**Comment by KirillOsenkov** [comment]
unlikely, we may have a script that pulls down the SDK but it would just use the installer I think
