### ISSUE TITLE
Root .resources.dll from transitive PackageReference not copied to build output

### ISSUE THREAD

**Issue by NightOwl888** [dotnet/sdk#40834]
### Describe the bug

When a NuGet package includes a root `.resources.dll` and is subsequently specified as a transitive PackageReference dependency then referenced by a project via PackageReference, the build output won't contain the root `.resources.dll` file. However, it does contain the localized `.resources.dll` files.

If the exact same PackageReference is directly referenced from the consuming project (that is, not transitive), the root `.resources.dll` file is then correctly included in the build output.

### To Reproduce

I have setup a repro at https://github.com/NightOwl888/IssueTransitiveSatelliteAssembly

To reproduce the error, run `dotnet test -c Debug` from the package root. You will receive the stack trace:

```console
F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly>dotnet test -c Debug
  Determining projects to restore...
  All projects are up-to-date for restore.
  IssueTransitiveSatelliteAssembly.Tests -> F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly\IssueTran
  sitiveSatelliteAssembly.Tests\bin\Debug\net8.0\IssueTransitiveSatelliteAssembly.Tests.dll
Test run for F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly\IssueTransitiveSatelliteAssembly.Tests\bin\Debug\net8.0\IssueTransitiveSatelliteAssembly.Tests.dll (.NETCoreApp,Version=v8.0)
Microsoft (R) Test Execution Command Line Tool Version 17.8.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed Test [19 ms]
  Error Message:
   System.IO.FileNotFoundException : Could not load file or assembly 'ICU4N.resources, Version=60.0.0.0, Culture=neutral, PublicKeyToken=efb17c8e4f0e291b'. The system cannot find the file specified.
  Stack Trace:
     at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(CultureInfo culture, Version version, Boolean throwOnFileNotFound)
   at System.Reflection.RuntimeAssembly.GetSatelliteAssembly(CultureInfo culture, Version version)
   at IssueTransitiveSatelliteAssembly.Tests.TestFixture.Test() in F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly\IssueTransitiveSatelliteAssembly.Tests\TestFixture.cs:line 13
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)


Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 18 ms - IssueTransitiveSatelliteAssembly.Tests.dll (net8.0)

F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly>
```

Take note that the file `IssueTransitiveSatelliteAssembly\IssueTransitiveSatelliteAssembly.Tests\bin\Debug\net8.0\ICU4N.resources.dll` does not exist on disk.

Then open the project file and uncomment the line:

```xml
<!--<PackageReference Include="ICU4N.Resources" Version="60.1.0-alpha.402" PrivateAssets="all" />-->
```

Run the tests again by using `dotnet test -c Debug` from the package root. The output is now:

```console
F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly>dotnet test -c Debug
  Determining projects to restore...
  Restored F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly\IssueTransitiveSatelliteAssembly.Tests\Iss
  ueTransitiveSatelliteAssembly.Tests.csproj (in 393 ms).
F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly\IssueTransitiveSatelliteAssembly.Tests\IssueTransitiv
eSatelliteAssembly.Tests.csproj : warning NU1504: Duplicate 'PackageReference' items found. Remove the duplicate
items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageReference' i
tems are: ICU4N.Resources 60.1.0-alpha.402, ICU4N.Resources 60.1.0-alpha.402.
C:\Program Files\dotnet\sdk\8.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(
266,5): warning NETSDK1188: Package ICU4N.Resources 60.1.0-alpha.402 has a resource with the locale 'de--phoneboo
k'. This locale is not recognized by .NET. Consider notifying the package author that it appears to be using an i
nvalid locale. [F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly\IssueTransitiveSatelliteAssembly.Test
s\IssueTransitiveSatelliteAssembly.Tests.csproj]
C:\Program Files\dotnet\sdk\8.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(
266,5): warning NETSDK1188: Package ICU4N.Resources 60.1.0-alpha.402 has a resource with the locale 'es--traditio
nal'. This locale is not recognized by .NET. Consider notifying the package author that it appears to be using an
 invalid locale. [F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly\IssueTransitiveSatelliteAssembly.Te
sts\IssueTransitiveSatelliteAssembly.Tests.csproj]
C:\Program Files\dotnet\sdk\8.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(
266,5): warning NETSDK1188: Package ICU4N.Resources 60.1.0-alpha.402 has a resource with the locale 'ja-jp-tradit
ional'. This locale is not recognized by .NET. Consider notifying the package author that it appears to be using
an invalid locale. [F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly\IssueTransitiveSatelliteAssembly.
Tests\IssueTransitiveSatelliteAssembly.Tests.csproj]
C:\Program Files\dotnet\sdk\8.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(
266,5): warning NETSDK1188: Package ICU4N.Resources 60.1.0-alpha.402 has a resource with the locale 'th-th-tradit
ional'. This locale is not recognized by .NET. Consider notifying the package author that it appears to be using
an invalid locale. [F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly\IssueTransitiveSatelliteAssembly.
Tests\IssueTransitiveSatelliteAssembly.Tests.csproj]
  IssueTransitiveSatelliteAssembly.Tests -> F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly\IssueTran
  sitiveSatelliteAssembly.Tests\bin\Debug\net8.0\IssueTransitiveSatelliteAssembly.Tests.dll
Test run for F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly\IssueTransitiveSatelliteAssembly.Tests\bin\Debug\net8.0\IssueTransitiveSatelliteAssembly.Tests.dll (.NETCoreApp,Version=v8.0)
Microsoft (R) Test Execution Command Line Tool Version 17.8.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 46 ms - IssueTransitiveSatelliteAssembly.Tests.dll (net8.0)
```

If you check the output, the file `IssueTransitiveSatelliteAssembly\IssueTransitiveSatelliteAssembly.Tests\bin\Debug\net8.0\ICU4N.resources.dll` now exists. The only thing that changed was that the `ICU4N.Resources` NuGet package was referenced directly instead of being served as a transitive dependency of the `ICU4N` package.

Note that no code in the ICU4N project is being run. It is only being referenced to deliver the `ICU4N.targets` file that is in the `buildTransitive` directory of the `ICU4N` package. The contents are:

<details>

<summary>ICU4N.targets</summary>

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <!-- Set to false to never automatically reference the ICU4N.Resources NuGet package -->
    <IncludeICU4NResources Condition=" '$(IncludeICU4NResources)' == '' ">true</IncludeICU4NResources>

    <ICU4NPackageVersion>60.1.0-alpha.402</ICU4NPackageVersion>
    <ICU4NMajorVersion>$(ICU4NPackageVersion.Split('.'))[0]</ICU4NMajorVersion>
    <ICU4NMinorVersion>$(ICU4NPackageVersion.Split('.'))[1]</ICU4NMinorVersion>
    <ICU4NResourcesPackageIsReferenced>false</ICU4NResourcesPackageIsReferenced>
    
    <ICU4NDataFolderName>icudt60b</ICU4NDataFolderName>
    <ICU4NDataDirectoryFragment>data/$(ICU4NDataFolderName)</ICU4NDataDirectoryFragment>
    <ICU4NDataDirectory>$(MSBuildProjectDirectory)/$(ICU4NDataDirectoryFragment)</ICU4NDataDirectory>
    <!-- TODO: Add more robust data checking -->
    <ICU4NDataExists>false</ICU4NDataExists>
    <ICU4NDataExists Condition=" Exists('$(OutputPath)/$(TargetFramework)/$(ICU4NDataDirectoryFragment)') ">true</ICU4NDataExists>
  
    <ICU4NResourcesPackageName>ICU4N.Resources</ICU4NResourcesPackageName>
    <ICU4NResourcesPackageName Condition="'$(TargetFramework)' == 'net40' Or '$(TargetFramework)' == 'net403'">ICU4N.Resources.NETFramework4.0</ICU4NResourcesPackageName>
  </PropertyGroup>

  <Target Name="GetICU4NPackageDetails" BeforeTargets="BeforeCompile">
    <!-- These properties are only updated when the current (consuming) project references the NuGet packages directly.
      If the library package is referenced, the resources package version will track the library package version.
      If the resources package is referenced, we will automatically exclude the duplicate reference. -->
    <PropertyGroup>
      <ICU4NResourcesPackageIsReferenced Condition="'%(PackageReference.Identity)'=='$(ICU4NResourcesPackageName)'">true</ICU4NResourcesPackageIsReferenced>
      <ICU4NPackageVersion Condition="'%(PackageReference.Identity)'=='ICU4N'">%(Version)</ICU4NPackageVersion>
    </PropertyGroup>
  </Target>
  
  <ItemGroup Condition=" '$(ICU4NResourcesPackageIsReferenced)' == 'false' And '$(IncludeICU4NResources.ToLowerInvariant())' == 'true' And '$(ICU4NDataExists.ToLowerInvariant())' == 'false' ">
    <PackageReference Include="$(ICU4NResourcesPackageName)" Version="$(ICU4NPackageVersion)" PrivateAssets="all" />
  </ItemGroup>

  <Target Name="CheckICU4NResourcesPackagesConfig" BeforeTargets="BeforeCompile" Condition=" '$(RestoreProjectStyle)' != 'PackageReference' ">
    <PropertyGroup>
      <ICU4NResourcesErrorMessage>If using packages.config, you must manually reference $(ICU4NResourcesPackageName) in your project with major version $(ICU4NMajorVersion). Alternatively,%0a</ICU4NResourcesErrorMessage>
      <ICU4NResourcesErrorMessage>$(ICU4NResourcesErrorMessage)download the icu4j-data-$(ICU4NMajorVersion).$(ICU4NMinorVersion).jar file from%0a</ICU4NResourcesErrorMessage>
      <ICU4NResourcesErrorMessage>$(ICU4NResourcesErrorMessage)https://github.com/unicode-org/icu/releases/tag/release-$(ICU4NMajorVersion)-$(ICU4NMinorVersion), unzip it with a zip utility, and%0a</ICU4NResourcesErrorMessage>
      <ICU4NResourcesErrorMessage>$(ICU4NResourcesErrorMessage)copy the /com/ibm/icu/impl/$(ICU4NDataDirectoryFragment) directory contents to the $(ICU4NDataDirectory) directory. Set "Copy To Output Directory"%0a</ICU4NResourcesErrorMessage>
      <ICU4NResourcesErrorMessage>$(ICU4NResourcesErrorMessage)to true for all of the files in the $(ICU4NDataDirectory) directory to ensure the files are copied to the application directory.%0a</ICU4NResourcesErrorMessage>
    </PropertyGroup>
    <Error Text="$(ICU4NResourcesErrorMessage)" Condition=" '$(IncludeICU4NResources.ToLowerInvariant())' == 'true' And '$(ICU4NDataExists.ToLowerInvariant())' == 'false' " />
  </Target>

</Project>
```

</details>

The transitive dependency is definitely being recognized by the build, as the localized `ICU4N.resources.dll` files are included in the output.

### Exceptions (if any)

```
   System.IO.FileNotFoundException : Could not load file or assembly 'ICU4N.resources, Version=60.0.0.0, Culture=neutral, PublicKeyToken=efb17c8e4f0e291b'. The system cannot find the file specified.
  Stack Trace:
     at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(CultureInfo culture, Version version, Boolean throwOnFileNotFound)
   at System.Reflection.RuntimeAssembly.GetSatelliteAssembly(CultureInfo culture, Version version)
   at IssueTransitiveSatelliteAssembly.Tests.TestFixture.Test() in F:\Users\shad\source\repos\IssueTransitiveSatelliteAssembly\IssueTransitiveSatelliteAssembly.Tests\TestFixture.cs:line 13
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

### Further technical details
- Output of `dotnet --info`
<details>

<summary>Click to expand</summary>

```
    .NET SDK:
     Version:           8.0.101
     Commit:            6eceda187b
     Workload version:  8.0.100-manifests.30fce108

    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.19045
     OS Platform: Windows
     RID:         win-x64
     Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

    .NET workloads installed:
     Workload version: 8.0.100-manifests.30fce108
    There are no installed workloads to display.

    Host:
      Version:      8.0.1
      Architecture: x64
      Commit:       bf5e279d92

    .NET SDKs installed:
      2.0.3 [C:\Program Files\dotnet\sdk]
      3.1.100 [C:\Program Files\dotnet\sdk]
      3.1.426 [C:\Program Files\dotnet\sdk]
      5.0.405 [C:\Program Files\dotnet\sdk]
      5.0.416 [C:\Program Files\dotnet\sdk]
      6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]
      6.0.321 [C:\Program Files\dotnet\sdk]
      8.0.101 [C:\Program Files\dotnet\sdk]

    .NET runtimes installed:
      Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    Other architectures found:
      arm64 [C:\Program Files\dotnet]
        registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
      x86   [C:\Program Files (x86)\dotnet]
        registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

    Environment variables:
      Not set

    global.json file:
      Not found

    Learn more:
      https://aka.ms/dotnet/info

    Download .NET:
      https://aka.ms/dotnet/download
```
    
</details>

- The IDE: Ryder (not sure of version) - originally reported at: https://github.com/NightOwl888/ICU4N/issues/69

Note that this behavior does not usually happen in Visual Studio 2022, only when running via `dotnet.exe`. It was brought to my attention because it recently failed in Ryder. ICU4N and ICU4N.Resources 60.1.0-alpha.402 were released more than a year ago and we haven't had any complaints about this issue until recently.

I attempted to downgrade to net6.0 and configure `global.json` to use the SDK 6.0.321, but got the same result as 8.0.101.

**Comment by Forgind** [comment]
@NightOwl888,

I don't think this is actually a bug. You said that transitive references are not copied, but I see a transitive reference being copied: J2N.
<img width="203" alt="image" src="https://github.com/dotnet/sdk/assets/12969783/93a1a3c1-ad36-450c-b177-254fd4cade1a">

J2N seems to be in your list of dependencies for any framework:
<img width="243" alt="image" src="https://github.com/dotnet/sdk/assets/12969783/3a033b0e-6304-471e-a887-9a0853808bb5">

Meanwhile, ICU4N.Resources is not. Tools like MSBuild don't necessarily have their .resources.dll in their NuGet package or in their list of dependencies either, but MSBuild has a set of supported distribution mechanisms, and those distribution mechanisms have explicit references to the localization package as here:
https://github.com/dotnet/sdk/blob/d50f666fd9a376ed17663915674118cf4c3eb529/src/Layout/tool_msbuild/tool_msbuild.csproj#L15

That ensures that whenever someone uses MSBuild from the SDK, it will have its loc package next to it. In your case, you're referencing ICU4N without referencing its Resources package, and the .resources.dll file isn't included in the nuget package itself:
<img width="234" alt="image" src="https://github.com/dotnet/sdk/assets/12969783/746b150a-ab59-470c-801c-2d4c5254bbc3">

So I don't see any way that the SDK could realize that ICU4N.Resources exists and needs to be imported alongside ICU4N except through ICU4N.targets. That comes in too late to affect whether NuGet will find it, though. I don't understand everything NuGet-related, but my understanding is that it pulls in PackageReferences and dependencies of PackageReferences, but in this case you're hoping that it will pull in a PackageReference, run some MSBuild code, then go back through PackageReferences and do it again. I don't think it makes more than one pass at that, as it would likely be prohibitively expensive to do that over and over again.

I'd suggest either using the distribution mechanism I mentioned earlier or giving ICU4N an explicit dependency on ICU4N.Resources.

**Comment by NightOwl888** [comment]
> I don't think this is actually a bug.

Could you explain specifically why it works in Visual Studio and not in MSBuild, then?

> You said that transitive references are not copied, but I see a transitive reference being copied

Yes, most of the localized `ICU4N.Resources.dll` files are copied (we are missing ~150 of them, but that is a different issue). However, the root `ICU4N.Resources.dll` file (the one that sits in the output directory along side `ICU4N.dll`) is NOT being copied to the build output. This is specifically the bug I am reporting here. It is a real problem because this is the one resource file that the application requires to function. The others will all fallback (possibly all the way to the root) if they are missing.

> MSBuild has a set of supported distribution mechanisms, and those distribution mechanisms have explicit references to the localization package

Could you explain more about this?

Since ICU resources are intended to be customized, the way we want this to work is:

1. By default, `ICU4N.Resources` is the included package. The majority of users will use this.
2. Executable developers that depend on `ICU4N` should be able to provide an alternate set of resource files. Usually, this will just be a subset of what is included in `ICU4N.Resources` to cut down on distribution size. These may be raw resource files in a `/data` folder instead of satellite assemblies.
3. Class library developers that depend on `ICU4N` should be able to customize the default resources and tell MSBuild to use their resource package instead of ours, transitively. All downstream users should be able to further customize the resources that the class library developer included (if, for example, the class library developer decided to exclude resources for a feature the end user needs).

If I include the `ICU4N.Resources` reference, it seems I can accomplish the first 2 by instructing those who want to customize the distribution to add another reference to `ICU4N.Resources` with `ExcludeAssets` set to `compile;runtime`. But class library developers who want to supply a custom set of resources would need to instruct all transitive users that they need to suppress the default `ICU4N.Resources` and include their own, somehow. This could be an issue if another class library depends on that one and does not also tell their users to suppress `ICU4N.Resources` and include the customized package.

I suppose I could try adding the direct reference to `ICU4N.Resources` and use `ExcludeAssets` set to `compile;runtime` straight away. Then I could use a custom `buildTransitive` .targets file to decide when to copy the files to the build output and to modify the `.deps.json` file accordingly. I am going to try that next. But it seems like I shouldn't need to do this to accomplish what I want. While I am hoping you fix this bug, the fact of the matter is there are now broken SDKs in the wild, so my build will need to be made tolerant of that fact.

The only other option would be to leave the `ICU4N.Resources` reference off completely, but then most users would have to manually reference it because `ICU4N` requires resources to function. I am hoping to make it "just work" by default and then allow those few users that need to customize the resources to override.
