### ISSUE TITLE
GenerateClsidMap failed unexpectedly

### ISSUE THREAD

**Issue by wjk** [dotnet/sdk#4099]
When I try to build a project of mine that sets EnableComHosting=true, I get the following build error:

```
Error	MSB4018	The "GenerateClsidMap" task failed unexpectedly.
System.InvalidCastException: Specified cast is not valid.
   at System.Reflection.Throw.InvalidCast()
   at System.Reflection.Metadata.MemberReferenceHandle.op_Explicit(EntityHandle handle)
   at Microsoft.NET.Build.Tasks.ClsidMap.GetComVisibleAttribute(MetadataReader reader, CustomAttributeHandleCollection customAttributes)
   at Microsoft.NET.Build.Tasks.ClsidMap.<IsComVisible>g__IsComVisibleCore|8_0(TypeDefinition typeDefinition, <>c__DisplayClass8_0& )
   at Microsoft.NET.Build.Tasks.ClsidMap.IsComVisible(MetadataReader metadataReader, TypeDefinition definition, Boolean assemblyComVisible)
   at Microsoft.NET.Build.Tasks.ClsidMap.Create(MetadataReader metadataReader, String clsidMapPath)
   at Microsoft.NET.Build.Tasks.GenerateClsidMap.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

I don't know what would cause this problem; I believe it started happening after I added a `ComImport` interface to the assembly. The code for the problematic project is available [here](https://github.com/wjk/MSIExtractApp/tree/shell-extension/src/MSIExtract.ShellExtension). This error is currently blocking all progress on this project. Thanks for looking into this for me!

### .NET Core Info

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment]
@rainersigwald @AaronRobinsonMSFT any ideas?

**Comment by AaronRobinsonMSFT** [comment]
@livarcocc I believe this is because the attribute on the class is also defined in the assembly. This makes the following cast invalid: 
https://github.com/dotnet/sdk/blob/fe6b50c78426124e34e56ecb7df8b6b86e6e0b48/src/Tasks/Microsoft.NET.Build.Tasks/ClsidMap.cs#L176

See https://github.com/dotnet/core-sdk/issues/5850 where it has also been reported.

**Comment by wjk** [comment]
This bug no longer occurs after I upgraded to .NET SDK version 3.1.200. Closing issue.
