### ISSUE TITLE
`dotnet -d` dumps stack to console

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/sdk#4104]
I just did `dotnet -d` but without anything else
```
dan@danmose3:~/git/fastregex$ dotnet -d
Telemetry is: Disabled
System.ArgumentException: cannot be empty (Parameter 'name')
   at Microsoft.DotNet.Cli.Utils.ToolCommandName..ctor(String name)
   at Microsoft.DotNet.CommandFactory.LocalToolsCommandResolver.Resolve(CommandResolverArguments arguments)
   at Microsoft.DotNet.CommandFactory.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.CommandFactory.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.CommandFactory.CommandFactoryUsingResolver.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
dan@danmose3:~/git/fastregex$
```
My expectation is that it doesn't dump stack to the console.

version:
```
dan@danmose3:~/git/fastregex$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  3.1.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by livarcocc** [comment]
cc @wli3 can you take a look? Maybe this is a good opportunity for @sfoslund to familiarize herself with this part of the code.

**Comment by sfoslund** [comment]
I have a fix for this [here](https://github.com/sfoslund/toolset/commit/de5cff97359b27f73fe2ddca74f7e88bf157c06e) but I'll wait until the repo merge is finished before making a PR.

**Comment by basz** [comment]
Since, I'm completely new to dotnet so this might be something else, but running `dotnet -d` gives me the exact same error with the latest SDK... As the fixing PR seems to have been merged, what could this be?

```
bas@rattletrap ~ % dotnet -d
Telemetry is: Disabled
System.ArgumentException: cannot be empty (Parameter 'name')
   at Microsoft.DotNet.Cli.Utils.ToolCommandName..ctor(String name)
   at Microsoft.DotNet.CommandFactory.LocalToolsCommandResolver.Resolve(CommandResolverArguments arguments)
   at Microsoft.DotNet.CommandFactory.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.CommandFactory.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.CommandFactory.CommandFactoryUsingResolver.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

```
bas@rattletrap ~ % dotnet --info 
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.403/

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.402 [/usr/local/share/dotnet/sdk]
  3.1.403 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by danmosemsft** [comment]
@baszis this because you need to use 5.0?

**Comment by basz** [comment]
yes it was... thanks.
