### ISSUE TITLE
[NETSDKE2E][Regression]With 7.0.317 SDK installed, .Net Host will stop working when creating F# mvc/webapi project.

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#41076]
1.install 7.0.317 SDK on win11-x64
2.in CLI, dotnet new mvc -lang F# -o fmvc
or dotnet new webapi -lang F# -o fwebapi
**Expected Result:**
F# mvc project can be install successfully.

**Actual Result:**
Failed with below error:
![image](https://github.com/dotnet/sdk/assets/65637796/6a6cdeab-0405-4e2d-a5ec-9234a94358c6)

Process terminated. Assertion failed.
Unbalanced condition
   at Microsoft.TemplateEngine.Core.Expressions.Cpp.CppStyleEvaluatorDefinition.EvaluateCondition(IReadOnlyList`1 tokens, IReadOnlyList`1 values)
   at Microsoft.TemplateEngine.Core.Expressions.Cpp.CppStyleEvaluatorDefinition.Evaluate(IProcessorState processor, Int32& bufferLength, Int32& currentBufferPosition, Boolean& faulted)
   at Microsoft.TemplateEngine.Core.Operations.Conditional.Impl.EvaluationState.Evaluate(IProcessorState processor, Int32& bufferLength, Int32& currentBufferPosition)
   at Microsoft.TemplateEngine.Core.Operations.Conditional.Impl.HandleMatch(IProcessorState processor, Int32 bufferLength, Int32& currentBufferPosition, Int32 token)
   at Microsoft.TemplateEngine.Core.Util.ProcessorState.Run()
   at Microsoft.TemplateEngine.Core.Util.Processor.Run(Stream source, Stream target, Int32 bufferSize, Int32 flushThreshold)
   at Microsoft.TemplateEngine.Core.Util.Processor.Run(Stream source, Stream target, Int32 bufferSize)
   at Microsoft.TemplateEngine.Core.Util.Processor.Run(Stream source, Stream target)
   at Microsoft.TemplateEngine.Core.Util.Orchestrator.ProcessFile(IFile sourceFile, String sourceRel, String targetDir, IGlobalRunSpec spec, IProcessor fallback, IEnumerable`1 fileGlobProcessors)
   at Microsoft.TemplateEngine.Core.Util.Orchestrator.RunInternal(IDirectory sourceDir, String targetDir, IGlobalRunSpec spec)
   at Microsoft.TemplateEngine.Core.Util.Orchestrator.Run(IGlobalRunSpec spec, IDirectory sourceDir, String targetDir)
   at Microsoft.TemplateEngine.Orchestrator.RunnableProjects.RunnableProjectOrchestrator.Run(IGlobalRunSpec runSpec, IDirectory directoryInfo, String target)
   at Microsoft.TemplateEngine.Orchestrator.RunnableProjects.RunnableProjectGenerator.CreateAsync(IEngineEnvironmentSettings environmentSettings, IRunnableProjectConfig runnableProjectConfig, IDirectory templateSourceRoot, IParameterSetData parameters, String targetDirectory, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.TemplateEngine.Orchestrator.RunnableProjects.RunnableProjectGenerator.CreateAsync(IEngineEnvironmentSettings environmentSettings, IRunnableProjectConfig runnableProjectConfig, IDirectory templateSourceRoot, IParameterSetData parameters, String targetDirectory, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Orchestrator.RunnableProjects.RunnableProjectGenerator.Microsoft.TemplateEngine.Abstractions.IGenerator.CreateAsync(IEngineEnvironmentSettings environmentSettings, ITemplate templateData, IParameterSetData parameters, String targetDirectory, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Edge.Template.TemplateCreator.InstantiateAsync(ITemplateInfo templateInfo, String name, String fallbackName, String outputPath, InputDataSet inputParameters, Boolean forceCreation, String baselineName, Boolean dryRun, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.TemplateEngine.Edge.Template.TemplateCreator.InstantiateAsync(ITemplateInfo templateInfo, String name, String fallbackName, String outputPath, InputDataSet inputParameters, Boolean forceCreation, String baselineName, Boolean dryRun, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Edge.Template.TemplateCreator.InstantiateAsync(ITemplateInfo templateInfo, String name, String fallbackName, String outputPath, IReadOnlyDictionary`2 inputParameters, Boolean forceCreation, String baselineName, Boolean dryRun, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.TemplateInvoker.CreateTemplateAsync(TemplateCommandArgs templateArgs, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.TemplateEngine.Cli.TemplateInvoker.CreateTemplateAsync(TemplateCommandArgs templateArgs, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.TemplateInvoker.InvokeTemplateAsync(TemplateCommandArgs templateArgs, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.TemplateEngine.Cli.TemplateInvoker.InvokeTemplateAsync(TemplateCommandArgs templateArgs, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.Commands.TemplateCommand.InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.TemplateEngine.Cli.Commands.TemplateCommand.InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.HandleTemplateInstantationAsync(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.HandleTemplateInstantationAsync(InstantiateCommandArgs args, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, TemplateGroup templateGroup, CancellationToken cancellationToken)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ExecuteIntAsync(InstantiateCommandArgs instantiateArgs, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, InvocationContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.TemplateEngine.Cli.Commands.InstantiateCommand.ExecuteIntAsync(InstantiateCommandArgs instantiateArgs, IEngineEnvironmentSettings environmentSettings, TemplatePackageManager templatePackageManager, InvocationContext context)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand`1.InvokeAsync(InvocationContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand`1.InvokeAsync(InvocationContext context)
   at Microsoft.TemplateEngine.Cli.Commands.BaseCommand`1.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<BuildInvocationChain>b__0(InvocationContext invocationContext, Func`2 _)
   at Microsoft.DotNet.Cli.Parser.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.DotNet.Cli.Parser.<>c__DisplayClass17_0.<UseParseErrorReporting>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<UseHelp>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<UseSuggestDirective>b__17_0(InvocationContext context, Func`2 next)
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<UseParseDirective>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<UseExceptionHandler>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<Invoke>g__FullInvocationChain|3_0(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(IConsole console)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

dotnet --info：
.NET SDK:
Version:   7.0.317
Commit:    791ccb71b5
 
Runtime Environment:
OS Name:     Windows
OS Version:  10.0.22631
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\7.0.317\
 
Host:
  Version:      7.0.20
  Architecture: x64
  Commit:       0fb6ac59fb
 
.NET SDKs installed:
  7.0.317 [C:\Program Files\dotnet\sdk]
 
.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 
Other architectures found:
  None
 
Environment variables:
  Not set
 
global.json file:
  Not found
 
Learn more:
https://aka.ms/dotnet/info
 
Download .NET:
https://aka.ms/dotnet/download

**Comment by v-xiaofchen** [comment]
This issue also repro's on MAC and Linux.
![image](https://github.com/dotnet/sdk/assets/99376012/f2c8a310-ed48-4370-b94a-4fce6c354dd6)

**Comment by v-ainigao** [comment]
This issue also repro's on ARM64OS.
![image](https://github.com/dotnet/sdk/assets/106054229/5ff212cb-ea3a-4cae-89d1-f07c7b17c140)

**Comment by vdanche** [comment]
not repro on new 7.0.317 build.
![image](https://github.com/dotnet/sdk/assets/65637796/b3a80785-860b-4aac-a07d-a7cad770d95e)
