### ISSUE TITLE
[9.0-preview.5] dotnet test fails on Windows when error is logged to the test output

### ISSUE THREAD

**Issue by martincostello** [dotnet/sdk#41541]
### Describe the bug

Using the .NET 9 preview 5 SDK on Windows, if an error is logged to the test output then `dotnet test` fails despite no tests failing.

Setting `$env:MSBUILDTERMINALLOGGER = "off"` does not resolve this, but it does remove the `Build failed with 17 error(s) and 1 warning(s)` output (shown below).

The issue does not reproduce on Linux or macOS, or in Visual Studio on Windows.

The only workaround to get the tests to pass seems to be to skip the relevant tests.

### To Reproduce

1. Clone https://github.com/martincostello/lambda-test-server/pull/696/commits/fc9c6b7ba73c159486534f47c558abb607a55e92
2. Run `build.ps1` in the root of the repository

### Exceptions (if any)

```console
Packaging library...
Restore complete (1.7s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  MartinCostello.Testing.AwsLambdaTestServer net8.0 succeeded (9.5s) → artifacts\bin\MartinCostello.Testing.AwsLambdaTestServer\release_net8.0\MartinCostello.Testing.AwsLambdaTestServer.dll
  MartinCostello.Testing.AwsLambdaTestServer net9.0 succeeded (11.0s) → artifacts\bin\MartinCostello.Testing.AwsLambdaTestServer\release_net9.0\MartinCostello.Testing.AwsLambdaTestServer.dll

Build succeeded in 16.1s
Running tests...
Restore complete (0.6s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  MartinCostello.Testing.AwsLambdaTestServer net9.0 succeeded (0.1s) → artifacts\bin\MartinCostello.Testing.AwsLambdaTestServer\release_net9.0\MartinCostello.Testing.AwsLambdaTestServer.dll
  MartinCostello.Testing.AwsLambdaTestServer.Tests succeeded (6.7s) → artifacts\bin\MartinCostello.Testing.AwsLambdaTestServer.Tests\release\MartinCostello.Testing.AwsLambdaTestServer.Tests.dll
  MartinCostello.Testing.AwsLambdaTestServer.Tests test failed with 17 error(s) and 1 warning(s) (7.0s)
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): warning : [xUnit.net 00:00:00.36]     Runtime_Generates_Valid_Aws_Trace_Id [SKIP]
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error : 2024-06-12T08:33:14.927Z   0e9cd1e6-0772-4e7d-b09c-7927bc14efb5    fail    2024-06-12T08:33:14.927Z        2c35d62b-be00-4336-b3bb-04b09aaa2d73       fail    2024-06-12T08:33:14.927Z        921bf8b5-3102-49a7-8230-c56355e94d3a    fail    2024-06-12T08:33:14.927Z   5f7a93d6-4b17-4b8b-92ac-45854b8a2c10    fail    2024-06-12T08:33:14.927Z        0ecadc7f-eae8-48d0-97b8-6b977a7a3c48       fail    2024-06-12T08:33:14.927Z        81e33baf-6d16-48e6-9714-6fc18fccd7a8    fail       2024-06-12T08:33:14.927Z        88ef34d6-36ff-44a2-99fc-a1952f279496    fail    2024-06-12T08:33:14.927Z  35dbf795-86f9-4299-bf97-b18c59793bc1     fail    System.ArgumentNullException: Value cannot be null. (Parameter 'source')
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error :    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error :    at System.Linq.Enumerable.Sum[TSource,TResult](IEnumerable`1 source)
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error :    at MartinCostello.Testing.AwsLambdaTestServer.MyHandler.SumAsync(MyRequest request, ILambdaContext context) in C:\Coding\martincostello\lambda-test-server\tests\AwsLambdaTestServer.Tests\MyHandler.cs:line 17
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error :    at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass26_0`2.<<GetHandlerWrapper>b__0>d.MoveNext()
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error : --- End of stack trace from previous location ---
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error :    at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken)
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error : 2024-06-12T08:33:17.078Z   0e9cd1e6-0772-4e7d-b09c-7927bc14efb5    fail    2024-06-12T08:33:17.078Z        2c35d62b-be00-4336-b3bb-04b09aaa2d73       fail    2024-06-12T08:33:17.078Z        921bf8b5-3102-49a7-8230-c56355e94d3a    fail    2024-06-12T08:33:17.078Z   5f7a93d6-4b17-4b8b-92ac-45854b8a2c10    fail    2024-06-12T08:33:17.078Z        0ecadc7f-eae8-48d0-97b8-6b977a7a3c48       fail    2024-06-12T08:33:17.078Z        81e33baf-6d16-48e6-9714-6fc18fccd7a8    fail       2024-06-12T08:33:17.078Z        88ef34d6-36ff-44a2-99fc-a1952f279496    fail    2024-06-12T08:33:17.078Z  35dbf795-86f9-4299-bf97-b18c59793bc1     fail    2024-06-12T08:33:17.078Z        0b750b91-e8f2-49e2-a0c5-29cc7e470ae9       fail    2024-06-12T08:33:17.078Z        413544f2-5e97-4c4f-af0b-13ba7abb3d1a    fail    2024-06-12T08:33:17.078Z   232d1d97-d8e3-4dc8-ba20-72499b8c7025    fail    2024-06-12T08:33:17.078Z        665765d3-d8f7-43de-aa8e-c19422e9a073       fail    2024-06-12T08:33:17.078Z                fail    2024-06-12T08:33:17.078Z                fail       System.InvalidOperationException: Failed to initialize handler.
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error :    at MartinCostello.Testing.AwsLambdaTestServer.LambdaTestServerTests.MyFailedInitializationHandler.InitializeAsync() in C:\Coding\martincostello\lambda-test-server\tests\AwsLambdaTestServer.Tests\LambdaTestServerTests.cs:line 569
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error :    at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InitializeAsync()
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error : 2024-06-12T08:33:17.116Z   0e9cd1e6-0772-4e7d-b09c-7927bc14efb5    fail    2024-06-12T08:33:17.116Z        2c35d62b-be00-4336-b3bb-04b09aaa2d73       fail    2024-06-12T08:33:17.116Z        921bf8b5-3102-49a7-8230-c56355e94d3a    fail    2024-06-12T08:33:17.116Z   5f7a93d6-4b17-4b8b-92ac-45854b8a2c10    fail    2024-06-12T08:33:17.116Z        0ecadc7f-eae8-48d0-97b8-6b977a7a3c48       fail    2024-06-12T08:33:17.116Z        81e33baf-6d16-48e6-9714-6fc18fccd7a8    fail       2024-06-12T08:33:17.116Z        88ef34d6-36ff-44a2-99fc-a1952f279496    fail    2024-06-12T08:33:17.116Z  35dbf795-86f9-4299-bf97-b18c59793bc1     fail    2024-06-12T08:33:17.116Z        0b750b91-e8f2-49e2-a0c5-29cc7e470ae9       fail    2024-06-12T08:33:17.116Z        413544f2-5e97-4c4f-af0b-13ba7abb3d1a    fail    2024-06-12T08:33:17.115Z   232d1d97-d8e3-4dc8-ba20-72499b8c7025    fail    2024-06-12T08:33:17.115Z        665765d3-d8f7-43de-aa8e-c19422e9a073       fail    2024-06-12T08:33:17.115Z                fail    2024-06-12T08:33:17.115Z                fail       2024-06-12T08:33:17.115Z        my-request-id   fail    2024-06-12T08:33:17.115Z        4dd0c9e1-c72f-4da6-a816-2cf586b99b09       fail    2024-06-12T08:33:17.115Z        a74716a4-8354-4e43-8f8a-81f2a7a748b9    fail    System.ArgumentNullException: Value cannot be null. (Parameter 'source')
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error :    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error :    at System.Linq.Enumerable.Sum[TSource,TResult](IEnumerable`1 source)
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error :    at MartinCostello.Testing.AwsLambdaTestServer.MyHandler.SumAsync(MyRequest request, ILambdaContext context) in C:\Coding\martincostello\lambda-test-server\tests\AwsLambdaTestServer.Tests\MyHandler.cs:line 17
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error :    at Amazon.Lambda.RuntimeSupport.HandlerWrapper.<>c__DisplayClass26_0`2.<<GetHandlerWrapper>b__0>d.MoveNext()
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error : --- End of stack trace from previous location ---
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): error :    at Amazon.Lambda.RuntimeSupport.LambdaBootstrap.InvokeOnceAsync(CancellationToken cancellationToken)

Test summary: total: 36, failed: 0, succeeded: 35, skipped: 1, duration: 5.9s
Build failed with 17 error(s) and 1 warning(s) in 15.3s
Exception: C:\Coding\martincostello\lambda-test-server\build.ps1:103
Line |
 103 |          throw "dotnet test failed with exit code $LASTEXITCODE"
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | dotnet test failed with exit code 1
```

### Further technical details

.NET SDK `9.0.100-preview.5.24307.3`

**Comment by WeihanLi** [comment]
I may have the same issue when upgrading to .NET 9 preview 5, test cases failed when running `dotnet test` via cli, pass when running in rider

failed CI: https://github.com/WeihanLi/dotnet-exec/actions/runs/9482401214/job/26127202128
detailed log: https://productionresultssa6.blob.core.windows.net/actions-results/eb6ba24d-4687-470f-8915-50b22cb172e6/workflow-job-run-1d849a45-2f30-5fbb-3226-b730a17a93af/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-06-12T12%3A30%3A09Z&sig=DwwQ%2FJhoYNbgpMtf%2B5JyatiNe5XKcAJCIQz3jd3xfck%3D&ske=2024-06-12T22%3A46%3A04Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-06-12T10%3A46%3A04Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2023-11-03&sp=r&spr=https&sr=b&st=2024-06-12T12%3A20%3A04Z&sv=2023-11-03

found some logs, not sure if related:

```
Errors: MSB4276: The default SDK resolver failed to resolve SDK "Microsoft.NET.SDK.WorkloadManifestTargetsLocator" because directory "/usr/share/dotnet/sdk/9.0.100-preview.5.24307.3/Sdks/Microsoft.NET.SDK.WorkloadManifestTargetsLocator/Sdk" did not exist.

```

**Comment by nohwnd** [comment]
Thanks for the report, there are others feedbacks like this, looks like we will have to write the forwarded errors as info, rather than as error. Not logical, but we can see the same for xunit, where every failed assertion fails adds one more error to the build.
