### ISSUE TITLE
MissingManifestResourceException in Sattellite assemblies.

### ISSUE THREAD

**Issue by harshjain2** [dotnet/sdk#419]
## Description
I've uploaded the repro project [here](https://github.com/harshjain2/samples/tree/master/ClassLibrary1).

When I refer ClassLibrary1ForTesting.csproj (instead of ClassLibrary1.csproj ) in ConsoleApp1.csproj, and execute the ConsoleApp, I get this error:
Unhandled Exception: System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "ClassLibrary1.Resources.Resources.resources" was correctly embedded or linked into assembly "ClassLibraryForTesting" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at ClassLibrary1.Resources.Resources.get_String1()
   at Program.Main(String[] args)

## Environment Info
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by nguerrera** [comment]
@harshjain2 The issue is that the name of the resource generated in to the .Designer.cs file is based on the RootNamespace of the project, which in turn is inferred from the project name. In this repro, you've left ClassLibrary1.csproj in the solution, so VS generates ClassLibrary1.Resources.Resources.resources. But you changed the P2P out from under VS to a different csproj, so what is actually built is ClassLibrary1ForTesting.csproj.

This is not a bug in the SDK.

Your options:

* Use just 1 csproj for the same set of files.

* If you must switch between two csprojs over the same set of files, set the root namespace explicitly so that it is the same regardless of which csproj is used.

``` XML
<RootNamespace>ClassLibrary1</RootNamespace>
```
