### ISSUE TITLE
[NETSDKE2E][Unstable]error MSB4242: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.SDK.WorkloadAutoIm..." displays when running command quickly in CLI

### ISSUE THREAD

**Issue by vdanche** [dotnet/sdk#42269]
Build:
[Pull request 525797: .NET 9 insertion into VS with .NET 9 included by default - Repos (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/525797) 
[Pipelines - Run main-35119.143 (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9911699&view=results)

In CLI, copy and paste below command:
dotnet new console -o pubc
cd pubc
dotnet publish -o 1p0
dotnet publish --self-contained=false -o 2p0
dotnet publish --runtime win-x64 --self-contained=false -o 3p0
dotnet publish --runtime linux-x64 --self-contained=false -o 4p0

Expected Result:
No error happen

Actual Result:
Below error happens
![image](https://github.com/user-attachments/assets/d989ba49-6399-41b5-b796-b86fc99878db)
    C:\Program Files\dotnet\sdk\9.0.100-preview.6.24328.19\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,38): error MSB4242:
      SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.SDK.WorkloadAutoIm
      portPropsLocator". Exception: "System.IO.IOException: The process cannot access the file 'C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.wo
      rkload.mono.toolchain.net8\9.0.0-preview.6.24327.7\WorkloadManifest.json' because it is being used by another process.
         at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocation
      Size, Nullable`1 unixCreateMode)
         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize
      , Nullable`1 unixCreateMode)
         at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallo
      cationSize, Nullable`1 unixCreateMode)
         at System.IO.File.OpenRead(String path)
         at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.LoadManifestsFromProvider(IWorkloadManifestProvider manifestProvider)
         at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.InitializeManifests()
         at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.GetInstalledWorkloadPacksOfKind(WorkloadPackKind kind)+MoveNext()
         at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, IWorkloadManifestProvider manifestProvider, IWorkloadR
      esolver workloadResolver)
         at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.CachingWorkloadResolver.Resolve(String sdkReferenceName, String dotnetRootPath, String sdkVersion, String userP
      rofileDir, String globalJsonPath)
         at Microsoft.NET.Sdk.WorkloadMSBuildSdkResolver.WorkloadSdkResolver.Resolve(SdkReference sdkReference, SdkResolverContext resolverContext, SdkResultFactory fac
      tory)
         at Microsoft.Build.BackEnd.SdkResolution.SdkResolverService.TryResolveSdkUsingSpecifiedResolvers(IReadOnlyList`1 resolvers, Int32 submissionId, SdkReference sd
      k, LoggingContext loggingContext, ElementLocation sdkReferenceLocation, String solutionPath, String projectPath, Boolean interactive, Boolean isRunningInVisualStu
      dio, SdkResult& sdkResult, IEnumerable`1& errors, IEnumerable`1& warnings)""

dotnet --info
.NET SDK:
 Version:           9.0.100-preview.6.24328.19
 Commit:            ef4c241666
 Workload version:  9.0.100-manifests.69688f42
 MSBuild version:   17.11.0-preview-24318-05+4a45d5633

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.6.24328.19\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [maui-windows]
   Installation Source: VS 17.12.35119.143
   Manifest Version:    9.0.0-preview.6.24327.7/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.maui\9.0.0-preview.6.24327.7\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.12.35119.143
   Manifest Version:    17.2.9714-net9-p6/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.maccatalyst\17.2.9714-net9-p6\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.12.35119.143
   Manifest Version:    17.2.9714-net9-p6/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.ios\17.2.9714-net9-p6\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.12.35119.143
   Manifest Version:    34.99.0-preview.6.340/9.0.100-preview.6
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.6\microsoft.net.sdk.android\34.99.0-preview.6.340\WorkloadManifest.json
   Install Type:              Msi

 [aspire]
   Installation Source: VS 17.12.35119.143
   Manifest Version:    8.0.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      9.0.0-preview.6.24327.7
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  9.0.100-preview.6.24328.19 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.6.24328.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24327.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.6.24327.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by marcpopMSFT** [comment]
@vdanche does this repro with the stand-alone sdk? I can't imagine there's anything different about VS that would cause it to repro in the insertion PR rather than in the lone SDK.

**Comment by vdanche** [comment]
> @vdanche does this repro with the stand-alone sdk? I can't imagine there's anything different about VS that would cause it to repro in the insertion PR rather than in the lone SDK.

It's intermittent, we did not run into this issue recently with the stand-alone sdk.

**Comment by marcpopMSFT** [comment]
Thanks, I don't think this is a blocker and we aren't sure how to fix it. There's basically a parallelism problem with the template engine and workloads hence why it doesn't happen every time and only happens if you're doing a lot of template engines activities in a short timeframe.

**Comment by MrChevere** [comment]
BAD PROGRAMMING

**Comment by v-yangpei** [comment]
We encounter this issue on Version 17.12.0 [35426.62.d17.12](Release Channel) when dotnet test in Win ARM x64 VM.https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10460791&view=results
![Image](https://github.com/user-attachments/assets/147932cb-0783-4b5c-bd62-dc3ef9ad9fff)
**Log:**
c:\ttm2\mstest0220>dotnet test
还原完成(0.5)
  mstest0220 失败，出现 1 错误 (0.1)
    C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(40,5): error MSB4018:
      “ResolvePackageFileConflicts”任务意外失败。
      System.IO.IOException: The process cannot access the file 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref
      \9.0.0\data\PlatformManifest.txt' because it is being used by another process.
         at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, Fil
      eShare share, FileOptions options)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare
       share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare sha
      re, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
         at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, Fil
      eShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
         at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
         at Microsoft.NET.Build.Tasks.ConflictResolution.PlatformManifestReader.LoadConflictItems(String manifestPath, L
      ogger log)+MoveNext()
         at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
         at Microsoft.NET.Build.Tasks.ConflictResolution.ConflictResolver`1.ResolveConflicts(IEnumerable`1 conflictItems
      , Func`2 getItemKey, ConflictCallback`1 foundConflict, Boolean commitWinner)
         at Microsoft.NET.Build.Tasks.ConflictResolution.ResolvePackageFileConflicts.ExecuteCore()
         at Microsoft.NET.Build.Tasks.TaskBase.Execute()
         at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
         at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLogging
      Context taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

dotnet --info:
![Image](https://github.com/user-attachments/assets/776064e4-37ad-4956-9dc1-e54edc4ccf81)

**Comment by vdtirlochan** [comment]
Issue also occurs in CLI with VS17.13.0 Preview 2.0 [35505.104.main] + net9.0.200 sdk installed
![Image](https://github.com/user-attachments/assets/0940a312-f816-4f6f-a4dc-3b845e6d6d49)
