### ISSUE TITLE
`dotnet workload install wasm-tools` breaks build of ordinary csproj projects

### ISSUE THREAD

**Issue by AArnott** [dotnet/sdk#42433]
### Describe the bug

I was building a Blazor project, and it recommended I install the `wasm-tools` workload so that output could be optimized. I did so.
Now all my csproj's fail to build with errors about the Aspire SDK, which I have never installed nor want to install:

> Error occurred while restoring NuGet packages: Invalid restore input. Invalid target framework 'unsupported'. Input files: D:\source\repos\Nerdbank.Cryptocurrencies\src\Nerdbank.Zcash.App\Nerdbank.Zcash.App.Desktop\Nerdbank.Zcash.App.Desktop.csproj.
> 1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props(14,3): error MSB4019: The imported project "C:\Program Files\dotnet\packs\Aspire.Hosting.Sdk\8.0.2\Sdk\AutoImport.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\packs\Aspire.Hosting.Sdk\8.0.2\Sdk\AutoImport.props" is correct, and that the file exists on disk.

### Further technical details

Visual Studio 2022 Update 10 (17.10.1)

<details><summary>dotnet --info</summary>

.NET SDK:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.d7126b9e
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.300\

.NET workloads installed:
 [android]
   Installation Source: SDK 8.0.300, VS 17.11.34929.205, VS 17.10.34928.147
   Manifest Version:    34.0.113/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.113\WorkloadManifest.json
   Install Type:        FileBased

 [aspire]
   Installation Source: SDK 8.0.300, VS 17.10.34928.147
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 8.0.300, VS 17.11.34929.205, VS 17.10.34928.147
   Manifest Version:    17.2.8078/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8078\WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: SDK 8.0.300, VS 17.11.34929.205, VS 17.10.34928.147
   Manifest Version:    17.2.8078/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8078\WorkloadManifest.json
   Install Type:        FileBased

 [maui-windows]
   Installation Source: SDK 8.0.300, VS 17.11.34929.205, VS 17.10.34928.147
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.61\WorkloadManifest.json
   Install Type:        FileBased

 [wasm-tools]
   Installation Source: SDK 8.0.300, VS 17.10.34928.147
   Manifest Version:    8.0.7/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.7\WorkloadManifest.json
   Install Type:        FileBased

 [wasm-tools-net7]
   Installation Source: SDK 8.0.300, VS 17.10.34928.147
   Manifest Version:    8.0.7/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net7\8.0.7\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  8.0.206 [C:\Program Files\dotnet\sdk]
  8.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  D:\source\repos\Nerdbank.Cryptocurrencies\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>

**Comment by AArnott** [comment]
Removing `wasm-tools` appears to have fixed the problem. So I strongly suspect the latest version of that workload somehow assumes I installed Aspire as well.

**Comment by sjrulandch** [comment]
Thanks for the post. Just hit this issue as well...

I had to remove: wasm-tools, ios
Worse I had to uninstall via VS installer.
5 months and this is still broke.
Great way to encourage me to NOT try other features in VS. Thanks MS.

**Comment by lxman** [comment]
Just hit it myself. Trying to clean it up I run across a big fat error running `dotnet workload clean` now. Thanks MS!

`Unhandled exception: System.Exception: Workload not found: maccatalyst. Known workloads: android ios macos maui maui-mobile maui-desktop maui-core maui-blazor maui-android maui-maccatalyst maui-ios maui-windows maui-tizen tvos wasm-tools wasm-experimental wasi-experimental mobile-librarybuilder microsoft-net-runtime-android microsoft-net-runtime-android-aot microsoft-net-runtime-ios runtimes-ios microsoft-net-runtime-maccatalyst runtimes-maccatalyst microsoft-net-runtime-macos microsoft-net-runtime-tvos runtimes-tvos runtimes-windows microsoft-net-runtime-mono-tooling microsoft-net-sdk-emscripten microsoft-net-sdk-emscripten-net6 microsoft-net-sdk-emscripten-net7 microsoft-net-sdk-emscripten-net8 wasm-tools-net6 microsoft-net-runtime-android-net6 microsoft-net-runtime-android-aot-net6 microsoft-net-runtime-ios-net6 runtimes-ios-net6 microsoft-net-runtime-maccatalyst-net6 runtimes-maccatalyst-net6 microsoft-net-runtime-macos-net6 microsoft-net-runtime-tvos-net6 runtimes-tvos-net6 runtimes-windows-net6 microsoft-net-runtime-mono-tooling-net6 wasm-tools-net7 wasm-experimental-net7 microsoft-net-runtime-android-net7 microsoft-net-runtime-android-aot-net7 microsoft-net-runtime-ios-net7 runtimes-ios-net7 microsoft-net-runtime-maccatalyst-net7 runtimes-maccatalyst-net7 microsoft-net-runtime-macos-net7 microsoft-net-runtime-tvos-net7 runtimes-tvos-net7 runtimes-windows-net7 microsoft-net-runtime-mono-tooling-net7 wasm-tools-net8 wasm-experimental-net8 wasi-experimental-net8 microsoft-net-runtime-android-net8 microsoft-net-runtime-android-aot-net8 microsoft-net-runtime-ios-net8 runtimes-ios-net8 microsoft-net-runtime-maccatalyst-net8 runtimes-maccatalyst-net8 microsoft-net-runtime-macos-net8 microsoft-net-runtime-tvos-net8 runtimes-tvos-net8 microsoft-net-runtime-mono-tooling-net8 aspire
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.GetPacksInWorkload(WorkloadId workloadId)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.IteratorSelectIterator`2.MoveNext()
   at System.Linq.Enumerable.IEnumerableWhereIterator`1.MoveNext()
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadGarbageCollector.GarbageCollectWorkloadManifestsAndPacks()
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadGarbageCollector.Collect()
   at Microsoft.DotNet.Workloads.Workload.Install.NetSdkMsiInstallerClient.GarbageCollect(Func`2 getResolverForWorkloadSet, Nullable`1 offlineCache, Boolean cleanAllPacks)
   at Microsoft.DotNet.Workloads.Workload.Clean.WorkloadCleanCommand.ExecuteGarbageCollection()
   at Microsoft.DotNet.Cli.WorkloadCleanCommandParser.<>c.<ConstructCommand>b__3_0(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)`

**Comment by MiYanni** [comment]
@dotnet/aspnet-blazor-eng or @lewing I'm not sure who owns this... 😅

**Comment by lewing** [comment]
@radical can you take a look?

**Comment by jcbeck37** [comment]
Best I can tell I have this issue. I am just trying to build a .NET 8 web api and it's breaking with this error:

> The imported project "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.92\Sdk\AutoImport.props" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.92\Sdk\AutoImport.props", which evaluated to "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.92\Sdk\AutoImport.props", is correct, and that the file exists on disk.

This is unrelated to anything I'm working on and I have no idea how to get my code to build when a totally unrelated dotnet pack is causing this to break.
