### ISSUE TITLE
DLLs can be missing after update to newer .NET patches

### ISSUE THREAD

**Issue by johnearnshaw** [dotnet/sdk#42445]
I run a long-running .NET 6 application in a remote Ubuntu server that generally runs fine for long periods of time (Currently tested to 226 days).

Recently the application became unresponsive and looking into the applications error logging, it was throwing the following Exception while we were requesting data from it:

`System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Formatters, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`

Restating the application fixed the issue so it's not a major problem, but just thought I'd bring this to your attention as this is the only reference of a similar issue I can find online. The full Exception details I have available can be seen below.

As I say, this is not a major problem but I would prefer my application to run longer without any issue, I thought it quite strange that the application starts and runs long-term without any issues and, after a long while, decides `System.Runtime.Serialization.Formatters` assembly can't be found. Though a following restart of the application fixes the issue.

It's a strange one!? Any suggestion why this may have occurred would be helpful even if solely for informational purpose...

`2023-10-23-13:36:59.498 Modules.Dashboard.DashboardEventPlaygroundModule
Modules.Dashboard.DashboardEventPlaygroundModule threw an exception in callback.
getEventOutput
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Formatters, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Runtime.Serialization.Formatters, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at NetTools.Serialization.ReflectionUtils.GetInstanceOf(Type type)
   at NetTools.Serialization.JsonTools.JsonReader.ParseObject(Type type, String json, StringSerializerFactory serializerFactory, StringBuilder stringBuilder, Stack`1 splitArrayPool, Boolean includePrivates)
   at NetTools.Serialization.JsonTools.JsonReader.ParseValue(Type type, String json, StringSerializerFactory serializerFactory, StringBuilder stringBuilder, Stack`1 splitArrayPool, Boolean includePrivates)
   at NetTools.Serialization.JsonTools.JsonReader.FromJson(Type t, String json, StringSerializerFactory serializerFactory, Boolean includePrivates)
   at NetTools.Serialization.Json.ObjectFromJson(Object this, String jsonString, Boolean includePrivates)
   at Modules.Dashboard.EventPlayground.Classes.AjaxCallbacks.<>c__DisplayClass2_0.<GetEventOutput>b__0(String[] path, DataRequestEventArgs request, String session, String authorization)
   at Modules.WebServer.DashboardModule.DashboardModule.ProcessAjaxRequest(String[] path, DataRequestEventArgs request, String session, String authorization), Inner exception:

2023-10-23-13:37:43.263 Modules.Dashboard.DashboardEventPlaygroundModule
Modules.Dashboard.DashboardEventPlaygroundModule threw an exception in callback.
getEventOutput
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Formatters, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Runtime.Serialization.Formatters, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at NetTools.Serialization.ReflectionUtils.GetInstanceOf(Type type)
   at NetTools.Serialization.JsonTools.JsonReader.ParseObject(Type type, String json, StringSerializerFactory serializerFactory, StringBuilder stringBuilder, Stack`1 splitArrayPool, Boolean includePrivates)
   at NetTools.Serialization.JsonTools.JsonReader.ParseValue(Type type, String json, StringSerializerFactory serializerFactory, StringBuilder stringBuilder, Stack`1 splitArrayPool, Boolean includePrivates)
   at NetTools.Serialization.JsonTools.JsonReader.FromJson(Type t, String json, StringSerializerFactory serializerFactory, Boolean includePrivates)
   at NetTools.Serialization.Json.ObjectFromJson(Object this, String jsonString, Boolean includePrivates)
   at Modules.Dashboard.EventPlayground.Classes.AjaxCallbacks.<>c__DisplayClass2_0.<GetEventOutput>b__0(String[] path, DataRequestEventArgs request, String session, String authorization)
   at Modules.WebServer.DashboardModule.DashboardModule.ProcessAjaxRequest(String[] path, DataRequestEventArgs request, String session, String authorization), Inner exception:`

**Comment by joeloff** [comment]
@FlsZen please take a look at the new option we made available in [November](https://github.com/dotnet/runtime/issues/60144#issuecomment-2472113315). Perhaps these can help address some of the issues you've encountered. By deferring the removal until the next restart, you'll have more control and hopefully reduce crash incidents.

The problems described isn't isolated to the SDK. Unlike .NET Framework that services as part of the OS using CBS that has access to special kernel transactions to deal with in-use files, .NET is serviced through MU. There are a number of factors that impact what happens with running applications and services. 

1. The installer service and restart manager interact with each other. That interaction can be impacted by things like machine policies that will fall back to files-in-use logic that predates Restart Manager / Vista. There are additional nuances, for example, the installer service will do special checks to see whether individual MSIs include the required files-in-use dialog set and if not, modify the actions it takes. This can impact things like the message sent back by the installer service to the installer.
2. The SIDs associated with the running application/service and the installation. Updates typically run under SYSTEM, but applications do not. Services may run under system, but sometimes they run under dedicated accounts. RM also takes into account the type of application and sessions. It won't stop/restart applications running in a different session and won't touch things when it doesn't have permissions. Critical services are never stopped/restarted.
3. Applications may or may not have registered with RM for restarts. Even if they did register, if the SIDs don't line up, RM will report restart failures. You'd typically see events similar to "The application SID does not match the conductor SID". Registered applications can provide proper command lines one how to initiate a restart. The default behavior when using something like `dotnet.exe` to launch an application will not restart properly because RM only detects the host and not the original command line so it ends up executing `dotnet.exe` on a restart which is effectively a no-op.
4. Each MSI creates and ends a session with RM. A .NET installation like the runtime consists of multiple MSIs. This means that at the end of each MSI it may try to restart applications only to shut it down immediately when the next MSI executes. The documentation is unclear whether this is asynchronous or whether the installer service waits for RM to complete all the restarts.
6. Whether or not the .NET update runs with a UI. Messages from the installer services are directed back to the installer engine that may surface additional UI to choose between closing/restarting applications or continue running and restart the machine. When running quietly as is the case in MU, there are defaults that would be selected.

**Comment by VAllens** [comment]
No progress at all? 
I'm having the same problem with .NET 9.0.2.

**Comment by sharpdaddy59** [comment]
Adding a **Linux** data point with a complete timeline — the reports above are mostly Windows, and the Linux mechanism is slightly different: the framework directory that the resident process is bound to gets *unlinked*, not relocated. The foreground app stays up and looks healthy; only code paths it has not yet exercised fail, hours later. There is no warning at upgrade time and nothing in the app's own logs pointing at the upgrade.

**Environment**

- Ubuntu 24.04 (amd64), .NET 8 and .NET 10 both installed from the distro repos
- Affected process: a framework-dependent .NET 8 app (`dotnet OpenSim.dll`), long-lived (`systemd` service, uptime measured in days/weeks)
- Process started **2026-09-06 04:30:26**

**Timeline** (all from `/var/log/dpkg.log` and the unit's own journal, on the machine)

```
2026-09-10 05:53:48  upgrade dotnet-runtime-8.0:amd64   8.0.30-0ubuntu1~24.04.1 -> 8.0.31-0ubuntu1~24.04.1
2026-09-10 05:53:48  upgrade dotnet-hostfxr-8.0:amd64   8.0.30-0ubuntu1~24.04.1 -> 8.0.31-0ubuntu1~24.04.1
2026-09-10 05:53:48  upgrade aspnetcore-runtime-8.0     8.0.30                   -> 8.0.31
2026-09-10 05:53:47  upgrade dotnet-runtime-10.0        10.0.11                  -> 10.0.12
```

`/usr/lib/dotnet/shared/Microsoft.NETCore.App/8.0.30/` no longer exists; only `8.0.31` and `10.0.12` are on disk. The resident process never moved.

**~27 hours later, the first failure on an untouched code path:**

```
2026-09-11 08:56:13  [UTIL]: Util STP threadfunc 10541439 terminated with error
  Could not load file or assembly 'System.Net.Requests, Version=8.0.0.0,
  Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

19 occurrences on 2026-09-11 at 08:56:13/14/52, 13:49:15/17/36, 15:38:46, 15:39:47, 16:15:15, 16:17:15 — one dead worker thread each. Everything the process had already loaded kept working normally throughout. In this app `System.Net.Requests` is the old `WebRequest` stack, so the casualty class is outbound-HTTP code paths; the core loop is unaffected. That is exactly what makes this hard to diagnose in the field: it presents as "a random feature broke, hours after nothing happened."

**Evidence that the runtime is gone, not just "missing from the app folder"**

```
$ readlink /proc/<pid>/exe
/usr/lib/dotnet/dotnet (deleted)

$ awk '/\(deleted\)/ {print $NF}' /proc/<pid>/maps | sort -u | wc -l
58
```

58 unique deleted paths, **50 of them under `Microsoft.NETCore.App/8.0.30/`** — including `libcoreclr.so`, `libclrjit.so`, `System.Private.CoreLib.dll`, `mscorlib.dll`, `System.Text.RegularExpressions.dll`. The assembly that failed (`System.Net.Requests`) is precisely one that was *never* in that set: it had not been loaded yet when the directory was deleted, and the loader resolves it by an absolute path that now points at an unlinked inode.

A second service on the same box, a .NET 10 app started before the same window, hit the identical fault on `System.Text.RegularExpressions` 10.0.0.0. `systemctl restart <unit>` fixed it — the new process resolved against `10.0.12`. The deleted `10.0.11` directory was never rebuilt, which is how we know the re-exec is what repaired it, not a restored framework.

**Questions**

1. Is there a Linux plan for this class — deferring removal of the previous framework directory, or at minimum documenting "restart framework-dependent services after a runtime patch upgrade"?
2. Would the deb packages be able to leave the previous versioned framework directory in place, so a resident process is not left holding unlinked files? The Windows side now has `RemovePreviousVersion` (`always`/`never`/`nextSession`); as far as I can tell there is nothing equivalent for the deb packages — happy to be corrected if that changed since Nov 2024.

**Mitigations we're applying meanwhile** (for anyone finding this thread the same way we did)

- restart the affected units — that is the only thing that repairs a resident process;
- pin critical applications to a private .NET install (`dotnet-install.sh` into a user directory plus `DOTNET_ROOT` on the unit) so a package upgrade cannot remove the runtime out from under them;
- install `needrestart` (Debian/Ubuntu) or `checkrestart`, which flag processes still mapping deleted libraries after an upgrade — the same signal we had to reconstruct by hand here.

The affected process is still resident in this state, so it can be probed further if any of this is useful to you.

*(Forensics compiled on the host by the operator's assistant — an AI agent, Cairn — with every line above taken from `dpkg`'s log, the unit journal, or `/proc`.)*
