### ISSUE TITLE
`dotnet build` results in "Unable to load the service index for source" and "Socket is not connected"

### ISSUE THREAD

**Issue by mrlife** [dotnet/sdk#43814]
### Describe the bug
Running `dotnet build` results in the following error messages:

>MSBuild version 17.9.8+b34f75857 for .NET
  Determining projects to restore...
/usr/local/share/dotnet/sdk/8.0.204/NuGet.targets(169,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/Users/user_name/Documents/app_name/AppName.sln]
/usr/local/share/dotnet/sdk/8.0.204/NuGet.targets(169,5): error :   Socket is not connected [/Users/user_name/Documents/app_name/AppName.sln]

I'm able to view https://api.nuget.org/v3/index.json in the browser without any issues.

### To Reproduce
Run `dotnet build` in project folder in terminal on macOS

### Exceptions (if any)
> Unable to load the service index for source https://api.nuget.org/v3/index.json

> Socket is not connected

### Further technical details
- Include the output of `dotnet --info`

> .NET SDK:
>  Version:           8.0.204
>  Commit:            c338c7548c
>  Workload version:  8.0.200-manifests.9f663350
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  14.6
>  OS Platform: Darwin
>  RID:         osx-arm64
>  Base Path:   /usr/local/share/dotnet/sdk/8.0.204/
> 
> .NET workloads installed:
> There are no installed workloads to display.
> 
> Host:
>   Version:      8.0.4
>   Architecture: arm64
>   Commit:       2d7eea2529
> 
> .NET SDKs installed:
>   7.0.100 [/usr/local/share/dotnet/sdk]
>   7.0.101 [/usr/local/share/dotnet/sdk]
>   7.0.200 [/usr/local/share/dotnet/sdk]
>   7.0.202 [/usr/local/share/dotnet/sdk]
>   7.0.203 [/usr/local/share/dotnet/sdk]
>   7.0.302 [/usr/local/share/dotnet/sdk]
>   7.0.304 [/usr/local/share/dotnet/sdk]
>   7.0.308 [/usr/local/share/dotnet/sdk]
>   7.0.309 [/usr/local/share/dotnet/sdk]
>   7.0.311 [/usr/local/share/dotnet/sdk]
>   7.0.312 [/usr/local/share/dotnet/sdk]
>   7.0.313 [/usr/local/share/dotnet/sdk]
>   7.0.314 [/usr/local/share/dotnet/sdk]
>   7.0.315 [/usr/local/share/dotnet/sdk]
>   7.0.316 [/usr/local/share/dotnet/sdk]
>   7.0.317 [/usr/local/share/dotnet/sdk]
>   8.0.100-rc.1.23463.5 [/usr/local/share/dotnet/sdk]
>   8.0.100-rc.2.23502.2 [/usr/local/share/dotnet/sdk]
>   8.0.100 [/usr/local/share/dotnet/sdk]
>   8.0.203 [/usr/local/share/dotnet/sdk]
>   8.0.204 [/usr/local/share/dotnet/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.19 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
> 
> Other architectures found:
>   x64   [/usr/local/share/dotnet/x64]
> 
> Environment variables:
>   Not set
> 
> global.json file:
>   Not found

**Comment by baronfel** [comment]
The 8.0.200 series of SDKs is out of support - please update your SDK to the 300 or 400 series and try again.

**Comment by mrlife** [comment]
@baronfel, thanks for the suggestion. I updated to this SDK version:

> Version:           8.0.402
 Commit:            70aa751718
 Workload version:  8.0.400-manifests.b6724b7a
 MSBuild version:   17.11.4+37eb419ad

It behaves a little differently in that it now tries 6 times, printing the following each time:

> /Users/user_name/Documents/app_name/AppName.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/Users/user_name/Documents/app_name/AppName.sln]

**Comment by mrlife** [comment]
@baronfel, the same is true for running `dotnet restore`. Any other ideas on the cause for the error or a solution/workaround to get past it?

**Comment by baronfel** [comment]
@nkolev92 is there any kind of first-response FAQ or troubleshooting step for networking issues during restore?

**Comment by nkolev92** [comment]
I could only find something on auth: https://github.com/NuGet/Home/wiki/Azure-DevOps-Artifacts-authentication-issues. 

Generally, when we encounter issues like the guidance is try a quick console app and see if it behaves the same as dotnet restore. 

cc @zivkan in case he has some generic write-ups

**Comment by zivkan** [comment]
@mrlife you can try running `dotnet add package DoesNotExist`, and it should give you the inner exception to the "unable to load the service index" exception. That'll tell you what the underlying cause was (we really need to fix this).

However, in the case of "socket is not connected", I've never seen that before, and don't have any ideas.

Something I sometimes ask people to do is to use `dotnet new console` to create a new console app, then change Program.cs to `await (new HttpClient()).GetAsync("https://api.nuget.org/v3/index.json");` to verify that the same exception occurs.  Change the URL to your package source if you're having this problem with a source other than nuget.org.

Assuming that also fails, first check curl, wget, your web browser, whatever. If those tools can access, but .NET can't, then report it to dotnet/runtime. If those tools also can't access the package source URL, then it's a problem with your networking and you need to find support elsewhere.

**Comment by zivkan** [comment]
@mrlife you didn't mention if this is your first time using dotnet, or if it previously worked and recently stopped working.

I'm wondering if there are any firewall rules, or maybe anti-virus (does mac have anti-virus?) that might be closing sockets when the app itself doesn't expect it to.

**Comment by mrlife** [comment]
@zivkan, thanks for all the suggestions. The error only seems to only be from .NET projects. I've been using .NET for years and this started maybe a year or so ago.

Here are my results from the suggestions:

Accessing `https://api.nuget.org/v3/index.json` via curl and the browser work.

Running `dotnet add package DoesNotExist` results with this output:

> Determining projects to restore...
  Writing /var/folders/2n/djygbs3j6pd2r0g_s4qps_xh_np7sx/T/tmpftsBO3.tmp
info : X.509 certificate chain validation will use the fallback certificate bundle at '/usr/local/share/dotnet/sdk/8.0.402/trustedroots/codesignctl.pem'.
info : X.509 certificate chain validation will use the fallback certificate bundle at '/usr/local/share/dotnet/sdk/8.0.402/trustedroots/timestampctl.pem'.
info : Adding PackageReference for package 'DoesNotExist' into project '/Users/UserName/MyProject/MyProject.csproj'.
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   Socket is not connected

Creating a new console project, updating the Program.cs, and running it results with this error:

> System.Net.Sockets.SocketException (57): Socket is not connected
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.get_RemoteEndPoint()
   at System.Net.Http.HttpConnectionPool.<ConnectAsync>g__GetRemoteEndPoint|103_0(Stream stream)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Program.<Main>$(String[] args) in /Users/UserName/TestProject/Program.cs:line 1
   at Program.<Main>(String[] args)

Should I close this issue out and reference it in a new issue in dotnet/runtime?

**Comment by zivkan** [comment]
sorry, I'm behind in my notifications.   I say yes, ask in dotnet/runtime.  NuGet uses HttpClient, and if the most simple "hello world" HttpClient usage doesn't work, then I as a NuGet expert can't help.

**Comment by mrlife** [comment]
@joeloff @marcpopMSFT 

Hi, possible to provide any guidance, workaround, or solution for this?

**Comment by mrlife** [comment]
Hi @karelz, I've been troubleshooting this in different ways and have a new data point to add. Running a `restore` or `build` command with the `--no-cache` options seems to temporarily clear up the error:

```
dotnet restore --no-cache
```

Does this provide any clarity on what may be the culprit?

Note that an app has to have Nuget packages for the error to occur. I have not had the opportunity to upgrade a project to .NET 9 yet.

**Comment by mrlife** [comment]
Hi @karelz, I've been troubleshooting this in different ways and have a new data point to add. Running a `restore` or `build` command with the `--no-cache` option seems to temporarily clear up the error:

```
dotnet restore --no-cache
```

Does this provide any clarity on what may be the culprit?

Note that an app has to have Nuget packages for the error to occur. I have not had the opportunity to upgrade a project to .NET 9 yet.

**Comment by zivkan** [comment]
@mrlife no, unfortunately it doesn't help.  [As the docs say](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-restore#options), all `--no-cache` does is tell NuGet to ignore its http-cache. This means that if it already has a valid HTTP response on disk that it could reuse, then it will ignore the file and make the HTTP request to re-download the content anyway. However, if your CI server is cleaned after every build, then the http cache will be empty, and `--no-cache` will have no impact at all.

Please try a console app that does something like this:

```cs
class Program
{
    public static async Task Main()
    {
        var client = new HttpClient();
        using response = await client.SendAsync("https://api.nuget.org/v3/index.json");
        Console.WriteLine("Response status code = " + response.StatusCode);
    }
}
```

**Comment by zivkan** [comment]
I work on NuGet, so perhaps the @dotnet/ncl team, who own HttpClient, can help.

**Comment by wfurt** [comment]
Few thoughts. `HttpClient`  prefers IPv6 when possible as well as it used DualMode sockets. We have seen problems with VPN on occasion when the VPN does not havdle that cases correctly.  Also it is failing in `.get_RemoteEndPoint` that is unusual. macOS is somewhat sensitive to doing that on socket that was closed by the peer. It is also possible that there is some other code that interceps it. And also `curl` may not try to get the peer - `HttpClient` & `Socket` do that for diagnostic purposes. 
To start with I can try to do packet capture and check what differences you see @mrlife. 

I think at this point we can transfer this to `runtime` since there is simple repro with `HttpClient`

**Comment by mrlife** [comment]
@wfurt, thank you for thinking over the issue. Do you need anything from me?

@zivkan, thank you for connecting with ncl. Is transferring something you're able to do?
