### ISSUE TITLE
Workload installation failed: Workload manifest microsoft.net.sdk.ios: 17.5.8030/8.0.100 from workload version 8.0.402.0 was not installed. Running "dotnet workload repair" may resolve this.

### ISSUE THREAD

**Issue by jaysidri** [dotnet/sdk#44039]
### Description

I'm trying to install a specific workload version for ios using the following command:

`sudo dotnet workload install ios --version 8.0.402.0
`

..which stops with the following error:

```Workload installation failed: Workload manifest microsoft.net.sdk.ios: 17.5.8030/8.0.100 from workload version 8.0.402.0 was not installed. Running "dotnet workload repair" may resolve this.```

Running the repair command gives me the following:

```No workloads are installed, nothing to repair. Run `dotnet workload search` to find workloads to install.```

Running ```dotnet workload list``` shows me the following:

```
Workload version: 8.0.402.0

Unhandled exception: System.IO.FileNotFoundException: Workload manifest microsoft.net.sdk.ios: 17.5.8030/8.0.100 from workload version 8.0.402.0 was not installed. Running "dotnet workload repair" may resolve this.
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.GetManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.LoadManifestsFromProvider(IWorkloadManifestProvider manifestProvider)
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.InitializeManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.GetInstalledManifests()
   at Microsoft.DotNet.Workloads.Workload.List.WorkloadListCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)

```

My global.json looks like this:
```
{
  "sdk": {
    "version": "8.0.0",
    "rollForward": "latestMajor",
    "allowPrerelease": true
  }
}
```

```
> dotnet --version
8.0.402

```

I'm on macOS Sonoma 14.6.1 (23G93) and my project build fine before upgrading. 

How do I fix this problem?

### Version with bug

8.0.90 SR9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.90 SR9

### Affected platforms

iOS, Android, macOS

**Comment by Jugep001** [comment]
I used these two commands, then it worked for me:
dotnet workload config --update-mode manifests 
dotnet workload update

**Comment by HackRanger** [comment]
@jaysidri did you find a workaround for this? 
I changing the XCode version and reinstalled .Net8 . 

Checking host configuration for connecting to 'localhost'...
Checking SSH configuration...
Initializing environment...
Checking available disk space...
Verifying dotnet runtime installation...
Checking if Rosetta is installed...
Checking Mono installation...
Checking host configuration for connecting to 'localhost'...
Host 'localhost' is configured correctly
Starting connection to 'localhost'...
Checking Broker 17.11.0.94 installation...
Starting Broker 17.11.0.94 in port 50694...
Broker 17.11.0.94 started successfully
Starting connection to 'localhost'...
SSH connection to 'localhost' has been established...
Starting registered Agents: IDB 17.11.0.94...
Starting IDB 17.11.0.94...
Checking IDB 17.11.0.94 installation...
Starting IDB 17.11.0.94 in port 50694...
IDB 17.11.0.94 started successfully
IDB 17.11.0.94 started
Starting registered Agents: ...
The Agents have been started successfully
Performing server validations against 'localhost'...
Setting up user remote session...
Selected project configuration for DotNet validation: C:\Users\91997\source\repos\AromaRetailMobile\AromaRetailMobile\AromaRetailMobile.csproj: AromaRetailMobile.Debug|AnyCPU|net8.0-ios.18.0
The dotnet SDK is already installed. Version: '8.0.400-rtm.24375.2'
dotnet validation completed
Selected project configuration for DotNet validation: C:\Users\91997\source\repos\AromaRetailMobile\AromaRetailMobile\AromaRetailMobile.csproj: AromaRetailMobile.Debug|AnyCPU|net8.0-ios.18.0
Removing previous workload cache '/Users/ec2-user/Library/Caches/Xamarin/XMA/SDKs/dotnet/metadata'...
Manifests directory: /Users/ec2-user/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.ios
Installing workloads using rollback file:
{
  "microsoft.net.sdk.ios": "18.0.8303/8.0.100",
  "microsoft.net.workload.mono.toolchain.current": "8.0.10/8.0.100",
  "microsoft.net.workload.mono.toolchain.net7": "8.0.10/8.0.100"
}
NuGet sources by default: N/A
NuGet sources from project: https://api.nuget.org/v3/index.json
Installing workload 'ios'...
Performing server validations against 'localhost'...
Starting disconnection from localhost...
Starting disconnection from localhost...
The connection to 'localhost' has been finished
Could not install workload 'ios'. Details: Workload installation failed: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten.Current' version '8.0.8' is lower than version '8.0.9' required by manifest 'microsoft.net.workload.mono.toolchain.current' [/Users/ec2-user/Library/Caches/Xamarin/XMA/SDKs/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.current/8.0.10/WorkloadManifest.json]

**Comment by HackRanger** [comment]
I updated visual studio and with latest version of sdk and workload manifest. After pair to mac , everything worked. I dont have this issue anymore.

**Comment by twojnarowski** [comment]
I have now the same issue in GH Actions with `Workload repair failed: Workload manifest microsoft.net.workload.emscripten.current: 9.0.5/9.0.100 from workload version 9.0.300 was not installed. Running "dotnet workload repair" may resolve this.` 
But doing what @Jugep001 suggests, with these two steps in the .yml fixed the issue:
```yml
    - name: Repair .NET workloads
      run: dotnet workload config --update-mode manifests

    - name: Restore Workloads
      run: dotnet workload restore
```
Although `Restore Workloads` steps now takes 5 minutes insead of 1 minute
