### ISSUE TITLE
Workloads are broken on Fedora 40

### ISSUE THREAD

**Issue by atrauzzi** [dotnet/sdk#44082]
I've just updated my system and it looks like I just got the latest `.403` of dotnet 8.  I install dotnet from the official Microsoft yum repository.

All workloads are now broken.

```
Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857
  RID:          linux-x64

.NET SDKs installed:
  8.0.403 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
---

```
❯ dotnet workload update
Unhandled exception: System.InvalidOperationException: No workload set information found in: /usr/share/dotnet/sdk-manifests/8.0.100/workloadsets/8.0.402-baseline.24467.1
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadSet.FromWorkloadSetFolder(String path, String workloadSetVersion, SdkFeatureBand defaultFeatureBand)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.<GetAvailableWorkloadSetsInternal>g__AddWorkloadSetsForFeatureBand|27_0(Dictionary`2 availableWorkloadSets, String featureBandDirectory)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.GetAvailableWorkloadSetsInternal(Nullable`1 workloadSetFeatureBand)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.RefreshWorkloadManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider..ctor(String sdkRootPath, String sdkVersion, Func`2 getEnvironmentVariable, String userProfileDir, String globalJsonPath, String workloadSetVersion)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider..ctor(String sdkRootPath, String sdkVersion, String userProfileDir, String globalJsonPath)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadResolverFactory.Create(String globalJsonStartDir)
   at Microsoft.DotNet.Workloads.Workload.InstallingWorkloadCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolverFactory workloadResolverFactory, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String tempDirPath)
   at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolverFactory workloadResolverFactory, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String tempDirPath)
   at Microsoft.DotNet.Cli.WorkloadUpdateCommandParser.<>c.<ConstructCommand>b__6_0(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

**Comment by BorisWilhelms** [comment]
I ran into the same issue (also on Fedora). I deleted a bunch of empty "baseline" folders in `/usr/share/dotnet/sdk-manifests/8.0.100/workloadsets`. `8.0.403-baseline.24474.13` is left as the only folder. This resolved the issue for me.

**Comment by baronfel** [comment]
I dug into the contents of the `rpm` a bit and it does seem to be the case that we're marking the baseline workload set but not any of the containing directories. If you set 

```shell
>sudo wget -O /etc/yum.repos.d/microsoft-prod.repo https://packages.microsoft.com/config/fedora/40/prod.repo
> repoquery --list dotnet-sdk-8.0
... content above
/usr/share/dotnet/sdk-manifests/8.0.100/microsoft.net.workload.mono.toolchain.net7/8.0.8/localize/WorkloadManifest.zh-Hant.json
/usr/share/dotnet/sdk-manifests/8.0.100/workloadsets/8.0.402-baseline.24467.1/baseline.workloadset.json
/usr/share/dotnet/sdk/8.0.402
/usr/share/dotnet/sdk/8.0.402/.toolsetversion
/usr/share/dotnet/sdk/8.0.402/.version
/usr/share/dotnet/sdk/8.0.402/AppHostTemplate
... content below
```

so I think we need to fix RPM construction to mark the directories involved here as well:

```
/usr/share/dotnet/sdk-manifests
/usr/share/dotnet/sdk-manifests/8.0.100
/usr/share/dotnet/sdk-manifests/8.0.100/workloadsets
/usr/share/dotnet/sdk-manifests/8.0.100/workloadsets/8.0.402-baseline.24467.1
```

This pattern repeats for the 8.0.306-baseline.24474.11 workload set, and several other 20x and 30x RPMs. We should also check the deb packages for similar authoring errors.

**Comment by baronfel** [comment]
The debs have the correct directory entries, so there's some kind of authoring difference here:

```
drwxr-xr-x root/root         0 2024-09-24 14:27 ./usr/share/dotnet/sdk-manifests/8.0.100/workloadsets/
drwxr-xr-x root/root         0 2024-09-24 14:27 ./usr/share/dotnet/sdk-manifests/8.0.100/workloadsets/8.0.403-baseline.24474.13/
```

**Comment by BorisWilhelms** [comment]
Same issue after latest update. Deleted empty `8.0.403-baseline.24474.13` folder, so that only `8.0.403-baseline.24474.13` is left.

**Comment by electronicasfederico** [comment]
Same issue with Opensuse Tumbleweed after deleting the empty folders in /usr/share/dotnet/sdk-manifests/8.0.100/workloadsets/ it works fine

**Comment by shunkino** [comment]
As discussions above, I think the issue is caused by the RPM package expanding empty directories, but I tried to investigate if there is anything can be done from the code perspective. 

This exception is thrown at the following line.
https://github.com/dotnet/sdk/blob/a945fa6000b891f4ccbb9f6dce75f24ec2764fef/src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadSet.cs#L103

This line is a part of the FromWorkloadSetFolder method that was refactored in the next commit, but the original implementation did not have any logic to throw an exception, and it just skipped adding to the availableWorkloadSets if the directory did not exist.
https://github.com/dotnet/sdk/commit/513a7442b64253e397db57262334024864e685e6
![Image](https://github.com/user-attachments/assets/c638c489-0cac-47aa-a927-d40fe633fad4)

I am not able to judge whether the baseline directory in workloadsets should be allowed to be empty or not, but I think it is clear that the functionality has changed due to this commit, so I think it would be effective to also examine if this change was intended by design as a way to solve the problem.

**Comment by cataggar** [comment]
I'm hitting this on Mariner 2 as well after trying to update the SDK. None of the `dotnet workload` subcommands work.

```
wsl ~//ms> dotnet workload update
Unhandled exception: System.InvalidOperationException: No workload set information found in: /usr/share/dotnet/sdk-manifests/8.0.100/workloadsets/8.0.301-baseline.24272.10
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadSet.FromWorkloadSetFolder(String path, String workloadSetVersion, SdkFeatureBand defaultFeatureBand)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.<GetAvailableWorkloadSetsInternal>g__AddWorkloadSetsForFeatureBand|28_0(Dictionary`2 availableWorkloadSets, String featureBandDirectory)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.GetAvailableWorkloadSetsInternal(Nullable`1 workloadSetFeatureBand)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.RefreshWorkloadManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider..ctor(String sdkRootPath, String sdkVersion, Func`2 getEnvironmentVariable, String userProfileDir, String globalJsonPath, String workloadSetVersion)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider..ctor(String sdkRootPath, String sdkVersion, String userProfileDir, String globalJsonPath)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadResolverFactory.Create(String globalJsonStartDir)
   at Microsoft.DotNet.Workloads.Workload.InstallingWorkloadCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolverFactory workloadResolverFactory, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String tempDirPath)
   at Microsoft.DotNet.Workloads.Workload.Update.WorkloadUpdateCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolverFactory workloadResolverFactory, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, IWorkloadManifestUpdater workloadManifestUpdater, String tempDirPath, Boolean isRestoring, WorkloadHistoryRecorder recorder)
   at Microsoft.DotNet.Cli.WorkloadUpdateCommandParser.<>c.<ConstructCommand>b__8_0(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
wsl ~//ms> cat /etc/os-release
NAME="Common Base Linux Mariner"
VERSION="2.0.20230208"
ID=mariner
VERSION_ID="2.0"
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"
```

**Comment by QazCetelic** [comment]
This is still a recurring issue for me. You can use the command `sudo find /usr/share/dotnet/sdk-manifests/8.0.100/workloadsets/ -empty -type d -delete` to delete all empty workload sets for a specific SDK.

**Comment by shunkino** [comment]
@marcpopMSFT I've confirmed that this issue is resolved in Azure Cloud Shell.
