### ISSUE TITLE
dotnet tool install with workaround NUGET_CERT_REVOCATION_MODE does no longer work

### ISSUE THREAD

**Issue by CPlusPlus17** [dotnet/sdk#44123]
### Describe the bug
Since RC2 there seems a change in the TLS/SSL enforcement of dotnet tool install.

### To Reproduce

Running this within our company with proxy:

`/home/application/.dotnet/dotnet tool install --global dotnet-sonarscanner `

Gives always the error "The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, OfflineRevocation".
For .net 8 NUGET_CERT_REVOCATION_MODE  worked to avoid this problem.

### Exceptions (if any)

```
#16 1.510 --------------------------------------------------------------------------------------
22:03:38   #16 2.548 Unhandled exception: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
22:03:38   #16 2.561  ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, OfflineRevocation
22:03:38   #16 2.561    at System.Net.Security.SslStream.SendAuthResetSignal(ReadOnlySpan`1 alert, ExceptionDispatchInfo exception)
22:03:38   #16 2.561    at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
22:03:38   #16 2.561    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
22:03:38   #16 2.561    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
22:03:38   #16 2.561    --- End of inner exception stack trace ---
22:03:38   #16 2.561    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
22:03:38   #16 2.561    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
22:03:38   #16 2.561    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
22:03:38   #16 2.561    at System.Net.Http.HttpConnectionPool.InjectNewHttp11ConnectionAsync(QueueItem queueItem)
22:03:38   #16 2.561    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
22:03:38   #16 2.561    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
22:03:38   #16 2.561    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
22:03:38   #16 2.561    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
22:03:38   #16 2.561    at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.DownloadPackageAsync(PackageId packageId, NuGetVersion packageVersion, PackageSourceLocation packageSourceLocation, Boolean includePreview, Nullable`1 includeUnlisted, Nullable`1 downloadFolder, PackageSourceMapping packageSourceMapping, Boolean isTool)
22:03:38   #16 2.561    at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.DownloadAndExtractPackage(PackageId packageId, INuGetPackageDownloader nugetPackageDownloader, String packagesRootPath, NuGetVersion packageVersion, PackageSourceLocation packageSourceLocation, Boolean includeUnlisted)
22:03:38   #16 2.561    at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.<>c__DisplayClass8_0.<InstallPackage>b__0()
22:03:38   #16 2.561    at Microsoft.DotNet.Cli.TransactionalAction.Run[T](Func`1 action, Action commit, Action rollback)
22:03:38   #16 2.561    at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.<>c__DisplayClass22_0.<ExecuteInstallCommand>b__1()
22:03:38   #16 2.561    at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.RunWithHandlingInstallError(Action installAction, PackageId packageId)
22:03:38   #16 2.561    at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.ExecuteInstallCommand(PackageId packageId)
22:03:38   #16 2.561    at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
22:03:38   #16 2.561    at Microsoft.DotNet.Tools.Tool.Install.ToolInstallCommand.Execute()
22:03:38   #16 2.561    at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
22:03:38   #16 2.561    at System.CommandLine.ParseResult.Invoke()
22:03:38   #16 2.561    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
22:03:38   #16 ERROR: process "/bin/sh -c NUGET_CERT_REVOCATION_MODE=offline /home/application/.dotnet/dotnet tool install --global dotnet-sonarscanner" did not complete successfully: exit code: 1
```

### Further technical details

- Ubuntu Noble
- dotnet-install.sh used for installation of SDK (dotnet-sdk-9.0.100-rc.2.24474.11-linux-x64)
- SSL/TLS Proxy which breaks the connection and used custom CA (Chain is trusted)
- 9.0.100-rc.1.24452.12 works without problems

**Comment by martincostello** [comment]
I wonder if there's any overlap with #43651?

That has been resolved in the latest nightly builds for 9.0, so maybe you could test to see if this issue has resolved too?

**Comment by tomap** [comment]
Hello, I have the exact same issue. 

My config is the following:
The command is run as part of a docker build via kaniko. 

The dotnet install was working fine in .Net 8 and even in .Net 9 RC1. But broken in .Net 9 RC1.

I am building inside a network with internet access via a proxy. The proxy is set via http_proxy/https_proxy

Maybe the revocation url is not called via the proxy?

**Comment by tomap** [comment]
Here are the logs:

```
INFO[0024] Cmd: /bin/sh                                 
INFO[0024] Args: [-c dotnet tool install --no-cache dotnet-reportgenerator-globaltool --ignore-failed-sources --tool-path /tools -v diag] 
INFO[0024] Running: [/bin/sh -c dotnet tool install --no-cache dotnet-reportgenerator-globaltool --ignore-failed-sources --tool-path /tools -v diag] 
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/index.json 179ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/page/4.0.0-alpha10/4.2.16.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/page/4.0.0-alpha10/4.2.16.json 115ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/page/4.2.17/5.1.1.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/page/4.2.17/5.1.1.json 133ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/page/5.1.2/5.3.11.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/page/5.1.2/5.3.11.json 136ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/index.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/index.json 117ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/page/4.0.0-alpha10/4.2.16.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/page/4.0.0-alpha10/4.2.16.json 117ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/page/4.2.17/5.1.1.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/page/4.2.17/5.1.1.json 120ms
[NuGet Manager] [Info]   GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/page/5.1.2/5.3.11.json
[NuGet Manager] [Info]   OK https://api.nuget.org/v3/registration5-gz-semver2/dotnet-reportgenerator-globaltool/page/5.1.2/5.3.11.json 146ms
Unhandled exception: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown, OfflineRevocation
   at System.Net.Security.SslStream.SendAuthResetSignal(ReadOnlySpan`1 alert, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.InjectNewHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.DownloadPackageAsync(PackageId packageId, NuGetVersion packageVersion, PackageSourceLocation packageSourceLocation, Boolean includePreview, Nullable`1 includeUnlisted, Nullable`1 downloadFolder, PackageSourceMapping packageSourceMapping, Boolean isTool)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.DownloadAndExtractPackage(PackageId packageId, INuGetPackageDownloader nugetPackageDownloader, String packagesRootPath, NuGetVersion packageVersion, PackageSourceLocation packageSourceLocation, Boolean includeUnlisted)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.<>c__DisplayClass8_0.<InstallPackage>b__0()
   at Microsoft.DotNet.Cli.TransactionalAction.Run[T](Func`1 action, Action commit, Action rollback)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.<>c__DisplayClass22_0.<ExecuteInstallCommand>b__1()
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.RunWithHandlingInstallError(Action installAction, PackageId packageId)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.ExecuteInstallCommand(PackageId packageId)
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallGlobalOrToolPathCommand.Execute()
   at Microsoft.DotNet.Tools.Tool.Install.ToolInstallCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

**Comment by tomap** [comment]
I tried NUGET_CERT_REVOCATION_MODE  but it did not work

My workaround:

```
mkdir lib
curl -L -o lib/dotnet-reportgenerator-globaltool.1.1.1.nupkg https://www.nuget.org/api/v2/package/dotnet-reportgenerator-globaltool
echo '<?xml version="1.0" encoding="utf-8"?><configuration><packageSources><clear /><add key="LocalRepo" value="./" /></packageSources></configuration>' > nuget.config
 dotnet tool install dotnet-reportgenerator-globaltool --add-source ./lib --tool-path /tools -v diag 
```

But clearly something is wrong

**Comment by tomap** [comment]
The dotnet/nightly/sdk does not seem to have the issue

```
.NET SDK:
 Version:           9.0.100-rtm.24516.6
 Commit:            3aa4e4a78d
 Workload version:  9.0.100-manifests.8a52fb46
 MSBuild version:   17.12.3+4ae11fa8e
```

If I'm not wrong, this matches this commit:
https://github.com/dotnet/sdk/commit/3aa4e4a78d
so there is a fix that will be available in either RC3 or RTM :)

**Comment by martincostello** [comment]
Well if it's the same as #43651 as I noted earlier https://github.com/dotnet/sdk/issues/44123#issuecomment-2408581441, then that issue is fixed, so then this would be too.

**Comment by baronfel** [comment]
Closing as this will be fixed in the upcoming GA release.
