### ISSUE TITLE
[NETSDKE2E]With net9RTM SDK isntalled, install wasm-toos/maui/aspire failed with error "Workload installation failed: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten.Current' version '9.0.0-rtm.24513.1' is lower than version '9.0.0'"

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/sdk#44217]
Build info:
.net9.0.100-rtm.24515.15(runtime-9.0.0-rtm.24511.16) SDK

Repro steps:
1.Download the NET9 RTM SDK.
2.Install workload with commands.
`dotnet workload install maui` / `dotnet workload install aspire`
or `dotnet workload install wasm-tools --skip-sign-check`

Expected Result:
workload installd successfully.

Actual Result:
workload installs failed with below error.
![Image](https://github.com/user-attachments/assets/4cb5be51-92e1-4200-95af-cb226bfd7a4c)
Workload installation failed: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten.Current' version '9.0.0-rtm.24513.1' is lower than version '9.0.0' required by manifest 'microsoft.net.workload.mono.toolchain.current' [C:\Program Files\dotnet\x64\sdk-manifests\9.0.100\microsoft.net.workload.mono.toolchain.current\9.0.0-rtm.24515.15\WorkloadManifest.json]

Note:
The same error also appears in dotnet --info.
![Image](https://github.com/user-attachments/assets/a920de01-ef10-42dd-98da-23c32aee914e)

dotnet --info:
.NET SDK:
 Version:           9.0.100-rtm.24515.15
 Commit:            b2ac8c11db
 Workload version:  9.0.100-manifests.5a1ed105
 MSBuild version:   17.12.3+4ae11fa8e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\x64\sdk\9.0.100-rtm.24515.15\

.NET workloads installed:
Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: Workload manifest dependency 'Microsoft.NET.Workload.Emscripten.Current' version '9.0.0-rtm.24513.1' is lower than version '9.0.0' required by manifest 'microsoft.net.workload.mono.toolchain.current' [C:\Program Files\dotnet\x64\sdk-manifests\9.0.100\microsoft.net.workload.mono.toolchain.current\9.0.0-rtm.24515.15\WorkloadManifest.json]
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.ComposeWorkloadManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.InitializeManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.GetAvailableWorkloadDefinitions()+MoveNext()
   at System.Linq.Enumerable.IEnumerableSelectIterator`2.MoveNext()
   at Microsoft.DotNet.Workloads.Workload.VisualStudioWorkloads.GetAvailableVisualStudioWorkloads(IWorkloadResolver workloadResolver)
   at Microsoft.DotNet.Workloads.Workload.VisualStudioWorkloads.GetInstalledWorkloads(IWorkloadResolver workloadResolver, InstalledWorkloadsCollection installedWorkloads, Nullable`1 sdkFeatureBand)
   at Microsoft.DotNet.Workloads.Workload.List.WorkloadInfoHelper.AddInstalledVsWorkloads(IEnumerable`1 sdkWorkloadIds)
   at Microsoft.DotNet.Cli.WorkloadCommandParser.ShowWorkloadsInfo(ParseResult parseResult, WorkloadInfoHelper workloadInfoHelper, IReporter reporter, String dotnetDir, Boolean showVersion)
   at Microsoft.DotNet.Cli.CommandLineInfo.PrintWorkloadsInfo()
   at Microsoft.DotNet.Cli.CommandLineInfo.PrintInfo()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

Host:
  Version:      9.0.0-rtm.24511.16
  Architecture: x64
  Commit:       b030c4dfdf
  RID:          win-x64

.NET SDKs installed:
  9.0.100-rtm.24515.15 [C:\Program Files\dotnet\x64\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-rtm.24514.7 [C:\Program Files\dotnet\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-rtm.24511.16 [C:\Program Files\dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-rtm.24511.2 [C:\Program Files\dotnet\x64\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by v-ainigao** [comment]
Not repro on yesterday's build: .net9.0.100-rtm.24514.15(runtime-9.0.0-rtm.24511.16)sdk

**Comment by v-ainigao** [comment]
The same issue also repro when creating a new project.
![Image](https://github.com/user-attachments/assets/4d20e887-a596-4c01-b85d-058a4ec8f12b)

**Comment by v-ainigao** [comment]
This issue also repro's on ARM64/Linux/MAC OS.

**Comment by marcpopMSFT** [comment]
@lewing I thought you were getting rid of the version requirement? I think we need a codeflow with a stable emsdk.

**Comment by v-ainigao** [comment]
Currently the latest error for installing maui/wasm-tools workload
![Image](https://github.com/user-attachments/assets/94bf56b4-9bc9-45f9-8eaf-0da325dea9b5)
but installed aspire can success
![Image](https://github.com/user-attachments/assets/3d3f83c7-c013-480b-9647-7af3c166c1c2)

**Comment by mmitche** [comment]
Is the isolated feed for emsdk included in the nuget.config when doing the workload restore? https://github.com/dotnet/sdk/blob/release/9.0.1xx/NuGet.config#L11

**Comment by marcpopMSFT** [comment]
The stable versions aren't going to show up on the dotnet9 feed anymore. However, I think at least one runtime build with a stable emsdk dependency showed up there so if you use that feed, you may be unable to do workload work at the moment. You'll have to use an additional feed per Matt above.

**Comment by v-ainigao** [comment]
> The stable versions aren't going to show up on the dotnet9 feed anymore. However, I think at least one runtime build with a stable emsdk dependency showed up there so if you use that feed, you may be unable to do workload work at the moment. You'll have to use an additional feed per Matt above.

After adding additional feed maui upgrade still fails with same errors.
![Image](https://github.com/user-attachments/assets/0dd35051-6816-4fd8-8c91-e37f49564308)

**Comment by v-ainigao** [comment]
This issue still repro's on net9.0.100SDK, Did I miss some additional feeds?
![Image](https://github.com/user-attachments/assets/b92de83a-6ab8-4599-85d6-bca939bb765f)

Workload update failed: Version 34.0.145 of package microsoft.android.sdk.windows is not found in NuGet feeds https://api.nuget.org/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/internal/_packaging/9.0.100-rtm.24518.46-shipping/nuget/v3/index.json.

**Comment by v-ainigao** [comment]
Today, installing maui in the latest 9.0.100SDK still failed.
![Image](https://github.com/user-attachments/assets/eefe10b1-891b-420f-84e3-ca453b1393fd)

**Comment by vdanche** [comment]
install maui workload on 9.0.100 SDK, it requires version 18.0.8310 of package microsoft.ios.sdk.net8.0_18.0.msi.x64 is not found... @marcpopMSFT Do we miss some feed?
![Image](https://github.com/user-attachments/assets/c57c70c1-0fa9-4322-8092-d91a644886ee)
feed use:
![Image](https://github.com/user-attachments/assets/962daa46-45f4-4625-a5ba-efd2bab9ff83)

**Comment by v-ainigao** [comment]
After adding additional feeds, maui/android workloads can be installed successfully. So, close it
![Image](https://github.com/user-attachments/assets/9f950d03-3a01-4d03-8f7f-0ab100ffc294)
![Image](https://github.com/user-attachments/assets/478d2d7b-28ce-409e-874b-3a5e58599667)

Additional feed:
 ```
<add key="darc-pub-xamarin-xamarin-macios-ecbd8510" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-xamarin-xamarin-macios-ecbd8510/nuget/v3/index.json" />
   <add key="darc-pub-dotnet-android-df9aaf2-2" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-android-df9aaf29-2/nuget/v3/index.json" />
<add key="darc-pub-xamarin-xamarin-macios-8354d6d" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-xamarin-xamarin-macios-8354d6d9/nuget/v3/index.json" />
```
