### ISSUE TITLE
Linux - System.InvalidOperationException: No workload set information found

### ISSUE THREAD

**Issue by savornicesei** [dotnet/sdk#44468]
### Describe the bug
Running  `dotnet restore` in a git repo with a .NET Core 8 WebApi project on openSUSE throws error
```
/usr/share/dotnet/sdk/8.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.props(14,38): error MSB4242: SDK Resolver Failure: "The SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" failed while attempting to resolve the SDK "Microsoft.NET.SDK.WorkloadAutoImportPropsLocator". Exception: "System.InvalidOperationException: No workload set information found in: /usr/share/dotnet/sdk-manifests/8.0.100/workloadsets/8.0.300-baseline.24224.15 [/windows/Proiecte/src/WebApi/WebApi.csproj]
/usr/share/dotnet/sdk/8.0.403/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.props(14,38): error MSB4242:    at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadSet.FromWorkloadSetFolder(String path, String workloadSetVersion, SdkFeatureBand defaultFeatureBand) [/windows/Proiecte/src/WebApi/WebApi.csproj]
....
```
Trying any of the commands:
```ps
dotnet workload repair
dotnet workload update
dotnet 
```
return
```
An issue was encountered verifying workloads. For more information, run "dotnet workload update".
Unhandled exception: System.InvalidOperationException: No workload set information found in: /usr/share/dotnet/sdk-manifests/8.0.100/workloadsets/8.0.300-baseline.24224.15
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadSet.FromWorkloadSetFolder(String path, String workloadSetVersion, SdkFeatureBand defaultFeatureBand)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.<GetAvailableWorkloadSetsInternal>g__AddWorkloadSetsForFeatureBand|27_0(Dictionary`2 availableWorkloadSets, String featureBandDirectory)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.GetAvailableWorkloadSetsInternal(Nullable`1 workloadSetFeatureBand)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider.RefreshWorkloadManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider..ctor(String sdkRootPath, String sdkVersion, Func`2 getEnvironmentVariable, String userProfileDir, String globalJsonPath, String workloadSetVersion)
   at Microsoft.NET.Sdk.WorkloadManifestReader.SdkDirectoryWorkloadManifestProvider..ctor(String sdkRootPath, String sdkVersion, String userProfileDir, String globalJsonPath)
   at Microsoft.DotNet.Workloads.Workload.Install.WorkloadResolverFactory.Create(String globalJsonStartDir)
   at Microsoft.DotNet.Workloads.Workload.Repair.WorkloadRepairCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolverFactory workloadResolverFactory, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader)
   at Microsoft.DotNet.Cli.WorkloadRepairCommandParser.<>c.<ConstructCommand>b__5_0(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)

```
### To Reproduce
I believe it's a linux-only & .NET 8-only issue due to the fact that the existing minor SDK versions are replaced with the latest released ones.
In my case, on openSUSE Tumbleweed, I'm using the (SLES repo)[http://packages.microsoft.com/sles/15/prod/] to manage dotnet installations. Since june till now, the following .NET 8 SDK versions were released and installed with `zypper dup`:
- 8.0.300
- 8.0.301
- 8.0.303 
- 8.0.401 
- 8.0.402
- 8.0.403
resulting in the following folder structure
```bash
λ ls -ls /usr/share/dotnet/sdk-manifests/8.0.100/workloadsets/
total 0
0 drwxr-xr-x 1 root root  0 Jun  4 09:36 8.0.300-baseline.24224.15
0 drwxr-xr-x 1 root root  0 Jul 29 20:18 8.0.301-baseline.24272.10
0 drwxr-xr-x 1 root root  0 Aug 20 07:28 8.0.303-baseline.24317.8
0 drwxr-xr-x 1 root root  0 Oct  3 22:46 8.0.401-baseline.24412.2
0 drwxr-xr-x 1 root root  0 Oct 26 14:50 8.0.402-baseline.24467.1
0 drwxr-xr-x 1 root root 50 Oct 26 14:50 8.0.403-baseline.24474.13
```
None of the folders have any content except the latest version. Based on the error received, it seems it looks in the .300 folder and fails without checking the rest of the existing folders.
Removing the obsolete folders (.300 -> .402)  fixed the issue and I was able to run `dotnet restore` successfully.

### Further technical details
.NET SDK:
 Version:           8.0.403
 Commit:            c64aa40a71
 Workload version:  8.0.400-manifests.18f19b92
 MSBuild version:   17.11.9+a69bbaaf5

Runtime Environment:
 OS Name:     opensuse-tumbleweed
 OS Version:  20241024
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.403/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
There are no installed workloads to display.

Host:
  Version:      8.0.10
  Architecture: x64
  Commit:       81cabf2857

.NET SDKs installed:
  2.1.818 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.103 [/usr/share/dotnet/sdk]
  3.1.426 [/usr/share/dotnet/sdk]
  5.0.408 [/usr/share/dotnet/sdk]
  6.0.427 [/usr/share/dotnet/sdk]
  7.0.410 [/usr/share/dotnet/sdk]
  8.0.403 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.35 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.35 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /windows/Proiecte/global.json

**Comment by savornicesei** [comment]
Ups! Seems like it was already reported in https://github.com/dotnet/sdk/issues/44082
