### ISSUE TITLE
dotnet publish regularly fails with OutOfMemory after update to .NET 9

### ISSUE THREAD

**Issue by weltkante** [dotnet/sdk#45336]
### Describe the bug
I've updated a private project to .NET 9 and started seeing regular build failures when running `dotnet publish`, making it almost impossible to build the project (like 9 out of 10 runs fail). Most of the time they fail with OutOfMemory exceptions, sometimes segmentation faults. Before the build the machine is using 1.25 out of 8 GB RAM during the build it goes up to about 1.58 GB when looking at with htop, so whatever peaks OOM must be doing a huge allocation. Its a virtual ubuntu machine with no swap configured for performance. (This was preconfigured either by the VM hosting company or the ubuntu installation image and not configured by me so I assume its a common setup.)

Command line to publish is `dotnet publish server -c Release -f net9.0 -r linux-x64 --self-contained false -o /game/bin`

We had no issues building the same codebase in .NET 8, first few builds on .NET 9 were fine too, before it suddenly started to regularly fail with OOM. Nothing really changed on the machine side I'm aware of and I'd like to know if there's anything I can do to diagnose this further.

### To Reproduce
The git repo where this occurs is not public and I'd like to know if there's anything I can do to diagnose this short of building a public repro.

### Exceptions (if any)
```
core succeeded (0.5s) → build/bin/core/Release/net9.0/core.dll
gateway succeeded (5.6s) → build/bin/gateway/Release/net9.0/gateway.dll
server net9.0 failed with 1 error(s) (11.2s)
/usr/share/dotnet/sdk/9.0.100/Roslyn/Microsoft.CSharp.Core.targets(89,5): error : Out of memory.
```
or sometimes
```
core succeeded (0.6s) → build/bin/core/Release/net9.0/core.dll
gateway succeeded (0.6s) → build/bin/gateway/Release/net9.0/gateway.dll
server net9.0                                                               CoreCompile (14.9s)
../compile.sh: line 3: 170587 Segmentation fault      dotnet publish server -c Release -f net9.0 -r linux-x64 --self-contained false -o /game/bin
```

### Further technical details
<details><summary>dotnet --info</summary>

```
.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.3068a692
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/9.0.100/

.NET workloads installed:
There are no installed workloads to display.
Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

.NET SDKs installed:
  7.0.410 [/usr/share/dotnet/sdk]
  9.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
</details>

**Comment by Forgind** [comment]
This definitely isn't an issue with the .NET SDK (we don't have segmentation faults), but it may be an issue with one of our bundled components. It looks like it's failing during compilation; the OOM exception seems to be from https://github.com/dotnet/roslyn, and the segmentation fault was during compilation. Roslyn may have some unmanaged code, but I think it's 95%+ managed, which makes it unlikely that that one is a Roslyn bug. Is this a pure C# solution, or do you also have C++ code?

For what it's worth, it wouldn't have to try to allocate a 6.5gb object all at once to get an OOM exception regardless. Fragmentation can be an issue, and I think it might throw an OOM exception if it goes beyond the amount of memory it expected to have to use? Not sure about that last part. One suggestion from a SO post I found suggested adding this to your app.config:
```
<runtime>
    <gcAllowVeryLargeObjects enabled="true" />    
</runtime>
```

I think you can still capture a dump of what was happening when the OOM exception fired, right? That might tell you more about what it was trying to allocate that pushed it over the edge and why.

**Comment by weltkante** [comment]
> Roslyn may have some unmanaged code, but I think it's 95%+ managed, which makes it unlikely that that one is a Roslyn bug. Is this a pure C# solution, or do you also have C++ code?

This is a pure C# project and not even a very large one in size of code (470 files, 12k lines of code). My guess is the occasional segmentation fault is coming from OOM as well, like, a native API fails to allocate and the error is not handled properly by either the runtime or the build system.

> Fragmentation can be an issue

shouldn't be an issue, Linux only has the x64 runtime and fragmenting a 64 bit process shouldn't happen (address space should be large enough), especially not for something simple as publishing an application

> One suggestion from a SO post I found suggested adding this to your app.config

app.config is for running the application, not for publishing it, I'd be surprised if that had any effect on `dotnet publish` but I'll try it

> I think you can still capture a dump of what was happening when the OOM exception fired, right?

thats what I hoped for to get information how to do, because its failing inside the publish system and I couldn't figure out how to capture a dump or get any more diagnostic information out of the publish command

For what its worth I just happened to get a different error among the usual OOM's, probably just another case of the final OOM hitting some native API instead of a managed allocation.

```
MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/MSBuildTempuser/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
```

with the file containing

```
UNHANDLED EXCEPTIONS FROM PROCESS 171558:
=====================
12/5/2024 7:04:55 PM
System.AggregateException: One or more errors occurred. (Connection reset by peer)
 ---> System.IO.IOException: Connection reset by peer
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.IO.Pipes.PipeStream.ReadCore(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.IO.Pipes.PipeStream.ReadCore(Span`1 buffer)
   at System.IO.Pipes.PipeStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Build.BackEnd.BufferedReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.<>c.<BeginReadInternal>b__38_0(Object <p0>)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Build.Internal.CommunicationsUtilities.ReadAsync(Stream stream, Byte[] buffer, Int32 bytesToRead)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================
```

**Comment by weltkante** [comment]
anyways, the main thing I'm looking for is how to diagnose build errors in the sdk, there surely is some way to capture dumps or get better diagnostics?
