### ISSUE TITLE
Dotnet watch falls over frequently with "An item with the same key has already been added"

### ISSUE THREAD

**Issue by paulguz-datapa** [dotnet/sdk#45455]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Since upgrading our ASP.Net Core projects to .Net 9 (but leaving the others alone for now), we are experiencing the following error when running dotnet watch:

```
dotnet watch ❌ System.ArgumentException: An item with the same key has already been added. Key: 
C:\xxx\yyy\zzz\aaa\Language.csproj
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.DotNet.Watcher.Tools.IncrementalMSBuildWorkspace.UpdateProjectConeAsync(String rootProjectPath, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.Program.RunAsync()
dotnet watch ❌ An unexpected error occurred
```
Language.csproj is a an assembly containing resource files.

Dotnet watch falls over at this point.  It happens very frequently, making Hot Reload impossible.

### Expected Behavior

Dotnet watch runs without failure

### Exceptions (if any)

 System.ArgumentException: An item with the same key has already been added

### .NET Version

9.0

### Anything else?

This did not happen in .Net 8

**Comment by tmat** [comment]
Anyone has a project they can share where this issue reproduces?

**Comment by limefrogyank** [comment]
Happening with my Maui hybrid app. In fact, it happened very early on and I just got used to recompiling everytime. I will try creating a project using the basic template from visual studio and see if it happens without any changes. (Tomorrow morning unless someone beats me to it.)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jofford** [comment]
Attaching a small sample project that has the error. It seems to be caused by a class library which [BlazorWasmApp.zip](https://github.com/user-attachments/files/18184182/BlazorWasmApp.zip)
 multiple frameworks.

Steps to reproduce:
1. `dotnet watch` the BlazorWasmApp.csproj
2. Change the html in Pages\Home.razor and click save

Here's what showed up when I ran it with `dotnet watch --verbose`

```
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
dotnet watch ⌚ File change: Add 'C:\..\BlazorWasmApp\BlazorWasmApp\BlazorWasmApp.Client\Pages\lak2f2kh.may~' (written 14:39:57.4387364 after 14:39:45.1684471).
dotnet watch ⌚ Ignoring file change during build: Update 'C:\..\BlazorWasmApp\BlazorWasmApp\BlazorWasmApp.Client\Pages\lak2f2kh.may~' (created 00:00:00.0000000 and written 00:00:00.0000000 before 14:39:45.1684471).
dotnet watch ⌚ Ignoring file change during build: Add 'C:\..\BlazorWasmApp\BlazorWasmApp\BlazorWasmApp.Client\Pages\Home.razor~RF375d9c5.TMP' (created 00:00:00.0000000 and written 00:00:00.0000000 before 14:39:45.1684471).
dotnet watch ⌚ File 'C:\..\BlazorWasmApp\BlazorWasmApp\BlazorWasmApp.Client\Pages\Home.razor~RF375d9c5.TMP' deleted after 14:39:45.1684471.
dotnet watch ⌚ File 'C:\..\BlazorWasmApp\BlazorWasmApp\BlazorWasmApp.Client\Pages\Home.razor' deleted after 14:39:45.1684471.
dotnet watch ⌚ Ignoring file change during build: Add 'C:\..\BlazorWasmApp\BlazorWasmApp\BlazorWasmApp.Client\Pages\Home.razor~RF375d9c5.TMP' (created 00:00:00.0000000 and written 00:00:00.0000000 before 14:39:45.1684471).
dotnet watch ⌚ File 'C:\..\BlazorWasmApp\BlazorWasmApp\BlazorWasmApp.Client\Pages\lak2f2kh.may~' deleted after 14:39:45.1684471.
dotnet watch ⌚ File change: Add 'C:\..\BlazorWasmApp\BlazorWasmApp\BlazorWasmApp.Client\Pages\Home.razor' (written 14:39:57.4387364 after 14:39:45.1684471).
dotnet watch ⌚ File 'C:\..\BlazorWasmApp\BlazorWasmApp\BlazorWasmApp.Client\Pages\Home.razor~RF375d9c5.TMP' deleted after 14:39:45.1684471.
dotnet watch ❌ System.ArgumentException: An item with the same key has already been added. Key: C:\..\BlazorWasmApp\SharedLib\SharedLib.csproj
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.DotNet.Watcher.Tools.IncrementalMSBuildWorkspace.UpdateProjectConeAsync(String rootProjectPath, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.Program.RunAsync()
dotnet watch ❌ An unexpected error occurred
```

**Comment by tmat** [comment]
Fixed by https://github.com/dotnet/sdk/pull/45602

**Comment by paulguz-datapa** [comment]
Is this fix in .Net 9.0.1?  Because I still get the error.

**Comment by tmat** [comment]
It's in 9.0.2xx

**Comment by eLPe21** [comment]
I just got the below on 9.0.300

```
dotnet watch ⌚ [Api (net9.0)] Exited
dotnet watch ❌ System.ArgumentException: An item with the same key has already been added. Key: 1451
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.CodeAnalysis.Emit.DeltaMetadataWriter.GetDelta(Compilation compilation, Guid encId, MetadataSizes metadataSizes)
   at Microsoft.CodeAnalysis.Compilation.SerializeToDeltaStreams(CommonPEModuleBuilder moduleBeingBuilt, DefinitionMap definitionMap, SymbolChanges changes, Stream metadataStream, Stream ilStream, Stream pdbStream, ArrayBuilder`1 updatedMethods, ArrayBuilder`1 changedTypes, DiagnosticBag diagnostics, Func`2 testSymWriterFactory, String pdbFilePath, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Emit.EmitHelpers.EmitDifference(CSharpCompilation compilation, EmitBaseline baseline, IEnumerable`1 edits, Func`2 isAddedSymbol, Stream metadataStream, Stream ilStream, Stream pdbStream, CompilationTestData testData, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.EmitDifference(EmitBaseline baseline, IEnumerable`1 edits, Func`2 isAddedSymbol, Stream metadataStream, Stream ilStream, Stream pdbStream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.EmitSolutionUpdateAsync(Solution solution, ActiveStatementSpanProvider solutionActiveStatementSpanProvider, UpdateId updateId, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.DebuggingSession.EmitSolutionUpdateAsync(Solution solution, IImmutableSet`1 runningProjects, ActiveStatementSpanProvider activeStatementSpanProvider, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExternalAccess.Watch.Api.WatchHotReloadService.GetUpdatesAsync(Solution solution, IImmutableSet`1 runningProjects, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watch.CompilationHandler.HandleManagedCodeChangesAsync(Func`3 restartPrompt, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.Program.RunAsync()
dotnet watch ❌ An unexpected error occurred
```

**Comment by ssttgg** [comment]
I too am seeing a similar error constantly (on every edit of my program) using 9.0.302 against a Blazor Server project.

```
dotnet watch ❌ System.ArgumentException: An item with the same key has already been added. Key: Microsoft.CodeAnalysis.Emit.EditAndContinue.DeletedPEMethodDefinition
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.CodeAnalysis.Emit.DeltaMetadataWriter.SerializeLocalVariablesSignature(IMethodBody body)
   at Microsoft.Cci.MetadataWriter.SerializeMethodBodies(BlobBuilder ilBuilder, PdbWriter nativePdbWriterOpt, Blob& mvidStringFixup)
   at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL(PdbWriter nativePdbWriterOpt, BlobBuilder ilBuilder, PooledBlobBuilder& mappedFieldDataBuilder, PooledBlobBuilder& managedResourceDataBuilder, Blob& mvidFixup, Blob& mvidStringFixup)
   at Microsoft.Cci.MetadataWriter.WriteMetadataAndIL(PdbWriter nativePdbWriterOpt, Stream metadataStream, Stream ilStream, Stream portablePdbStreamOpt, MetadataSizes& metadataSizes)
   at Microsoft.CodeAnalysis.Compilation.SerializeToDeltaStreams(CommonPEModuleBuilder moduleBeingBuilt, DefinitionMap definitionMap, SymbolChanges changes, Stream metadataStream, Stream ilStream, Stream pdbStream, ArrayBuilder`1 updatedMethods, ArrayBuilder`1 changedTypes, DiagnosticBag diagnostics, Func`2 testSymWriterFactory, String pdbFilePath, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Emit.EmitHelpers.EmitDifference(CSharpCompilation compilation, EmitBaseline baseline, IEnumerable`1 edits, Func`2 isAddedSymbol, Stream metadataStream, Stream ilStream, Stream pdbStream, CompilationTestData testData, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.EmitDifference(EmitBaseline baseline, IEnumerable`1 edits, Func`2 isAddedSymbol, Stream metadataStream, Stream ilStream, Stream pdbStream, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.EmitSolutionUpdateAsync(Solution solution, ActiveStatementSpanProvider solutionActiveStatementSpanProvider, UpdateId updateId, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.DebuggingSession.EmitSolutionUpdateAsync(Solution solution, IImmutableSet`1 runningProjects, ActiveStatementSpanProvider activeStatementSpanProvider, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExternalAccess.Watch.Api.WatchHotReloadService.GetUpdatesAsync(Solution solution, IImmutableSet`1 runningProjects, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watch.CompilationHandler.HandleManagedCodeChangesAsync(Func`3 restartPrompt, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.Program.RunAsync()
dotnet watch ❌ An unexpected error occurred
```

**Comment by tmat** [comment]
@eLPe21 @ssttgg These are unrelated issues. Please open new issue with a repro or logs collected like so:

1) set `Microsoft_CodeAnalysis_EditAndContinue_LogDir=%temp%\HotReloadLog`
2) run `dotnet watch --verbose` and reproduce the issue
3) Share `%temp%\HotReloadLog` and dotnet watch output on the issue

Thanks!

**Comment by bronthulke** [comment]
I've started having this issue again.

`dotnet` version is 10.0.101

Is anyone else seeing this again?

Here is an example

```
dotnet watch ❌ [YouLi.UI.WebCore (net9.0)] Exited with error code -1
dotnet watch ❌ An unexpected error occurred: System.ArgumentException: An item with the same key has already been added. Key: 0
   at Microsoft.CodeAnalysis.Collections.Internal.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at Microsoft.CodeAnalysis.Collections.SegmentedDictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.CodeAnalysis.Collections.ImmutableSegmentedDictionary`2.ValueBuilder.AddRange(IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Collections.ImmutableSegmentedDictionary`2.AddRange(IEnumerable`1 pairs)
   at Microsoft.CodeAnalysis.Collections.ImmutableSegmentedDictionary.ToImmutableSegmentedDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 keyComparer)
   at Microsoft.CodeAnalysis.Emit.DefinitionMap.MakeLambdaAndClosureMapFromMetadata(EditAndContinueMethodDebugInformation debugInfo, IMethodSymbolInternal method, DebugId methodId, IReadOnlyDictionary`2& lambdaMap, IReadOnlyDictionary`2& closureMap)
   at Microsoft.CodeAnalysis.Emit.DefinitionMap.TryCreateVariableSlotAllocator(Compilation compilation, IMethodSymbolInternal method, IMethodSymbolInternal topLevelMethod, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.Emit.PEDeltaAssemblyBuilder.TryCreateVariableSlotAllocator(MethodSymbol method, MethodSymbol topLevelMethod, DiagnosticBag diagnostics)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, SourceExtensionImplementationMethodSymbol extensionImplementationMethod, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, MethodInstrumentation instrumentation, DebugDocumentProvider debugDocumentProvider, ImmutableArray`1& codeCoverageSpans, BindingDiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 lambdaRuntimeRudeEditsBuilder, ArrayBuilder`1 closureDebugInfoBuilder, ArrayBuilder`1 stateMachineStateDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol containingType)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers()
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean emittingPdb, Boolean hasDeclarationErrors, Boolean emitMethodBodies, BindingDiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CompileMethods(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Compile(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Emit.EmitHelpers.EmitDifference(CSharpCompilation compilation, EmitBaseline baseline, IEnumerable`1 edits, Func`2 isAddedSymbol, Stream metadataStream, Stream ilStream, Stream pdbStream, EmitDifferenceOptions options, CompilationTestData testData, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.EmitDifference(EmitBaseline baseline, IEnumerable`1 edits, Func`2 isAddedSymbol, Stream metadataStream, Stream ilStream, Stream pdbStream, EmitDifferenceOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.EmitSolutionUpdateAsync(Solution solution, ActiveStatementSpanProvider solutionActiveStatementSpanProvider, UpdateId updateId, ImmutableDictionary`2 runningProjects, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.DebuggingSession.EmitSolutionUpdateAsync(Solution solution, ImmutableDictionary`2 runningProjects, ActiveStatementSpanProvider activeStatementSpanProvider, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.ExternalAccess.Watch.Api.WatchHotReloadService.GetUpdatesAsync(Solution solution, ImmutableDictionary`2 runningProjects, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watch.CompilationHandler.HandleManagedCodeChangesAsync(Boolean autoRestart, Func`3 restartPrompt, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.Program.RunAsync()
```

**Comment by tmat** [comment]
@bronthulke  Please see the [previous comment](https://github.com/dotnet/sdk/issues/45455#issuecomment-3081631405).

**Comment by phillipzada** [comment]
Hi I think this is the same issue

Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: /src/Common/Common.Messaging.Abstractions/bin/Debug/net10.0/Common.Messaging.Abstractions.pdb

   at Microsoft.DotNet.Watch.PollingDirectoryWatcher.ForeachEntityInDirectory(DirectoryInfo dirInfo, Action`2 fileAction)

   at Microsoft.DotNet.Watch.PollingDirectoryWatcher.ForeachEntityInDirectory(DirectoryInfo dirInfo, Action`2 fileAction)

   at Microsoft.DotNet.Watch.PollingDirectoryWatcher.ForeachEntityInDirectory(DirectoryInfo dirInfo, Action`2 fileAction)

   at Microsoft.DotNet.Watch.PollingDirectoryWatcher.ForeachEntityInDirectory(DirectoryInfo dirInfo, Action`2 fileAction)

   at Microsoft.DotNet.Watch.PollingDirectoryWatcher.CheckForChangedFiles()

   at Microsoft.DotNet.Watch.PollingDirectoryWatcher.PollingLoop()

   at System.Threading.Thread.StartCallback()
