### ISSUE TITLE
PackTask" task failed unexpectedly. System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by niemyjski** [dotnet/sdk#838]
I'm running VS2017 RC3 (Latest) and I'm seeing this randomly when I build my solution or the `Foundatio.Redis` package.

Just clone (https://github.com/exceptionless/foundatio) and try building different projects / run the tests

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "PackTask" task failed unexpectedly.
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NuGet.Build.Tasks.Pack.PackTaskLogic.GetSourceFiles(IPackTaskRequest`1 request, String currentProjectDirectory)
   at NuGet.Build.Tasks.Pack.PackTaskLogic.GetPackArgs(IPackTaskRequest`1 request)
   at NuGet.Build.Tasks.Pack.PackTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Foundatio	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets	104	
```

**Comment by niemyjski** [comment]
Also, is there a good place to log an issue with the VS Test runner? I can't seem to be able to profile any unit tests either. And My redis unit tests aren't discoverable now either :\

**Comment by srivatsn** [comment]
This issue was moved to NuGet/Home#4536

**Comment by srivatsn** [comment]
@niemyjski You can log them at https://github.com/Microsoft/VSTest
