### ISSUE TITLE
Specifying both 'TargetFrameworks'  and 'TargetFramework' causes dotnet run to fail badly.  

### ISSUE THREAD

**Issue by fearthecowboy** [dotnet/sdk#8676]
I found this bug with a far more complicated example, but distilled it down to the minimum possible repro. 

## Steps to reproduce
``` powershell
# PowerShell Script
mkdir bug
cd bug
dotnet new console
dotnet add package newtonsoft.json 

# Add a "TargetFrameworks" element
(Get-Content .\bug.csproj).replace('<TargetFramework>', "<TargetFrameworks>netcoreapp2.0</Target
Frameworks>`n    <TargetFramework>") | Set-Content bug.csproj

# wipe clean
rmdir -r -force obj ; rmdir -r -force bin ; 

# restore and run project
dotnet restore ; dotnet run

# OUTPUT:
  Restoring packages for C:\tmp\bug\bug.csproj...
  Generating MSBuild file C:\tmp\bug\obj\bug.csproj.nuget.g.props.
  Generating MSBuild file C:\tmp\bug\obj\bug.csproj.nuget.g.targets.
  Restore completed in 606.02 ms for C:\tmp\bug\bug.csproj.

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version
=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does
 not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Console.get_Out()
   at System.Console.WriteLine(String value)
   at bug.Program.Main(String[] args)
```

## Expected  behavior

Ideally, having `<TargetFramework>...` specified in the `csproj` file  should negate the necessity of having to use `--framework` on the command line. 

Second, even if that's not the 'expectation' -- it certainly should yell, like it would if you don't have `<TargetFramework>...` in the csproj:

``` powershell
# remove the TargetFramework element
(Get-Content .\bug.csproj).replace('TargetFramework>', "TargetFramework_>") | Set-Content bug.cs
proj

# clean, restore and run again
 rmdir -r -force obj ; rmdir -r -force bin ; dotnet restore ; dotnet run
  Restoring packages for C:\tmp\bug\bug.csproj...
  Generating MSBuild file C:\tmp\bug\obj\bug.csproj.nuget.g.props.
  Generating MSBuild file C:\tmp\bug\obj\bug.csproj.nuget.g.targets.
  Restore completed in 629.54 ms for C:\tmp\bug\bug.csproj.
Unable to run your project
Your project targets multiple frameworks. Please specify which framework to run using '--framework'.
```

But, the real irritant is that it's pulling in the completely weird/wrong dependencies, and dying in a blaze of pain:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version
=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does
```

## Actual behavior
Running the program will throw an exception because it's somehow picked up the wrong assemblies.
``` text
  Restoring packages for C:\tmp\bug\bug.csproj...
  Generating MSBuild file C:\tmp\bug\obj\bug.csproj.nuget.g.props.
  Generating MSBuild file C:\tmp\bug\obj\bug.csproj.nuget.g.targets.
  Restore completed in 606.02 ms for C:\tmp\bug\bug.csproj.

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version
=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does
 not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Console.get_Out()
   at System.Console.WriteLine(String value)
   at bug.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16278
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

## Final Thoughts
Why doesn't having a single value in `<TargetFrameworks>...` not behave  exactly the same as just having a `<TargetFramework>...` specified.

**Comment by Joe4evr** [comment]
Found this issue as I hit it in a different scenario:

What I have is a `Directory.Build.props` for some global configuration, which includes:
`<TargetFramework>netstandard2.1</TargetFramework>`
With the release of .NET 5, there is one project in this solution that I wanted to multi-target, so I added this to that specific project:
`<TargetFrameworks>$(TargetFramework);net50</TargetFrameworks>`
At this point, I noticed that the compiler only compiled for `net50`, and that was a bit confusing.

On gitter, we found one workaround is to use TargetFramework**s** in the .props file after which everything works as intended, but someone else then pointed out that third party tools (for example, ReSharper) will then complain that only one TFM is specified in the element meant for multiple.

**Comment by dsplaisted** [comment]
@Joe4evr I'd suggest putting the following in the project file you want to multi-target:

```xml
<TargetFrameworks>$(TargetFramework);net50</TargetFrameworks>
<TargetFramework />
```

This will unset the `TargetFramework` value from the `Directory.Build.props` file and should cause the project to behave normally.

**Comment by baronfel** [comment]
I think this should just work today, actually. We can reopen if not, plus some of the work @jonathanpeppers is doing for 10.0.200+/11 will separately mitigate this.

**Comment by jonathanpeppers** [comment]
Yes, I believe what would happen with:
* https://github.com/dotnet/sdk/pull/51509

It would just use `$(TargetFramework)` no s, and go on with it.
