### ISSUE TITLE
Dot Net Standard Nuget Package 1.6.1 is throwing System.IO.PathTooLongException, while restoring the package. For Same project and same location 1.6.0 get installed correctly

### ISSUE THREAD

**Issue by kulkarnisachin07** [dotnet/sdk#869]
GET https://www.nuget.org/api/v2/Packages(Id='NETStandard.Library',Version='1.6.1')
OK https://www.nuget.org/api/v2/Packages(Id='NETStandard.Library',Version='1.6.1') 1316ms
Restoring packages for D:\Workspace\source\avocet\AvocetProjects\Source\Workflows\PSDCWorkflowFramework\Slb.WorkflowManager\src\Slb.WorkflowManager\Slb.WorkflowManager.csproj...
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
at System.IO.PathHelper.GetFullPathName()
at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
at System.IO.Path.GetFullPathInternal(String path)
at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
at System.IO.FileInfo..ctor(String fileName)
at NuGet.Protocol.LocalFolderUtility.GetPackagesConfigFolderPackage(String root, PackageIdentity identity, ILogger log)
at NuGet.Protocol.FindLocalPackagesResourcePackagesConfig.GetPackage(PackageIdentity identity, ILogger logger, CancellationToken token)
at NuGet.Protocol.LocalPackageMetadataResource.<>c__DisplayClass3_0.b__0()
at System.Threading.Tasks.Task1.InnerInvoke() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.PackageManagement.UI.UIActionEngine.<GetPackageMetadataAsync>d__15.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.PackageManagement.UI.TaskCombinators.<>c__DisplayClass1_02.<b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.PackageManagement.UI.TaskCombinators.d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.PackageManagement.UI.UIActionEngine.d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.PackageManagement.UI.UIActionEngine.d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at NuGet.PackageManagement.UI.UIActionEngine.d__6.MoveNext()
========== Finished ==========
Time Elapsed: 00:00:02.8204987

**Comment by piotrpMSFT** [comment]
@kulkarnisachin07 this issue is outside of the SDK's control. It looks like the nuget packages folder for your user account is too far from the root and the combined path of that root folder + the contents of the nuget package exceed Windows' maximum path length.

The workaround here is to move your nuget packages folder closer to the root of your drive. [This document](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior) should help with that approach.

I don't really think there is another good alternative here. However, if you want to discuss packaging in 1.6.1 with the team then please open this issue in the dotnet/corefx repo. That's where NetStandard.Library is developed.
