### ISSUE TITLE
Cannot install prereleased tool package from dotnet-install-tool without specifying the exact version

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/sdk#9037]
To install a prerelease version of a CLI tool, users must know the exact version they want to install. This means they have to open a browser to nuget.org or myget.org to find the package.

For example, this is the console output for dotnet-watch
```
> dotnet install tool --global dotnet-watch --source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json
Install failed. Failed to download package:
NuGet returned:

Failed to restore package.
WorkingDirectory:
Arguments: restore C:\Users\namc\AppData\Local\Temp\0rc552nv.kmy\wjh4elju.lgh.csproj --source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json --runtime win10-x64 /p:BaseIntermediateOutputPath=\"C:\Users\namc\.dotnet\tools\dotnet-watch\gx5ifack.dyr\"
Output:   Restoring packages for C:\Users\namc\AppData\Local\Temp\0rc552nv.kmy\wjh4elju.lgh.csproj...
C:\Users\namc\AppData\Local\Temp\0rc552nv.kmy\wjh4elju.lgh.csproj : error NU1103: Unable to find a stable package dotnet-watch with version

C:\Users\namc\AppData\Local\Temp\0rc552nv.kmy\wjh4elju.lgh.csproj : error NU1103:   - Found 124 version(s) in https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json [ Nearest version: 2.1.0-preview1-27934 ]
C:\Users\namc\AppData\Local\Temp\0rc552nv.kmy\wjh4elju.lgh.csproj : error NU1103:   - Found 1 version(s) in C:\Users\namc\.dotnet\x64\sdk\NuGetFallbackFolder [ Nearest version: 2.1.0-preview1-28124 ]
  Restore failed in 680.98 ms for C:\Users\namc\AppData\Local\Temp\0rc552nv.kmy\wjh4elju.lgh.csproj.

Usage: dotnet install tool [options] <PACKAGE_ID>

Arguments:
  <PACKAGE_ID>   NuGet Package Id of the tool to install.

Options:
  -g, --global        Install user wide.
  --version           Version of the tool package in NuGet.
  --configfile        The NuGet configuration file to use.
  --source <SOURCE>   Specifies a NuGet package source to use during installation.
  -f, --framework     The target framework to install the tool for.
  -h, --help          Show help information.
```

This is the console output when trying to specify `--version 2.1.0-*`
```
> dotnet install tool --global dotnet-watch --version 2.1.0-* --source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json
System.ArgumentException: Illegal characters in path.
Parameter name: path
   at System.IO.Path.GetFullPath(String path)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.DotNet.ToolPackage.ToolPackageObtainer.EnsureDirectoryExists(DirectoryPath path)
   at Microsoft.DotNet.ToolPackage.ToolPackageObtainer.CreateIndividualToolVersionDirectory(String packageId, PackageVersion packageVersion)

   at Microsoft.DotNet.ToolPackage.ToolPackageObtainer.ObtainAndReturnExecutablePath(String packageId, String packageVersion, Nullable`1 nugetconfig, String targetframework, String source)
   at Microsoft.DotNet.Tools.Install.Tool.InstallToolCommand.ObtainPackage(DirectoryPath executablePackagePath, DirectoryPath offlineFeedPath)
   at Microsoft.DotNet.Tools.Install.Tool.InstallToolCommand.Execute()
   at Microsoft.DotNet.Cli.DotNetTopLevelCommandBase.RunCommand(String[] args)
   at Microsoft.DotNet.Tools.Install.InstallCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

*Ideas*

- Support wildcards `--version 2.1.0-*`
- Support a `--prerelease` flag

cc @KathleenDollard

**Comment by heaths** [comment]
While I'm not a fan of long command line options, `dotnet list package --include-prerelease` exists and, IMO, sets a precedent. Maybe `--pre` could be an alias, though it's odd to have two longopts right away.

**Comment by DamianEdwards** [comment]
FYI NuGet/Home#912 is being fixed right now. This could be revisited for an upcoming SDK update.

**Comment by wli3** [comment]
Thanks! This should be an easy change once the code flows to SDK. And we would add it once it is available since it is highly requested as well. @KathleenDollard

**Comment by aolszowka** [comment]
Is there no other work around today than knowing the complete `major.minor.revision-dev`?

Our use case is to try and give developers some tooling while they're working on updating the tooling[0]. I suspect our usecase is similar to what @yufeih was attempting to describe above. Having to have them edit the batch file to contain the current version is kinda a bummer, the next step is for us to write a PowerShell script to extract out the version from the CSPROJ File.

Here's what we're doing (with a batch file), is there a better way?

```batch
@ECHO OFF

SET PACKAGE_NAME=REDACTED

REM Clear any packages out of the local nuget package cache
REM This is because `dotnet tool install --no-cache` appears to be broken?
SET PACKAGE_CACHE_FOLDER=%userprofile%\.nuget\packages\%PACKAGE_NAME%
ECHO Attempting to Clean Existing Package Cache From %PACKAGE_CACHE_FOLDER%
IF EXIST "%PACKAGE_CACHE_FOLDER%" (
RMDIR /Q /S "%PACKAGE_CACHE_FOLDER%"
)

ECHO.
ECHO Delete Existing Packs
IF EXIST nupkg (
RMDIR /q /s nupkg
)

ECHO.
ECHO Building / Packing
dotnet pack --configuration Debug --version-suffix "dev"

ECHO.
ECHO Uninstall Existing Tooling
dotnet tool uninstall %PACKAGE_NAME%

ECHO.
ECHO Install the Latest Prerelease
dotnet tool install --add-source=nupkg --no-cache %PACKAGE_NAME% --version=2.0.0-dev
```

[0] I heard you like your tooling in your tooling

**Comment by nkolev92** [comment]
@aolszowka 

Try `--version "*-*"`

It's basically what https://github.com/dotnet/sdk/issues/9037#issuecomment-581651532 enabled.

**Comment by aolszowka** [comment]
@nkolev92 Solid this works, any reason to keep this open still then? or does this not work for most others?

**Comment by nkolev92** [comment]
I think the issue is open because the switch has not been added yet. 

I'm not the owner though, so it's just a guess :)

**Comment by wli3** [comment]
Yes. The switch has not been added yet.

**Comment by wli3** [comment]
fixed in https://github.com/dotnet/sdk/pull/19646
